### ISSUE TITLE
Mask does not apply dynamically

### ISSUE THREAD

**Issue by aparna999** [JsDaddy/ngx-mask#100]
I have an Angular app and it contains a dropdown list of country codes and a phone number input field. My requirement is to update the phone number with the corresponding phone # mask of the country whenever the country code changes which does not seem to work as intended.

Code in : 
https://stackblitz.com/edit/angular-e394pt

**Comment by YuriiZadorozhnyi** [comment]
Hello.
As I see all works fine.
You just need to select country, otherwise your  mask is undefined and does not work.
Am I right?

**Comment by aparna999** [comment]
@YuriiZadorozhnyi Yeah it works but what I meant to say is the input field does not get updated upon selection changes. Say, if you select US +1 then the input is (713) 222-3333. Now select Japan +81, the phone number in the input field remains same. Expected to be 71-3222-3333. If you type in the phone number it applies the correct mask but on selection change it does not.

**Comment by YuriiZadorozhnyi** [comment]
You need do this: 
import { Subject } from 'rxjs/Subject'; 
mask$: Subject<string> = new Subject();
  setMask(id){
    this.mask$.next(this.data.filter(data => data.id === id)[0].mask)
    setTimeout(() => this.userForm.get('phoneNumber').setValue('9999999999'), 0);
  }
  <mat-form-field>
    <input matInput placeholder="Phone Number" 
      mask="{{mask$ | async}}" formControlName="phoneNumber" />
  </mat-form-field>

**Comment by YuriiZadorozhnyi** [comment]
<mat-form-field>
    <input matInput placeholder="Phone Number" 
      mask="{{mask$ | async}}" formControlName="phoneNumber" />
  </mat-form-field>

**Comment by YuriiZadorozhnyi** [comment]
Link here:
https://stackblitz.com/edit/angular-cicjvx?file=app%2Fapp.component.ts

**Comment by aparna999** [comment]
@YuriiZadorozhnyi Thank you.
