### ISSUE TITLE
Copy+Paste does not position the cursor at the end 

### ISSUE THREAD

**Issue by ppapla** [JsDaddy/ngx-mask#1000]
# 🐞 bug report

### Description

Hello, 
I have similar issue with version `13.1.10` as described here https://github.com/JsDaddy/ngx-mask/issues/131.
When I use `thousandSeparator` and paste a number "1234567", it places the cursor in the middle of the number instead of the end.

## 🔬 Minimal Reproduction

```
<input type="text" matInput mask="separator.0" thousandSeparator="," maxlength="9">
```

**Comment by NepipenkoIgor** [comment]
@ppapla  Thank you that you using ngx-mask . Please try version >=13.1.11

**Comment by ppapla** [comment]
@NepipenkoIgor Thanks a lot, now it works as expected.
