### ISSUE TITLE
For empty number input mask sets input value as 0 instead of null

### ISSUE THREAD

**Issue by dianadomino24** [JsDaddy/ngx-mask#1002]
### Description

When user deletes all digits from number input, input becomes empty but if inspect the input value in console or debugger, its value is actually 0 instead of null. This creates bug when input has required validator which shows that empty input is valid (because it's value is set as 0) whereas it should be invalid. 

When I set debugger in writeValue method of input, I see that input value null is transformed into 0 after this._maskService.applyValueChanges call. 

## 🔬 Minimal Reproduction

  `<input mask="separator.2" [(ngModel)]="value" />`

**Angular Version:**

<pre><code>
    "ngx-mask": "^11.1.4",
    "@angular/cdk": "12.2.3",
    "@angular/common": "^12.2.3",
    "@angular/compiler": "^12.2.3",
    "@angular/core": "^12.2.3",
    "@angular/forms": "^12.2.3",
</code></pre>

**Video of debugger**

https://user-images.githubusercontent.com/63780561/165263365-99a66ea1-6e01-40ec-b64d-97d0a74f52fc.mov

**Comment by zmays** [comment]
+1

**Comment by xakeppok** [comment]
hi @dianadomino24 can you please provide all your code for reproducing this issue ?

**Comment by ZhidkovGV** [comment]
@xakeppok Hi, I'm a colleague  of Diana, I'll ask her to provide minimal reproduction on StackBlitz in comming days

**Comment by dianadomino24** [comment]
Hey @xakeppok! 
Sorry for the long reply)
Here is the minimal [reproduction](https://stackblitz.com/edit/angular-ngx-wrong-empty-mask-example-xempty?file=src%2Fapp%2Fapp.component.html%3AL11,src%2Fapp%2Fapp.component.ts%3AL10,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.module.ts):

Please, note that when I delete everything from the input, the value is set to 0 instead of null. So I can't distinguish whether user filled in 0 (which is valid) or it's empty input (which is invalid). 

![image](https://user-images.githubusercontent.com/63780561/193650092-0ece990b-3663-4dd8-a40c-e5a562d2f82b.png)

**Comment by andriikamaldinov1** [comment]
@dianadomino24  @zmays Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected -  https://stackblitz.com/edit/angular-1hp1gb?file=src%2Fmain.ts

**Comment by subhabrata2017** [comment]
In empty text box if I am pressing period key "." its not appearing. I am using ngx-mask: 15.1.0", with angular 15
