### ISSUE TITLE
Clear input in Firefox with backspace using a mask not working correctly

### ISSUE THREAD

**Issue by L-VE** [JsDaddy/ngx-mask#1005]
# 🐞 bug report

### Description

When selecting the value in an input field using a mask and try to clear it with backspace, the value in the input is not cleared until you enter backspace again.

## 🔬 Minimal Reproduction

I created a project in stackblitz to reproduce the issue: https://stackblitz.com/edit/angular-ivy-pbczej?file=src/app/app.component.ts  
I have an input whose validation errors are shown via a separate custom component. 
The input has a mask 000 with a min validator (min 777), so you can only enter a number with 3 digits with a min of 777.
A validation error must be show when the input is invalid and has been touched.

Now when you enter '444' en leave the input and try to select the value and use backspace to clear the value, it's doesn't clear the input value.
The formcontrol value is cleared apparently but the value of the input itself is not. So you have to use backspace again to clear the value.

![demo](https://user-images.githubusercontent.com/4353734/167380216-8685d102-fc09-40ba-8945-fea98a0192b1.gif)

I can only reproduce this in firefox, if the conditions to show validation errors are put inside a custom reusable component and it's using the control.invalid property. I don't see this issue occurring in chrome or when I remove the control.invalid condition in the fieldErrorComponent.

## 🔥 Exception or Error
<pre><code>
/
</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 13.3.5
Node: 16.13.2
Package Manager: yarn 1.22.17
OS: linux x64

Using ngxmask version 13.1.1, 

</code></pre>

**Anything else relevant?**

Firefox 99.0 (64-bit)

**Comment by andriikamaldinov1** [comment]
@L-VE Thanks for your using Ngx-Mask. Please update to latest version.
Sorry,but we can't recognize this issue becouse it work at all browsers.. Pls use workaround

**Comment by L-VE** [comment]
I have tried it again with the latest versions of angular and ngx-mask and it still doesn't work in firefox.
Reproduction: https://stackblitz.com/edit/angular-axbrrb?file=src%2Fapp%2Fapp.component.ts
Do you have a proper workaround because we didn't find one?
![Peek 2023-09-12 14-40](https://github.com/JsDaddy/ngx-mask/assets/4353734/ee9bb571-8f07-46e3-951f-198aa96dea1a)
