### ISSUE TITLE
Changing "hiddenInput" breaks the entered value

### ISSUE THREAD

**Issue by gultyayev** [JsDaddy/ngx-mask#1008]
# 🐞 bug report

### Is this a regression?

The bug was introduced by this commit 4dcd6838

![image](https://user-images.githubusercontent.com/22374911/170031244-4edcee6b-2ef2-47c3-9d59-d2818e21a3f0.png)

### Description

When used a mask which hides entered values fully or partially there is a bug when you switch the `hiddenInput` value. If the value is entered when `hiddenInput` is true, then when turning it off we lose a half of the entered value. If instead it was false and then turned on the value stays intact.

## 🔬 Minimal Reproduction

Was not able to create a reproduction as latest version of the lib isn't working with the latest Angular. But should be smth like it 
https://stackblitz.com/edit/angular-ivy-mask-cabthi?file=src%2Fapp%2Fapp.component.ts

## 🌍 Your Environment

**Angular Version:** any. Not related to the Angular's version

**Anything else relevant?**

I discovered that the cause is the line 58 `if (this.hiddenInput && !this.writingValue) {` of `mask.service.ts`. If changed to `if (this.hiddenInput) {` then the issue is not reproducible anymore.

**Comment by xakeppok** [comment]
@gultyaev Thank you that you using ngx-mask . Please try version >=13.1.11

**Comment by xakeppok** [comment]
@gultyaev  sorry. My mistake >=14.0.2

**Comment by rushabh-wadkar** [comment]
@NepipenkoIgor @andriikamaldinov1 Any plans to fix this for v12 ?
Can you atleast provide what changes are needed just to fix this. I have already forked the project. I'll patch this on my own.

**Comment by andriikamaldinov1** [comment]
@rushabh-wadkar Thanks for using Ngx-mask. We have added updated version for 12 angular this is 13.2.1
It example all work as exepcted - https://stackblitz.com/edit/base-angular-12-app-hqsdro?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
