### ISSUE TITLE
Untyped Form imported from @angular/forms in ngx-mask: "14.0.2".

### ISSUE THREAD

**Issue by zainuleb** [JsDaddy/ngx-mask#1016]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13

### Description

 Whenever you import  import { NgxMaskModule } from 'ngx-mask'; there appears an error from ngx-mask in node_modules.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

**Angular Version:13.3**

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by GlebChiz** [comment]
@zainuleb Thank you that using ngx-mask. Please try version >=14.0.3
