### ISSUE TITLE
v14.0.2 does not work with Angular 13

### ISSUE THREAD

**Issue by sgshivamgarg8** [JsDaddy/ngx-mask#1017]
# 🐞 bug report

### Is this a regression?
No

### Description

Latest version v14.0.2 is not working with Angular 13. I am getting UntypedFormControl error. Please fix this as I need to use v14.0.2 due to issue #1008 fix.

## 🔬 Minimal Reproduction

Just create an Angular 13 project and install latest version of ngx-mask. Import NgxMaskModuke.forRoot() in app.module and run.

## 🌍 Your Environment

**Angular Version:** 13

**Comment by gultyaev** [comment]
You are running an incompatible version, aren't you? v14 has breaking changes and so this library apparently

**Comment by sgshivamgarg8** [comment]
> You are running an incompatible version, aren't you? v14 has breaking changes and so this library apparently

The Library does not mention anywhere that v14 is not compatible with Angular 13.
And they fixed a bug which was present before angular 14.
The issue is I cant update my app to ng14.

**Comment by sgshivamgarg8** [comment]
Now getting this error as mentioned in #1021
