### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by jalmirante** [JsDaddy/ngx-mask#1021]
Angular 13.0.4
ngx-mask 14.0.3

I add "import { NgxMaskModule, IConfig } from 'ngx-mask';" in my module and when doing the "ng serve" the following error appears:

![Captura de Pantalla 2022-06-25 a la(s) 22 15 20](https://user-images.githubusercontent.com/12002628/175796524-c595da2d-f53a-4820-a722-d3d19650bde5.png)

**Comment by liverant** [comment]
+1

**Comment by lionmo** [comment]
I'm getting the same error. Angular version 13

**Comment by lixaotec** [comment]
+1

**Comment by NepipenkoIgor** [comment]
@jalmirante  Seems like we cant reproduce problem 
For example you could look on this  https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-lzamyg?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html
If you still has an issue please open new issue with right template and provide stackblitz example of what you tried to do

**Comment by gabrielluizoc** [comment]
@EmersonCoosta uninstall ngx-mask version 14 and install one compatible with version 13, I had this problem too and I'm using version 13.1.13 https://www.npmjs.com/package/ngx-mask/v/13.1.13

`npm i ngx-mask@13.1.13`

**Comment by Augusto96Ribeiro** [comment]
@gabrielluizoc Obrigado, procurei muito por essa solução.
