### ISSUE TITLE
Ignoring prefix in pasted content

### ISSUE THREAD

**Issue by MoxxiManagarm** [JsDaddy/ngx-mask#1024]
# 🚀 feature request

### Description

I want the defined prefix to be ignored within pasted strings.

```
<input mask="AAA-AAA-AAA" prefix="FOO-" />
```

Currently, when I paste "FOO-DDD-DDD-DDD" on that input field, the value becomes "FOO-FOO-DDD-DDD". But I want the "FOO-" of the pasted content to be ignored.

### Describe the solution you'd like

Please let me decide whether or not to ignore the beginning of a string matching the prefix, when the full string is pasted.

**Comment by MoxxiManagarm** [comment]
Any suggestions for a workaround appreciated.

**Comment by Nabeeh-AlSawaf** [comment]
any ideas or updates ?

**Comment by andriikamaldinov1** [comment]
@MoxxiManagarm @Nabeeh-AlSawaf Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-tpudhe?file=src%2Fmain.ts
