### ISSUE TITLE
Compiler issue after install this mask lib

### ISSUE THREAD

**Issue by hirenmistry17** [JsDaddy/ngx-mask#1025]
![image](https://user-images.githubusercontent.com/50474523/177939176-eed5eee9-3857-458a-899b-db55f722d072.png)

Hello Team,
I'm getting this error after i have install this package, any help would be great,
i have done install this npm and added in module and try to implement in input tag

**Comment by rdebeasi** [comment]
I recently got the same error. It turns out that I was had installed ngx-mask 14.x in an Angular 13.x application. Running `npm i ngx-mask@13` installed the correct version of ngx-mask, which fixed the issue for me.

**Comment by NepipenkoIgor** [comment]
@rdebeasi  @hirenmistry17  Сould you create a stackblitz example and/or provide package.json

**Comment by NepipenkoIgor** [comment]
@hirenmistry17 @rdebeasi  I will close this issue. Please if you  interesting or still has this problem please open new one by template that we suggest
