### ISSUE TITLE
Fieldmask with dashes and optional numbers reproduces not wanted dashes when fillingin th eform

### ISSUE THREAD

**Issue by arnevm123** [JsDaddy/ngx-mask#1027]
# 🐞 bug report

### Is this a regression?

 I don't think so
### Description

 A clear and concise description of the problem...

When making a simple fieldmask containing optional numbers and a separating char ( '/' or '-') the separating char gets duplicated sometimes when filling in the input field.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/93863978/181265009-cf95bde8-694f-409e-a9b0-812d46c14777.png">

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-mask-qd8dzq?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre>
@angular/animations 11.0.2

@angular/common 11.0.2

@angular/compiler 11.0.2

@angular/core 11.0.2

@angular/forms 11.0.2

@angular/platform-browser 11.0.2

@angular/platform-browser-dynamic 11.0.2

@angular/router 11.0.2

ngx-mask 11.1.0

rxjs 6.6.3

tslib 2.0.3

zone.js 0.11.3
<code>

</code></pre>

**Anything else relevant?**

**Comment by NepipenkoIgor** [comment]
@arnevm123  Hi. Thank you that using ngx-mask.  Please use  ngx-mask >=14.2.2.  Pay attention that perhaps you need migrate to ng12+
Also  please check https://stackblitz.com/edit/angular-material-13-starter-x1xj4z-99bgwi?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts
