### ISSUE TITLE
Num Lock dot or comma key does not work or seams to be blocked when decimalMarker is comma (,)

### ISSUE THREAD

**Issue by ek1mb4** [JsDaddy/ngx-mask#1029]
I am coding an invoice and most of the accountants use num lock keyboard to type fast, and in Portuguese we use mostly commas for decimals. But when I have a comma as the value of decimalMarker input, num lock dot (.) does not work.

**Comment by NepipenkoIgor** [comment]
@ek1mb4  HI. Thank you for request and using our package. Please try ngx-mask version >=14.2.0

**Comment by ek1mb4** [comment]
@NepipenkoIgor many thanks for this great package. All the best to you all.
