### ISSUE TITLE
Custom decimal locale/format

### ISSUE THREAD

**Issue by framasev** [JsDaddy/ngx-mask#1032]
# 🚀 feature request
Decimal format (commas or dots) is defined based on locale: dots in decimals are always converted to commas for particular locale (and vice versa) when `separator.${n}` is used.

**Consequences:** custom decimal format isn't allowed.

**Example problem**: allow to input decimals in any format (commas or dots) and convert to dot format on blur.

**Straightforward non-working solution:**
```typescript
@Directive({
  selector: '[decimalPointFormat]'
})
class DecimalPointFormatDirective {
  constructor(private ngControl: NgControl) {}

  @HostListener('blur')
  private handleBlur(): void {
    const value = this.elementRef.nativeElement.value;
    const formattedValue = value.replace(',', '.');

    this.ngControl.control?.setValue(formattedValue);
  }
}
```

```html
<input [formControl]="control" mask="separator" decimalPointFormat />
```

**Cause of problem:** setting a formatted value triggers [`writeValue`](https://github.com/JsDaddy/ngx-mask/blob/57a9f60b05f5526e6125a4f9136cf5368f0ea495/projects/ngx-mask-lib/src/lib/mask.directive.ts#L515) and [`Number.toLocaleString`](https://github.com/JsDaddy/ngx-mask/blob/2a7bc7d4dea116c25b1aa597c6fdb75e565ebc59/projects/ngx-mask-lib/src/lib/mask.service.ts#L234) overrides a previously formatted value: commas formatted to dot then overridden to commas again (based on locale).

### Describe the solution you'd like
Provide a `decimalLocale` input to override a decimal locale:
```html
<input mask="separator" decimalLocale="de-DE'">
```

Provide a `decimalFormat` input to override a decimal format, move to [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) formatting:
```typescript
format = new Intl.NumberFormat('de-DE');
```
```html
<input mask="separator" decimalFormat="format">
```

**Comment by daniel-seitz** [comment]
Does using decimalMarker="," fix your issue?

**Comment by BulletQQ** [comment]
Due to the use of ".toLocaleString" a lot of problems appeared, because of this, in fact, the whole package does not work correctly, I thought you fixed this bug a long time ago, since everything was in order in version 12, and many people asked you to fix the problem with the call " .toLocaleString" . now, in fact, ngx-mask works under 1 locale, for example, if thousandSeparator="." is set. decimalMarker="," then this will only work for the European locale, and if, for example, you open a site with the US locale, then everything will break

**Comment by BulletQQ** [comment]
> @BulletQQ @framasev Hi. Can you check the new version, does it solve your problem?
> 
> https://stackblitz.com/edit/stackblitz-starters-twgftg?file=src%2Fmain.ts

I just checked and everything seems to be ok, thanks

**Comment by andriikamaldinov1** [comment]
@BulletQQ @framasev Thanks for using Ngx-Mask.
If you have any problems in the future please open a new issue with teamplate.
