### ISSUE TITLE
Number entered display goes from decimal, right to left

### ISSUE THREAD

**Issue by hjk2022** [JsDaddy/ngx-mask#1036]
### Description

I'm using `mask="separator.2" thousandSeparator=","` to format number input and working ok. Now, would like to see numbers-input appears from right to left. For example, entering `123`, display becomes
`0.01`

`0.12`

`1.23` 

### Describe alternatives you've considered

Have to use js?

**Comment by jefersonduwe** [comment]
The same a suggested here #523, but unfortunately they didn't understand;

**Comment by andriikamaldinov1** [comment]
Dublicate #827
