### ISSUE TITLE
Pad decimal values when they are 0

### ISSUE THREAD

**Issue by daniel-seitz** [JsDaddy/ngx-mask#1040]
### Description
I'd like to have an option in order to switch on showing the decimal 0s when i.e. a currency is entered.

<input mask="separator.2" thousandSeparator="." decimalMarker="," >

Enter 1
Instead of showing 1 €
I'd like to see 1,00 €

What about something like padDecimals="true"?

An alternative could be mask="separator.2!" (notice the **!**)

**Comment by nedimjahic** [comment]
Thus is exactly what we need. Any movement on the issue?

**Comment by CarlosBCIII** [comment]
I need this too...
