### ISSUE TITLE
Initial value not populating in input

### ISSUE THREAD

**Issue by KseinyaR-STCU** [JsDaddy/ngx-mask#1041]
# 🐞 bug report

### Is this a regression?

Have not checked previous versions.

### Description

When an input has an initial value on page load, the mask attribute stops the value from showing.

My repro has two input fields set to the same value. The first does not have the mask, and it shows the initial value. The second is using a mask and is showing blank on page load.

I expect the input field with the mask to show the initial value on page load.

## 🔬 Minimal Reproduction

https://codesandbox.io/s/optimistic-montalcini-815no3

```
import { Component, OnInit } from "@angular/core";
import { TimeoutError } from "rxjs";

@Component({
  selector: "app-root",
  template: ` <div>
    <strong> Initial value set </strong>
    <br />
    <span>Input without mask</span>
    <input [value]="testValue" />
    <br />
    <span>Input with mask</span>    
    <input [value]="testValue" mask="00-00" />
    <br />
    <button (click)="changeValue()">Click to change the value</button>
    <br /><br />
    <strong> Initial values with timeout </strong>
    <br />
    <span>Input without mask</span>
    <input [value]="timeoutValue" />
    <br />
    <span>Input with mask</span>
    <input [value]="timeoutValue" mask="00-00" />
  </div>`,
  styleUrls: ["./app.component.css"]
})
export class AppComponent implements OnInit {
  testValue = "1234";
  timeoutValue = "1111";

  changeValue() {
    this.testValue = "9876";
  }

  ngOnInit() {
    setTimeout(() => {
      this.timeoutValue = "4444";
    }, 0);
  }
}
```

## 🔥 Exception or Error

The mask attribute borks the initial value of the input field. If the value is changed (by typing in the field or programmatically via the button click), then the value shows.

## 🌍 Your Environment

**Angular Version:**

The repro has angular 12.2.0, but I'm seeing this in angular 14 as well.

**Comment by KseinyaR-STCU** [comment]
### Workaround

We have found a workaround that might help others. If you set the initial value in a setTimeout on page load, it will properly show in the UI. Even a timeout of 0ms works.

```
ngOnInit() {
    setTimeout(() => {
      this.timeoutValue = "4444";
    }, 0);
  }
```

**Comment by Maximaximum** [comment]
I'm still experiencing this issue

**Comment by andriikamaldinov1** [comment]
@KseinyaR-STCU @Maximaximum Thanks for your using Ngx-Mask. 
It example, all work as expected in all version angular 
16 - https://stackblitz.com/edit/angular-vxsicb?file=src%2Fmain.ts
12 - https://codesandbox.io/s/silent-snow-epnotg?file=/src/app/app.component.ts
