### ISSUE TITLE
Thousand separator not working well with decimal format

### ISSUE THREAD

**Issue by cqmdeveloper** [JsDaddy/ngx-mask#1044]
# 🐞 bug report

### Is this a regression?

 Not Really sure.

### Description

  I have a decimal number with dot(.) as decimal separator and I also have a comma (,) as thousands separator but when the number is displayed inside the input text it looks totally wrong.
If I change the thousands separator it starts to work, the same if I remove it but I still need the dot as decimal separator and the comma as thousands separator (i don't need it with locale settings)

this is exactly what documentation says about formatting.
![image](https://user-images.githubusercontent.com/90806762/200699354-93317b9b-08f1-46b2-81eb-8f4ebbfe3b18.png)

Any idea of what is going on here? or what i did wrong? please =) need your help

**Angular Version:**

![image](https://user-images.githubusercontent.com/90806762/200698508-47d490ad-8eef-4276-aa8f-5b81a0f1254c.png)

**Comment by belugasanity** [comment]
I'm also seeing this same issue in my project. I'm on Angular 14 as well. Does upgrading to 15 fix it?

**Comment by herickwilke** [comment]
We had to stop using ngx-mask in our project due this problem. Still can't find a solution.

**Comment by sbarranco** [comment]
Same issue here in v14. We had to stop using this in our project.

**Comment by andriikamaldinov1** [comment]
@sbarranco, @herickwilke @belugasanity @cqmdeveloper 
We just check all case with this thousandSeparator in stackblitz and its work as expected.
https://stackblitz.com/edit/angular-4kswwe?file=src%2Fmain.ts
Please check this example.
If still have a questions, please give us more details an examples.

**Comment by andriikamaldinov1** [comment]
@sbarranco @herickwilke @belugasanity @cqmdeveloper 
Thank you for using ngx-mask. 
I'm closing issue as everything works as expected.
If you have any problems in the future in using the ngx-mask, open issue using the template
