### ISSUE TITLE
Add Support for Directive Composition in Angular 15

### ISSUE THREAD

**Issue by zhaosiyang** [JsDaddy/ngx-mask#1049]
Error occurred when I tried to compose MaskDirective,
![image](https://user-images.githubusercontent.com/15252454/204951346-407b1fb3-4a11-44dc-8924-e3a8584455d3.png)

Is it possible to mark MaskDirective as `standalone: true` so that it becomes compatible with directive composition?

**Comment by NepipenkoIgor** [comment]
@zhaosiyang  Hi . Yes we will plan this next release.

**Comment by NepipenkoIgor** [comment]
@zhaosiyang  Please try ngx-mask version >= 15.0.0. If you will have any issues please create new by template
