### ISSUE TITLE
dropSpecialCharacters  not working

### ISSUE THREAD

**Issue by MehboobAshraf** [JsDaddy/ngx-mask#105]
I want to drop special characters of input value on binding.
I used dropSpecialCharacters property but its not working

**Comment by NepipenkoIgor** [comment]
@MehboobAshraf Could you provide example how you try to use this option ?

**Comment by MehboobAshraf** [comment]
<input type="text" name="cnicNumber" dropSpecialCharacters="true" mask="00000-0000000-0" maxlength="15" minlength="15"
                  class="form-control"
                   placeholder="CNIC Number" [(ngModel)]="cnic"  required> 
@NepipenkoIgor I tried to use this option like this.

**Comment by NepipenkoIgor** [comment]
@MehboobAshraf please use binding `[dropSpecialCharacters]="true"`. I will change doc in case `dropSpecialCharacters="true"` true is string not a boolean . Waiting for your feedback

**Comment by MehboobAshraf** [comment]
@NepipenkoIgor I just resolved it by removing this (dropSpecialCharacters="true"). may be it is true by default and yes my input is string

**Comment by NepipenkoIgor** [comment]
@MehboobAshraf  you should use boolean or string[ ]. In Array you can drop partial special characters
