### ISSUE TITLE
Documentation link leads to 404

### ISSUE THREAD

**Issue by rdebeasi** [JsDaddy/ngx-mask#1059]
# 🐞 bug report

### Is this a regression?

Yes. According to archive.org, the documentation link [previously redirected to the GitHub repo](https://web.archive.org/web/20210722022803/https://github.com/JsDaddy/ngx-mask).
### Description
The documentation link on the GitHub repo appears to be broken.

## 🔬 Minimal Reproduction
1. Click the link in the top right of the GitHub repo.
<img width="319" alt="Screen Shot 2022-12-29 at 10 12 32 AM" src="https://user-images.githubusercontent.com/1299370/209972779-b76de132-25bf-4f18-8a33-17c036dbf6c7.png">
2. A 404 error page appears.
<img width="1215" alt="Screen Shot 2022-12-29 at 10 09 26 AM" src="https://user-images.githubusercontent.com/1299370/209972816-3e1d5510-d5f4-46dd-9f29-2cd33d89ce22.png">

I'd expect this link to lead to https://jsdaddy.github.io/ngx-mask/.

Thank you!!

**Comment by NepipenkoIgor** [comment]
@rdebeasi  Thank you that using ngx-mask. Fixed
