### ISSUE TITLE
Issue with empty string using dropSpecialCharacters and showMaskTyped

### ISSUE THREAD

**Issue by tkhayden805** [JsDaddy/ngx-mask#1063]
**Description**
I have the following input:
`  <input
    formControlName="input"
    type="text"
    mask="(000) 000-0000"
    [dropSpecialCharacters]="false"
    [showMaskTyped]="true"
  />`
If I were to add a value such as 1234567890 and then remove all the characters and just have an empty string, the form value should be an empty string but it is "(".

**Minimal Reproduction**

https://stackblitz.com/edit/angular-ivy-gagkpe?file=src/app/app.component.html

- Type a phone number into the input field
- Delete all characters
- Expected field value should be "" but is "(".

Angular version: 15.1.1
ngx mask version: 12.0.0

**Comment by NepipenkoIgor** [comment]
@tkhayden805  Thank you that using ngx-mask. 
ngx-mask version 12 is pretty old and you should update it to latest version 15.0.2. You are using  ng15 and everything should be in sync
Please check example 
https://stackblitz.com/edit/angular-ivy-j8xwcm?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
Than i forked from you question
