### ISSUE TITLE
Passing decimalMarker in provideEnvironmentNgxMask(config) does not format initial decimal number correctly

### ISSUE THREAD

**Issue by jure123** [JsDaddy/ngx-mask#1066]
If we set` decimalMarker: ","` in `provideEnvironmentNgxMask(config)` in app.module.ts, initial decimal number won't format correctly in input field (eg. 12.34 will appear as 1234). However, it will be formatted correctly if we explicitely define `<input decimalMarker="," ...>`.

Reproduction:
https://stackblitz.com/edit/angular-13-zhsicj?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

First input field relies on config options provided in module.app.ts and is not displayed correctly:
```
provideEnvironmentNgxMask(provideEnvironmentNgxMask({
      decimalMarker: ',',
      thousandSeparator: '.',
    })
```

Second input explicitely defines: `<input decimalMarker="," thousandSeparator="." ... />` and is displayed correctly.

I think this issue started from version 15. It worked with <15 when default config was set as `NgxMaskModule.forRoot(maskConfig)`

**Comment by jure123** [comment]
I think this fix will solve this issue: https://github.com/JsDaddy/ngx-mask/compare/develop...jure123:ngx-mask:patch-1

**Comment by NepipenkoIgor** [comment]
@jure123  Please open PR and add relevant tests to cover this issue

**Comment by andriikamaldinov1** [comment]
@jure123  Thanks for using Ngx-mask and contributing. We merged your PR into develop. 
Please update ngx-mask to latest version.

**Comment by Apoorvneema98** [comment]
Module '"ngx-mask"' has no exported member 'NgxMaskModule' issue on angular 16
