### ISSUE TITLE
separator and 0* doesn't work together ? 

### ISSUE THREAD

**Issue by datskill** [JsDaddy/ngx-mask#1068]
Hey, 

i would like to have an input with numbers only and separator but without decimal numbers. 

I tried `mask="separator || 0*" ` but its not working 
![image](https://user-images.githubusercontent.com/17290172/216953966-9e38306f-3c49-4245-9810-c2c10ef2a440.png)

stackblitz : https://stackblitz.com/edit/ngx-mask-separator-it6sux?file=src/app/app.component.ts

Is this a bug or is there another way to achieve that ?  

thanks

**Comment by NepipenkoIgor** [comment]
@datskill  You need to use `mask="separator.0"`
Please update in your case mask to ngx-mask 8.1.0 or above 
I patched your example please check https://stackblitz.com/edit/ngx-mask-separator-qfjr2x?file=src%2Fapp%2Fapp.component.html
