### ISSUE TITLE
Input seleciontStart goes to wrong position after dynamic mask changes while typing

### ISSUE THREAD

**Issue by mikaelboff** [JsDaddy/ngx-mask#1069]
# 🐞 bug report

### Is this a regression?
No

### Description

Using dynamic mask (mask composed by two masks), when it changes from to smaller mask to the bigger one, the caret position (selectionStart) doesn't go to the end on the input, it stays on the middle of it, on the old position.

## 🔬 Minimal Reproduction
Editor:
https://stackblitz.com/edit/angular-ivy-mask-dynamic-issue?file=src%2Fapp%2Fapp.component.html

Browser:
https://angular-ivy-mask-dynamic-issue.stackblitz.io/

## 🔥 Exception or Error

![Reproduction](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExY2M3ZmYxZWZiMGNmYmY1MzEwNDIyZGM3YjZjODBhODc4MGY1OGQzNSZjdD1n/Pcd5gAVAUHVWIbNrev/giphy.gif)

## 🌍 Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.17
Node: 16.19.0 (Unsupported)
Package Manager: npm 8.19.3
OS: linux x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.17
@angular/cli                    12.2.17
@schematics/angular             12.2.17
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
ngx-mask version: 15.0.2

**Comment by mikaelboff** [comment]
@NepipenkoIgor Hello, I'm needing these to my enterprise project, best regards!!

**Comment by NepipenkoIgor** [comment]
@mikaelboff  Merged. And thank you that using ngx-mask and contributing . Ngx-mask 15.0.3 just published
