### ISSUE TITLE
Dynamic || operator does not work

### ISSUE THREAD

**Issue by tugando** [JsDaddy/ngx-mask#1071]
The following mask does not work, only the first case (2x numeric values) is allowed:

mask="00||SS"

According to the ngx-mask documentation (v15.0.2), both 2x numeric or 2x alpha values should be allowed.

**Comment by andriikamaldinov1** [comment]
@tugando Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-kdqwka?file=src%2Fmain.ts
