### ISSUE TITLE
NullInjectorError: No provider for NgxMaskPipe!

### ISSUE THREAD

**Issue by cmalard** [JsDaddy/ngx-mask#1072]
# 🐞 bug report

### Description

Hello there 🙋
Following the README, I can't make `ngxMaskPipe` works

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-13-qga3fs?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error

```
Error: R3InjectorError(AppModule)[NgxMaskPipe -> NgxMaskPipe -> NgxMaskPipe]:
NullInjectorError: No provider for NgxMaskPipe!
```

## 🌍 Your Environment

**Angular Version:**

```
"@angular/...": "15.1.5",
"ngx-mask": "15.0.2",
```

**Anything else relevant?**

I managed to make it work with
```
providers: [{ provide: NgxMaskPipe, useClass: NgxMaskPipe }],
```
but feels like a workaround :-)

**Comment by dougmbarcellos** [comment]
Try:

```ts
      imports: [
        ...,
        NgxMaskPipe,
      ],
      providers: [..., NgxMaskPipe, provideEnvironmentNgxMask()],
```

**Comment by NepipenkoIgor** [comment]
@cmalard  At first personally i don't like using pipe as a service. Pipe it is special things in Angular that we need to use in template . You could easily use `NgxMaskApplierService` for your purpose .
```
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, FormsModule],
  providers: [
    provideNgxMask(),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

And then 
```
  constructor(private readonly maskService: NgxMaskApplierService) {
    this.ibanMasked = this.maskService.applyMask(this.IBAN, this.IBAN_MASK);
  }
```
I just forked your example please look 
https://stackblitz.com/edit/angular-13-vtfzel?file=src/app/app.component.ts
