### ISSUE TITLE
Cursor jumps to the end when deleting first digit

### ISSUE THREAD

**Issue by shankar5147** [JsDaddy/ngx-mask#1073]
when editing 7,12,854 if 7 is deleted then cursor jumps to end. If it is 7,12,854 and if you delete 2 it works fine. but deleted first digit of 7 cursor jumps to end.

Angular CLI: 9.0.7
Node: 12.11.1
Angular: 9.0.7

**Comment by NepipenkoIgor** [comment]
@shankar5147  Hi . Thank you that using ngx-mask. If you still have issue please recreate it by suggested template . Very important to provide stackblitz
