### ISSUE TITLE
Fixed the value of input in  2 decimale 

### ISSUE THREAD

**Issue by Ombre2** [JsDaddy/ngx-mask#1076]
I use ngx-mask version ^13.1.15 

And i want fixed the value for example the real value is 237, 356 . I want the output of the ngx-mask show 237,36 

Can you help me please

**Comment by andriikamaldinov1** [comment]
@Ombre2  Thanks for using Ngx-mask. We add two new function "inputTransformFn" and "outputTransformFn".
It example with your case - https://stackblitz.com/edit/stackblitz-starters-tq4snm?file=src%2Fmain.ts
