### ISSUE TITLE
Special characters not displayed with pipe when mask contains asterisk

### ISSUE THREAD

**Issue by dominic-ks** [JsDaddy/ngx-mask#1077]
# 🐞 bug report

### Is this a regression?

No, I don't know if this has ever worked.

### Description

I am attempting to use a couple of simple masks for users to enter some measurement information, offering both imperial (ft / ins ) and metric (m / cm). Both of these are similar in what I need - I want users to be able to enter one or more digits for the first portion and optionally up to two digits for the second portion.

I have created these masks:

 - Imperial: 0*'09 - e.g. 1'11 or 11'1
 - Metric: 0*.09 - e.g. 2.22 or 22.2

This works fine when the mask is used for an input field, however, when passing the same values to the mask pipe with these masks, the deliminating character is not displayed. 

This _appears_ to be my use of the asterisk (*), since removing that or using a more specific mask without it allows the character to be displayed. 

## 🔬 Minimal Reproduction

 - https://stackblitz.com/edit/angular-ivy-dtfido?file=src/app/app.component.ts

## 🔥 Exception or Error

 - N/A

## 🌍 Your Environment

**Angular Version:**

 - 15.2.0

**Anything else relevant?**

No.

**Comment by NepipenkoIgor** [comment]
@dominic-ks  Hi. Thank you that using ngx-mask.  Yes Pipe worked in wrong way at all . Please use  version ngx-mask >= 15.1.0 . 
Also i updated you stackblitz https://stackblitz.com/edit/angular-ivy-9tx69j?file=src%2Fapp%2Fapp.component.html 
If you will have an issue please give me know

**Comment by dominic-ks** [comment]
Thanks, @NepipenkoIgor, that does indeed work for values when they are initially loaded (though looks like the suffix is omitted in your SB?). If you update the values in the inputs though, the special characters are lost again and the suffix is then added..?
