### ISSUE TITLE
Patch fix #1069 into 14.2 version for compatibility 

### ISSUE THREAD

**Issue by mikaelboff** [JsDaddy/ngx-mask#1079]
# 🚀 feature request

### Description

I'm wondering if it would be possible to patch the Fix ([#1069](https://github.com/JsDaddy/ngx-mask/issues/1069)) into version 14.2 and create version 14.2.5.

The reason to this is to maintain compatibility for projects with angular version < 14, since [This commit](https://github.com/mikaelboff/ngx-mask/commit/fc9c262f0a751ebc1d772cfe500cf1529f03f094#diff-9556503b7e3692c9f1b317e27dac8e2740d9c1a0d19c083dda59d9328a09a2d3) has changed the peer dependencies of angular version to >=14.0.0.

### Describe the solution you'd like

Patch the fix to 14.2 version and generate 14.2.5 to maintain compatibility.

### Describe alternatives you've considered

I've considered updating our entire enterprise angular application, but it is not on our next milestones.

**Comment by andriikamaldinov1** [comment]
@mikaelboff Thanks for using Ngx-mask. We did a downgrade with a lot of fixes from version 16 to version 14. Use version 14.3.0 for angular 14.
It example with version 14 angular - https://stackblitz.com/edit/angular-14-demo-a4oupv?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fmain.ts,src%2Froutes.ts
