### ISSUE TITLE
Mask does not apply dynamically on v1.0.3

### ISSUE THREAD

**Issue by vkansal77** [JsDaddy/ngx-mask#108]
need the same below functionality in v1.0.3 because my project is compatible with this version only. reason is project dependencies, please let me know how soon this can be available in v1.0.3

https://stackblitz.com/edit/angular-cicjvx?file=app%2Fapp.component.ts

**Comment by NepipenkoIgor** [comment]
@vkansal77 We will  try to answer your question tomorrow.  We should investigate code base for this achievement

**Comment by vkansal77** [comment]
please also let me know which version is compatible with the below dependencies, only v1.0.3 works if i use any other version i get ERROR in Error: Metadata version mismatch for module ngx-mask/ngx-mask.d.ts, found version 4, expected 3 

"@angular-devkit/core": "^0.4.5",
    "@angular/animations": "^4.4.6",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",

**Comment by vkansal77** [comment]
i have one issue , if i have postal code like this 'A9A 9A9' ...i just want user to type in this format only. but currently it allows digits '222 222'. please let me know if there is way to achieve that user can type on A9A 9A9.

**Comment by vkansal77** [comment]
i have another question if don't have format then mask keeps the last format. can i pass null to mask ?

**Comment by NepipenkoIgor** [comment]
@vkansal77 Hi. latest version with major bug fixes compatible with versions 6+ . You should upgrade project to current stack
