### ISSUE TITLE
[QUESTION] - Is there any way to change mask key input?

### ISSUE THREAD

**Issue by FernandoIberian** [JsDaddy/ngx-mask#1081]
Hi! Thank you for the work on this library. Currently i'm using this mask:
`<input mask="separator.2" thousandSeparator=".">` which gives a result like: "1.000.000,32"

That's the expected output, but I would like to know if it is possible that if you pressed the key "." (Period), a ","(Comma) will be replaced instead. Periods on thousand are placed automatically, but i need to change "Period" input to "Comma" input (only for decimals).

So far i've tried with keydown/up events and nothing worked. Is there any way i could get this working? Thank you!

**Comment by andriikamaldinov1** [comment]
@FernandoIberian Thanks for your using Ngx-Mask.  You can change this from [decimalMarker]
It example - https://stackblitz.com/edit/angular-m2xtu8?file=src%2Fmain.ts
