### ISSUE TITLE
NullInjectorError after upgrading from ngx-mask v15.0.2 to v15.1.0

### ISSUE THREAD

**Issue by syamanashi** [JsDaddy/ngx-mask#1087]
# 🐞 bug report

### Is this a regression? YES

 Yes, the previous version in which this bug was not present was: 15.0.2

### Description

 When injecting NgxMaskApplierService into a component in order to utilize the applyMask method, the NullInjectorError is thrown:

<pre><code>
NullInjectorError: No provider for NgxMaskApplierService!
</code></pre>

## 🔬 Minimal Reproduction

Version 15.0.2 example with no error (before regression introduced):
https://stackblitz.com/edit/angular-13-3n9nqh?file=src/app/app.component.html

Version 15.1.0 example with error (demonstrates regression):
https://stackblitz.com/edit/angular-13-yaiykc?file=package.json

## 🔥 Exception or Error

<pre><code>

ERROR NullInjectorError: R3InjectorError(AppModule)[NgxMaskApplierService -> NgxMaskApplierService -> NgxMaskApplierService]: 
  NullInjectorError: No provider for NgxMaskApplierService!
    at NullInjector.get (provider_collection.ts:46:1)
    at R3Injector.get (r3_injector.ts:303:48)
    at R3Injector.get (r3_injector.ts:303:48)
    at R3Injector.get (r3_injector.ts:303:48)
    at ChainedInjector.get (component_ref.ts:135:4)
    at lookupTokenUsingModuleInjector (di.ts:380:1)
    at getOrCreateInjectable (di.ts:434:50)
    at Object.ɵɵdirectiveInject (shared.ts:62:17)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:9:26)
    at getNodeInjectable (di.ts:640:31)

</code></pre>

## 🌍 Your Environment

**Angular Version:** 15.1.1

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by znotdead** [comment]
I think you can use NgxMaskService instead

**Comment by NepipenkoIgor** [comment]
Hi all. @znotdead  You are totally right. @syamanashi  NgxMaskApplierService is not using directly and from ngx-mask v15.1.1 is not a part of public API at all. 
I just fix your example , please look 
https://stackblitz.com/edit/angular-13-wv9dxv?file=package.json,src%2Fapp%2Fapp.component.ts

**Comment by syamanashi** [comment]
> Hi all. @znotdead You are totally right. @syamanashi NgxMaskApplierService is not using directly and from ngx-mask v15.1.1 is not a part of public API at all. I just fix your example , please look https://stackblitz.com/edit/angular-13-wv9dxv?file=package.json,src%2Fapp%2Fapp.component.ts

Roger that.  Thank you, Igor!
