### ISSUE TITLE
Add trailing zeros to an input that's tied to a value, for example "2,7" shown as "2,700" but value being 2,7

### ISSUE THREAD

**Issue by YavuzDev** [JsDaddy/ngx-mask#1088]
# 🚀 feature request

Is it possible to add trailing zeros to an input that's binded to a value so for example 2,7 shown as 2,700 but the value being 2,7.
I still want to be able to edit it to 2,75 for example and then it should show 2,750 or if it's 2 it should show 2,000.

 A clear and concise description of the problem or missing capability...

so for example this code:

`<input type="text" placeholder="{{'grid.ltv-grid.haircut-construction-deposit' | translate}}"
                       mask="separator.3" [decimalMarker]="decimalMarker" [thousandSeparator]="thousandSeparator"
                       [(ngModel)]="ltvMatrix.constructionDepositHaircut"
                       [ngClass]="{'invalid': !haircutConstructionDepositIsValid()}"
                       [disabled]="!showEditFunctionality()"/>`

it's tied to a value and that value is for example "1,5" I want it to show "1,500".
Or if it's "1,52" it should show "1,520" and if it's "1" I want it to show "1,000"

 If you have a solution in mind, please describe it.

I do not, I have tried asking chatgpt but it couldn't figure it out

 Have you considered any alternative solutions or workarounds?

No I have not

**Comment by andriikamaldinov1** [comment]
@YavuzDev Thanks for your using Ngx-Mask. Please update to latest version.
We add leadZero for separator to add zeros to the end of model - https://stackblitz.com/edit/angular-suuti3?file=src%2Fmain.ts
