### ISSUE TITLE
Error on dynamic mask 

### ISSUE THREAD

**Issue by FilipeTabosa** [JsDaddy/ngx-mask#109]
Version: 2.6.3

I am getting an error on updating a dynamic mask. On the country that I live a cellphone may have two different patterns. 
The first one is "(00)0000-0000" ->(10 digits)
The second one is "(00)00000-0000" -> (11 digits). 

I would like to update the pattern as the user is typing. if the cellphone number has 10 digits or less it will show the first case, otherwise it will show the second mask.

to do so, I am using the following code:

 ` <input id="cellphone" [(ngModel)]="newUser.cellphone" (ngModelChange)="onChangeCellphone($event)" name="cellphone" type="text" mask="{{cellphoneMask | async}}" [dropSpecialCharacters]="false" class="form-control">
`
where cellphoneMask is declared on the typescript:

```
 @Input()
  public cellphoneMask: Subject<string> = new Subject();
```

and updated according to the value from the event found on (ngModelChange)

```
  onChangeCellphone(event) {
    console.log(event.length);
    console.log(event);
    if (event.length <= 13) {
      console.log("first mask");
      this.cellphoneMask.next('(00)0000-00000'); // I've put an extra value here in order to have the same number of characters from the second-mask.

    } else {
      console.log("second mask");
      this.cellphoneMask.next('(00)00000-0000'); 

    }
  }
```

The update is happening as intended, and whenever I type the 11º digit the second console.log is triggered as intended; However, the displayed mask is not updated. If I try to type a 12º digit, the number does not appear, as intended, but the displayed mask is updated. It is like the mask is not assyncronous and only updates on its second call.

**Comment by NepipenkoIgor** [comment]
@FilipeTabosa Thanks, we will investigate  this.

**Comment by FilipeTabosa** [comment]
Update:

I download the libbrary and tried to reproduce this error.  So I managed  to figure you that it was happening because the function "onInput()" was being called before "maskExpression". So if I changed the mask from my input it would not happen until another Input request was emitted. 

I tried putting the following code on the maskExpression:

```
 @Input('mask')
  public set maskExpression(value: string) {
    console.log(value);
	console.log(this._maskValue);
	this._maskValue = value || '';
	
    if (!this._maskValue) {
      return;
    }
    this._maskService.maskExpression = this._maskValue;
    this._maskService.maskSetter$$.emit(this._maskValue);
	let caretShift: number = 0;
    this._maskService.applyValueChanges(
      0,
      (shift: number) => caretShift = shift
    );
  }
```
This is far from the best solution and emits an  ExpressionChangedAfterItHasBeenCheckedError, but with that I could manage to find where the problem was happening. I will try to figure out a better way to fix it

**Comment by FilipeTabosa** [comment]
I made some modifications on the last code that I put, mostly to fix tslint mistakes.  I did not find any better way to avoid ExpressionChangedAfterItHasBeenCheckedError than using a timeout. Feel free to make suggestions/modifications =).

```
 @Input('mask')
  public set maskExpression(value: string) {
    // Checks whether there is a previous and a current mask value in order
    // to validate if the user is trying to change the mask from the input.
    let diffMasks: boolean = false;
    if (value !== null && this._maskValue !== null) {
      diffMasks = true;
    }
    this._maskValue = value || '';
    if (!this._maskValue) {
      return;
    }


    this._maskService.maskExpression = this._maskValue;
    this._maskService.maskSetter$$.emit(this._maskValue);
    // Case the user is trying to change the mask from the input, call applyMaskOnMaskUpdate();
    if (diffMasks) {
      // Uses a timeout to avoid ExpressionChangedAfterItHasBeenCheckedError
      setTimeout(() => {
        this._maskService.applyMaskOnMaskUpdate();
      }, 0);
    }
  }
```

**Comment by NepipenkoIgor** [comment]
@FilipeTabosa  Hi. Thank you. I tried fix. Please try new v 2.7.4

**Comment by FilipeTabosa** [comment]
Working perfectly, thank you!
