### ISSUE TITLE
rxjs@6 support

### ISSUE THREAD

**Issue by midrissi** [JsDaddy/ngx-mask#110]
Version: 2.6.3

I have migrated my application to the latest version of angular (6.0.0) and to the latest rxjs version (6.1.0).

When I start the application, I get the following error:
```sh
ERROR in ./node_modules/ngx-mask/esm5/ngx-mask.js
Module not found: Error: Can't resolve 'rxjs/operators/take' in 'node_modules/ngx-mask/esm5'
```

**Comment by NepipenkoIgor** [comment]
@midrissi Hi , thanks for PR .  I removed rxjs from code and update all deps . Please try new version

**Comment by midrissi** [comment]
Fixed! Thanks a lot :-)
