### ISSUE TITLE
dropSpecialCharacters does not return a suffix

### ISSUE THREAD

**Issue by KhrystynaPr** [JsDaddy/ngx-mask#1101]
dropSpecialCharacters="false" returns the prefix but not the suffix
is there a way not to skip the suffix?

 "ngx-mask": "^15.0.2",

 [dropSpecialCharacters]="false"
input: 12.44%
output: 12.44

**Comment by NepipenkoIgor** [comment]
@KhrystynaPr  Hi. Thank you that using our ngx-mask .Please update ngx mask and use mask version >=15.1.2 .
As example you could check https://stackblitz.com/edit/angular-uvhshl?file=src%2Fmain.ts
