### ISSUE TITLE
Problems after updating to 15.1.0 from 14.0.3 with special characters.

### ISSUE THREAD

**Issue by Angeltariel** [JsDaddy/ngx-mask#1103]
Hi everyone. 
I have an interesting problem after updating. In the 14 version all work well, but in the 15 something go wrong.

I use a custom mask like this '(000) 000-0000 ext. 999999' with shownMaskExpression like this '(___) ___-____ ext. ______'.

But after the update, this mask doesn't work. I spent some time investigating this moment. 
And I don't know why but the problem is in the symbol 't'. If we removed this symbol from the mask all start to work. 
And another case is if we don't remove the symbol 't' but use one pattern like  '(000) 000-0000 ext. 000000' all work too.

Can somebody help me with this moment? Here are some examples: https://stackblitz.com/edit/angular-bucehu?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@Angeltariel Thank you for using ngx-mask. Please update ngx-mask to latest version.
https://stackblitz.com/edit/angular-klmced?file=src%2Fmain.ts

**Comment by Angeltariel** [comment]
@andriikamaldinov1 Thanks for fixing this point, much appreciated!
