### ISSUE TITLE
Unable to set mask by decimals using TS.

### ISSUE THREAD

**Issue by joseserrano15** [JsDaddy/ngx-mask#1111]
Hello everyone, I'm trying to set a mask for keep always a specific number of decimals using TS. 
I'm using `this.maskService.applyMask('8768', '0*.00')`
The output I expect is **8768.00**, but I have the same value **8768**.
Is there something that I am doing wrong or that I am missing to add?
Thanks.

**Comment by andriikamaldinov1** [comment]
@joseserrano15 Thanks for using Ngx-Mask. Please update to latest version.
We added a new feature:
1) outputTransformFn => it transformed value in model
2) inputTransformFn => it transformed value in input when user type
It example with ur case and with inputTransformFn - https://stackblitz.com/edit/angular-tddhiz?file=src%2Fmain.ts

**Comment by joseserrano15** [comment]
Awesome! Thanks for the new features and the example.
