### ISSUE TITLE
When using mask="separator.X" the value in the input is displayed without zeros at the end

### ISSUE THREAD

**Issue by gloammer** [JsDaddy/ngx-mask#1115]
# 🚀 feature request

### Describe the solution you'd like

Hi!
I faced a case like this:

When using `mask="separator.4"` the mask removes zeros at the end of the number, for example if I specify `4` decimal places the number `0.0300` will appear as `0.03` when I change the value of the input.

The approach with a mask `0*.0000` works differently, with the value of the input is `0.0300` and its subsequent change the value will still contain zeros.

Here is a small example that describes the situation: https://stackblitz.com/edit/angular-bvr1zk?file=src/main.ts

This issue seems to describe a similar situation: https://github.com/JsDaddy/ngx-mask/issues/1088

### Describe alternatives you've considered

I think they should work the same way and not hide zeros.

To do this, in the method `numberToString` in `toLocaleString` we should  pass value of `minimumFractionDigits`, which must be equal to `X` from `mask="separator.X"`

```
public numberToString(value: number | string, minimumFractionDigits: number): string {
        if (!value && value !== 0) {
            return String(value);
        }

        return Number(value).toLocaleString('fullwide', {
            useGrouping: false,
            maximumFractionDigits: 20,
            minimumFractionDigits
        });
    }
```

**Comment by andriikamaldinov1** [comment]
@gloammer Thanks for your using Ngx-Mask. Please update to latest version.
We add leadZero for adding zero to the end of model - https://stackblitz.com/edit/angular-suuti3?file=src%2Fmain.ts
