### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Maximaximum** [JsDaddy/ngx-mask#1134]
Hello!

Would you mind releasing a version that supports Angular 16 please?

Thank you

**Comment by NepipenkoIgor** [comment]
@Maximaximum  Yes . we plan to release next couple days

**Comment by andesonline20** [comment]
Hi @NepipenkoIgor ,
Im not sure but is the compatibility for Angular 16 is release ? I have some issue on my project regarding on the ngx-mask
![image](https://github.com/JsDaddy/ngx-mask/assets/13011050/6720b381-c3ca-4b98-bc02-9ba2575fa12e)

currently the version of ngx-mask on my project is ^15.1.4.

I hope you can help me on this issue.

Thank you :)

**Comment by NepipenkoIgor** [comment]
@andesonline20  Hi . Public API allow only access to directive, pipe, service, provides and config.  You need import directive itself and set needed providers . Please check documentation for more information .

**Comment by NepipenkoIgor** [comment]
@korjikk  Yes .  We wanted to fix some issues before ng16 . A believe next week we will be able to release . Maybe earlier .

**Comment by NepipenkoIgor** [comment]
@Maximaximum @korjikk  Version 16.0.0 available . Please check and if you will have some problems please create issues by template with stackblitz example
