### ISSUE TITLE
Better changelog

### ISSUE THREAD

**Issue by weilinzung** [JsDaddy/ngx-mask#1143]
The current changelog is not helpful: https://github.com/JsDaddy/ngx-mask/blob/develop/CHANGELOG.md

**Comment by NepipenkoIgor** [comment]
@weilinzung  Hi. We could discuss this .  Do you have some thoughts ? Some examples ?

**Comment by weilinzung** [comment]
@NepipenkoIgor  the most common one is using https://github.com/semantic-release/semantic-release to handle it

**Comment by NepipenkoIgor** [comment]
@weilinzung Thank you . We will investigate and improve this part. But any way you could help and contribute this issue with PR

**Comment by andriikamaldinov1** [comment]
@weilinzung Thanks for using Ngx-mask. We added semantic-release, and close this issues.
