### ISSUE TITLE
Percentage mask is not working when Upgrading from version 14 to 15

### ISSUE THREAD

**Issue by lizelleboshoff** [JsDaddy/ngx-mask#1146]
Hi,

We currently make use of the Percentage mask along with Angular.  After upgrading from version 14 to version 15 the percentage suffix is now included in the Model value.  

This is how it is implemented:
mask="percent.2" [dropSpecialCharacters]="false" suffix="%" 

Version 14.2.4:
Model value is without the suffix eg. 75.25

Version 15.1.3:
Model value includes the suffix eg. 75.25%.  This breaks any calculations or validations.

If I set dropSpecialCharacters to true it removes the suffix but it also removes the decimal point. eg 7525.

Can you please assist.

**Comment by andriikamaldinov1** [comment]
@lizelleboshoff Thank you for using ngx-mask. Please update ngx-mask to latest version.
Check this example, all work as expected - https://stackblitz.com/edit/angular-fvftg4?file=src%2Fmain.ts

**Comment by lizelleboshoff** [comment]
Hi @andriikamaldinov1 , I had a look at your example and even your example is not working.
In your example it removes the percentage sign AS WELL as the Decimal point.

![image](https://github.com/JsDaddy/ngx-mask/assets/48944540/e7b27ff2-e731-46ef-a316-9dd3f160c257)

75.89% is shown as 7589
Can you please relook at your example and revert back to me?

Thank you.

**Comment by andriikamaldinov1** [comment]
@lizelleboshoff Please update ngx-mask to latest version.
Input valu 75.89=> formControl.value 75.89. It work as expected 
https://stackblitz.com/edit/angular-fvftg4?file=src%2Fmain.ts

**Comment by lizelleboshoff** [comment]
Thank you very much.
We are not on Angular 16 yet because we are still waiting for other third-party packages to be upgraded to Angular 16.  I will wait until we can upgrade.

**Comment by sadalsuud** [comment]
I am on angular v15 but lastest version 16.2.2 is not compatible with angular 15 ...   :disappointed:
