### ISSUE TITLE
Did not reset field with mask directive when send form but this fields is not valid

### ISSUE THREAD

**Issue by LimarenkoDenis** [JsDaddy/ngx-mask#115]

**Comment by LimarenkoDenis** [comment]
My Reproduceing
Dynamically create phone control field, 
type a value and it became valid, but when I submit a form and reset values, all field as expected reset, except field with the mask directive

**Comment by tylerstarcher** [comment]
Might be close to the same thing, have a form with a masked field that is not touched or dirty. When I submit that form and reset the form, with values being set to the form values that are submitted (for context, its a profile form), the masked field then becomes dirty.

**Comment by Coffee-Tea** [comment]
I have the same issue: form.reset() reset value in the form and masked fields but visually fields contain (don't clear) values.

**Comment by brenoprata10** [comment]
You can always set the formControl value to empty string and then call the reset function, this worked for me:
`this.formGroup.get('FORM_CONTROL').reset();`
`this.formGroup.get('FORM_CONTROL').setValue('');`
