### ISSUE TITLE
ngx-mask version 16.x.x not compatible with Angular 15

### ISSUE THREAD

**Issue by jure123** [JsDaddy/ngx-mask#1150]
If we install ngx-mask@16.0.2 in Angular 15 project and import NgxMaskDirective in angular module, we get the following build error:

```
Error: node_modules/ngx-mask/lib/ngx-mask.directive.d.ts:68:114 - error TS2344: Type '{ maskExpression: { alias: "mask"; required: false; }; specialCharacters: { alias: "specialCharacters"; required: false; }; patterns: { alias: "patterns"; required: false; }; prefix: { alias: "prefix"; required: false; }; ... 14 more ...; triggerOnMaskChange: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"maskExpression"' is incompatible with index signature.
    Type '{ alias: "mask"; required: false; }' is not assignable to type 'string'.

static ɵdir: i0.ɵɵDirectiveDeclaration<NgxMaskDirective, "input[mask], textarea[mask]", ["mask", "ngxMask"], ....
```

This is because @angular/core@15.x.x has different `ɵɵDirectiveDeclaration -> InputMap` signature than Angular Core 16.

Angular 15 - https://github.com/angular/angular/blob/15.2.x/packages/core/src/render3/interfaces/public_definitions.ts
`InputMap extends {[key: string]: string},`

Angular 16 - https://github.com/angular/angular/blob/16.0.x/packages/core/src/render3/interfaces/public_definitions.ts
`InputMap extends {[key: string]: string|{alias: string|null, required: boolean}},`

Unfortunately ngx-mask@16.x.x compiles with the new declaration not compatible with older Angular.

Maybe it would be a good solution to downgrade ngx-mask back to Angular 15 Core and recompile it, which will probably make it compatible with all Angular 14+ versions. Unless ngx-mask@16 uses some Angular 16 specific features (I think it doesn't) it's not advisable that you upgrade to the latest Angular core. This is problematic for our Angular 14,15 projects that rely on ngx-mask and we cannot easily upgrade to Angular 16.

Kindly ask you to consider this idea.

**Comment by wnabil** [comment]
Why not upgrading your project to Angular 16 ?

**Comment by wnabil** [comment]
14.2.4 is working fine for me with angular 15

**Comment by lucasferreiraz** [comment]
> 14.2.4 is working fine for me with angular 15

It's a stopgap solution that worked for me, thank you very much.

My Angular project was on version 15.2.8 and I was trying to use ngx-mask version 16.0.8 and getting the same error, I downgraded to version 14.2.4 and it worked normally.

**Comment by NepipenkoIgor** [comment]
@notchris  Currently yes . We will make LTS version a little bit later . Focused on current stable version for ng16

**Comment by Et3rnal** [comment]
Same issue

├── @angular-devkit/build-angular@15.2.8
├── @angular/animations@15.2.9
├── @angular/cli@15.0.5
├── @angular/common@15.2.9
├── @angular/compiler-cli@15.2.9
├── @angular/compiler@15.2.9
├── @angular/core@15.2.9
├── @angular/router@15.2.9
├── ngx-mask@16.2.4
├── tslib@2.5.3
├── typescript@4.8.4
└── zone.js@0.12.0

ngx-mask@15.1.5 (latest 15) seems to build fine under angular 15
https://github.com/JsDaddy/ngx-mask/blob/develop/CHANGELOG.md#15152023-05-12

**Comment by abhijit-chikane** [comment]
you can check the package version compatibility [here](https://ngx-libs.com/?search=mask&versions=16,15,14,13,12)

**Comment by Saiuke** [comment]
It is still not working for me. I'm trying the version `16.2.9` in an Angular `15.0.1` project.

**Comment by abhijit-chikane** [comment]
> It is still not working for me. I'm trying the version `16.2.9` in an Angular `15.0.1` project.

It will not
Please check compatibility
Please install v15

**Comment by bertdewolf** [comment]
Will this be fixed so that we can use 16.x.x in angular 15 projects? I cannot simply upgrade the whole project and version 15.x.x of ngx-mask is buggy.

**Comment by andriikamaldinov1** [comment]
@bertdewolf @Saiuke @October1988 @abhijit-chikane @Et3rnal @notchris @lucasferreiraz @wnabil @jure123 
Thanks for using Ngx-mask. We did a downgrade with a lot of fixes from version 16 to version 15. Use version 15.2.0 for angular 15.
It example with version 15 angular - https://stackblitz.com/edit/angular-ivy-u5zutw?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html
