### ISSUE TITLE
Backspace doesnt work

### ISSUE THREAD

**Issue by DopamineLady** [JsDaddy/ngx-mask#1155]
Hello! :)

Its amazing project, but if I want to delete a value in input by backspace and its longer than 6 characters and I have separator and suffix there, I cant delete it by backspace.

Can you help me, please? 

mask: 'separator': {thousandSeparator: ',', suffix: ' sm' -> something like this :) 

Thanks a lot! 

If you have any questions, please let me know, I can show you this case.

**Comment by andriikamaldinov1** [comment]
@DopamineLady Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected  - https://stackblitz.com/edit/angular-j3wim1?file=src%2Fmain.ts
Or maybe we did something wrong, if so make an example on stackblits
