### ISSUE TITLE
Especific mask for NgModel

### ISSUE THREAD

**Issue by viniciosyals** [JsDaddy/ngx-mask#116]
Exemple

Input: 00/00/0000
NgModel: 0000-00-00

This is possible?

**Comment by NepipenkoIgor** [comment]
@viniciosyals interesting new feature . We will discuss this and maybe try to implement

**Comment by NepipenkoIgor** [comment]
@viniciosyals it is current functionality.  You should use 
`mask="0000-00-00"  [dropSpecialCharacters]="false"`
