### ISSUE TITLE
hiddenInput bug - paste with whitespace

### ISSUE THREAD

**Issue by Kondziowsky** [JsDaddy/ngx-mask#1167]
# 🐞 bug report

### Is this a regression?

 Not sure about it.

### Description

 Strange behaviour of [hiddenInput]="true" when creating a simple masked input. When you copy and paste number with whitespace there is unexpected changes for value.

## 🔬 Minimal Reproduction

 I reproduced my issue on stackblitz: 
https://stackblitz.com/edit/angular-ngxmask-hiddeninput-issue-kdjdnu

Additional: try to paste '123456 ' multiple times for sure

## 🌍 Your Environment

**Angular Version:**

<pre><code>

 Angular v15, more details in stackblitz

</code></pre>

**Comment by andriikamaldinov1** [comment]
@Kondziowsky Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-ngxmask-hiddeninput-issue-hkwtu1?file=src%2Fapp%2Fapp.module.ts

In the future we are planning a smaller version of the Angular 16
