### ISSUE TITLE
repeat pattern for letters does not work with other repeat patterns

### ISSUE THREAD

**Issue by Skwal98** [JsDaddy/ngx-mask#1169]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 16.0.8

### Description

It's not possible to use a repeat pattern **S**{(count)}, f.e. 'S{2}' with any other repeat pattern.
`A{5}.0{2}` - correct
`A{5}.A{2}` - correct
`A{5}.S{2}` - it's impossible to write more than one character

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-rojoqm?file=src%2Fmain.ts

## 🌍 Your Environment

**Angular Version:**

<pre><code>
angular v16.0.5

</code></pre>

**Comment by andriikamaldinov1** [comment]
@Skwal98  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/stackblitz-starters-vfja6t?file=src%2Fmain.ts
