### ISSUE TITLE
Metadata version mismatch for module E:/projects/COCOA/mnbx3/ManagerBox3/angular-src/node_modules/ngx-mask/ngx-mask .d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by mrjleo198901** [JsDaddy/ngx-mask#117]
Hi guys,
Pls I have this issue, I downloaded the latest version of this library, BUT i got this error:
Metadata version mismatch for module E:/projects/COCOA/mnbx3/ManagerBox3/angular-src/node_modules/ngx-mask/ngx-mask
.d.ts, found version 4, expected 3,....

I'm using angular 4.3.6

Greetings

**Comment by marcusvmdomingos** [comment]
Same error here.

angular 4.2.0
