### ISSUE TITLE
Leadzero do not work on blur, but only after refresh page

### ISSUE THREAD

**Issue by gerwinbouwhuis** [JsDaddy/ngx-mask#1182]
# 🚀 feature request

Hi there!

Leadzero is fixed in https://github.com/JsDaddy/ngx-mask/issues/1115,
if you use it with as example:  
separator.3 
leadzero=true 

and you type in the input 10.2 and you go outside the input field, the value is not update to 10.200, 
only after refresh the page.

I think it would be nice if the value is updated also on blur.

**Comment by NepipenkoIgor** [comment]
@gerwinbouwhuis  Hi . Could you provide stackblitz

**Comment by gerwinbouwhuis** [comment]
https://stackblitz.com/edit/stackblitz-starters-ch25ng?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@gerwinbouwhuis  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/stackblitz-starters-eny7fx?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@gerwinbouwhuis   Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/stackblitz-starters-bdozqb?file=src%2Fmain.ts

**Comment by gerwinbouwhuis** [comment]
@andriikamaldinov1 Thank you very much for the quick fix, it works as expected :)
