### ISSUE TITLE
Prefix of '$' results in angular reactive form value of zero upon erasing

### ISSUE THREAD

**Issue by russcarver** [JsDaddy/ngx-mask#1184]
# 🐞 bug report

### Is this a regression?

Unknown

### Description

When using a currency mask inside of an Angular Material reactive form field, the value of the form control is being set to zero when the user erases all input.

## 🔬 Minimal Reproduction

```
    <mat-form-field floatLabel="always">
      <mat-label id="amountLabel" [innerHTML]="amountLabel"></mat-label>
      <input aria-labelledby="amountLabel" autocomplete="off" formControlName="amount" mask="separator.2"
                 matInput prefix="$" thousandSeparator=",">
    </mat-form-field> 
    
     amount: new FormControl<undefined | string>(undefined)
```

## 🔥 Exception or Error

When I listen to the valueChanges Observable of the form field, the value shows zero (number, not string) when erased. If I remove the "prefix" attribute, all is fine (the value is an empty string).  The field is NOT a required field.

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.0
Node: 16.15.1
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.12
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.2.12
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.4.0
typescript                      4.7.4
</code></pre>

Unknown if this is a problem with Angular Material or just Angular or a specific browser. I'm using Chrome on an M2 Max Macbook Pro (Version 114.0.5735.198 (Official Build) (arm64))

**Comment by russcarver** [comment]
For a work-around, I'm listening to the field with a "(keyup)" and if "Backspace" or "Delete" was pressed, I then set the field value to "undefined" if the field has only "$".

**Comment by andriikamaldinov1** [comment]
@russcarver Could you provide stackblitz or another environment ?

**Comment by russcarver** [comment]
@andriikamaldinov1 

Here it is: https://stackblitz.com/edit/angular-t9dzh6-5hy5vu?file=src%2Fapp%2Fapp.css,src%2Fapp%2Fapp.html,src%2Fapp%2Fapp.ts

If you add a value and then erase it, you'll see the result is reported as zero.  It should be an empty string.  Note, that my FormControl is of type "string", but the value (in the `valueChanges`) comes out as a "number". I suspect this has something to do with the mask. 

Having a value of type string is important to my app. Since HTML `<input>` of `type="number"` does not work consistently in all browsers, my numerice fields are all of type string and I have a custom validator that handles invalid data.

Regardless, when the value is erased, I need to send an unused value to the server (-1 in this case since -1 is not a valid value of the field in my full app).  Zero is not allowed either in my validation this field (my full app shows an error when zero).

All other Angular Material fields (without a mask) return an empty string when erased (see the non-masked field in the example).

If you can't produce an empty string in this scenario with the mask, perhaps add a parameter allowing a user to specify the value when it's erased?

**Comment by andriikamaldinov1** [comment]
@russcarver Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-oecgmb?file=src%2Fmain.ts

**Comment by russcarver** [comment]
Unfortunately, I cannot yet. It appears your 15.x version is tied to Angular 15 and your 16.x version is tied to Angular 16. We are not able to upgrade to either for several more months yet.

**Comment by russcarver** [comment]
Finally had a chance to upgrade and it worked great!
