### ISSUE TITLE
hiddenInput not showing remaining mask characters with showMaskTyped

### ISSUE THREAD

**Issue by quis0** [JsDaddy/ngx-mask#1186]
# 🐞 bug report

### Is this a regression?

 No, tried in 15.1.5 and 16.0.6

### Description

 Remaining part of the mask (placeHolderCharacters) not showing up when hiddenInput is true

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-nuifs2?file=src%2Fmain.ts

## 🌍 Your Environment

**Angular Version:**

<pre><code>@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@schematics/angular             15.2.9
rxjs                            7.5.4
typescript                      4.8.4
</code></pre>

**Comment by andriikamaldinov1** [comment]
@quis0 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-naa3lf?file=src%2Fmain.ts
