### ISSUE TITLE
mask and hide doesn't work together when special char is there

### ISSUE THREAD

**Issue by SafNaaz** [JsDaddy/ngx-mask#1191]
how to make masking and unhiding using eye icon make work together?

<input [patterns]="accountNumberPattern" [hiddenInput]="true" mask="000-00-0000">

accountNumberPattern: { 0: { pattern: new RegExp('\d'), symbol: '*' } }

this works fine.

problem is suppose

1, I input 123-4 (masked way), on clicking on eye icon, its showing only 4

2, I input 123-45 (masked way),on clicking on eye icon, all fine

3, I input 123-45-6 (masked way), on clicking on eye icon, its showing only 6

3, I input 123-45-67 (masked way), on clicking on eye icon, all good

just for the 2 cases, its behaving weird. might be something to do with separator. but what to do?

**Comment by andriikamaldinov1** [comment]
@SafNaaz Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-idq44b?file=src%2Fmain.ts

**Comment by SafNaaz** [comment]
Great! Thank you!

One minor observation,

If any blank space there, then also issue is there

Eg 000-00-0000 works fine. But 000 - 00 - 0000 doesn’t work. 

Please fix this as well if possible

**Comment by rushabh-wadkar** [comment]
> @SafNaaz Thanks for your using Ngx-Mask. Please update to latest version. It example, all work as expected - https://stackblitz.com/edit/angular-idq44b?file=src%2Fmain.ts

Hey @SafNaaz We are using ngx-mask@12 and we have @angular version set to v12 only. It's not possible for us to upgrade the angular version due to the timelines. Is it possible that you roll out a fix for the above ngx-mask@12 version please ? Or just atleast give me alteratives to fix this as patch for sometime.

**Comment by rushabh-wadkar** [comment]
@NepipenkoIgor @andriikamaldinov1 Any plans to fix this for v12 ?
Can you atleast provide what changes are needed just to fix this. I have already forked the project. I'll patch this on my own.

**Comment by andriikamaldinov1** [comment]
@rushabh-wadkar Thanks for using Ngx-mask. We have added updated version for 12 angular this is 13.2.1
It example all work as expected - https://stackblitz.com/edit/base-angular-12-app-hqsdro?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
