### ISSUE TITLE
ngx-mask - The date mask is broken

### ISSUE THREAD

**Issue by FractalMind** [JsDaddy/ngx-mask#1193]
# 🐞 bug report

### Is this a regression?

I don't know

### Description

The mask will work as expected when the input is empty. But if you overwrite the date, the mask goes banana

## 🔬 Minimal Reproduction
1. Go in your date demo
[https://jsdaddy.github.io/ngx-mask/](https://jsdaddy.github.io/ngx-mask/)

2. Enter a date
3. Correct the date

![ngx-mask-enter-date](https://github.com/JsDaddy/ngx-mask/assets/5481933/28ac8450-226d-4c30-a1b2-0c24c96c5e7e)
enter: 10062023
enter: 11062023

![1111](https://github.com/JsDaddy/ngx-mask/assets/5481933/0932b361-b55d-4b87-a867-12b31b825d87)
enter: 11111111
enter: 22222222

## 🌍 Your Environment

**Angular Version:**

"@angular/cdk": "15",
"@angular/common": "^15.1.0",
"@angular/core": "^15.1.0",
"@angular/material": "15",
"ngx-mask" : "^16.2.2",

Not working on Angular 16 either
https://stackblitz.com/edit/stackblitz-starters-bauaai?file=src%2Fmain.ts

With love ❤️

**Comment by andriikamaldinov1** [comment]
@FractalMind  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/stackblitz-starters-1yfbym?file=src%2Fmain.ts
