### ISSUE TITLE
NgxMaskPipe does not handle decimals correctly

### ISSUE THREAD

**Issue by sofieravyts** [JsDaddy/ngx-mask#1196]
When adding a mask 'separator.2'  with thousandSeparator='.' to an input field, the value is correctly returned and formatted for my locale 'nl-BE'

When trying to write out the masked value using the mask pipe the string is not correct. 
I would expect the same as shown in the input field?

Stackblitz: https://stackblitz.com/edit/angular-srav-ngxmask?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@sofieravyts Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-srav-ngxmask-wg1xty?file=src%2Fmain.ts
