### ISSUE TITLE
Mask is emitting empty string on onModelChange without user interaction

### ISSUE THREAD

**Issue by Forsaiken** [JsDaddy/ngx-mask#1197]
# 🐞 bug report

### Is this a regression?

Yes, when I downgrade my version to 15.1.5 the error stopped

### Description

Basically the input is emitting a value change in the onModelChange without the user do anything to the input when the changeDetection is onPush he is emitting the value of the ngModel, but when there is no changeDetection he is emitting a empty string ('').

## 🔬 Minimal Reproduction

 I'm trying to reproduce the error, but no success :(

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

**Angular Version:** 16.1.1

<pre><code>
Angular CLI: 16.1.4
Node: 18.14.2
Package Manager: npm 9.6.0
OS: win32 x64
</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@Forsaiken  Could you provide stackblitz or another environment ?

**Comment by andriikamaldinov1** [comment]
@Forsaiken  thanks for using ngx-mask. Sorry, but we don't have enough data to restore the problem, if you can reproduce this problem, please open a new ishue.
