### ISSUE TITLE
Invalid digit mask

### ISSUE THREAD

**Issue by dancornilov** [JsDaddy/ngx-mask#1200]
# 🐞 bug report

### Is this a regression?

I am not sure

### Description

Now, we use 0*, which means that the user can input any digit value. Currently, any digit from 0 to 9 is considered invalid.

## 🔬 Minimal Reproduction
Here is repo with reproduction of this **error**
https://github.com/dancornilov/ngx-mask-bug

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 16.0.6
Node: 17.3.0 (Unsupported)
Package Manager: npm 8.3.0
OS: darwin arm64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.0.6
@angular/cli                    16.0.6
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4

</code></pre>

## 🌍 Examples

<img width="477" alt="Screenshot 2023-07-21 at 17 17 14" src="https://github.com/JsDaddy/ngx-mask/assets/24212761/198e496c-058e-4a4a-a4ef-2510362d2820">
<img width="275" alt="Screenshot 2023-07-21 at 17 17 18" src="https://github.com/JsDaddy/ngx-mask/assets/24212761/748863c8-eeea-4747-a371-7114a8ad5b66">

**Comment by dancornilov** [comment]
@NepipenkoIgor Hey, thanks for your effort and dedication to the open source community. I understand that this topic can be discussed and implemented in other versions. However, for now, there is a possibility to put a mask on the input, and any numeric value should be considered valid?

**Comment by ManuBucaciuc** [comment]
Hi. I would start by expressing my gratitude to all your hard work in building such useful library.
Regarding this issue, it seems like I also encountered it in my projects and I'm still not sure if it's a regression or not.
Do we have any resolution on this?

Advanced thank you!

**Comment by andriikamaldinov1** [comment]
@dancornilov @ManuBucaciuc  Thanks for using Ngx-mask. Pls update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-zpf2cg?file=src%2Fmain.ts
