### ISSUE TITLE
leadZeroDateTime and showMaskTyped issue

### ISSUE THREAD

**Issue by Leonek** [JsDaddy/ngx-mask#1202]
# 🐞 bug report

### Is this a regression?

No.

### Description

When showMaskTyped and leadZeroDateTime are ON with date input there is issue while typing value (some random zeros are appear and there is no way to remove them).

I figure out that there is problem with such `mask` `0000-M0-d0 Hh:m0:s0.sss` or `0000-M0-d0`. 
With `d0-M0-0000 Hh:m0:s0.sss` seems working fine.

I guess its critical issue cuz it is core functionality of lib.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-vwnpbx?file=src%2Fapp%2Fapp.component.html

## 🌍 Your Environment

Angular v15

**Anything else relevant?**

Browser: Chrome 115

**Comment by andriikamaldinov1** [comment]
@Leonek Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-ivy-wbvme9?file=src%2Fapp%2Fapp.component.html
