### ISSUE TITLE
How to put fixed +1 before phone mask (000) 000-0000

### ISSUE THREAD

**Issue by jiwansidhu** [JsDaddy/ngx-mask#121]

**Comment by NepipenkoIgor** [comment]
@jiwansidhu we should add this functionality , in current version its unavailable.

**Comment by EuRusik** [comment]
Any update?

**Comment by NepipenkoIgor** [comment]
@EuRusik  In progress

**Comment by NepipenkoIgor** [comment]
@jiwansidhu @EuRusik  Please try new version 6.1.1

**Comment by jiwansidhu** [comment]
Thanks man @NepipenkoIgor .. I switched back to this. It fixed my issue :)

**Comment by MNorgren** [comment]
Any update on this one? I am wanting an optional prefix on the phone mask.
i.e. -
User can enter the following as valid options: 
(234) 567-8901 (value = 2345678901)
+1 (234) 567-8901 (value = 12345678901)

**Comment by sbeka** [comment]
How can I get the value along with the prefix?
