### ISSUE TITLE
showMaskedType for date input not working

### ISSUE THREAD

**Issue by bertdewolf** [JsDaddy/ngx-mask#1210]
# 🐞 bug report

### Description

Using angular 15 and ngx-mask 15, the showMaskedType is not working as expected.
```
<input
  [mask]="'M0/d0/0000'"
  [leadZeroDateTime]="true"
  [showMaskTyped]="true"
  [dropSpecialCharacters]="false"
/>
```

I'm unable to insert 01/03/2011 when showMaskedType is true
When false, I'm able to insert this value

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-8kzmss?file=src%2Fapp%2Fapp.component.html

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 15.2.4
Node: 14.21.3
Package Manager: npm 6.14.18
OS: darwin x64

Angular: 15.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@schematics/angular             15.2.4
ng-packagr                      15.2.2
rxjs                            6.6.7
typescript                      4.9.4
    
</code></pre>

**Comment by andriikamaldinov1** [comment]
@bertdewolf Thanks for using Ngx-Mask. Please update to latest version.
All work as expected - https://stackblitz.com/edit/angular-ivy-mb2bnz?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts
