### ISSUE TITLE
Mask "separator.1" with decimalMarker "," sets input value string.

### ISSUE THREAD

**Issue by brylkovskyi** [JsDaddy/ngx-mask#1211]
**Conditions**:
- Ngx-mask version 16.2.8
- Angular version 16.1.5
- Locale uk_UA (in this locale default decimal marker is comma)
- mask config:  mask="separator.1" decimalMarker=','

**Conditions where issue is not reproduced**
- ngx-mask version 15.1.5
- Angular version 15.2.9

**Steps to reproduce**
1. enter in input field text 12,2
2. verify form control value

**Actual**: typeof input value is string, input value is "12,2"
**Expected**: typeof input value is number, input value is 12.2

**Stackblitz example**
https://stackblitz.com/edit/stackblitz-starters-2ztbvw?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@brylkovskyi Hi. Can you check the new version, does it solve your problem?

https://stackblitz.com/edit/stackblitz-starters-twgftg?file=src%2Fmain.ts

**Comment by sebike95** [comment]
Yes, thank you.

**Comment by andriikamaldinov1** [comment]
@sebike95 @brylkovskyi Thanks for using Ngx-Mask.
If you have any problems in the future please open a new issue with teamplate.
