### ISSUE TITLE
Backspace not working with separator

### ISSUE THREAD

**Issue by stevenspears** [JsDaddy/ngx-mask#1215]
# 🐞 bug report

### Is this a regression?

Confirmed working in 7.4.3: https://stackblitz.com/edit/angular-ngx-mask-example?file=src%2Fapp%2Fapp.component.ts
Not working in my project: 15.0.2

### Description

 When cursor is after (to the right) of the separator, backspace does not work. Nothing happens.

## 🔬 Minimal Reproduction

To recreate:
	1. Enter amount (e.g. 23000, formats to 23,000)
	2. Move cursor to right-side of separator/comma
	3. Use Backspace
Result: Nothing happens
Example, forked from issue #909 https://stackblitz.com/edit/angular-eqvb6z?file=src%2Fmain.ts
Uses ngx-mask 16.1.7

 https://stackblitz.com/edit/angular-eqvb6z?file=src%2Fmain.ts

## 🌍 Your Environment

**Angular Version:**
See stackblitz

**Comment by stevenspears** [comment]
Using the web demo site, https://jsdaddy.github.io/ngx-mask/#3, I have noticed the space and dot separators seem ok, and the comma separator doesn't work.

Can be recreated on the demo site, options > separators:

<input type='text' mask="separator" thousandSeparator="," />

**Comment by andriikamaldinov1** [comment]
@stevenspears  Thanks for using Ngx-Mask. Please update to latest version.
All work as expected - https://stackblitz.com/edit/angular-jkvseb?file=src%2Fmain.ts
