### ISSUE TITLE
ngx-mask throws validation errors on numbers when using reactive forms

### ISSUE THREAD

**Issue by vmuresanu** [JsDaddy/ngx-mask#1225]
# 🐞 bug report

### Is this a regression?

 Yes, in version 15 it definitely worked

### Description

 When using reactive forms and mask directive with numbers only mask, we get an ngx-mask validation error, even though control from the logical perspective is valid. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-2qcthl?file=src%2Fmain.ts 

## 🔥 Exception or Error

<pre>"requiredMask": "0*", "actualValue": 44 <code>

</code></pre>

## 🌍 Your Environment

**Angular Version: 16.2.1**
<pre><code>

</code>@angular-devkit/architect            0.1602.1
@angular-devkit/build-angular        16.2.1
@angular-devkit/core                 16.2.1
@angular-devkit/schematics           16.2.1
@angular/cdk                         16.2.2
@angular/cli                         16.2.1
@angular/material                    16.2.2
@angular/material-date-fns-adapter   16.2.2
@schematics/angular                  16.2.1
rxjs                                 7.8.1
typescript                           5.0.4
zone.js                              0.13.1</pre>

**Anything else relevant?**

**Comment by vmuresanu** [comment]
After further investigation, I noticed that this bug only reproduces if the control is populated from the start with a value (like in stackblitz example). However if the control is empty and user enters some numerical value the error does not appear.

**Comment by malyavi-nochum** [comment]
This is occurring for us in Angular 15 too if we upgrade the ngx-mask package to 15.2.*

**Comment by andriikamaldinov1** [comment]
@vmuresanu @malyavi-nochum Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-jtfxoc?file=src%2Fmain.ts

**Comment by vmuresanu** [comment]
@andriikamaldinov1 works as expected. Thanks!
