### ISSUE TITLE
Copy&Paste of previous value after form reset isn't set value

### ISSUE THREAD

**Issue by ao1is** [JsDaddy/ngx-mask#1232]
# 🐞 bug report

### Is this a regression?
I'm not sure

### Description

1. Define simple form with form control. Bind masked input to form control.
```
public form = this.fb.group({
    inputValue: this.fb.control(undefined),
});
```
```
<input type="text"
       [formControl]="form.controls.inputValue"
       [mask]="'9999999999999'"/>
```
2. Enter any value, e.g. '15'.
3. FormControl's value set to 15.
4. Copy entered value and reset form by calling `form.reset()`
5. Value in input cleared.
6. Paste copied value into input by Ctrl+V.
7. **Actual**: FormControl's value set to null.
**Expected**: FormControl's value set to pasted value.

## 🔬 Minimal Reproduction

Sample: [https://stackblitz.com/edit/ngx-mask-copy-paste-bug](https://stackblitz.com/edit/ngx-mask-copy-paste-bug)
Demo: [https://www.screencast.com/t/xxN69caKI](https://www.screencast.com/t/xxN69caKI)

## 🌍 Your Environment
Angular Version: 16.1.7
Chrome Version: 116.0.5845.188

**Comment by andriikamaldinov1** [comment]
@ao1is Thanks for using Ngx-mask. Update to latest version.
It example, all work as expected - https://stackblitz.com/edit/ngx-mask-copy-paste-bug-m6mo2b?file=src%2Fmain.ts
