### ISSUE TITLE
Not working for v16

### ISSUE THREAD

**Issue by NauPareja** [JsDaddy/ngx-mask#1241]
**Version**

NgxMask: 16.1.7

Angular:
- @angular-devkit/architect       0.1601.8
- @angular-devkit/build-angular   16.1.8
- @angular-devkit/core            16.1.8
- @angular-devkit/schematics      16.1.8
- @angular/cdk                    16.1.7
- @angular/material               16.1.7
- @schematics/angular             16.1.8
- rxjs                            7.8.1
- typescript                      5.1.6
- zone.js                         0.13.1

**Component Module**
```
import { NgxMaskDirective, NgxMaskPipe, provideNgxMask } from 'ngx-mask';

@NgModule({
  declarations: [DemoComponent, OauthComponent],
  imports: [
    CommonModule,
    DemoRoutingModule,
    NgxTippyModule,
    MatDialogModule,
    ReactiveFormComponent,
    TableComponent,
    ModalComponent,
    MatExpansionModule,
    NgxMaskDirective,
    NgxMaskPipe,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [provideNgxMask()],
})
export class DemoModule {}
```

**Component Template**

```
  <input mask="0000" />
  <input mask="separator.2" />
```

**Comment by NepipenkoIgor** [comment]
@NauPareja  Please provide stackblitz and create issue using suggested template
