### ISSUE TITLE
writeValue stops to update Input when input is undefined

### ISSUE THREAD

**Issue by luizluan** [JsDaddy/ngx-mask#1242]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I believe is under 14

### Description

The start value from input must be undefined 
The textfield can or not have mask 

## 🔬 Minimal Reproduction

Just install de library add [mask] and [patterns] atribute and set [(ngModel)] as undefined

## 🔥 Exception or Error

![image](https://github.com/JsDaddy/ngx-mask/assets/13450436/fd917b22-b857-4a2d-8507-201de7ec343e)
 
I believe that the routine must write empty if the input is undefined. 
What happens is that I fill in the ngModel using an external script, or by actually filling in the input, and after changing pages the input returns to being undefined and the old value remains in the input.

</code></pre>

## 🌍 Your Environment

Angular Version: 16

**Comment by luizluan** [comment]
The mask also has to be undefined.

**Comment by luizluan** [comment]
It seems that the value is stored by the service, is there any command to clear the ngx-mask service?

**Comment by andriikamaldinov1** [comment]
@luizluan Hi. Could you provide stackblitz ??

**Comment by luizluan** [comment]
> @luizluan Hi. Could you provide stackblitz ??

Sure 
https://stackblitz.com/edit/stackblitz-starters-mc5b3i

**Comment by andriikamaldinov1** [comment]
@luizluan Thanks for using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/stackblitz-starters-9jfkan?file=src%2Fmain.ts
