### ISSUE TITLE
Module '"ngx-mask"' has no exported member 'MaskPipe'. After 13.2.1 Upgrade

### ISSUE THREAD

**Issue by Siva8877** [JsDaddy/ngx-mask#1245]
Im Using "ngx-mask": "^13.1.14". Till last week it worked fine. After 13.2.1 Upgrade we are getting build issue like "Module '"ngx-mask"' has no exported member 'MaskPipe'."

I used to import { MaskPipe } from 'ngx-mask'- and use transform function.
this.maskPipe.transform

**Comment by andriikamaldinov1** [comment]
@Siva8877 Thanks for using Ngx-mask. 
Could you provide stakcblitz?
Because here's an example and it works as expected - https://stackblitz.com/edit/angular-ivy-fms6ed?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fmain.ts

**Comment by lukk84** [comment]
Please note the difference between `MaskPipe` vs `NgxMaskPipe` and `MaskDirective` and `NgxMaskDirective`
Those changes were introduce with https://github.com/JsDaddy/ngx-mask/pull/1053
I'm not sure if such a breaking change should be part of minor update from `13.1.x` and `13.2.x`

**Comment by andriikamaldinov1** [comment]
@Siva8877 @lukk84 
This is not a minor version update, as we have not updated version 13 for a long time and this update includes many fixes that are in version 16. 
Please use NgxMaskPipe in the new version

**Comment by lukk84** [comment]
fixes are ok, breaking changes not...
