### ISSUE TITLE
showMaskTyped change causes caret to jump to end of field

### ISSUE THREAD

**Issue by dfrye7** [JsDaddy/ngx-mask#1246]
# 🐞 bug report

### Is this a regression?

No, present in previous versions.

### Description

When the user enters some data into the masked field, and then something external to the user's input (an observable, timeout, etc.) changes showMaskTyped from "false" to "true", the caret jumps to the end of the field rather than maintaining it's position where the user is typing.

## 🔬 Minimal Reproduction

StackBlitz demonstration: https://stackblitz.com/edit/angular-pkhtfx?file=src%2Fmain.ts

## 🔥 Exception or Error

Caret jumps to end of the field

## 🌍 Your Environment

**Angular Version:**

<pre><code>
16.2.2
</code></pre>

**Comment by andriikamaldinov1** [comment]
@dfrye7 Thanks for using Ngx-mask. Please update to latest version.
All work as expected - https://stackblitz.com/edit/angular-krqaud?file=src%2Fmain.ts
