### ISSUE TITLE
Missing changelog for v13.2.1

### ISSUE THREAD

**Issue by vivek201** [JsDaddy/ngx-mask#1247]
The version 13.2.1 was published in 9/21 but in the changelog (https://github.com/JsDaddy/ngx-mask/blob/develop/CHANGELOG.md#131152022-05-29), I could only find changes for upto 13.1.15. Can you please update the changelog for this?

**Comment by andriikamaldinov1** [comment]
@vivek201 Thanks for using Ngx-mask.
 We update CHANGELOG - https://github.com/JsDaddy/ngx-mask/blob/develop/CHANGELOG.md#feature-1321
