### ISSUE TITLE
v16 not working

### ISSUE THREAD

**Issue by nandomegale** [JsDaddy/ngx-mask#1248]
If you put some number, reset form, and put the same number again, the directive dont work.

https://stackblitz.com/edit/qyg2jm?file=src%2Fexample%2Finput-overview-example.html,src%2Fexample%2Finput-overview-example.ts

1 - 
![image](https://github.com/JsDaddy/ngx-mask/assets/25829011/2941c0e5-3118-4823-a929-6c5b69d820f1)

2 - 
![image](https://github.com/JsDaddy/ngx-mask/assets/25829011/8b856dab-65fc-4c9f-b293-7bcbc5f25f2a)

3 - 
![image](https://github.com/JsDaddy/ngx-mask/assets/25829011/c0f5cac6-0f7c-4bde-85a5-2c9573aa9774)

4 - 
![image](https://github.com/JsDaddy/ngx-mask/assets/25829011/2aa5c702-eec6-409f-a470-e92b2a5ec6ef)

Credits: https://github.com/Brenerr

**Comment by andriikamaldinov1** [comment]
@nandomegale  Thanks for using Ngx-mask. Please update to latest version.
All work as expected - https://stackblitz.com/edit/angular-z1vo9p?file=src%2Fmain.ts
