### ISSUE TITLE
using (000) 000-0000 as mask cursor move to left everytime on entring 4th digit. help wanted.

### ISSUE THREAD

**Issue by anup-wadhwani** [JsDaddy/ngx-mask#125]

**Comment by eisidoro** [comment]
same problem here using mask="(00) 00000-0000"

**Comment by AllanPinheiroDeLima** [comment]
Same here. Someone knows how to solve ?

**Comment by NepipenkoIgor** [comment]
@anup-wadhwani @eisidoro @AllanPinheiroDeLima Thanks. I will check

**Comment by ghiscoding** [comment]
oh yeah I got that problem too and it's a little weird that if you continue typing the cursor will eventually move back to the correct location but only near the end (like around 8-9th char)

**Comment by NepipenkoIgor** [comment]
@eisidoro @AllanPinheiroDeLima @ghiscoding Please try latest version , 2.9.4

**Comment by ghiscoding** [comment]
@NepipenkoIgor 
Thanks it does help in the original question, however doing a copy+paste is worst than before. If I do a paste, it's now 2 or 3 characters behind (instead of being completely at the end). I can open another issue if you wish

**Comment by NepipenkoIgor** [comment]
@ghiscoding Yes ,  please open another one.

**Comment by eisidoro** [comment]
Thanks, it works.

**Comment by AllanPinheiroDeLima** [comment]
Worked for me too, but I did'nt run a test like @ghiscoding  did. I will try and open an issue or comment again if I see the problem

**Comment by ghiscoding** [comment]
@AllanPinheiroDeLima 
I did open another issue #131 and it was fixed within the same day :)
I don't see any other errors anymore
