### ISSUE TITLE
LeadZeroDateTime gives wrong date

### ISSUE THREAD

**Issue by gerwinbouwhuis** [JsDaddy/ngx-mask#1251]
LeadZeroDateTime gives wrong date

"d0/M0/0000" with LeadZeroDateTime = true

Add (4122000), expected 04-12-2000 but gives 01/02/2000
Add (442000), expected 04-04-2000 but gives 04/02/0000

Example: 
https://stackblitz.com/edit/stackblitz-starters-zln7s7?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html

**Comment by LikDan** [comment]
The same problem. This is because of when you try to enter number that bigger than necessary (for example 3,4,5,6,7,8,9 in hours) the cursor position stay between 0 and this number 
For example when you use mask Hh:m0 and try to enter 9 you expect that input will be '09|' but it is '0|9' (the '|' symbol represents cursor)

**Comment by andriikamaldinov1** [comment]
@gerwinbouwhuis @LikDan   Thanks for using Ngx-Mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-4mpg1y?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html

**Comment by gerwinbouwhuis** [comment]
@andriikamaldinov1 

I found some bugs:

- if you type 33 => it shows 03/03, but the cursor is not on the right position
- if you type 913 =>  it shows 09/01/3, but the cursor is not on the right position

**Comment by andriikamaldinov1** [comment]
@gerwinbouwhuis Please update to latest version.
t example all work as expected - https://stackblitz.com/edit/stackblitz-starters-rnfwft?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html

**Comment by gerwinbouwhuis** [comment]
@andriikamaldinov1 

It works now correct, thnx!!
