### ISSUE TITLE
How can I use for a mask like this: 00h00 ?

### ISSUE THREAD

**Issue by darlondjc** [JsDaddy/ngx-mask#1252]

**Comment by darlondjc** [comment]
It’s just a mask with 00h00, where 0 is any number 0-9 and h is the literal
letter. When I put the first two numbers, the mask should complete with the
h and then I put the other two numbers.

Em ter., 10 de out. de 2023 às 04:02, Andrii Kamaldinov <
***@***.***> escreveu:

**Comment by darlondjc** [comment]
It’s the same mask for hour and minutes (00:00), but with the h in the
middle.

Em ter., 10 de out. de 2023 às 08:14, Darlon ***@***.***> escreveu:

**Comment by darlondjc** [comment]
Any solution?

**Comment by andriikamaldinov1** [comment]
@darlondjc Hi. Thanks for using Ngx-Mask.
Here is an example of how you can use it - https://stackblitz.com/edit/angular-8ubdab?file=src%2Fmain.ts

**Comment by darlondjc** [comment]
Thanks for the help. It worked perfectly.

Em seg., 6 de nov. de 2023 às 09:25, Andrii Kamaldinov <
***@***.***> escreveu:
