### ISSUE TITLE
Struggling with relatively simple mask

### ISSUE THREAD

**Issue by varadero** [JsDaddy/ngx-mask#1253]
My ngx-mask version is 16.3.9 and I want to achieve the following:
- Allow 1 or 2 digit integers
- Allow decimals with 1 or 2 digits before and after the separator

I have tried what not but without full success.

For example I tried with `mask="00.00||00.0||0.00||0.0||00||0"` hoping that this will allow:
- 00.00 = 2 digits before and 2 digits after the separator
- 00.0 = 2 digits before and 1 digit after the separator
- 0.00 = 1 digit before and 2 digits after the separator
- 0.0 = 1 digit before and 1 digit after the separator
- 00 = 2 digits
- 0 = 1 digit

If I apply such mask, then if I type "1.23" the value in the input field becomes "12.3".

Any ideas how can I achieve the "1 or 2 digit integer or 1 or 2 digits before and after the decimal separator" type of mask ?

**Comment by andriikamaldinov1** [comment]
@varadero  Thanks for using Ngx-Mask. For ur case please use mask="09.09"
It example all work as expected - https://stackblitz.com/edit/angular-egcqzy?file=src%2Fmain.ts,src%2Fglobal_styles.css
