### ISSUE TITLE
Simple masks like mask="09.99" do not work

### ISSUE THREAD

**Issue by varadero** [JsDaddy/ngx-mask#1256]
# 🐞 bug report

I am using version 16.x and I am having simple mask:

```html
<input maxlength="5" mask="09.99" />
```

The user cannot type anything after it types the point - simply nothing happens if I type:

```
1.
```

and try to continue with the digits after the dot. The same happens if I type two digits followed by point:

```
12.
```

Something terrible must have happened after version 15.0.0 - if I downgrade to it at least I can type numbers like:
```
12.34
```

but strangely not numbers like `1.23` - it becomes `1...3`.

**Comment by andriikamaldinov1** [comment]
@varadero  Thanks for using Ngx-Mask. For ur case please use mask="09.09"
It example all work as expected - https://stackblitz.com/edit/angular-egcqzy?file=src%2Fmain.ts,src%2Fglobal_styles.css
