### ISSUE TITLE
Pasting value into mask with prefix also add prefix.

### ISSUE THREAD

**Issue by XadGar** [JsDaddy/ngx-mask#1269]
# 🐞 bug report

### Is this a regression?
It reproduces in 15.2.0 version and later.
Version 15.1.5 and lower works fine.

### Description

When any value is pasted into mask with prefix prefix digits also added into value

## 🔬 Minimal Reproduction
1) open live documentation
![image](https://github.com/JsDaddy/ngx-mask/assets/129369084/56427459-5f49-43e8-85d9-8d8300e4d999)
2) paste any string value without "prefix", for example "11qq22"
3) mask added "71122"
![image](https://github.com/JsDaddy/ngx-mask/assets/129369084/a691545e-f958-4329-a5c1-4c9d7321f9cc)

## 🔥 Exception or Error
No exceptions or errors

**Comment by andriikamaldinov1** [comment]
@XadGar  Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://jsdaddy.github.io/ngx-mask/#4
