### ISSUE TITLE
Allow the ability to enter decimal point when masking as a Currency field using separator.2

### ISSUE THREAD

**Issue by tnfoundry** [JsDaddy/ngx-mask#1270]
# 🚀 feature request

### Description

End users would like the ability to key in currency values without having to type the leading zero. For example, if keying in 0.25, the user would like to type .25 rather than 0.25. 

### Describe the solution you'd like

If user keys in 0.25 into input, the user would like to type .25 rather than 0.25

### Describe alternatives you've considered

Have not found one, but would love to be pointed in the right direction as it seems like this would be a very common request.

**Comment by andriikamaldinov1** [comment]
@tnfoundry  Thanks for using Ngx-mask.  We have added this behaviuor. Please update to latest version.
03 => 0.3
.3 => 0.3
It example -  https://stackblitz.com/edit/angular-pj14ds?file=src%2Fmain.ts

**Comment by tnfoundry** [comment]
Woohoo! Awesome Andrii. This is greatly appreciated!!
