### ISSUE TITLE
Empty string is not detected as change

### ISSUE THREAD

**Issue by Brener-Alves** [JsDaddy/ngx-mask#1271]
# 🐞 bug report

### Is this a regression?

 It reproduces in 16.4.1 version

### Description

 The library does not recognize when the same value entered is changed after an empty string

## 🔬 Minimal Reproduction

1. Enter a number:
![image](https://github.com/JsDaddy/ngx-mask/assets/122981545/72df6e1e-0158-4acc-a623-a2a3adc1616c)

2. Click button to insert empty string:
![image](https://github.com/JsDaddy/ngx-mask/assets/122981545/e5d95014-d326-4873-9aa3-f89f8c159317)

3. Enter the same number you entered previously. The value is not updated in the form:
![image](https://github.com/JsDaddy/ngx-mask/assets/122981545/77a27eb7-387f-4261-a5d9-8ee49851b7e9)

 https://stackblitz.com/edit/angular-5hacyx?file=src%2Fmain.ts,package.json

## 🔥 Exception or Error

<pre><code>
No exceptions or errors

</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>
16

</code></pre>

**Comment by andriikamaldinov1** [comment]
@Brener-Alves Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-a7qc9o?file=src%2Fmain.ts,src%2Findex.html
