### ISSUE TITLE
Number input not editable when mask is empty

### ISSUE THREAD

**Issue by rdebeasi** [JsDaddy/ngx-mask#1274]
# 🐞 bug report

### Is this a regression?

Not as far as I'm aware

### Description

When a blank mask is applied to an input with `type="number"`, the input is not editable. (Our component has optional masking, and when the masking is disabled, we set `mask` to an empty string.) This behavior does not occur with `type="text"`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mask-eqarfj?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error

No error message

## 🌍 Your Environment

**Angular Version:** 16.1.0

<pre><code>
Angular CLI: 16.2.8
Node: 16.14.2
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.6
@angular-devkit/build-angular   16.0.6
@angular-devkit/core            16.2.8
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.1
@angular/cli                    16.2.8
@schematics/angular             16.2.8
ng-packagr                      16.2.3
rxjs                            6.6.7
typescript                      4.9.5
zone.js                         0.13.3

</code></pre>

**Anything else relevant?**

Thank you!!!

**Comment by ms-emp** [comment]
Any fix for this?

**Comment by andriikamaldinov1** [comment]
@ms-emp @rdebeasi Thanks for using Ngx-mask. Please update to version 16.4.2.
It example all work as expected - https://stackblitz.com/edit/angular-ivy-mask-yxqxnw?file=src%2Fapp%2Fapp.component.html

**Comment by rdebeasi** [comment]
Awesome - that fixes it on my end as well. Thank you!!
