### ISSUE TITLE
Using showTypedMask option causes form control to be invalid even if one of mask is fulfilled

### ISSUE THREAD

**Issue by Ihuarraquax** [JsDaddy/ngx-mask#1276]
# 🐞 bug report

### Is this a regression?

Do not know
### Description

Using showTypedMask option causes form control to be invalid even if one of mask is valid. Check screen and stackblitz

![image](https://github.com/JsDaddy/ngx-mask/assets/29738793/689264d1-4169-4a00-b4e0-744dfd6232bb)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-f3qfph?file=src%2Fmain.ts

1. Open stackblitz
2. Type 5 digits in both inputs
3. See validation error

## 🔥 Exception or Error

form control validation error: `{ "mask": { "requiredMask": "00000-0000", "actualValue": "12324" } }`

## 🌍 Your Environment

**Angular Version:**

angular 16
ngx-mask 16.4.1

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@Ihuarraquax Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-gvb8nk?file=src%2Fmain.ts
