### ISSUE TITLE
Cannot use allowNegativeNumbers with specialCharacters

### ISSUE THREAD

**Issue by lucasousi** [JsDaddy/ngx-mask#1278]
# 🐞 bug report

### Is this a regression?

No

### Description

It is not possible to use `allowNegativeNumbers` equals `true` together with a custom value to `specialCharacters` property. 
The value is rendered well, but the model value remains positive even for negative values.

I think the problem is in `ngOnChanges` fn of the `ngx-mask.directive.ts` file. The `if` statement for `specialCharacters` replaces the value of `this.specialCharacters` that was updated by the `allowNegativeNumbers` `if` statement.

![image](https://github.com/JsDaddy/ngx-mask/assets/37607560/ba50876a-8e86-4183-bb23-8d1773fd1f5a)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ngx-mask-special-characteres-allow-negative-numbers?file=src%2Fmain.ts

</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>
16.2.12

</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@lucasousi   Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/ngx-mask-special-characteres-allow-negative-numbe-krjdnd?file=src%2Fmain.ts
