### ISSUE TITLE
Mask does not work

### ISSUE THREAD

**Issue by dancornilov** [JsDaddy/ngx-mask#128]
Module:
import {NgxMaskModule} from 'ngx-mask';
imports: [
NgxMaskModule.forRoot()
];

Component:
<input [formControlName]="'phone'" type="text" mask="[00]-[000]-[000]" />

**Comment by NepipenkoIgor** [comment]
@dancornilov Hi, could you show your environment  (package.json)???

**Comment by dancornilov** [comment]
`{
  "name": "izi",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "prestart": "",
    "start": "ng serve --host 0.0.0.0 --disable-host-check --live-reload false",
    "prebuild": "",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.2",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/router": "6.0.2",
    "angular-6-social-login-temp": "^1.1.14",
    "angular2-jwt": "^0.2.3",
    "angularx-social-login": "^1.2.0",
    "core-js": "^2.5.7",
    "icon-font-generator": "^2.1.7",
    "ng-dynamic-component": "^3.0.0",
    "ng-pick-datetime": "^6.0.4",
    "ngx-mask": "^2.9.3",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.7",
    "@angular/cli": "6.0.2",
    "@angular/compiler-cli": "6.0.2",
    "@angular/language-service": "6.0.2",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.112",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.7.2"
  }
}
`

**Comment by dancornilov** [comment]
"dependencies": {
    "@angular/animations": "6.0.2",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/router": "6.0.2",
    "angular-6-social-login-temp": "^1.1.14",
    "angular2-jwt": "^0.2.3",
    "angularx-social-login": "^1.2.0",
    "core-js": "^2.5.7",
    "icon-font-generator": "^2.1.7",
    "ng-dynamic-component": "^3.0.0",
    "ng-pick-datetime": "^6.0.4",
    "ngx-mask": "^2.9.3",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.7",
    "@angular/cli": "6.0.2",
    "@angular/compiler-cli": "6.0.2",
    "@angular/language-service": "6.0.2",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.112",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.7.2"
  }
}

**Comment by dancornilov** [comment]
Will somebody help me solve my problem?

**Comment by dancornilov** [comment]
@NepipenkoIgor no nothing, maybe should set any options?

**Comment by NepipenkoIgor** [comment]
@dancornilov  Try latest version . I added  [ and ] as default symbols for mask. By the way you could read doc and find section with customization.

**Comment by lfreneda** [comment]
@dancornilov, fixed?

**Comment by nmorozov** [comment]
Same problem. It does not work at all.

**Comment by kapilraghuwanshi** [comment]
@dancornilov 

I am using the latest one-

app.module.ts

import { NgxMaskModule, IConfig } from 'ngx-mask';

export let options: Partial<IConfig> | (() => Partial<IConfig>);

@NgModule({
  imports: [
    NgxMaskModule.forRoot(options)],
}
})

Do not forget to add this line in your module - where you want to use it (not in app.module.ts):
@NgModule({
imports: [ NgxMaskModule.forChild() ]
})

**Comment by maplion** [comment]
I think this should be reopened.  I'm using Angular 7 and the latest ngx-mask and the given setup isn't working.

For starters, even doing what @kapilraghuwanshi  has done, it doesn't make sense from a logical or linter standpoint as the variable `options` is used before assignment [additionally, if one follows the documented instructions that don't say import IConfig, it gives a typing issue, as well as another linter error for using const without assigning options].  Bypassing the linter issues, without options or with options, it still doesn't recognize the module as existing for me, even when properly added to additional modules where it is being used as @kapilraghuwanshi  has shown.

@NepipenkoIgor For a library like this, it should be as simple as `npm install ngx-mask --save` and adding it to AppModule and I think there is a problem if it is not.  Please consider reopening.

**Comment by paulobusato** [comment]
> Do not forget to add this line in your module - where you want to use it (not in app.module.ts):
> @NgModule({
> imports: [ NgxMaskModule.forChild() ]
> })

This was missing for me :( thanks a lot !

**Comment by gmrosa** [comment]
I don't know why but it works that whay in angular ^8

in your app.module.ts

import { NgxMaskModule, IConfig } from 'ngx-mask';

export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

@NgModule({
    imports: [
        NgxMaskModule.forRoot(options)
    ]

in the module where you want to use it

import { NgxMaskModule } from 'ngx-mask';

@NgModule({
    imports: [
        NgxMaskModule

cheers
