### ISSUE TITLE
Decimal value round option

### ISSUE THREAD

**Issue by alpayoguz** [JsDaddy/ngx-mask#1288]
Ngx mask is not rounding decimal values as default. For example if value  is 1999.98955 and "seperator.2" is selected, then it should be like 1999.99 Please add this option

**Comment by andriikamaldinov1** [comment]
@alpayoguz Thanks for using Ngx-maks. We have inputTransformFn. Where u can write our own function.

It example - https://stackblitz.com/edit/stackblitz-starters-vutf6u?file=src%2Fmain.ts
