### ISSUE TITLE
Percent pipe should allow negative percentages starting with 0 and support to start with '-' character

### ISSUE THREAD

**Issue by durmuse** [JsDaddy/ngx-mask#1292]
Hi,

I have run into the following issues while using 'percent.2' pipe with negative numbers:
1) Negative number sign(-) can only be applied after the number is typed, So I end up having to go back to the first character to place the negative sign. The mask should allow us to start typing with "-" character also.
2) Currently mask only allows numbers equal to or greater than 1 to be negative. I'd like to have negative percentages starting with 0 also (-0.12%, -0.25%, etc.)

Thanks.

**Comment by tkutcher** [comment]
Not sure if related, but seems allowNegativeNumbers is not behaving as anticipated in general. The demos/examples at https://jsdaddy.github.io/ngx-mask/#11 do not appear to be functioning as expected.

**Comment by joshuaGnol** [comment]
@durmuse  try add prefix="-" to input

**Comment by durmuse** [comment]
@joshuaGnol : In my case user can enter both positive and negative numbers so I cannot use a prefix.

**Comment by andriikamaldinov1** [comment]
@durmuse @tkutcher @joshuaGnol  Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-8ebtka?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@durmuse  Please update to latest version.
 It example - https://stackblitz.com/edit/stackblitz-starters-temmpb?file=src%2Fmain.ts
