### ISSUE TITLE
ngx-mask with special characters at the beginning

### ISSUE THREAD

**Issue by mnovikovleobit** [JsDaddy/ngx-mask#1294]
# 🐞 bug report

### Is this a regression?

Not sure, but looks like no

### Description

If `mask` starts with a special character (I tested it with braces and parentheses), it will type in the special character on any keypress (characters that are not allowed in the mask itself) and then block all the next ones.

## 🔬 Minimal Reproduction

[ ngx-mask live demo](https://jsdaddy.github.io/ngx-mask/#8)
Second mask from the bottom, **ALLOW FEW MASK IN ONE EXPRESSION**. Try typing any of the characters that are not in the mask.

## 🌍 Your Environment

Not environment-specific

**Comment by andriikamaldinov1** [comment]
@twesk Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - [[ngx-mask live demo](https://jsdaddy.github.io/ngx-mask/#8)](https://jsdaddy.github.io/ngx-mask/#8)
