### ISSUE TITLE
syntactic error, like you lost the curly bow.

### ISSUE THREAD

**Issue by olena1994** [JsDaddy/ngx-mask#1295]
Hello, this code is from your documentation - <span>{{value | mask: 'separator': {thousandSeparator: ',', suffix: ' sm'}}</span>  on https://github.com/JsDaddy/ngx-mask/blob/develop/USAGE.md url.
If I copy and paste this in HTML, then there is a syntactic error, like you lost the curly bow. How does it look right?

**Comment by andriikamaldinov1** [comment]
@olena1994 Thanks for using Ngx-mask. We fix this syntactic error.
