### ISSUE TITLE
To initialize a variable with a value, the mask is not being applied correctly

### ISSUE THREAD

**Issue by ViniciusRochaDcide** [JsDaddy/ngx-mask#1299]
To initialize a variable with a value, the mask is not being applied correctly

![image](https://github.com/JsDaddy/ngx-mask/assets/63124103/a1fe287f-66df-42ec-a844-9cb9f72d5ea7)

https://stackblitz.com/edit/angular-nhtwrw?file=src%2Fmain.ts

"dependencies": {
    "@angular/animations": "^17.0.1",
    "@angular/common": "^17.0.1",
    "@angular/compiler": "^17.0.1",
    "@angular/core": "^17.0.1",
    "@angular/forms": "^17.0.1",
    "@angular/platform-browser": "^17.0.1",
    "@angular/router": "^17.0.1",
    "ngx-mask": "^17.0.4",
    "rxjs": "^7.8.1",
    "tslib": "^2.6.2",
    "zone.js": "^0.14.2"
  }

**Comment by andriikamaldinov1** [comment]
@ViniciusRochaDcide  Thanks for using Ngx-mask. Please update to lates version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-slqrk6?file=src%2Fmain.ts
