### ISSUE TITLE
The prefix is not removed when we set the control value

### ISSUE THREAD

**Issue by walkadaw** [JsDaddy/ngx-mask#1301]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 16.x.x

### Description

When we set in control value with prefix control value equal value what we set.

## 🔬 Minimal Reproduction

[ https://stackblitz.com/...](https://stackblitz.com/edit/stackblitz-starters-hhmiyy?file=src%2Fmain.ts)

## 🔥 Exception or Error

<pre><code>

const prefix = 'prefix';
const value = '000123'

control.setValue(prefix + value);

control.value === value // true
</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@walkadaw  Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-xzh6l9?file=src%2Fmain.ts
