### ISSUE TITLE
Cursor changes place when deleting multiple characters in version 17

### ISSUE THREAD

**Issue by pieterjansas** [JsDaddy/ngx-mask#1304]
When the input has a prefix in combination with mask and showMaskTyped, and you're deleting multiple characters. The cursor jumps to place 4 when 5 characters are left. 

This only happens from Angular version 17, in version 16 it worked as expected.

https://github.com/JsDaddy/ngx-mask/assets/11029312/477699e9-c56e-41b8-9cb7-ad482aed8af9

Example bug version 17: https://stackblitz.com/edit/stackblitz-starters-ex5l1t?file=src%2Fmain.ts

Example working version 16: https://stackblitz.com/edit/angular-sdodhb?file=src%2Fmain.ts

**Comment by nischiemineo** [comment]
I do have the same issue :( Is there a plan to fix this?

**Comment by nischi** [comment]
I do have the same issue, are they plans to fix this?

**Comment by andriikamaldinov1** [comment]
@pieterjansas @nischi   Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-1lfut3?file=src%2Fmain.ts
