### ISSUE TITLE
NgxMaskPipe keeps previous configs when transform() called

### ISSUE THREAD

**Issue by bsayat** [JsDaddy/ngx-mask#1308]
# 🐞 bug report

### Description

when you call transform() method of NgxMaskPipe with some configs, this configs affects on another transform() method call without/with configs.

## 🔬 Minimal Reproduction
```
console.log(this._mask.transform('55555', '00 (000)', { suffix: ' DDD' })); // 55 (555) DDD
console.log(this._mask.transform('55555', '00 (000)', { prefix: 'DDD ' })); // DDD 55 (555) DDD
```

https://stackblitz.com/edit/stackblitz-starters-udi4kf?file=src%2Fmain.ts

## 🌍 Your Environment
You can find it in stackblitz

**Comment by andriikamaldinov1** [comment]
@bsayat Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-ggvjfy?file=src%2Fmain.ts
