### ISSUE TITLE
Copy+Paste does not position the cursor at the end (it is 2-3 behind)

### ISSUE THREAD

**Issue by ghiscoding** [JsDaddy/ngx-mask#131]
Using `mask="000-000-0000"` and doing a paste of a phone number like "1234567890" will correcly mask "123-456-7890" but will leave the cursor 2 behind (cursor is between the number 8 and 9). If try a different mask of `(000) 000-0000`, the cursor is now 3 behind (cursor is now between the number 7 and 8).

**Comment by NepipenkoIgor** [comment]
@ghiscoding  you expected that cursor should be on the end of input ?

**Comment by ghiscoding** [comment]
Yes a paste should always leave cursor at the end

**Comment by NepipenkoIgor** [comment]
@ghiscoding please try latest version

**Comment by ghiscoding** [comment]
wow thanks for the super fast support. It works :)

**Comment by NepipenkoIgor** [comment]
@ghiscoding And you. I am Waiting  new issues ))))
