### ISSUE TITLE
Mixed Type is not respecting the mask.

### ISSUE THREAD

**Issue by dinbtechit** [JsDaddy/ngx-mask#1312]
# 🐞 bug report

### Is this a regression?

Does not appear to be. As it is an issue even on the demo site.

### Description

```
<input mask="AAA 000-S0S" />
```

when the mask is set to `AAA 000-S0S`.
It should only accept the first  3 should allow characters only, followed by space, number, dash, character, number, character.

Right now it is accepting numbers or character when the mask is `AAA`.

![image](https://github.com/JsDaddy/ngx-mask/assets/17984781/915a0e54-f5c6-4bd9-9861-ee015813c450)

## 🔬 Minimal Reproduction

Check out the Mixed type in the demo site - https://jsdaddy.github.io/ngx-mask/#5

**Comment by dinbtechit** [comment]
Turns out we have to use the letter `S` instead of `A` to enforce strict characters. The documentation is not clear.

```
<input mask="SSS 000-S0S" />
```

**Comment by andriikamaldinov1** [comment]
@dinbtechit Thanks for using Ngx-mask. It link for our documentation - https://github.com/JsDaddy/ngx-mask/blob/develop/USAGE.md

All work as expected. The screenshot is attached below
<img width="627" alt="Screenshot 2024-03-26 at 12 35 40" src="https://github.com/JsDaddy/ngx-mask/assets/129040945/20be3735-23c4-46fe-8688-0b42786c8757">
