### ISSUE TITLE
Not able to add a zero value when using separator mask

### ISSUE THREAD

**Issue by ojpbay** [JsDaddy/ngx-mask#1314]
When using a mask of separator (any number of decimal places) you are unable to add a value of 0.

This can be see in the demo for separators at https://jsdaddy.github.io/ngx-mask/#1. When adding a value of zero the form control value stays empty. Change it to anything else and it works.

![image](https://github.com/JsDaddy/ngx-mask/assets/1391064/f940a453-a115-49cb-a3af-34ba14ee54ef)

Add something other than zero and the form control value is updated:
![image](https://github.com/JsDaddy/ngx-mask/assets/1391064/3bc61b91-2f9f-4c82-9c1e-36545a2ded49)

**Comment by andriikamaldinov1** [comment]
@ojpbay Thanks for using Ngx-mask. 
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-bankkd?file=src%2Fmain.ts
