### ISSUE TITLE
Selecting one or multiple values and then replacing it results in strange behaviour

### ISSUE THREAD

**Issue by KaiBrouxAca** [JsDaddy/ngx-mask#1348]
# 🐞 bug report

### Is this a regression?

I don't know if it occurred in a previous version.

### Description

If [keepCharacterPositions]="true" is added on an input, there is some strange behaviour when selecting one or multiple values and then directly replacing it with another value.

## 🔬 Minimal Reproduction

https://github.com/JsDaddy/ngx-mask/assets/165287931/c077bc6c-f940-4fc1-bb9f-573edb4ab700

## 🔥 Exception or Error

None

**Comment by KaiBrouxAca** [comment]
Additional behaviour:

https://github.com/JsDaddy/ngx-mask/assets/165287931/650a6fb6-c3a8-4906-b976-52183e1fbc18

**Comment by andriikamaldinov1** [comment]
@KaiBrouxAca 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected -https://stackblitz.com/edit/angular-17-starter-project-cjc7qw?file=src%2Fmain.ts
