### ISSUE TITLE
It is impossible to enter more than 4 digits in input, when thousandSeparator="," is used on input

### ISSUE THREAD

**Issue by volodymyrmilovanov2022** [JsDaddy/ngx-mask#1349]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 16.3.5

### Description

 When I use mask="separator.2" and set thousandSeparator="," on input, i cannot enter more than 4 digits. It was Ok when i had 16.3.5 version, and has been broken after update to 17.0.7

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-17-starter-project-evcdxx?file=src%2Fmain.ts

## 🌍 Your Environment

**Angular Version:17**

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by leviSnow** [comment]
I am facing the same issue, the problem started in 17.0.5
Version 17.0.4 works fine for me.

**Comment by AbbTek** [comment]
Same issue here 17.0.4 works fine for me.

**Comment by russcarver** [comment]
17.0.7 has the issue as well.

**Comment by joshuaGnol** [comment]
Having same issue with version 17.0.8 using FormControl
When input number  _12345_, it will return as _123.00_ 

https://stackblitz.com/edit/angular-txwonf?file=package.json,src%2Fmain.ts,src%2Fkarma.conf.js

**Comment by arielZusman** [comment]
adding the decimalMarker="." solved the issue for me

**Comment by thealexfranklin** [comment]
> decimalMarker="."

yep. this did the trick.

**Comment by andriikamaldinov1** [comment]
@volodymyrmilovanov2022 @LYSBALL @AbbTek @russcarver @joshuaGnol  @thealexfranklin 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-17-starter-project-bkcx3g?file=src%2Fmain.ts
