### ISSUE TITLE
patterns functionality not working

### ISSUE THREAD

**Issue by stamminator** [JsDaddy/ngx-mask#135]
Using the `patterns` example defined in the README.md, defining a custom pattern for use in a mask does not work. All it does is cancel out the default pattern and treat the character as a literal instead of a pattern.

https://stackblitz.com/edit/angular-auuzgg

Trying to use non-default patterns (for example, `X` instead of `0`) does not solve the issue. It still only allows literal `X` values to be input.

**Comment by NepipenkoIgor** [comment]
@stamminator  Hi. We will check

**Comment by stamminator** [comment]
Hi @NepipenkoIgor, were you able to confirm this bug?

**Comment by NepipenkoIgor** [comment]
@stamminator 
Problem with JSON.parse/stringify  and we cant use string in this case 
we should use this functionality in next way 
```
<input type="text" [patterns]="patterns" mask="(000-000)" />
and in component 

public patterns =  {'0': { pattern: new RegExp('\[a-zA-Z\]')}}
```
I will change  doc
