### ISSUE TITLE
I want to use both  period ('.') and comma (',') as input

### ISSUE THREAD

**Issue by bovandersteene** [JsDaddy/ngx-mask#1354]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 17.0.4

### Description

After upgrading to version 17.0.7, I can no longer use a period ('.') as a decimal separator in my environment, where the comma (',') is the default on my operating system. Our application relies on the period ('.') as the default decimal separator.
This was working fine until version 17.0.4. 
For now I downgraded again to version 17.0.4

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-17-starter-project-zcyisb?file=src%2Fmain.tsb

## 🌍 Your Environment

**Angular Version:**

<pre>Angular: 17.3.2<code>

</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@bovandersteene 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-17-starter-project-bkcx3g?file=src%2Fmain.ts
