### ISSUE TITLE
Input marked dirty after updating to Angular 17

### ISSUE THREAD

**Issue by patrickuhlmann** [JsDaddy/ngx-mask#1357]
When we updated from Angular 16 to Angular 17 (which included updating related libraries like ngx-mask), we faced a regression. A input field in a form was marked dirty right after initialisation. I created a [StackBliz](https://stackblitz.com/edit/stackblitz-starters-uhiza3?file=src%2Fmain.ts) to reproduce the problem. Just click the button "Check dirty" and you will see as output that the input field using ngx-mask is dirty while the others are not dirty. All are assigned the same way.

I am not sure if this is related to a number of other issues that are already closed regarding wrong "dirty" behavior.

As a workaround we are currently using Version 16.4.2 of ngx-mask with Angular 17. This seems to work.

**Comment by achapman009** [comment]
> 16.4.2

We are facing the same issue. Thank you for providing a version to fallback to in the meantime.

**Comment by joelryan2k** [comment]
I'm seeing this behavior when upgrading from ngx-mask 17.0.5 to 17.0.6

I [forked the above stackblitz](https://stackblitz.com/edit/stackblitz-starters-qgaahf?file=package.json) and just backed off to 17.0.5 and the input is not dirty

**Comment by matviienko-danylo** [comment]
Do you have an approximate time frame when this fix [(1358): add trailing zero when mask="separator.1" and leadZero="true"](https://github.com/JsDaddy/ngx-mask/pull/1359) will work with Angular 17 ?

**Comment by HabooshHaddad** [comment]
Hello
any updates on this bug ?

**Comment by andriikamaldinov1** [comment]
@matviienko-danylo this request was merged with version 17.0.8
