### ISSUE TITLE
Is there a way to use outside an input?

### ISSUE THREAD

**Issue by sandrocsimas** [JsDaddy/ngx-mask#136]
Example:
````html
<p mask="000.000.000-00">{{ client.personal_data.cpf_number }}</p>
````

**Comment by NepipenkoIgor** [comment]
@sandrocsimas  Hi , in next release going to add mask pipe

**Comment by sandrocsimas** [comment]
Thanks, @NepipenkoIgor!

**Comment by NepipenkoIgor** [comment]
@sandrocsimas you could try `<p >{{ client.personal_data.cpf_number | mask:000.000.000-00 }}</p>`

**Comment by sandrocsimas** [comment]
Great, @NepipenkoIgor! I will try today, thanks!
