### ISSUE TITLE
Mask for 1-9 values (instead of 0-9)

### ISSUE THREAD

**Issue by xtrandom** [JsDaddy/ngx-mask#1366]
# 🚀 feature request

### Description

9 allows 0-9 optional, 0 allows 0-9 required; Is it possible to create a mask for 1-9? Ideally, I want 1-99 value but not 0-99. I tried leadZero=true, but that did not work. There's probably a way already, but I'm not finding it. Perhaps custom regex mask? But wondering it's possible with basic mask.

Currently using 16.4.2 for Angular 16

Thank you!

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by tmoun-opt** [comment]
You want a custom pattern https://github.com/JsDaddy/ngx-mask/blob/develop/USAGE.md#custom-pattern-for-this

Basic only supports "0-9" and "optional 0-9"

**Comment by andriikamaldinov1** [comment]
@xtrandom Thanks for using Ngx-mask. We've added the ability to use custom patterns to do this.
It example  with custom pattern - https://stackblitz.com/edit/angular-17-starter-project-xuxtoa?file=src%2Fmain.ts
