### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by jl91** [JsDaddy/ngx-mask#137]
Afternoon, 

I'm using angular 4 in a projects and when i try to use the latest version of ngx-mask 2+ e get these errors. 

![captura de tela de 2018-07-05 15-51-09](https://user-images.githubusercontent.com/12367418/42342392-4a7cf814-806c-11e8-92b0-a8218427823c.png)

But when i put the 1.0.3 it works, but with a lot of bugs...

**Comment by jl91** [comment]
My package.json


"dependencies": {
   "@angular/animations": "4.4.6",
   "@angular/common": "4.4.6",
   "@angular/compiler": "4.4.6",
   "@angular/core": "4.4.6",
   "@angular/forms": "4.4.6",
   "@angular/http": "4.4.6",
   "@angular/platform-browser": "4.4.6",
   "@angular/platform-browser-dynamic": "4.4.6",
   "@angular/router": "4.4.6",
   "class-validator": "0.7.1",
   "core-js": "2.5.1",
   "ngx-mask": "^2.1.11",
   "rxjs": "5.5.5",
   "zone.js": "0.8.18"
 },

**Comment by lfaguiar** [comment]
I have the same problem

**Comment by jl91** [comment]
Just for a while, to use the latest develop version in angular 4.4.6 i made a fork.

https://www.npmjs.com/package/ngx-mask-fixed

**Comment by 9brabus9** [comment]
I checked this in angular 4.4.7 All worked great
Please update your angular version before 4.4.7 + and update ngx-mask version 6+
