### ISSUE TITLE
Angular 18 Support

### ISSUE THREAD

**Issue by arman-g** [JsDaddy/ngx-mask#1371]
Please update the library to support angular v18.

Thank you for your work!

**Comment by jvermeer-ssi** [comment]
#1369

**Comment by andriikamaldinov1** [comment]
@arman-g  you have problems with the current version 17.1.0 on angular 18 ?
We use this version on our projects that are on version 18 and everything works as expected.
We plan to update the packages after the close of the critical issues.

**Comment by arman-g** [comment]
> @arman-g you have problems with the current version 17.1.0 on angular 18 ? We use this version on our projects that are on version 18 and everything works as expected. We plan to update the packages after the close of the critical issues.

I tried it now, and no issues as well. Please update the packages when you are ready. Thanks for this great package!

**Comment by andriikamaldinov1** [comment]
@arman-g Thanks for using Ngx-mask. We updated Ngx-mask to version 18.0.0.
