### ISSUE TITLE
valueChanges emitts when an incorrect value is set programmatically

### ISSUE THREAD

**Issue by CarlaMorosan** [JsDaddy/ngx-mask#1372]
# 🐞 bug report

### Description

valueChanges emitts when an incorrect value is set programmatically

## 🔬 Minimal Reproduction

Check Stackblitz: https://stackblitz.com/edit/angular-ivy-mask-fsq2va?file=src%2Fapp%2Fapp.component.ts

1. Have an input with a form control 
2. Set the 'SSS-SSS-SSS' mask
3. Subscribe to the form control's valueChanges
4. Set the form control with an incorrect value (e.g. 978-1-93624-386-0)
5. Check the value emitted

## 🔥 Exception or Error

valueChanges emitts the incorrect value, even though the value wasn't applied in the input

**Comment by MattKuhn123** [comment]
I almost think that the correct course of action would be to throw an exception in this case. What do you think?

Because if the application code calls setValue, but the mask alters the value somehow (in your example, by blanking it out), that could result in unexpected behavior.

**Comment by MattKuhn123** [comment]
In my tinkering, I'm not finding a way to interrupt valueChanges from being called with the value passed-in to setValue (not in **ControlValueAccessor**, **OnChanges**, nor **Validator**). 

Obviously, application code can set _emitEvent_ to _false_, but that's outside of this library.

So, maybe the best path is to allow the unmasked value to be written to the native element, add something to the ValidationErrors, and log a warning in the console? At least then the view will accurately reflect the model.

**Comment by CarlaMorosan** [comment]
I think the last approach you suggested might be helpful (let the unmasked value be written in the input, but signal somehow that the value set isn't correct according to the mask). 
Also, as an additional option for the user side, I am thinking of checking the value before setting it in the form control - is there a method that checks if the value is correct according to the mask (something that won't trigger other events)?

**Comment by MattKuhn123** [comment]
@CarlaMorosan , I wonder if you really _do_ want to check if the incoming value would be correct? Because This library already marks the form as invalid if the displayed value doesn't match the mask. Does it make sense to allow the incorrect value thru, and then _afterwards_ check if the form is invalid? (Keeping in mind that this library still needs to be patched to display the invalid value).

**Comment by andriikamaldinov1** [comment]
@CarlaMorosan  @MattKuhn123  @allenkepler-finastra
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-pflcha?file=src%2Fmain.ts
