### ISSUE TITLE
Option for visible mask

### ISSUE THREAD

**Issue by chesminsky** [JsDaddy/ngx-mask#138]
Hi!
Do you have plans to make mask visible as an option ?
Like at this picture
![image](https://user-images.githubusercontent.com/11498406/42408418-254c0cfa-81d5-11e8-916a-14a9330eeba5.png)

**Comment by XardasLord** [comment]
Is this option available ?

**Comment by duredhel13** [comment]
Any news on this?

**Comment by NepipenkoIgor** [comment]
@chesminsky @duredhel13 We have just release v6.2.4 . Please try.
