### ISSUE TITLE
Optional custom pattern symbols do not work correctly after special characters

### ISSUE THREAD

**Issue by tmoun-opt** [JsDaddy/ngx-mask#1386]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 14.2.4

### Description

 Optional custom pattern symbols do not work correctly after special characters. Details in stackblitz.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-17-starter-project-xf8skb?file=src%2Fmain.ts

## 🔥 Exception or Error

<pre><code>

n/a
</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>

17.0.4
</code></pre>

**Anything else relevant?**
 Might be related to issues found in #1370

**Comment by andriikamaldinov1** [comment]
@tmoun-opt  
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-17-starter-project-jzsjyy?file=src%2Fmain.ts
