### ISSUE TITLE
Bug: Backspace issue with floating numbers starting with 0

### ISSUE THREAD

**Issue by HaRuT-1994** [JsDaddy/ngx-mask#1389]
There is a bug in ngx-mask when handling floating numbers that start with 0. Specifically, when trying to delete the third(ex, actually from middle) zero in a number like 0.00001 using the backspace key, the behavior is not as expected. 
The third zero should be deleted, resulting in the number 0.0001. However, when backspace is pressed, it changes to 0,001. If backspace is pressed again, it changes to 001.

**Comment by NepipenkoIgor** [comment]
@HaRuT-1994  Please provide https://stackblitz.com/

**Comment by HaRuT-1994** [comment]
https://stackblitz.com/edit/stackblitz-starters-9vgrj9?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@HaRuT-1994  Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-ivdvo1?file=package.json
