### ISSUE TITLE
Mask for date in format "d0/M0" not working as expected - impossible to set "month" value as 10,11 or 12

### ISSUE THREAD

**Issue by onyzhin** [JsDaddy/ngx-mask#1390]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 15.*

### Description

When using `mask="d0/M0"`  it is impossible to set the "month" value to 10, 11, or 12. The input mask does not allow these values to be entered correctly.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-hzzc27?file=src%2Fmain.ts

1. Add an input field with the mask attribute set to "d0/M0":  `<input mask="d0/M0" />`
2. Try to input a date with the month value as 10, 11, or 12.

## 🔥 Exception or Error

The input field does not allow to set the month value to 10, 11, or 12. 

## 🌍 Your Environment

**Angular Version:**

<pre><code>16.*
17.*
18.*
</code></pre>

**Comment by andriikamaldinov1** [comment]
@onyzhin Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-khbhgl?file=package.json
