### ISSUE TITLE
bug by using mask=0{9}

### ISSUE THREAD

**Issue by thibaud57** [JsDaddy/ngx-mask#1399]
If i use mask as =0{8} or {10} or whatever i ve got an error { "mask": { "requiredMask": "0{8}", "actualValue": 1 } }
until i type 8 chars.
And until 10 in the other exemple.

But here when I type { "mask": { "requiredMask": "0{9}", "actualValue": 1 } }
I ve got only the error with first char, then it disapears, as if i have no error. 
But i ve actual value as 2 or 3 (less than 9 but still no error like in the other demonstration.

I'm using                 "ngx-mask": "^15.2.0",

**Comment by andriikamaldinov1** [comment]
@thibaud57  Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/angular-17-starter-project-f9qjp8?file=src%2Fmain.ts

**Comment by thibaud57** [comment]
Ok thanks for answer but problem is I need to keep Angular15 for moment
