### ISSUE TITLE
Using mask separator.2 with decimal marker with comma is not functional

### ISSUE THREAD

**Issue by tiryu** [JsDaddy/ngx-mask#1405]
# 🐞 bug report

### Is this a regression?

 Actually, it's ok when you are using the version 17.0.8 but over than this its non functional.

### Description

 When you're using optionsConfig with 

- decimalMarker: ','

And on an input **mask="separator.2"** with a value like "15 000,00" or "15000" , the display of this value will be : "1 500 000"

<pre><code>
const ngxMaskConf = {
	suffix: ' €',
	thousandSeparator: ' ',
	decimalMarker: ',', // commenting this will be ok but not the marker i need
	leadZero: true
} as optionsConfig;
</code></pre>

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/stackblitz-starters-cthkvg?file=src%2Fboot.module.ts](https://stackblitz.com/edit/stackblitz-starters-cthkvg?file=src%2Fboot.module.ts)

## 🌍 Your Environment
```

Angular Version: 17
Material Version: 17
NgxMask Version: 17.0.9
```

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@tiryu 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-sttbfw?file=src%2Fboot.module.ts
