### ISSUE TITLE
Can't delete minutes with backspace using hour mask

### ISSUE THREAD

**Issue by bartekdabros** [JsDaddy/ngx-mask#1410]
# 🐞 bug report

### Is this a regression?
Yes, it works in ver. 16.2.8

### Description
Can't delete minutes with backspace using hour mask

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-vj1vzc?file=src%2Fmain.ts

- input correct time
- select minutes (eg. with shift)
- press backspace button

## 🔥 Exception or Error
minutes not deleted, but cursor moves to position before colon

## 🌍 Your Environment
angular ver. 18
ngx-mask ver. 17 and 18

**Anything else relevant?**
works correctly with delete button

**Comment by andriikamaldinov1** [comment]
@bartekdabros 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-b8frgn?file=angular.json,package.json,src%2Fmain.ts
