### ISSUE TITLE
adding the value of "00/00/0000" for the mask "M0/d0/0000" is considered valid?

### ISSUE THREAD

**Issue by abdulrahmanriyaz** [JsDaddy/ngx-mask#1412]
# 🐞 bug report

### Is this a regression?
Not sure.

### Description
Its possible to add all zeroes in the date month format and it gets accepted as valid e.g with the mask
"M0/d0/0000" the value "00/00/0000" is considered valid. Do you know if this is intended behavior or is this a bug?

<input
    placeholder="MM/dd/YYYY"
    mask="M0/d0/0000"
    [dropSpecialCharacters]="false"
    [leadZeroDateTime]="true"
/>

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Package                         Version
---------------------------------------------------------
@angular/cli                    17.0.1
@angular/compiler-cli           17.0.3
ngx-mask                            ^18.0.0,
</code></pre>

**Comment by propkitty** [comment]
I am also having this same problem. Also, if I specifically do the year as 0000 (with month and day correct), it changes the year to 1900 rather than letting me throw it invalid.

**Comment by andriikamaldinov1** [comment]
@propkitty @abdulrahmanriyaz 

The standard validation of our mask is based on the number of entered characters matching the mask. For example, if your mask is "M0/d0/0000" or "00/00/0000", it will be considered valid as the validation only checks the number of entered characters.

If you want to implement additional custom checks, you need to write your own custom patterns. Here's an example:
https://stackblitz.com/edit/stackblitz-starters-zrffjb?file=src%2Fmain.ts

If you have any further questions or issues, please feel free to open a new issue using the provided template.
