### ISSUE TITLE
Date mask with trailing dot (d0.M0.) can lead to doubled dots

### ISSUE THREAD

**Issue by ischerf-buhl** [JsDaddy/ngx-mask#1415]
# 🐞 bug report

### Is this a regression?

No (I think)

### Description

When using the date specialties (d0 + M0) with the German format of dots after them, there is a problem if a user only enters 2s. The month then is considered February, but when you keep typing, there is not only one dot appearing, but two.

Expected: 22.2.
Actual: 22.2..

If you do this with a 3, it will only show as 3.3. and not let you continue to enter anything.

## 🔬 Minimal Reproduction

[Stackblitz Example](https://stackblitz.com/edit/stackblitz-starters-jcy9xx?file=src%2Fmain.ts)
Please enter a lot of '2's in the field.

## 🌍 Your Environment

In my local environment I have this with angular@18.2.0 + ngx-mask@17.0.7
In stackblitz it is the same behaviour with angular@16.2.11 + ngx-mask@18.0.0

**Anything else relevant?**

In my case, I can get around this issue by using leadZeroDateTime as you can see in the example.

**Comment by andriikamaldinov1** [comment]
@ischerf-buhl  
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-emuuu5?file=src%2Fmain.ts
