### ISSUE TITLE
Cursor should be placed right before of the next replaced charachter

### ISSUE THREAD

**Issue by papirosko** [JsDaddy/ngx-mask#1416]
When using masks with custom separators, the cursor is placed before the separator.
Example, 

```
                    <input type="text"
                           prefix="+7 " mask="(000) 000 00 00"
                           [showMaskTyped]="true">
```
<img width="181" alt="image" src="https://github.com/user-attachments/assets/5bbaaa70-5c8e-423e-bcc4-2d19981af45a">

Instead the cursor should be placed after the `(`, so user will clearly understand there the next charachter will be placed

**Comment by andriikamaldinov1** [comment]
@papirosko  
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-ochbqj?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json

**Comment by papirosko** [comment]
better at initial focus on input:
<img width="335" alt="image" src="https://github.com/user-attachments/assets/79b0ae32-2030-463c-81cb-0837dc46c0c5" />


but still bad, when you type any unsupported letter or press backspace, or type a digit and then delete it with backspace:

<img width="248" alt="image" src="https://github.com/user-attachments/assets/326aa3cb-539b-44d2-b7a2-ac2a34ce5cd0" />


check here:
https://stackblitz.com/edit/stackblitz-starters-qzphq5mc?file=package.json,src%2Fapp%2Fapp.component.html
