### ISSUE TITLE
Ngx-mask properties 'dropSpecialCharacters' and 'specialCharacters' work incorrect 

### ISSUE THREAD

**Issue by MykhayloZelisko** [JsDaddy/ngx-mask#1418]
# 🐞 bug report

### Is this a regression?

No

### Description

In a component with ControlValueAccessor, the dropSpecialCharacters property does not work (its value is always false).
Also, specialCharacters does not work correctly. When it is set, no character can be entered

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-luqpnh?file=src%2Fapp%2Finput%2Finput.component.html

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 17.3.6
Node: 20.10.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.3.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.6
@angular-devkit/build-angular   17.3.6
@angular-devkit/core            17.3.6
@angular-devkit/schematics      17.3.6
@schematics/angular             17.3.6
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.5
</code></pre>

**Comment by andriikamaldinov1** [comment]
@MykhayloZelisko 
Thanks for using Ngx-mask. Problem in your CVA you take value from el.target.value where value always like in input.

public changeValue($event: Event): void {
    const value = ($event.target as HTMLInputElement).value;
    this.onChange(value);
  }


If you bind control in your input it will be work as expected. We added example on your stackblitz with your CVA and without it.


It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-w6hfjm?file=src%2Fapp%2Fapp.component.ts,package.json,src%2Fapp%2Fapp.component.html,src%2Fapp%2Finput%2Finput.component.html
