### ISSUE TITLE
Optional digit

### ISSUE THREAD

**Issue by williancsilva** [JsDaddy/ngx-mask#142]
The User will input (99) 9999-9999 or (99) 9999**9**-9999 (bolder digit is optional).

Tryed (00) 0009-0000 and (00) 0000-00009.

input: 11240244244
result: (11) 2402-44244
my need: (11) 24024-4244

Thanks. 
PS: It's a nice work.

**Comment by NepipenkoIgor** [comment]
@williancsilva  This is awesome that package help your work. Waiting for new issues )
