### ISSUE TITLE
Issue with cursor placement after decimal is removed using mask="separator.2" and  separatorLimit

### ISSUE THREAD

**Issue by tp1906** [JsDaddy/ngx-mask#1420]
When I attempt to remove a decimal on an input with mask="separator.2" and  separatorLimit="10",  the cursor jumps to an incorrect position.  See attached screenshots.

1. If I enter 40.32 and remove the decimal, the value becomes 40 and the cursor jumps to first position.  
2. . If I enter 40.3 and remove the decimal, the value becomes 40 and the cursor jumps to second position.  

Thank you.
![entry with xx xx entry](https://github.com/user-attachments/assets/fa67c574-d767-4000-83b2-94034d15f2dd)
![entry with xx xx entry - decimal removed](https://github.com/user-attachments/assets/1ea43348-2c4e-4bb0-9d9c-0b5b8bb480d0)
![entry with xx x entry - decimal removed](https://github.com/user-attachments/assets/2086bb51-9a1c-493d-b783-150c9e054ab3)
![entry with xx x entry](https://github.com/user-attachments/assets/3f452e9a-38b0-4a33-898c-08ac67839d07)

**Comment by andriikamaldinov1** [comment]
@tp1906 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-cqaqix?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json
