### ISSUE TITLE
Numbers starting with 0.0X and separator.10 or greater do not work.

### ISSUE THREAD

**Issue by pookdeveloper** [JsDaddy/ngx-mask#1426]
# 🐞 bug report

### Is this a regression?

No

### Description

With decimal numbers that start at 0.0X and separator.10 or greater, it rounds the number and it shouldn't, if I modify it by hand it does work

In testControl 2 it should be the number: 0,0850000000

![image](https://github.com/user-attachments/assets/04624022-2fcf-44c7-81bf-ecef3aa640f9)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/stackblitz-starters-pq3bbe?file=src%2Fapp%2Fapp.component.ts

## 🌍 Your Environment

**Angular Version:**

18.2.2

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@pookdeveloper 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-pbwfg8?file=package.json

**Comment by pookdeveloper** [comment]
@andriikamaldinov1  still doesn't work, (he actualizado el stackblitz)
[stackblitz-starters-nhmnqgov](https://stackblitz.com/edit/stackblitz-starters-nhmnqgov?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component)


testcontrol3 has a value of:

  testControl3 = new FormControl('99999999999999999999,9999999999');

However, it states:

<img width="677" height="94" alt="Image" src="https://github.com/user-attachments/assets/619693a4-cb4c-4266-bb90-5ddbd7fd2196" />

but if I remove the decimals and leave 999999999999999999, also fails so it seems that the problem is on both sides:
on inputs: separatorLimit and mask

from 999999999999999 is already broken

**Comment by pookdeveloper** [comment]
<img width="1849" height="730" alt="Image" src="https://github.com/user-attachments/assets/585bedbe-94f0-4272-a787-b013183565a6" />
