### ISSUE TITLE
Default config not work (provideNgxMask)

### ISSUE THREAD

**Issue by pookdeveloper** [JsDaddy/ngx-mask#1427]
# 🐞 bug report

### Is this a regression?

No

### Description

Added a configuration for the entire application but it does not work, if I specify it at the component level directly in the HTML it works

![image](https://github.com/user-attachments/assets/44fc7cdd-dce7-47f9-b0e4-e35b8f1d27d0)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-uv85k3?file=package.json

## 🌍 Your Environment

**Angular Version:**

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@pookdeveloper 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-pu55ii?file=package.json,src%2Fmain.ts
