### ISSUE TITLE
Does not work in Lazy Loaded module

### ISSUE THREAD

**Issue by BesikSakhiashvili** [JsDaddy/ngx-mask#143]
Hello
ngx-mask does not work in Lazy Loaded module

**Comment by NepipenkoIgor** [comment]
@BesikSakhiashvili Hi , will check

**Comment by NepipenkoIgor** [comment]
@BesikSakhiashvili Could you provide error or clarify problem ??

**Comment by ng-rams** [comment]
When the mask is changed in the component it doesn't apply the new filter.
