### ISSUE TITLE
clearIfNotMatch: true - is not clears the text box value

### ISSUE THREAD

**Issue by SathyaChenniappan** [JsDaddy/ngx-mask#144]
clearIfNotMatch: true - Clears the text box text but the text box still holds the entered value.

I am using reactive forms.

Please help me to fix the issue.

**Comment by NepipenkoIgor** [comment]
@SathyaChenniappan Hi, please try v6.0.1

**Comment by SathyaChenniappan** [comment]
@NepipenkoIgor Thanks a lot.
