### ISSUE TITLE
showMaskTyped together with keepCharacterPositions and pressing DEL key breaks mask

### ISSUE THREAD

**Issue by jeffrey-planon** [JsDaddy/ngx-mask#1441]
# 🐞 bug report

### Is this a regression?

I don't know, first time using ngx-mask.

### Description

Pressing DEL key seems to break the mask, e.g. the special characters in the mask get removed and completely changing the whole mask.

## 🔬 Minimal Reproduction

1. Go to https://jsdaddy.github.io/ngx-mask and navigate to Options and then Keep Character Position example
2. Enter the value 123456789, this should give a masked value of 123-456-789
3. Put cursor/caret after 6, so between 6 and -
4. Press DEL on keyboard

## 🌍 Your Environment

**Angular Version:** 17
**Ngx-mask version:** 18.0.0

<pre><code>
Angular CLI: 17.3.8
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 17.3.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             15.2.9
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.5
webpack                         5.95.0
zone.js                         0.14.10
</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@jeffrey-planon 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://jsdaddy.github.io/ngx-mask and navigate to Options and then Keep Character Position example

**Comment by jeffrey-planon** [comment]
@andriikamaldinov1 thank you for fixing it so fast however I found another bug now.

When I enter the value 111-222-333 and I select the first 3 characters (111) and start typing to replace them it again breaks the mask.
