### ISSUE TITLE
Support of large numbers with mask seperator

### ISSUE THREAD

**Issue by partyfever** [JsDaddy/ngx-mask#1442]
# 🐞 bug report

### Is this a regression?

No

### Description

After entering a large value as number using the mask "seperator", values are rounded down: 

- Input:    123456789123456789
- Output: 123456789123456780

## 🔬 Minimal Reproduction

Please allow me to show the bug in the provided example site: 
https://jsdaddy.github.io/ngx-mask/#9
![image](https://github.com/user-attachments/assets/d355b69b-3e6f-4b5e-a699-1a3e77248383)

## 🌍 Your Environment

**Angular Version: 18.2.3

**Comment by andriikamaldinov1** [comment]
@jeffrey-planon 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://jsdaddy.github.io/ngx-mask and navigate to Separators![Image](https://github.com/user-attachments/assets/6928a12e-c71a-4ebd-9112-d2743cfd80ab)
