### ISSUE TITLE
Separator mask does not allow delete first digit

### ISSUE THREAD

**Issue by lucasousi** [JsDaddy/ngx-mask#1446]
# 🐞 bug report

### Is this a regression?

I'm not sure, able to reproduce in `18.0.2`

### Description

When using the `separator` mask, the input value is incorrectly formatted when deleting the first digit.

How to Reproduce:

1. Enter the value `60,05`.
2. Use delete or backspace to remove the number `6`.

**Expected:** The input value should become `0,05`.
**Result:** The input value changes to `5`.
**Workaround:** Setting the mask to `00,00` resolves the issue.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-y5nctd

## 🔥 Exception or Error

None

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 17.3.8
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@angular/material               17.3.10
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8

</code></pre>

**Comment by andriikamaldinov1** [comment]
@lucasousi 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-mhfhzg?file=package.json
