### ISSUE TITLE
Changing "hiddenInput" breaks the entered value (again)

### ISSUE THREAD

**Issue by BGBRWR** [JsDaddy/ngx-mask#1449]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 18.0.0

### Description

When used a mask which hides entered values fully or partially there is a bug when you switch the hiddenInput value. If the value is entered when hiddenInput is true, then when turning it off we lose all but the last typed value. If the inverse and hiddenInput was false and then turned on the value stays intact.

It only happens on type (keydown). You can set the value programmaticly or via paste and it will work.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-jc1ukg?file=src%2Fmain.ts

## 🌍 Your Environment

**Angular Version:**

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 18.2.11
Node: 20.12.1
Package Manager: npm 10.8.2
OS: win32 x64
</code></pre>

**Anything else relevant?**

This was fixed last year with this issue https://github.com/JsDaddy/ngx-mask/issues/1008. 

This commit (https://github.com/JsDaddy/ngx-mask/commit/3c818dcce5246f29f1db160d7d07995abd5fec05#diff-1198ef06aa3895ce10c29918343a334a7562f988bcef000720b6acb6b70fd0caL81-R83) is what is causing this bug.

Here is the blame: https://github.com/JsDaddy/ngx-mask/blame/0bf5c93064885ed394f526d14ad23c3f8beb9e8e/projects/ngx-mask-lib/src/lib/ngx-mask.service.ts#L83.

**Comment by andriikamaldinov1** [comment]
@BGBRWR  
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-6smr1z?file=package.json
