### ISSUE TITLE
Angular v6 - mask disappears when type in field

### ISSUE THREAD

**Issue by MikeOtown** [JsDaddy/ngx-mask#1450]
# 🐞 bug report

### Is this a regression?

no

### Description

When typing in a field with a mask, the mask disappears.  What version of ngx-mask should I use with my Angular v6.1 project?

## 🌍 Your Environment

**Angular Version:**

Angular CLI: 6.2.9
Node: 14.21.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9 (cli-only)
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9 (cli-only)
@angular/cdk                      6.4.7
@angular/cli                      6.2.9
@angular/material                 6.4.7
@schematics/angular               0.8.9 (cli-only)
@schematics/update                0.8.9
rxjs                              6.6.7
typescript                        2.9.2
webpack                           4.16.4

**Comment by BGBRWR** [comment]
If you want to see the mask set `[showMaskTyped]="true"`. And for Angular v6 the latest version of ngx-mask that might work is [8.2.0](https://www.npmjs.com/package/ngx-mask/v/8.2.0) but that is 5 years ago so ymmv.

**Comment by andriikamaldinov1** [comment]
@MikeOtown Thanks for using Ngx-mask!

You can find all the latest released versions of Ngx-mask on our [Changelog page](https://github.com/JsDaddy/ngx-mask/blob/develop/CHANGELOG.md) . This page includes a detailed history of updates, features, and fixes for each version. Feel free to pick the version that best suits your needs. 

If you have any questions or issues in the future, please feel free to open a new issue using the provided template.
