### ISSUE TITLE
OutputTransformFn is not used when setting an empty value

### ISSUE THREAD

**Issue by angheladrian** [JsDaddy/ngx-mask#1456]
When a `OutputTransformFn` function is configured, this is not always called when the control value is set programmatically.

### Is this a regression?

Works fine with version `8.0.2`

I would say it was introduced with the fix for [#1447](https://github.com/JsDaddy/ngx-mask/pull/1447)

## 🔬 Minimal Reproduction

Consider having an input:

`<input type="text" formControlName="amount" mask="separator.0">`

When setting the values in code:

`form.amount.setValue(null)`

Then the `OutputTransformFn` is not called. 

I think the problem is in [NgxMaskService.formControlResult](https://github.com/JsDaddy/ngx-mask/blob/develop/projects/ngx-mask-lib/src/lib/ngx-mask.service.ts#L536) method. 
Correct would be: `this.onChange(this.outputTransformFn(''));`

## 🌍 Your Environment

**Angular Version:**

<pre><code>
 18.2.11
</code></pre>

**Comment by andriikamaldinov1** [comment]
@angheladrian 
Thanks for using Ngx-mask. Please update to latest version.
