### ISSUE TITLE
'comma' (\u002c) is transformed to 'full stop' (\u002e) when overwriting [specialCharacters] with empty array

### ISSUE THREAD

**Issue by elac85** [JsDaddy/ngx-mask#1457]
# 🐞 bug report

### Is this a regression?

Not sure.

### Description

I want to reset the default special characters, and enable my special characters as a regex, so I overwrite the default special character array with an empty one, and add a custom pattern to the input field. In this setup, if I type 'comma' (,) in the input, it will be transformed to 'full stop' (.)

## 🔬 Minimal Reproduction

[Stackblitz Example](https://stackblitz.com/edit/stackblitz-starters-zdn51f?file=src%2Fmain.ts)

**Comment by andriikamaldinov1** [comment]
@elac85 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-31zq1t?file=package.json
