### ISSUE TITLE
Cursor jumps to the end of the line in input with two masks and a prefix

### ISSUE THREAD

**Issue by dmiap1** [JsDaddy/ngx-mask#1458]
# 🐞 bug report

### Is this a regression?

Not sure

### Description

Please consider a following input containing two masks and a prefix. Bug manifests when a long line for mask 2 is entered. When trying to delete characters with Backspace or to enter a character in the middle of the string the cursor jumps to the end of the line.

    <input class="form-control" id="id-buggy-input" maxlength="40" name="buggy-input"
                            type="text" mask="00) 000-00-00||00) 000-00-00; 0 (000) 000-00-00"
                            prefix="8 (0"
                            [showMaskTyped]="true"
                            [specialCharacters]="[ '(' ,')' , '-', ';', '.', ' ' ]"
                            [dropSpecialCharacters]="false"
                            />

## 🔬 Minimal Reproduction
[stackblitz](https://stackblitz.com/edit/stackblitz-starters-yshtkf?file=src%2Fmain.ts)
1. Enter a line 8 (011) 111-11-11; 1 (111) 111-11-11
2. Place a cursor in the middle of the line
3. Press Backspace or input a number

Observe that the cursor jumps to the end of the line

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 18.2.9
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.2.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.9
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.9
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@dmiap1 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-d9aq8h?file=package.json
