### ISSUE TITLE
untouched input with a mask of separator.2 has a value of an empty string

### ISSUE THREAD

**Issue by LYSBALL** [JsDaddy/ngx-mask#1472]
# 🐞 bug report

### Is this a regression?

Yes, the bug started in version 18.0.3

### Description

An untouched input should have a null value, and that was the behavior prior to version 18.0.3. But with version 18.0.3 (19.0.2 still has this issue) the value is an empty string. An untouched input, also if i set a variable specifically to be null, the null value should persist if the input was not touched.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-d732gt
and switch the version from 18.0.3 to 18.0.2 to see the changed in behavior.

## 🌍 Your Environment

angular 19

**Comment by andriikamaldinov1** [comment]
@LYSBALL 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-wknsmc?file=package.json
