### ISSUE TITLE
prefix is not shown when input field is empty

### ISSUE THREAD

**Issue by DevDuki** [JsDaddy/ngx-mask#1476]
# 🐞 bug report

### Is this a regression?

Yes, I think it is a regression, unless it was an intended to change it this way (but I hope not). At version v15.2.3 the `prefix` attribute used to behave different than it does now at version v18.0.4 (I think it did so since v16+).

### Description

So before when I added a prefix, it was visible as a "value" of the input field and the cursor started right after it (in my case the prefix value is "CHF " (with a single whitespace afterwards))
![image](https://github.com/user-attachments/assets/c01f6b0f-f852-4933-bf2f-b0ec8456472d)

But now the prefix is not visible at all at the beginning. Only after the user starts typing the prefix gets added automatically and the value typed by the user gets appended after the prefix. But I would prefer if the prefix was already visible inside the input field from the beginning. 
Before typing:
![image](https://github.com/user-attachments/assets/7060128d-40a6-48ba-8178-b3b919fd4469)
After typing the number "1":
![image](https://github.com/user-attachments/assets/208d0c73-a994-4380-97f0-5d6a6aad0ab9)

Please don't make me use `[showMaskTyped]="true"` because that looks very ugly with the current configuration. Before it worked perfectly fine without `[showMaskTyped]="true"`, so I hope it can be redone the same way again.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-dwzsnjzy?file=src/app/app.component.html,src/app/app.module.ts

## 🌍 Your Environment

**Angular Version:** v18.2.13
**ngx-mask Version:** v18.0.4

Please note that I cannot upgrade ngx-mask to v19+ yet, because my project requires Angular to stay at v18 for now.

**Comment by andriikamaldinov1** [comment]
@DevDuki 
Thanks for using Ngx-mask. Please update to latest version.
We added input property instantPrefix controls the display behavior of a prefix in the input.

When set to true, the prefix is displayed even if the model is empty.
When set to false, the prefix only becomes visible when a value is present in the model.

It example  - https://stackblitz.com/edit/stackblitz-starters-m8jajttu?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts
