### ISSUE TITLE
Changing mask after component is initialized doesn't update mask

### ISSUE THREAD

**Issue by ng-rams** [JsDaddy/ngx-mask#148]
have a mask that defaults to ""
When the component is loaded to "000-000-0000" it doesn't enforce with the new mask.

**Comment by NepipenkoIgor** [comment]
@ng-rams Hi , сould you provide code example. What hook do you use for initialization ?

**Comment by ng-rams** [comment]
html file: 
<form-text
[name]="'phone'"
[(ngModel)]="model.phone"
[required]="true"
[customMask]="'000-000-0000'">
</form-text>

---------------------------------------------------------------

custom component .ts file
@Component({
  providers: [TEXT_INPUT_ACCESSOR_PROVIDER],
  selector: 'form-text',
  template: `
<div [hidden]="hidden" class="form-group row">
  <div class="col-sm-9">
    <input type="text" [attr.id]="identifier"
      [ngClass]="{'form-control':true, 'is-invalid': (invalid | async) }"
      [(ngModel)]="value"
      (input)="onInputChange($event)"
      [attr.mask]="customMask"
    />    
  </div>
</div>
})

**Comment by NepipenkoIgor** [comment]
@ng-rams Hi , awesome
