### ISSUE TITLE
Reopening #1446 - Separator mask does not allow delete first digit

### ISSUE THREAD

**Issue by lucasousi** [JsDaddy/ngx-mask#1481]
# 🐞 bug report

### Is this a regression?

These bugs appeared after the fix of https://github.com/JsDaddy/ngx-mask/issues/1446

### Description

When using the `separator` mask, the input value is incorrectly formatted when deleting the first digit.

**How to Reproduce:**

1. Enter the value `60,05`.
2. Use delete or backspace to remove the number `6`.

**Expected:** The input value should become `0,05`.
**Result:** The input value changes to `0.,05`.
**Workaround:** Setting the mask to `00,00` resolves the issue.

**How to Reproduce 2:**

1. Enter the value `200.05`
2. Use delete or backspace to remove the number `2`

**Expected:** The input value should become `00.05`
**Result:** The input value changes to `0.0.05`
**Workaround:** Setting the mask to `000,00` resolves the issue.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/stackblitz-starters-zu8pge

## 🔥 Exception or Error

None

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 17.3.8
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.3.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@angular/material               17.3.10
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8

</code></pre>

**Comment by SealTecH** [comment]
It looks like this issue has been present since v 15.2.X 
Also, probably, it has some relation to apm feature, because I tried to find a stable version without the bug but with apm, but in 15.2.X both of them appear

**Comment by andriikamaldinov1** [comment]
@lucasousi 
Thanks for using Ngx-mask. Please update to latest version.

It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-9mbjbckm?file=src%2Fboot.component.ts,package.json

**Comment by lucasousi** [comment]
> @lucasousi Thanks for using Ngx-mask. Please update to latest version.
> 
> It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-9mbjbckm?file=src%2Fboot.component.ts,package.json

In this example 1 and 3, I think the bug isn't fully fixed. 
For example 1, when we delete the number `2` from `200.05`, the input value changes to `0.05`. One zero disappears.
For example 3, when we delete the number `1` from `1 000 000.05`, the input value changes to `0.05`. Many zeros disappear.

Is this the expected behavior?

**Comment by andriikamaldinov1** [comment]
@lucasousi Yes, this is expected behavior. Because there cannot be a number 0000000.05 in the separator. In previous versions, this was a bug.
