### ISSUE TITLE
Dynamic mask clears input model value, even if the value is correct

### ISSUE THREAD

**Issue by XardasLord** [JsDaddy/ngx-mask#151]
Hello, when I try to load data whick has a dynamic mask getting from a function like this: 
`[mask]="zipCodeMask()"`.

My input looks like: 
```
            <input type="text" [mask]='zipCodeMask()' [clearIfNotMatch]="isZipCodeMaskActive()" [dropSpecialCharacters]="false" class="form-control" name="zipCode" [(ngModel)]="_contractor.zipCode" #zipCode="ngModel" [ngClass]="{ 'is-invalid': f.submitted && zipCode.invalid }"
              required />
```

on my `ngOnInit()` function I load the model. Mask works fine but only problem is when I load data from DB, only input which has a mask is not filled.

**Comment by NepipenkoIgor** [comment]
@XardasLord  Hi , i tested delayed assignment and didn't find problem . Could you provide more complex example ??
