### ISSUE TITLE
Possibility to add more masks like 31-12-9999?

### ISSUE THREAD

**Issue by masaanli** [JsDaddy/ngx-mask#156]
Title says enough :)

Possibility to add more masks like 31-12-9999?
So that it's also checking on max number of 31 before the -

**Comment by NepipenkoIgor** [comment]
@masaanli Hi. You could use custom patterns. Please look in doc.

**Comment by masaanli** [comment]
@NepipenkoIgor can you give an example how to do that for the date, for example above?

**Comment by NepipenkoIgor** [comment]
@masaanli If i understand you right 31 should be fixed numbers ?

**Comment by 9brabus9** [comment]
We updated ngx-mask and added new pattern Mask: d0/m0/0000
You need to use this pattern in your case.
