### ISSUE TITLE
How to achieve "***-***-1234" in masking pattern ? 

### ISSUE THREAD

**Issue by Oddadmix** [JsDaddy/ngx-mask#160]

**Comment by NepipenkoIgor** [comment]
@Oddadmix  Hi , what you mean when use `*` ?

**Comment by Oddadmix** [comment]
@NepipenkoIgor * as a string not regex. 

What is the masking pattern that I can use ?

**Comment by Alexandr98** [comment]
Did you mean * as a letter? If you yes, then try this mask="SSS-SSS-000".

**Comment by arti040** [comment]
I won't create a new thread but how to achieve something like this:

[[undetermined letters/numbers][optional dash or one space]] * many times?

Example: 4FSS-4234 FS1W-42 324-BB

**Comment by ojemuyiwa** [comment]
I think he meant example: Bank card number **** **** **** 2345

**Comment by Oddadmix** [comment]
Perfect. Thanks @Alexandr98  & @ojemuyiwa  I will try it but I think it should work.

**Comment by chr1soscl** [comment]
@Oddadmix Hi, I am also looking to mask a Credit card number, what mask did you use?

**Comment by Oddadmix** [comment]
@chr1soscl I used two different patterns one with ***-***-000 for the masked and for the unmased I used 000-000-000.

Hope that helps.
