### ISSUE TITLE
Currency Mask example

### ISSUE THREAD

**Issue by ufoscout** [JsDaddy/ngx-mask#161]
Is it possible to build a currency mask with this library?
Something like this:
http://next.plnkr.co/edit/zjJw8gfvaVFIUN9OIvea?p=preview&preview

If yes, could you please provide an example?

**Comment by unnamed92** [comment]
Try this one: mask="99,999.999.999".
You can add so many characters as you need or remove the coins.

**Comment by jmac-slash0** [comment]
This is what worked for me:

`<input type="text" [specialCharacters]="[ '$', ',' ]" mask="$000,000,000,000">`

Input: 123456 Output: $123,456

**Comment by Alexandr98** [comment]
@ufoscout You can use prefix like this prefix="$".

**Comment by that70schris** [comment]
this doesn't really seem sufficient, using `mask="$000,000"` with input `1234` yields `$123,4`

**Comment by kidargaw** [comment]
<input type="text" mask="separator" thousandSeparator="," prefix="$" >
