### ISSUE TITLE
Thousand number separator

### ISSUE THREAD

**Issue by dMartinezAyuso** [JsDaddy/ngx-mask#162]
Hi, 

Is it possible to add dinamically a separtor for number with thousands. Example:
(1) InputValue-> 12342.12     MaskValue-> 12,342.12
(2) InputValue-> 132123454     MaskValue->132,123,454
(3)InputValue-> 12     MaskValue->12

This is a great tool. Thanks for sharing!

**Comment by Alexandr98** [comment]
You can specify mask manually. For example: 
 mask="00,000.00"
 mask="000,000.00".
