### ISSUE TITLE
Can I use this on contenteditable divs?

### ISSUE THREAD

**Issue by ruudyroon** [JsDaddy/ngx-mask#163]
just curious,

I wanted to apply mask to this tag

<span #plannedTotal contenteditable (blur)="update('plannedTotal'+':'+ plannedTotal.innerText)"> {{convertToHHMM(session.plannedTotal)}} </span>

wondering if this is possible.

**Comment by NepipenkoIgor** [comment]
@ruudyroon you should use  mask pipe `<span>{{phone | mask: '(000) 000-0000'}}</span>`

**Comment by ruudyroon** [comment]
Thanks!

**Comment by NepipenkoIgor** [comment]
@ruudyroon  And you
