### ISSUE TITLE
value clears out in the input of type formcontrol where masking has been applied

### ISSUE THREAD

**Issue by rakesh00005** [JsDaddy/ngx-mask#165]
I have an input field like below.

`<input [formControl]="price" mask="00.00">`

While entering a number, masking is applied with no probs. But when the value is getting from API call, value in the input clears out and not able to enter a value.

**Comment by NepipenkoIgor** [comment]
@rakesh00005  Hi , we will check

**Comment by rakesh00005** [comment]
Change in title.
Actually i can able to enter a value but the issue is value coming from API call is not populating in input field. When i remove "mask" attribute, value is getting displayed.

**Comment by jcebidanes** [comment]
Maybe is the same problem that I have  #167.
I identified if change the type number to string work fine.
