### ISSUE TITLE
ng build prod: WARNING: "export 'ɵa' (imported as 'i21') was not found in 'ngx-mask'

### ISSUE THREAD

**Issue by Coffee-Tea** [JsDaddy/ngx-mask#166]
Hi, it looks like not big blocker, but anyway during
`ng build --prod` all modules which use ngx-mask throw warning
```
WARNING in ./src/app/app.module.ngfactory.js
96:3852-3858 "export 'ɵa' (imported as 'i21') was not found in 'ngx-mask'
```

ngx-mask - 6.1.2
angular packages - 6.0.4.

**Comment by unnamed92** [comment]
Could you provide full list of your dependencies?
I've tested your case in the project from scratch but didn't get your error.

**Comment by Coffee-Tea** [comment]
@unnamed92 Hmmm, interesting, here is the list of dependencies:

`
"dependencies": {
    "@angular/animations": "^6.0.4",
    "@angular/cdk": "6.3.0",
    "@angular/common": "^6.0.4",
    "@angular/compiler": "^6.0.4",
    "@angular/core": "^6.0.4",
    "@angular/forms": "^6.0.4",
    "@angular/http": "^6.0.4",
    "@angular/material": "6.3.0",
    "@angular/platform-browser": "^6.0.4",
    "@angular/platform-browser-dynamic": "^6.0.4",
    "@angular/router": "^6.0.4",
    "@ngx-progressbar/core": "^5.0.1",
    "@ngx-progressbar/http": "^5.0.1",
    "@ngx-progressbar/router": "^5.0.1",
    "angular-in-memory-web-api": "^0.6.0",
    "angular-tree-component": "^7.2.0",
    "angular2-hotkeys": "^2.1.2",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.10",
    "moment": "^2.22.1",
    "ngx-bootstrap": "^3.0.1",
    "ngx-mask": "^6.1.2",
    "ngx-order-pipe": "^2.0.1",
    "particlesjs": "^2.2.2",
    "primeicons": "^1.0.0-beta.7",
    "primeng": "^6.0.0-rc.1",
    "rxjs": "^6.2.1",
    "rxjs-tslint": "^0.1.4",
    "tolefocus": "^0.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.4",
    "@angular-devkit/build-angular": "~0.6.3",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.4",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
`

**Comment by mralienlucky** [comment]
Same warning, and console error ERROR TypeError: or(...).onFocus is not a function
`  "dependencies": {
    "@angular/animations": "6.1.7",
    "@angular/common": "6.1.7",
    "@angular/compiler": "6.1.7",
    "@angular/core": "6.1.7",
    "@angular/forms": "6.1.7",
    "@angular/http": "6.1.7",
    "@angular/platform-browser": "6.1.7",
    "@angular/platform-browser-dynamic": "6.1.7",
    "@angular/router": "6.1.7",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "bootstrap": "^4.1.3",
    "bootstrap-datepicker": "^1.8.0",
    "core-js": "^2.5.7",
    "jquery": "^3.3.1",
    "jquery-touchswipe": "^1.6.19",
    "ngx-clipboard": "^11.1.7",
    "ngx-infinite-scroll": "^6.0.1",
    "ngx-mask": "^6.1.3",
    "ngx-smart-modal": "^6.0.4",
    "ngx-toastr": "^8.10.2",
    "ngx-validators": "^4.1.0",
    "ngx-webstorage": "^2.0.1",
    "popper.js": "^1.14.4",
    "rxjs": "^6.3.2",
    "rxjs-compat": "^6.3.2",
    "zone.js": "^0.8.26"
  },
`

**Comment by Alexandr98** [comment]
@Coffee-Tea We reproduced with your dependencies in new project and error not found.

**Comment by AdityarajuE** [comment]
ERROR in ./node_modules/ng2-gauge-with-color-band/ng2-gauge-with-color-band.ngfactory.js 16:193-198
"export 'ɵa' (imported as 'i1') was not found in 'ng2-gauge-with-color-band'
