### ISSUE TITLE
If type number not show value in input.

### ISSUE THREAD

**Issue by jcebidanes** [JsDaddy/ngx-mask#167]
Not show value if type is number.

```
object { value: 4.56 }
<input [(ngModel)]="obeject.value" [dropSpecialCharacters]="false" mask='0*.00' class="form-control">
```

If change type to string work fine.
`object { value: "4.56" }`

**Environment:**
"@angular/core": "^5.2.0"
"ngx-mask": "^6.1.2"

**Comment by ruudyroon** [comment]
Facing the same issue

**Comment by NepipenkoIgor** [comment]
@ruudyroon @jcebidanes Please try latest version 6.1.3
