### ISSUE TITLE
optional character on the lefthandside?

### ISSUE THREAD

**Issue by Barbiero** [JsDaddy/ngx-mask#169]
Suppose you use the mask `90000-0000`. I expected it would work in a sense that the leftmost character(ie, the `9`) is optional, and the `-` character would stay on the 5th position(when counting from right to left). However, if I input `12345678`, it will render `12345-678` instead of `1234-5678`. If I were to add another character, it will work as expected, ie. `12345-6789`

Is there any way to achieve that behavior?

Edit:
Currently I am achieving this behavior by extending `MaskDirective` and then dynamically changing the `maskExpression` like so:

```typescript
  writeValue(inputValue: string) {
    this.checkMask(inputValue)
    return super.writeValue(inputValue)
  }

  @HostListener('input', ['$event'])
  onInput(e: KeyboardEvent): void {
    const el = e.target as HTMLInputElement
    const readValue = el.value
    this.checkMask(readValue)
    el.value = readValue
    super.onInput(e)
  }
```

where `checkMask` is my own function that verifies the length of `inputValue` so that it changes between  `00000-0000` and  `0000-0000` masks through the `maskExpression` prop.

**Comment by unnamed92** [comment]
9 never evaluate as optional character because you  always type it.
You can use optional character only in the end of a line.
