### ISSUE TITLE
Please add brackets ([]) on patterns in README.md

### ISSUE THREAD

**Issue by charlesartbr** [JsDaddy/ngx-mask#170]
Please update README.md file changing:

`<input type='text' patterns="customPatterns" mask="(000-000)" >`

To:

`<input type='text' [patterns]="customPatterns" mask="(000-000)" >`

This took me one hour to found out what was wrong with my code.

**Comment by NepipenkoIgor** [comment]
@charlesartbr Tanks , we merged PR
