### ISSUE TITLE
Custom CPF/CNPJ Pattern

### ISSUE THREAD

**Issue by SaadeMotion** [JsDaddy/ngx-mask#172]
Hello, i'm trying to achieve Brazilian CPF/CNPJ pattern. Using with Angular Form Validator it works, but with custom pattern it doesn't,

```
public cpfcnpjPattern = {
		'P' : {
			pattern : new RegExp('([0-9]{2}[\.]?[0-9]{3}[\.]?[0-9]{3}[\/]?[0-9]{4}[-]?[0-9]{2})|([0-9]{3}[\.]?[0-9]{3}[\.]?[0-9]{3}[-]?[0-9]{2})')
		}
	}
```

this piece of regex works in any other regex tester. please can you help?

**Comment by unnamed92** [comment]
@SaadeMotion 
RexExp in mask checks a string with only 1 symbol in it. You can not check a long string with several characters.
