### ISSUE TITLE
Add ability to use MaskPipe/MaskService inside component

### ISSUE THREAD

**Issue by nazar-kuzo** [JsDaddy/ngx-mask#173]
Currently, there is no ability to inject MaskPipe/MaskService into component constructor to apply mask in TypeScript.

**Comment by Alexandr98** [comment]
@nazar-kuzo We released new version with that property, try 6.2.8.

**Comment by nazar-kuzo** [comment]
@Alexandr98, so I have installed the 6.2.8 version and here what I have:

ngx-mask.d.ts (file)
![image](https://user-images.githubusercontent.com/13677730/46296909-1dcbbd00-c5a4-11e8-9fe8-b1cd5cae609d.png)

Seems like default d.ts generator renamed exports.

Also, MaskPipe has a dependency on MaskApplierService, so it makes things complicated where they supposed to be simple:

Example 1:
I would like to apply mask inside my component

Solution 1:
1. Inject MaskApplierService into component constructor
2. create instance of MaskPipe and pass instance of MaskApplierService into constructor parameter
3. use MaskPipe.transform method

Solution 2:
1. Register MaskPipe as provider in my module like:
    { provide: MaskPipe, useClass: MaskPipe }
2. Inject MaskPipe into component constructor
3. use MaskPipe.transform method

Proposed Solution
Can we make MaskPipe constructor parameterless, so we can use it as pure pipe?
If MaskApplierService is used just as way to avoid code duplication, it could be used
as internal class without need to be exported and registered as Angular Injectable.

This will allow create instances of MaskPipe without and additional steps provided
and it will behave as pure stateless function.

**Comment by lixaotec** [comment]
Is this possible already? to use in component?

**Comment by nazar-kuzo** [comment]
@lixaotec 
It is 😊

**Comment by lixaotec** [comment]
Thanks dude. Just managed to it. Passed maskpipe in a constructor . Worked very well, im building a generic pipe for my datatable

**Comment by guidogr95** [comment]
@lixaotec Is there an example you could provide with the parameters you passed to the maskPipe please? Thanks a lot
