### ISSUE TITLE
Mask according to the length of the text

### ISSUE THREAD

**Issue by felipefsv** [JsDaddy/ngx-mask#176]
Hi,

is it possible to add a mask according to the length of the text entered?

As in:

1234 =  "12-34"
123456 = "12345-6"

**Comment by NepipenkoIgor** [comment]
@felipefsv Hi . Сould you describe your pattern ?

**Comment by felipefsv** [comment]
@NepipenkoIgor Hello!

eg: if input is "92036365019" (11 digits) mask applied should be: "920.363.650-19". If input is "22137884000163" (14 digits) mask should be "22.137.884/0001-63". It's a matter of individual or business id code.

**Comment by NepipenkoIgor** [comment]
@felipefsv  Condition mask interesting . Do we have only two conditions ?

**Comment by felipefsv** [comment]
@NepipenkoIgor Yes, exactly. It's Brazilian taxpayer doc id standard.

**Comment by lhenriquelpc** [comment]
@NepipenkoIgor I'm interested in this possibility.

**Comment by christopheelkhoury** [comment]
@lhenriquelpc why not open a PR with it?

**Comment by lhenriquelpc** [comment]
> @lhenriquelpc why not open a PR with it?

@christopheelkhoury, do you mean a PR to improve the documentation?
