### ISSUE TITLE
Issue with Android devices in certain masks

### ISSUE THREAD

**Issue by ImJeevesh** [JsDaddy/ngx-mask#178]
I tried using the demo example at [https://jsdaddy.github.io/ngx-mask/](https://jsdaddy.github.io/ngx-mask/) on my android device for Date, Date and Hour, Hour masks but when I enter 100 the cursor shifts pointer to just before last 0. Seems like this occurs only when we try to enter 100. I used google keyboard for entering digits in the following scenario.

**Comment by NepipenkoIgor** [comment]
@ImJeevesh Hi.  Сould you provide screen and version of your system . Also which browser did you use ?

**Comment by ImJeevesh** [comment]
> @ImJeevesh Hi. Сould you provide screen and version of your system . Also which browser did you use ?

I use Chrome Android v69 on a Custom Rom (Android 9 / Nexus 5x). See if this screen works for you [https://streamable.com/4ru9e](https://streamable.com/4ru9e)

**Comment by ImJeevesh** [comment]
@NepipenkoIgor It didn't work for me... On entering 100 shows 10/0 but with wrong cursor placement (just before last zero digit) although for any combination it works fine.

**Comment by Thegrep01** [comment]
@ImJeevesh your mask style 00/00/000. You tried to enter 100, for this case you need to change mask to 000/00/00

**Comment by Thegrep01** [comment]
@ImJeevesh we check this. And we founded that this problem appears only with google chrome/android 9/100 in input
