### ISSUE TITLE
matAutocomplete and mask

### ISSUE THREAD

**Issue by aacdevelop** [JsDaddy/ngx-mask#183]
Hi, 
Given this input 

<input *ngIf="field.isInputMask" matInput #fieldElement type="text" (keypress)="keyPress($event)" class="accent-color" [ngModel]="field.value" [placeholder]="field.name" [matAutocomplete]="auto" [readonly]="locked || field.isReadOnly || disabled" mask="{{field.inputMask}}" (ngModelChange)="changeValue($event)" (blur)="focusOut(field)"/>

i receive the following:

FieldValidationComponent.html:28 ERROR Error: More than one custom value accessor matches form control with unspecified name attribute

Trying a bit with all the properties I found that I cannot use matAutocomplete and mask at the same time. Someone has a suggestion?

**Comment by Wikster2012** [comment]
The error is stating the problem stems from not having a specified `name` attribute. Did you try adding the missing `name` attribute? Did that not resolve the issue?

Something like,

```html
<input *ngIf="field.isInputMask" 
    name="_unique_name_here_"
    matInput
    #fieldElement
    type="text"
    (keypress)="keyPress($event)" 
    class="accent-color" 
    [ngModel]="field.value" 
    [placeholder]="field.name" 
    [matAutocomplete]="auto" 
    [readonly]="locked || field.isReadOnly || disabled"  
    mask="{{field.inputMask}}"
    (ngModelChange)="changeValue($event)"
    (blur)="focusOut(field)"/>
```

**Comment by Serge0111** [comment]
Hi @aacdevelop 
the following error "FieldValidationComponent.html:28 ERROR Error: More than one custom value accessor matches form control with unspecified name attribute" occurs because [matAutocomplete] uses formControl under the hood but it's not allowed to use more than 1 formControl... so that's why it doesn't work in your case.

**Comment by kfirufk** [comment]
ahh.. I see that this issue was closed a long time ago. but isn't any way to overcome this ? i want to mask spaces at the beginning of the input

**Comment by SAVpro** [comment]
"name" тщ

> Ошибка заключается в том, что проблема связана с отсутствием указанного `name`атрибута. Вы пытались добавить недостающий `name`атрибут? Это не решило проблему?
> 
> Что-то вроде,
> 
> ```
> <input *ngIf="field.isInputMask" 
>     name="_unique_name_here_"
>     matInput
>     #fieldElement
>     type="text"
>     (keypress)="keyPress($event)" 
>     class="accent-color" 
>     [ngModel]="field.value" 
>     [placeholder]="field.name" 
>     [matAutocomplete]="auto" 
>     [readonly]="locked || field.isReadOnly || disabled"  
>     mask="{{field.inputMask}}"
>     (ngModelChange)="changeValue($event)"
>     (blur)="focusOut(field)"/>
> ```

"name" не помог =(
https://stackoverflow.com/questions/44070998/value-not-displaying-for-material2-autocomplete

до сих пор нет решения заставить работать вместе с  matAutocomplete ?
