### ISSUE TITLE
Good example for SSN?

### ISSUE THREAD

**Issue by tskweres** [JsDaddy/ngx-mask#187]
Would like to make in an input show:

` ***-**-3321 `

for example

**Comment by NepipenkoIgor** [comment]
@tskweres `*` you mean any character ? And 3321 should be fixed numbers ?

**Comment by tskweres** [comment]
had a client who had a requirement to live mask the numbers as the user is typing....but show the last 4, and still retain the original value of what was typed.

The requirements have since been changed, but still an interesting problem to solve

**Comment by ryanlangton** [comment]
I'm in need of this feature too. Any ETA?

**Comment by sashidhar540** [comment]
We also had the same requirement to mask SSN value as 'XXX-XX-1234' and still need to retain the original value.

**Comment by Serge0111** [comment]
@tskweres, hey what's up, try new version, 7.7.0
