### ISSUE TITLE
Form is being marked as ng-dirty

### ISSUE THREAD

**Issue by cbruce11** [JsDaddy/ngx-mask#189]
The ng-mask is causing the form to be marked as dirty. I see that you have made some changes to possibly address this issue but I have updated to the most recent version and still am having the same issue.

**Comment by Alexandr98** [comment]
@cbruce11 We can't reproduce this issue, but we create new angular cli project and compare with our ngx mask, problem not found.
You could to show screen with problem?

**Comment by mecp** [comment]
I am also facing this issue. I am using reactive form, I will try to recreate the issue in a stack blitz and then post here.

**Comment by sonusindhu** [comment]
I am facing same issue. Here is the example:

https://stackblitz.com/edit/ngx-mask-issue-48
