### ISSUE TITLE
can you keep the decimal point two

### ISSUE THREAD

**Issue by wqdjl** [JsDaddy/ngx-mask#19]
eg.  *.00

**Comment by victorschinaider** [comment]
Nice!

**Comment by NepipenkoIgor** [comment]
@wqdjl Could you provide more complex example or give a link?

**Comment by MalithHatananchchige** [comment]
You should be able to see it here
https://github.com/RobinHerbots/Inputmask

**Comment by NepipenkoIgor** [comment]
@wqdjl @victorschinaider We add support for `*` character . You can use latest version with mask `0*.00`

**Comment by kordenv** [comment]
> @wqdjl @victorschinaider We add support for `*` character . You can use latest version with mask `0*.00`

doesn't work

my mask: 0*.00000
formControl remove dot
i write: 123.12345 and get 12312345

why?

**Comment by robpoyntz** [comment]
I have a similar problem to @kordenv 

``mask="0*.00"``
Input value: 178.09
Output value: 17809

(Although it does work correctly if I use ``mask="comma_separator.2"``)
