### ISSUE TITLE
Using mask between different child modules

### ISSUE THREAD

**Issue by OlgaMatosova** [JsDaddy/ngx-mask#190]
Hi
I am using Angular 5.2
I have in my app several child modules, and when I try to add ngx-mask in root module app.module.ts as NgxMaskModule.forRoot() , it doesn't work in child module and I get error "The pipe 'mask' could not be found". Could you help me with this? I really like your lib

**Comment by Serge0111** [comment]
Hi @OlgaMatosova,
We released new version 6.2.8, try it.

**Comment by luizjunior05** [comment]
The same is happening to me.

`ngx-mask: 6.5.18`
`angular: 6.0.0`

**Comment by taivu** [comment]
I was able to get this to work by importing `NgxMaskModule` into my child module, and under `imports` i have `NgxMaskModule.forChild()`

**Comment by taivu** [comment]
to clarify, inside of my imports in `app.module` im using `NgxMaskModule.forRoot()` and inside of my lazy loaded module `lazy.module` i have `NgxMaskModule.forChild()`. v7.3.5

**Comment by raniel90** [comment]
Thanks @taivu. Works for me

**Comment by humpedli** [comment]
@taivu If you have NgxMaskModule in two different modules, don't you have a default~<first_module_name>~<second_module_name> chunk if you use it like you wrote? Because I have and I don't know why, but it slows down the application.

**Comment by Amitjbhalerao** [comment]
thanks @taivu , works for me.
