### ISSUE TITLE
autoclear view by select and click

### ISSUE THREAD

**Issue by zmnv** [JsDaddy/ngx-mask#192]
```
<input type="text" id="phone" formControlName="phone" prefix="+7 " mask="(000) 000 00 00" />
```

It works fine until I _double click_ to input field or _select_ then _click_.

1. Select text in input
2. Click to input text...
3. ngx-mask removes visible phone number, but doesn't update form model "phone". 

how to fix?

PS: It works without prefix.

PPS: Is it #188 ? Please update master.

---
Angular 5.1.0
ngx-mask 6.2.4

**Comment by Serge0111** [comment]
Hi @zmnv,
thanks for the issue, i found where the bug is,  i will fix it shortly

**Comment by Serge0111** [comment]
Hi @zmnv,
try 6.2.6 version

**Comment by zmnv** [comment]
Yes, CTRL+A then Backspace is fixed.

But. Try to select all and DEL. Same bag ^)
