### ISSUE TITLE
IE not working the demo

### ISSUE THREAD

**Issue by me-amit** [JsDaddy/ngx-mask#193]
I am trying to load the demo appliction on IE 11. But it is not loading
https://jsdaddy.github.io/ngx-mask/

When I opened it in IE it will only show the loading and in console it is showing the error like 
SCRIPT5022: Exception thrown and not caught
_for-of.js (14,1)

**Comment by Alexandr98** [comment]
@me-amit Hi, we have just fixed issue - connected polyfills for IE. This should works for you.
