### ISSUE TITLE
Clear using select all and backspace

### ISSUE THREAD

**Issue by oakfield** [JsDaddy/ngx-mask#200]
The NgModel doesn't update when you clear the input in some ways, such as by selecting all text with CTRL + A.

Steps to reproduce:

1. Go to the first example on the demo page.
2. Type some text, such as "12345678".
3. Select all text in the input through either CTRL + A or by holding the left mouse button and dragging the mouse.
4. Clear the text by pressing backspace.

Expected behavior: the NgModel updates to "Empty."

Actual behavior: the NgModel does not update.

**Comment by ashishyadav23** [comment]
Any update I am also facing same issue

**Comment by Serge0111** [comment]
hi @oakfield ,
try version 6.4.13 , it should work.

**Comment by silvl** [comment]
Having same issue in v 7.3.0

**Comment by kovaldenys96** [comment]
It hasn't fixed yet... The same for v. 8.1.7

**Comment by NepipenkoIgor** [comment]
@oakfield @ashishyadav23 @kovaldenys96 
![ezgif-5-2f0fff893c83](https://user-images.githubusercontent.com/7725146/89897343-898f0000-dbe7-11ea-8131-5d16fac24b72.gif)
It seems work as expected
