### ISSUE TITLE
Possibility to add property repeat mask?

### ISSUE THREAD

**Issue by AntonDershen** [JsDaddy/ngx-mask#201]
Afternoon.
For example, I need to make mask with 10 symbols.
I can create mask = "AAAAAAAAAA" or I can create mask = "A" and set repeatMask=10.

That would be a good feature.

**Comment by Alexandr98** [comment]
@AntonDershen Hi, we fixed this in version 6.5.15
For example:
<input type="text" mask="A{10}">
and A repeats 10 times.
