### ISSUE TITLE
Custom pattern issue

### ISSUE THREAD

**Issue by AntonDershen** [JsDaddy/ngx-mask#202]
Afternoon,
I create custom patterns : 
`public customPatterns= {`     
    `'0': { pattern: new RegExp(/[1-9]/)},`     
    `'1': { pattern: new RegExp(/[0-9]/)},`     
 `};`

And create mask:
`   public mask: '01';
`
And I can input value 0. But in pattern '0' value 0 is not exists.

If i change code like this:

`public customPatterns= {`     
    `'F': { pattern: new RegExp(/[1-9]/)},`     
    `'1': { pattern: new RegExp(/[0-9]/)},`     
 `};`  
`   public mask: 'F1';
`
I can input value F, but value f is not exist in patter 'F'.

if i change code like this:

`public customPatterns= {`     
    `'1': { pattern: new RegExp(/[1-9]/)},`     
    `'2': { pattern: new RegExp(/[0-9]/)},`     
 `};`  
`   public mask: '12';
`

everything works fine.

**Comment by Alexandr98** [comment]
Hi @AntonDershen, we’ve fixed this issue when you create custom pattern, for example:
public customPatterns= {‘F’: { pattern: new RegExp(/[1-9]/)}}.
mask= ‘FF’.
