### ISSUE TITLE
Add ability to pass patterns/config to MaskPipe

### ISSUE THREAD

**Issue by LaserUnicorns** [JsDaddy/ngx-mask#206]
Right now pipe accepts value and mask, if would be nice to pass optional patterns object or full config to pipe

**Comment by Alexandr98** [comment]
Hi @LaserUnicorns please send example.

**Comment by LaserUnicorns** [comment]
So basically i want this pipe usage in template
```
<span>
  {{ value | mask:myMask:myPatterns }}
</span>
```
or
```
<span>
  {{ value | mask:myMask:myConfig }}
</span>
```

This is similar to mask directive, where I can supply custom patterns
```
<input type='text' [patterns]="customPatterns" mask="(000-000)" >
```

**Comment by Alexandr98** [comment]
@LaserUnicorns Hi, try version 6.4.12.
