### ISSUE TITLE
ngx-mask breaks ngModel default writeValue flow

### ISSUE THREAD

**Issue by nazar-kuzo** [JsDaddy/ngx-mask#208]
MaskDirective.writeValue has such check at the beginning:
if (inputValue === undefined) {
      return;
}

This actually causes input not updating the value, but the model does, so we trap into situation where the
input shows value but model has 'undefined'.

Steps to reproduce:
1. create input with mask on it and ngModel bound to field
2. type whatever inside input
3. set field = undefined

Expected result:
input is empty

Actual result:
input is not cleared but field does

Possible fix:

Replace line of code:
if (inputValue === undefined) {
      return;
}

To:
if (inputValue === undefined) {
      inputValue = null; // or whatever else "", etc
}

**Comment by Alexandr98** [comment]
@nazar-kuzo Hi, we fixed this. We replaced return with inputValue = '', try now.

**Comment by nazar-kuzo** [comment]
Perfect, thanks!

**Comment by Alexandr98** [comment]
@nazar-kuzo Try version 6.3.10
