### ISSUE TITLE
warning when try to build production mode

### ISSUE THREAD

**Issue by zMADCATz** [JsDaddy/ngx-mask#209]
I try to build production mode but I see warning from cli

<img width="932" alt="screen shot 2561-10-04 at 11 34 13" src="https://user-images.githubusercontent.com/9088059/46453250-b93e7700-c7ca-11e8-999b-3085d1e4e2a2.png">

should I worry about it ?

**Comment by 9brabus9** [comment]
Hey @zMADCATz,
Could you send print screen how you use MaskPipe?

**Comment by zMADCATz** [comment]
@9brabus9 
I use it in input tag like this
`<input type="text" value="{{taxPayerNo | mask: '0-0000-00000-00-0'}}" readonly />`

**Comment by 9brabus9** [comment]
@zMADCATz,  did you try to delete all node_modules and do npm i?

**Comment by zMADCATz** [comment]
@9brabus9  It's work thank you.
