### ISSUE TITLE
Direction of mask

### ISSUE THREAD

**Issue by gfdeluca** [JsDaddy/ngx-mask#214]
Its posible to add a direction to the input so the mask be a little more friendly? My approach comes to telephone numbers.
For example I am from Argentina, the telephone number mask is like this (900) 0000-0000, so if you don't put de first letter (really the final number) the mask finish like this, (123) 4567-890, but if you can set the direction from right to left it ll be (12) 3456-7890

**Comment by orochiminami** [comment]
Could someone do this functionality? Using (or trying to use) pipes and directives to do this work is a waste of time and lines od code...

**Comment by christopheelkhoury** [comment]
@gfdeluca I didn't understand your requirement

**Comment by Thegrep01** [comment]
@gfdeluca Thanks for your suggestion, we think about implementation this feature in future

**Comment by thelebdev** [comment]
This discussion says it's `Done`
[This](https://github.com/JsDaddy/ngx-mask/projects/2#card-19557800) card says otherwise
