### ISSUE TITLE
After selecting all text and pressing backspace nothing happens

### ISSUE THREAD

**Issue by KevinLira** [JsDaddy/ngx-mask#215]
It seems to be a common behavior of the component, although, it is still a litte bit strange. 

You can:
Write on a masked field and erase it without any problem, character by character.
Write on a masked field, and select all the content, and press Delete, Works Fine.

but you can't:
Write on a masked field, select all the content and press backspace. text does not goes out. tested in Chrome, Safari and IE

**Comment by Alexandr98** [comment]
@KevinLira Hi, When we reproduced this, all worked fine.
What operating system are you using?

**Comment by KevinLira** [comment]
Using Windows 10 for Chrome and IE11
Using iOS 12 for Safari

**Comment by KevinLira** [comment]
Version 6.5.16 Fix this issue. Thanks
