### ISSUE TITLE
Using single and double quote as special chars

### ISSUE THREAD

**Issue by maettyhawk** [JsDaddy/ngx-mask#217]
I'm having trouble to use single and double quotes as special characters...
I fail to escape the double quotes, so I thought I could use &qout; instead. But also using single quote in the mask fails, I'm not able to add any characters to the input field when the caret position is right before the defined quote.

**Comment by 9brabus9** [comment]
hi @maettyhawk,
Could you give an example of mask that you want to use?

**Comment by 9brabus9** [comment]
Hi @maettyhawk,
We added single and double quotes to specialCharacters, so right now you can use their code for your case : &#39; for ', &#34; for ". Try 6.5.16
example: mask="0&#34;0&#39;0.00"

**Comment by 9brabus9** [comment]
Hi @maettyhawk,
We added single and double quotes to specialCharacters, so right now you can use their code . Try 6.5.16
