### ISSUE TITLE
Mask removes the rest of digits when changed in middle

### ISSUE THREAD

**Issue by Lev09** [JsDaddy/ngx-mask#222]
I am using Mask for phone numbers and have noticed an issue. When I change the number in middle it  deletes the rest on right side except first digit.

Here is the mask I am using: `\+9 999 999-99-99`

Here is how it looks:

![mark-issue-3 1](https://user-images.githubusercontent.com/4953382/47024761-63c37c00-d173-11e8-9b62-ef5d7f21197b.gif)

**Comment by NepipenkoIgor** [comment]
@Lev09 Hi we will check

**Comment by Thegrep01** [comment]
@Lev09 We checked this, all works

**Comment by Thegrep01** [comment]
@Lev09 send us your package.json or try latest version of ngx-mask

**Comment by Lev09** [comment]
I am no longer working on that project so I don't have the package.json

But anyway thanks for your time and effort.

**Comment by Thegrep01** [comment]
@Lev09 okay
