### ISSUE TITLE
Option to add masked value in ngModel

### ISSUE THREAD

**Issue by macin40** [JsDaddy/ngx-mask#228]
How can I bind the ngModel with the masked value,
Currently if , masking is 00-00-00 (HH-MM-SS), the value of a ngModel variable will be 000000,
How can I make the value  00-00-00 in ngModel variable?
To be more specific I want the makes characters to be included in ngModel.

**Comment by NepipenkoIgor** [comment]
@macin4 Hi , please use ` [dropSpecialCharacters]="false"`
