### ISSUE TITLE
RegEx for 24 hour time -> HH:MM:SS

### ISSUE THREAD

**Issue by macin40** [JsDaddy/ngx-mask#229]
How to get this masking, such that the maximum value for the hour is 23, 
Right now I am using, 
public customPatterns = {
    '0': {pattern: new RegExp('\[01]|2')},
    '1': {pattern: new RegExp('\[0-9]|[0-3]')},
    '2': {pattern: new RegExp('\[0-5]')},
    '3': {pattern: new RegExp('\[0-9]')},
    '4': {pattern: new RegExp('\[0-9]')}
  };
 mask="01:23:23.444"

where the maximum input it upto  29, but I want it upto 23

**Comment by Nanra** [comment]
Try this one :

mask="01:23:23"

patterns = {
    '0': {pattern: new RegExp('[01]|2')},
    '1': {pattern: new RegExp('[03]|[0-3]')},
    '2': {pattern: new RegExp('[0-5]')},
    '3': {pattern: new RegExp('[0-9]')},
  };

And i got like this Picture.
![screenshot from 2018-11-21 18-32-20](https://user-images.githubusercontent.com/9511668/48838766-ee734880-edbb-11e8-8479-e94b49b0e5e6.png)

**Comment by akvaliya** [comment]
It removed `:` from output. Is there a way to achieve this? Also like to show validation on incomplete field.

**Comment by Rickybarb5** [comment]
@akvaliya I have the same issue. Any fix one this?

**Comment by Rickybarb5** [comment]
@akvaliya  set [dropSpecialCharacters]="false"
