### ISSUE TITLE
Need to use single quote for height mask

### ISSUE THREAD

**Issue by ruudyroon** [JsDaddy/ngx-mask#230]
it needs to work like this 

eg - 6'11" or 5'11" 

is it possible to have single quote in special characters? Every time I try to add the application breaks

 specialCharacters="[ ''' ]"

**Comment by ruudyroon** [comment]
I saw this ticket 
https://github.com/JsDaddy/ngx-mask/issues/217

but didn't understand the last answer "We added single and double quotes to specialCharacters, so right now you can use their code . Try 6.5.16"

**Comment by NepipenkoIgor** [comment]
@ruudyroon We will check

**Comment by ruudyroon** [comment]
@NepipenkoIgor  this was a mistake from my side it seems the mask is working for single quotes 

i just had to escape the quote with this '0\'\'00\'
