### ISSUE TITLE
ngx mask is setting form.pristine = false if form has Input with value bound with ngModel 

### ISSUE THREAD

**Issue by kcprabase** [JsDaddy/ngx-mask#232]
I have a form with mat input that uses ngx-mask. When i have to edit form, it prepopulates data in all fields of form. But I found that in such case, if i check if the form is pristine or not using `let isPristine = form.pristine`, false is set to isPristine. No field has been even touched  and it sets it to false. Can this issue be fixed. I need this because I need to save my form data only if the form is not pristine.
Following is the code, and below that you can see that that one field has pristine = false. that causes whole form's pristine = false.

![image](https://user-images.githubusercontent.com/33727948/47614139-03adcd80-dac3-11e8-8b71-1172b0df0e20.png)

![image](https://user-images.githubusercontent.com/33727948/47614147-1aecbb00-dac3-11e8-83ff-982a4b0ed04e.png)

**Comment by NepipenkoIgor** [comment]
@kcprabase we will check

**Comment by Thegrep01** [comment]
@kcprabase i did not find this prob, please give more details about your prob and config or  try the latest version of ngx-mask
