### ISSUE TITLE
showMaskTyped cursor moves forward when input does not match mask

### ISSUE THREAD

**Issue by iplante** [JsDaddy/ngx-mask#235]
This is demonstrable on the [demo page](https://jsdaddy.github.io/ngx-mask/). 

1. Go to the Phone Number input with showMaskTyped=true.
2. Type numbers - the mask cursor will move forward as you type as expected, and the mask will be applied.
3. Erase your input, and start typing non-numbers (letters, special characters, etc.) in the field. The characters won't be displayed, but the cursor moves forward in the mask.

**Expected behavior**: The incorrect input, such as letters, will not be displayed in the mask AND the cursor will not move forward.

**Comment by iplante** [comment]
@NepipenkoIgor @Alexandr98 any updates?

**Comment by Thegrep01** [comment]
@iplante This problem can not be fixed

**Comment by Zima04** [comment]
Hello @iplante,
I ran into the problem of the initial position of the cursor and wrote a function for putting the cursor in the right place of your mask.
I hope this helps you ;)

//**Your component.ts**// 
setSelectionRange(input, selectionStart, selectionEnd, value) {
    if (value) return;
    if (input.setSelectionRange) {
      input.focus();
      input.setSelectionRange(selectionStart, selectionEnd);
    } else if (input.createTextRange) {
      let range = input.createTextRange();
      range.collapse(true);
      range.moveEnd('character', selectionEnd);
      range.moveStart('character', selectionStart);
      range.select();
    }
  }

/* Html */
  <input type="text" class="form-control" mask="(000) 000-00-00" prefix="+1" [showMaskTyped]="true"
                 id="input-phone-1" formControlName="phone" #inputPhone1 (click)="setSelectionRange(inputPhone1, 3, 3,form.get('phone').value)">

**Comment by rakeshnayak360** [comment]
this solution doesn't work
