### ISSUE TITLE
Repeat mask is not working.

### ISSUE THREAD

**Issue by AntonDershen** [JsDaddy/ngx-mask#237]
When i inputed mask A {9} repeat is working.
But when i inputed A {10) (I input two or more digits value) repeat is not working.
I investigated your code:
In file mask.directive.ts your have method _repeatPatternSymbols.
In this method your have this pattern {[0-9a-zA-Z]}. This pattern match only 1 digit value for repeat mask.
Please fix that.

**Comment by NepipenkoIgor** [comment]
@AntonDershen Thank you. We will check this.

**Comment by PalanikumarNet** [comment]
It is working for only up to {9}, not working for {10}
