### ISSUE TITLE
Mask - 0*.00 not working properly

### ISSUE THREAD

**Issue by Exerlol** [JsDaddy/ngx-mask#238]
Hello, first of all thanks for a great plugin and for all the effort your putting in this project :) 

Here's what I'm currently facing in my app, I'm trying to use this mask 0*.00 on my input, something like this for example: 

`<input type="number" required mask="0*.00" matInput [ngModel]="unitPrice" placeholder="Unit price" #unitPrice="ngModel" name="unitPrice">`

It all looks fine on front end as it comes to masking... however, once i try to submit this form value of unit price is just number without decimal places...anyways to clarify it more below are example photos of what I'm talking about

![input](https://user-images.githubusercontent.com/10726640/48055546-2a998d00-e1b0-11e8-8735-a90491d51d1c.png)

![obj](https://user-images.githubusercontent.com/10726640/48055534-240b1580-e1b0-11e8-9675-ea6c46be98c2.png)

Any ideas if I'm doing something wrong? Or is this a known issue with ngx-mask?

**Comment by NepipenkoIgor** [comment]
@Exerlol  You don't use `dropSpecialCharacters` options. Default it true . You should `[dropSpecialCharacters]="false"`
