### ISSUE TITLE
ShowMaskTyped - doesn't replace letters in mask

### ISSUE THREAD

**Issue by tavianm** [JsDaddy/ngx-mask#239]
Hello, 

First of all, thanks for this useful plugin!

I'm trying to use a mask containing `0{2}-0{5}-0{5}-A{11}-0{2}` with `[showMaskTyped]="true"`.

Unfortunately, my input appears like that `__-_____-_____-AAAAAAAAAAA-__`.

Am i missing something or doesn't showMaskTyped handle letter in mask replacing?

**Comment by NepipenkoIgor** [comment]
@tavianm  Hi. Thank you for use it. We will check this behavior

**Comment by Thegrep01** [comment]
@tavianm [showMaskTyped]="true" works only for phone number

**Comment by Thegrep01** [comment]
@tavianm  check the latest version
