### ISSUE TITLE
Can it work with ionic's ion-input?

### ISSUE THREAD

**Issue by brevleq** [JsDaddy/ngx-mask#24]
Hi, I tried use your directive with Ionic 2 ion-input, however nothing happened:

    <ion-item>
                <ion-label floating>CEP</ion-label>
                <ion-input type="text" name="cep" id="cep" #cepInput="ngModel"
                           [(ngModel)]="cliente.cep" specialCharacters="false" mask='00.000-000'
                           required></ion-input>
      </ion-item>

Is there something I can do to make it work with Ionic?

**Comment by victorschinaider** [comment]
I don't know, i will see something.

**Comment by cesargrano** [comment]
Please can you see why it does not work on IONIC or IONIC 2

**Comment by lucascco** [comment]
@brevleq @victorschinaider @cesargrano We create one mask lib to work with Ionic that uses the NGX-MASK service: https://github.com/Pluritech/ion-mask

**Comment by NepipenkoIgor** [comment]
@lucascco awesome , perfect work
