### ISSUE TITLE
Mask while typing

### ISSUE THREAD

**Issue by sayax** [JsDaddy/ngx-mask#246]
Hi, i came across an issue where i want mask to apply on input while typing numbers
For example, if i typed 1000 mask should apply 1 000, currently it shows like 100 0, my mask is 
mask="000 000 000 000", or am i doing something wrong?
I want it to work like number pipe in angular 6, to divide number every thousandths

**Comment by Thegrep01** [comment]
For 1 000 you need 0 000 mask, for 10 000 - 00 000 and so on

**Comment by Thegrep01** [comment]
@sayax We added this feature in 7.1.0 ver, please update ngx-mask to the latest

**Comment by sayax** [comment]
@Thegrep01  thank you for this feature, but now we have another issue that the cursor not in a right place when mask separates digits.
