### ISSUE TITLE
Use mask in field email type=email

### ISSUE THREAD

**Issue by schirato** [JsDaddy/ngx-mask#247]
Hi, when set my input field **type=email** this is error is show: **Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.** 

And may field in desktop is crashed after input any value and try remove value inputed.

I need type=email for the show keyboard email in mobile

**Comment by Thegrep01** [comment]
@schirato 
This mask is for text typed fields. For what you need to use it with emails ?

**Comment by schirato** [comment]
To apply the mask A*@A*.SSS in an input type e-mail, since I need the keyboard e-mail in the mobile. And you do not need to do all typescript validation.

**Comment by Thegrep01** [comment]
@schirato standard html input with email type has validation

**Comment by ezequiel88** [comment]
if format email 'teste@teste.com.br' ?
