### ISSUE TITLE
showMaskTyped seems not work

### ISSUE THREAD

**Issue by veronesecoms** [JsDaddy/ngx-mask#248]
I have this input:

`<input required [(ngModel)]="mesAnoReferente" dropSpecialCharacters="false" minlength="8" mask="00/00/0000" showMaskTyped="true" type="text" id="inputMesAno" name="inputMesAno" class="form-control">`

The mask is working but the showMaskTyped is not showing the format of my mask. I'm forgetting something?

**Comment by chrisbertrandsagecom** [comment]
ShowMaskedType only works with numbers at the moment. You will need to wrap your showMaskTyped in square brackets like so... [showMaskTyped] to get it to work.

mask.service.ts ln 34 regex needs changing to allow characters too. I will look at creating a pull request.

**Comment by Thegrep01** [comment]
@chrisbertrandsagecom greate answer
