### ISSUE TITLE
Using 9*.9 is not working as expected

### ISSUE THREAD

**Issue by santhosh-ps** [JsDaddy/ngx-mask#249]
Thank you very much for creating this wonderful module just a minor issue we faced:

Using 9*.99 we should be able to enter '.23' i.e to begin with '.',  but it's not working, behaviour is similar to using 0*.99 as if number before '.' is required.

**Comment by Thegrep01** [comment]
@santhosh-ps 
Checked, works correctly
<img width="227" alt="#" src="https://user-images.githubusercontent.com/38587958/49727903-0aab2c80-fc7a-11e8-95bf-3ba2ffd122c1.png">

**Comment by Thegrep01** [comment]
@santhosh-ps send me your package.json
