### ISSUE TITLE
the cursor moves as you enter an invalid value

### ISSUE THREAD

**Issue by NeoSimvolist** [JsDaddy/ngx-mask#250]
the cursor moves in this case:
showMaskTyped = true;
Mask: +5 (000) 000 0000

try to enter something other than numbers

Is this a bug or a feature?)

**Comment by Thegrep01** [comment]
@NeoSimvolist This problem can not be fixed

**Comment by Thegrep01** [comment]
The other packages work the same, we will try to fix this but later
