### ISSUE TITLE
Currency Mask allow Zero as first input(ie. $ 002500)

### ISSUE THREAD

**Issue by Rajanusa** [JsDaddy/ngx-mask#258]
Hi,

The currency mask allow Zero as first input(ie. $ 002500). 
Please find my mask attribute and prefix property and let me know, how to avoid this input.
                <input type="Text"  mask='0*.00' prefix="$ " [dropSpecialCharacters]="false">
Thanks
Raj

**Comment by sayax** [comment]
you should use pattern in mask as [1-9] to disallow first 0 input

**Comment by Thegrep01** [comment]
`public customPatterns = {'0': { pattern: new RegExp('\[1-9\]')}};`
in your app component
`[patterns]="customPatterns"`
as input attribute

**Comment by Rajanusa** [comment]
> `public customPatterns = {'0': { pattern: new RegExp('\[1-9\]')}};`
> in your app component
> `[patterns]="customPatterns"`
> as input attribute

Hi,
A user should be allowed to enter 0.50 but should not be allowed to enter 075
Please suggest.
Thanks
Raj
