### ISSUE TITLE
Demo page is down - returns 404

### ISSUE THREAD

**Issue by komichar** [JsDaddy/ngx-mask#262]
The demo page is down.

Visiting the [https://jsdaddy.github.io/ngx-mask/](https://jsdaddy.github.io/ngx-mask/) gives 404.

It was working a few days ago when I last visited it.

Any idea?

**Comment by NepipenkoIgor** [comment]
@komichar Hi. Thank you . We will work with new deploy system . And this page will be available soon

**Comment by NepipenkoIgor** [comment]
@komichar  Please try . And pay attention  that we added new features and fix a lot issues
