### ISSUE TITLE
Wierd if select all used with prefix

### ISSUE THREAD

**Issue by Et3rnal** [JsDaddy/ngx-mask#263]
I found a bug on 7.2.0, using firefox and chrome
All you need to reproduce is a simple mask and a prefix, now enter anything then Ctrl + A and backspace and the prefix will be duplicated!

If you do it for a few times you can't even type!
My mask is
`mask="00 0000 0000"`
Also, is there a way to make prefix visible by default without using "showMaskTyped"?
thanks

**Comment by Thegrep01** [comment]
@Et3rnal we will check this, but prefix is visible by default

**Comment by Thegrep01** [comment]
@Et3rnal can you give more information about your config ?

**Comment by Thegrep01** [comment]
@Et3rnal I check, but did not find such proplem

**Comment by luishmcmoreno** [comment]
I'm facing the same problem.

Config: 

```
Angular CLI: 6.2.8
Node: 10.13.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.8
@angular-devkit/build-angular     0.8.8
@angular-devkit/build-optimizer   0.8.8
@angular-devkit/build-webpack     0.8.8
@angular-devkit/core              0.8.8
@angular-devkit/schematics        0.8.8
@angular/cli                      6.2.8
@ngtools/webpack                  6.2.8
@schematics/angular               0.8.8
@schematics/update                0.8.8
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```
My HTML:
    <input class="form-control" type="text" id="plate" prefix="BUS-" mask="AAA-AAA" formControlName="plate">

When I press Ctrl+A (Select All) and backspace, the value of the input transform to: BUS-BUS
