### ISSUE TITLE
Undefined value instead of emtpy string after formControl deleted

### ISSUE THREAD

**Issue by emelnychenko** [JsDaddy/ngx-mask#265]
I'm using mask for number like input. Type defined as int32 inside protobuf file. 

`
<input matInput
                                           formControlName="taxId"
                                           mask="00-0000000"
                                           placeholder="Business Tax ID"
                                    >
`

By default value of formControl equal "undefined". Than I've tried next scenario: write something and delete it. Value of formControl equal empty string "" (in my case it's not matched numeric format like int32, just empty string). There is no possibility to configure default value as "undefined". Here code which works fine:

`
<input matInput 
                                           formControlName="zipCode"
                                           placeholder="Postal Code"
                                           type="number"
                                           minlength="5"
                                           maxlength="5"
                                    >
`

When you're deleted value from formControl it will equal 'undefined'. 

Is it possible to fix it? Thanks.

**Comment by Thegrep01** [comment]
@emelnychenko First of all mask works only with input type text, if you want to gent number values from input with mask check this issue [https://github.com/JsDaddy/ngx-mask/issues/240](url)

**Comment by emelnychenko** [comment]
I'm understand it. I will describe more detail. API built on PHP and using official protobuf package. `012` - it's numeric value for PHP and can be parsed as a number. `''` - it's empty string. Field is optional and can pass `null` or numeric value(string like number or real number) as valid one. My request was about replacing empty value `''` to `undefined` after any formControl modification.

**Comment by Thegrep01** [comment]
@emelnychenko as a solution can offer you to check the value from your input and if it is empty string. you can not to set value of undefined to formControlName only null value
