### ISSUE TITLE
Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.

### ISSUE THREAD

**Issue by KeithCrabtree** [JsDaddy/ngx-mask#266]
Running into this issue when I have an input with type 'email', even though the mask directive is not present. I saw the other closed issue that was similar but I'm not understanding why your mask directive's `onFocus` is firing in this case. Maybe something simple I'm overlooking?

**Comment by Thegrep01** [comment]
@KeithCrabtree Can you give a bit more information how to reproduce your problem, because i did not find this prob

**Comment by KeithCrabtree** [comment]
@Thegrep01 my issue was a little strange. I have what is essentially an input component. It's simply a label and input with a handful of `Input`s that set attributes and so on. One of these I had called `mask`, which was the string I wanted to use for the phone/postal code mask and `null` otherwise. Apparently you can't conditionally add/remove the mask attribute so I created another input component to use for email, which doesn't have it. Thanks for your time!
