### ISSUE TITLE
Currency formatting not updated supplied data

### ISSUE THREAD

**Issue by soupman99** [JsDaddy/ngx-mask#267]
Great  tool!

When I set `mask="*0.00"`  and type in 125.00 my value is saved as 12500 which is correct.  However, when I reload the page and data is pre-populated into the field the value in the form field reads 12500 not 125.00

Also, there should probably be a way to populate from the right.  For instance

`___.__`
`___._1`
`___.12`
`__1.25`
`_12.50`
`125.00`

**Comment by Thegrep01** [comment]
@soupman99 Because you save 12500 and mask does not know where put . , however if you use 000.00 mask will work correctly or you can use `[dropSpecialCharacters]="false"` and save 125.00

**Comment by tcrite** [comment]
I agree with having ability to start typing from the right would be a nice to-have. A similar issue I'm having is if I pass in say, 6.3...I'd expect 6.30 to be displayed. Instead I'm just getting the 6.3. I tried using masks of "000.00", "999.99", and "coma_separator.2"

**Comment by ValeriaKochegarova** [comment]
@soupman99 you need set mask="0*.00" and add [dropSpecialCharacters]="false" that will work correct for your case
