### ISSUE TITLE
Separator is not working with sufix

### ISSUE THREAD

**Issue by humpedli** [JsDaddy/ngx-mask#268]
If I combine **separator** mask type with **sufix**, input reacts weird.

`<input type="text" mask="separator" sufix=" HUF">`

Examples:

Type in: `1` You will get --> `1 HUF` = _ok_
Type in: `11` You will get --> `11HU HUF` = **not ok**, expected: `11 HUF`
Type in: `111` You will get --> `111HUHU HUF` = **not ok**, expected: `111 HUF`
Type in: `1111` You will get --> `1 111HUHUHU HUF` = **not ok**, expected: `1 111 HUF`
...

**Comment by Thegrep01** [comment]
@humpedli Yes now separator is not working with sufix, we will add this in next versions

**Comment by NepipenkoIgor** [comment]
@christopheelkhoury It will be awesome if you can help us

**Comment by Tipster74743** [comment]
This is affecting the dot_separator and coma_separator as well. I could also do a PR if needed.

**Comment by Thegrep01** [comment]
@Tipster74743 It will be great!!!

**Comment by christopheelkhoury** [comment]
Y'all still need help with this?

**Comment by Tipster74743** [comment]
I'm going to make a PR for that.

**Comment by Thegrep01** [comment]
@humpedli check the latest version
