### ISSUE TITLE
separator with "." instead of "space"

### ISSUE THREAD

**Issue by nickinylin** [JsDaddy/ngx-mask#269]
Hello! I really like your tool! Unfortunately im stuck with a problem. Is is possible to make the thousand separator with a dot "." instead of a space between the numbers?

**Comment by Thegrep01** [comment]
@nickinylin We will add this functionality in latest versions

**Comment by Thegrep01** [comment]
@nickinylin maybe tomorrow

**Comment by nickinylin** [comment]
Wow perfect! That was fast 🎅🏼😃 have a great day

**Comment by Thegrep01** [comment]
@nickinylin check the latest version and readme

**Comment by nickinylin** [comment]
This was very helpful, but i noticed something i apperently didn't test for before. Isn't it possible to write a negative value? I can only write positive, so i can't put a "-" in front of the value

**Comment by Thegrep01** [comment]
@nickinylin you can use [dropSpecialCharacters]="false"

**Comment by nickinylin** [comment]
I don't think that works as expected. I can't write a a "-" initially, and if i write for example "1234" and put the curser in the beginning and write "-", then the field is now "-123" and i can't add anything anymore to the input field. I have to delete it all again :( Thanks for your time!

**Comment by Thegrep01** [comment]
@nickinylin fix this, it will be added as soon as possible
