### ISSUE TITLE
Show special characters #

### ISSUE THREAD

**Issue by ganeshjangam** [JsDaddy/ngx-mask#272]
Hello, 

 Tried multiple ways but not able to apply masking for this value : **123451234512345123451234512345123**

its a secrete code and 
Expected mask like this : **###.#####.####.######.######.####.#####**

How can i do this ? Please guide.

**Comment by AlexeyDolya** [comment]
@ganeshjangam you can use secure mask, for this you define custom pattern for instance:
  custom pattern: Z: {
            pattern: new RegExp('\\d'),
            symbol: '#'
   }

mask expression: ZZZ.Z0.0000
