### ISSUE TITLE
clearIfNotMatch  is not working properly with mask 0*.00

### ISSUE THREAD

**Issue by akvaliya** [JsDaddy/ngx-mask#276]
I am trying to use mask `0*.00` for amount & i tried to use `[clearIfNotMatch]="true"`

As per ex. `2017.22` is valid value but it still clears input on blur.

So basically with mask `0*.00` if you use `[clearIfNotMatch]="true"`, it clears input even if value is valid.

I tried with different valid values & it clears every time whether value is valid or not.

What am i missing here?

**Comment by Thegrep01** [comment]
@akvaliya Now `[clearIfNotMatch]="true"` does not works with multiply mask, we will add this in new versions

**Comment by ValeriaKochegarova** [comment]
@akvaliya we fixed this you can try to use it in the latest version
