### ISSUE TITLE
Using thousand separator mask and decimals at the same time

### ISSUE THREAD

**Issue by EkaterinaMozheiko** [JsDaddy/ngx-mask#277]
Hi,
your new feature of thousand separator mask is great, but is it possible to add feature to enter decimals while using mask for thousand separator? It is especially important for currency fields.

**Comment by Thegrep01** [comment]
@EkaterinaMozheiko Hi, we added this in the new version

**Comment by Thegrep01** [comment]
@EkaterinaMozheiko check the latest version
