### ISSUE TITLE
mask dot_separator allows special characters

### ISSUE THREAD

**Issue by juanprojas** [JsDaddy/ngx-mask#279]
Hi,

Why when i use mask="dot_separator" or separator, the mask allows special characters? , i used  [dropSpecialCharacters]="true" but it does not work either, is this a bug?

**Comment by achubai** [comment]
I have the same question/issue and think it is a bug because you can do such things:
`mask="separator" --> 223 123,,,,,.123123,,,`
`mask="dot_separator" --> 23.213      ,123213       0`
