### ISSUE TITLE
Currency Prefix $ is not appear in input control on form load in DEV Server / QA Server

### ISSUE THREAD

**Issue by Rajanusa** [JsDaddy/ngx-mask#282]
Hi

I use the ngx-mask and it works in local web app and hosted web app.
In local web app, on form load, all control has $ prefix without user focus on any input control.
The same app hosted in DEV Server/ QA Server, it shows $ prefix only when focus on that control otherwise, it is not showing.
This is behavior comes in Chrome browser and did not check other browser.
I want all the prefix to appear when the form load so that user know the user input data type.
Please guide me on this.

Thanks
Rajan

**Comment by ValeriaKochegarova** [comment]
@Rajanusa  we fixed this and try to update mask latest version
