### ISSUE TITLE
ngForm bug, mask removes some symbols

### ISSUE THREAD

**Issue by frkntony** [JsDaddy/ngx-mask#284]
For some reason I'm unable to get several symbols as my value e.g .@ 

Well, I'm trying to use it for facebook validation. It forces me to use the mask. I'm only allowed to type numbers, letters and dots --> expected behavior. All good here. However, I try to get my value in ngForm, it throws the error. 

The code that causes the bug: 

**my ts**
```
  facebookValidation = {
    facebookMask: '00000000000000000000000000000000000000000000000000',
    facebookPattern: {'0': { pattern: new RegExp('\[\\w.-\]')}}
  };
```
**my html**

`<input type="text" name="facebook" [patterns]="this.facebookValidation.facebookPattern" mask="{{this.facebookValidation.facebookMask}}" class="socials-form__input" placeholder="Facebook"  [ngModel]="(dataMainInfo.aSocialNet.facebook && dataMainInfo.aSocialNet.facebook.sUrl)?dataMainInfo.aSocialNet.facebook.sUrl:''" autocomplete="off" minlength="3">`

**Reproduced**
![](https://i.imgur.com/GhqIYB6.jpg)
![](https://i.imgur.com/ZnEhFpJ.jpg)

When I change my ts and allow underscores instead of dots it works fine and doesn't remove underscores.
changed ts
```
  facebookValidation = {
    facebookMask: '00000000000000000000000000000000000000000000000000',
    facebookPattern: {'0': { pattern: new RegExp('\[\\w_-\]')}}
  };
```
**Reproduced**
![](https://i.imgur.com/vO8VSw0.jpg)
![](https://i.imgur.com/4ZheLbe.jpg)

**Comment by sebikeller** [comment]
Seems like `.` is a [special character](https://github.com/JsDaddy/ngx-mask#specialcharacters-string-) compared to `_`, so you should add `dropSpecialCharacters="false"` to your `<input/>`'s attribute list, then it works.

**Comment by frkntony** [comment]
Yup, it fixed it.

I probably should read docs more careful next time.

Thanks a lot for the answer. 

P.S.
**I suggest that everything should be a special character**. Meaning '_' shouldn't work as well. I think if underscore didn't work it'd shed some light on the problem for me. I really got confused because I didn't see '.' under the special characters.

**Comment by sebikeller** [comment]
You can also define the special characters by yourself. #rtfm ;)
