### ISSUE TITLE
Dynamic Mask Issue

### ISSUE THREAD

**Issue by drafenous** [JsDaddy/ngx-mask#289]
Hi everyone,
I'm using by the first time this module, and i trying to make a dynamic mask change for brazilian phone.

In brazil, we have 2 phone numbers formats:
Residential numbers: (00) 0000-0000 (area code) 4 digits - 4 digits.
Mobile numbers: (00) 90000-0000 (area code) 5 digits - 4 digits.

How to make to change this mask format when user is typing?

Kind Regards,
Drafenous.

**Comment by spelbreker** [comment]
same problem. other case

**Comment by spelbreker** [comment]
<input type="text" [mask]="currentMask" [formControl]="splitCtrl">

TS file
`  currentMask = '00:00:00.00';`

it changed the mask in code now

**Comment by MRMokwa** [comment]
@drafenous Did you get it working? Could you provide your solution?

**Comment by thaylongs** [comment]
> @drafenous Did you get it working? Could you provide your solution?

Hi @drafenous, look this: https://github.com/JsDaddy/ngx-mask/issues/271#issuecomment-492841525
