### ISSUE TITLE
ionic 2

### ISSUE THREAD

**Issue by cesargrano** [JsDaddy/ngx-mask#29]
No ion-input ionic 2 does not work, would have some solution for this

**Comment by NepipenkoIgor** [comment]
I didn't work with ionic , @cesargrano сould you help ?

**Comment by lucascco** [comment]
@cesargrano @NepipenkoIgor We create one mask lib to work with Ionic that uses the NGX-MASK service: https://github.com/Pluritech/ion-mask

**Comment by NepipenkoIgor** [comment]
@lucascco awesome , perfect work
