### ISSUE TITLE
Delete key not working with 'showMaskTyped'

### ISSUE THREAD

**Issue by cmaart** [JsDaddy/ngx-mask#291]
Reproducable on the demo site for me. Enter something in the field, tab out of it, tab back to it (or click inside and CTRL+A) and use the DEL key to remove the contents. Model is not updated. Backspace works.

![image](https://user-images.githubusercontent.com/4008452/51835239-11126800-22fd-11e9-8d24-32716deb9920.png)

**Comment by Thegrep01** [comment]
@cmaart we do not find this problem, try to use the latest version

**Comment by vaclav-antosik** [comment]
Issue is there.
Using version "ngx-mask": "^7.7.2".

In attached demo app:
![image](https://user-images.githubusercontent.com/8505433/55140971-9c5f7c80-5139-11e9-9eaf-3b6227bb1582.png)

1. Write date into "input". (You can observe value changes in console.)
2. Select whole date. Selection must be from beginning into end.
3. Press "delete" button.
4. Model is not updated. (You can observe no log in console about value changes.)

This is happening only if showMaskTyped = true.
