### ISSUE TITLE
Invalid mask does not mark form field as invalid

### ISSUE THREAD

**Issue by sdesmond** [JsDaddy/ngx-mask#293]
I don't see any examples of this behavior, but it seems like an obvious use case.  If the field does not match the mask, is it supposed to mark the form field as invalid?  

When using the mask in a form, I would want an invalid entry to trigger an invalid form, but I'm not seeing any errors in my app when the input is not filled out properly.

**Comment by remoteme** [comment]
I was going to ask exactly the same question, it would be a great feature !

**Comment by NepipenkoIgor** [comment]
@sdesmond @remoteme  We will add this in next release

**Comment by NepipenkoIgor** [comment]
@sdesmond @remoteme  Thank you. Please latest version of ngx-mask
