### ISSUE TITLE
cant add specialCharacters to pipe

### ISSUE THREAD

**Issue by IldarZainulinDev** [JsDaddy/ngx-mask#298]
Example:
```
phone = 722223334445555
<span>{{phone | mask: '0-000-000-000 Int. 0000'}}</span>
```
my expectations: 7-2222-333-444 Int. 5555

**Comment by Thegrep01** [comment]
@IldarZainulinDev Cause mask pipe use our mask service and we do not have such mask '0-000-000-000 Int. 0000
