### ISSUE TITLE
Mask doesn't work perfectly on mobile

### ISSUE THREAD

**Issue by bernardold** [JsDaddy/ngx-mask#30]
I want to use ngx-mask for a responsive angular4 project.

Tried in the example at https://nepipenkoigor.github.io/ngx-mask/ and on mobile browsers the inputs bug when a special character is inputted by its mask. It acts like the cursor goes 1 character back

**Comment by RenatoSilveiraGomes** [comment]
Same here.

**Comment by NepipenkoIgor** [comment]
@bernardold New version of ngx-mask available. You could check work of cursor and other options

**Comment by suhelkhan1** [comment]
I am experiencing the same issue on latest version also.

**Comment by rcasachi** [comment]
Same here

**Comment by gtsopour** [comment]
@NepipenkoIgor same from me. Please just check mask="000 000 00 00" with a native Android browser.

**Comment by gtsopour** [comment]
@NepipenkoIgor @suhelkhan1 Any update about Android devices anyone?

**Comment by NepipenkoIgor** [comment]
@gtsopour Hi , we will work with this before weekend

**Comment by gtsopour** [comment]
Thanks @NepipenkoIgor for the quick response.

**Comment by gtsopour** [comment]
@NepipenkoIgor Sorry for coming again but its really critical for me. Did you manage to check it or you suggest me to dig into the code too?

**Comment by LimarenkoDenis** [comment]
@gtsopour, @rcasachi, @suhelkhan1,   Sorry guys, that we postpone testing this bug, I tested it on default android browser, and it works fine there, could you please clarify or provide more details? My android version 5.1

**Comment by gtsopour** [comment]
@LimarenkoDenis For me its working as a mask but the cursor is moved when I am typing. Can you check that?

**Comment by gtsopour** [comment]
@LimarenkoDenis @NepipenkoIgor any update on this?

**Comment by NepipenkoIgor** [comment]
@gtsopour Hi. We don't have this device and it is difficult to reproduce this problem . Could you help find problem and maybe fix it with PR ?

**Comment by NepipenkoIgor** [comment]
related #94
