### ISSUE TITLE
Comma stripped from number by dropSpecialCharacters

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#302]
When I enter a number say: 1.931,89 the result in the model becomes 193189 instead of 1931.89 It looks like dropSpecialCharacters() removes the comma as well. 

```
<input
    mask="dot_separator.2"
    [dropSpecialCharacters]="true"
    [(ngModel)]="value"
>
```

**Comment by Thegrep01** [comment]
@basvdijk we will fix this in the latest versions

**Comment by basvdijk** [comment]
@Thegrep01 any thoughts on when a new version will be released with this bugfix?
