### ISSUE TITLE
Mask no applied properly after clearing input

### ISSUE THREAD

**Issue by zaalbarxx** [JsDaddy/ngx-mask#303]
Hi!
I found some issue with mask and prefix. You can check it out here:
https://stackblitz.com/edit/angular-nly5eu
Basically when you fill the input with some value and then you select the whole text and use backspace to clear the value the mask will behave incorrectly. Considering this scenario:
![image](https://user-images.githubusercontent.com/3301242/52431013-a389e700-2b07-11e9-8648-f8337f2939d6.png)
when you hit backspace you'll get:
![image](https://user-images.githubusercontent.com/3301242/52431036-aedd1280-2b07-11e9-9e2f-2ec86486af8d.png)
I tried to find the root cause of this problem, but for now I was not be able to track it down, maybe you have some idea how to fix it and you could guide me a bit or make a quick fix ? I would gladly make a PR, but I'd need to know first what could be wrong with this code ?
Cheers :)

**Comment by ValeriaKochegarova** [comment]
@zaalbarxx we fixed this you can use it in the latest version
