### ISSUE TITLE
clearIfNotMatch not working for Reactive Form

### ISSUE THREAD

**Issue by ermamud** [JsDaddy/ngx-mask#304]
Using the latest version at the moment (`7.4.0`), the `clearIfNotMatch` does not work for a reactive form field. This is my code example:
```
<input class="form-control mb-2" [ngClass]="{'is-invalid': hasError('phone')}" type="text" formControlName="phone" mask="(000) 000-0000" [showMaskTyped]="true" [clearIfNotMatch]="true" [dropSpecialCharacters]="true">
```

I tried with the `forRoot` method on the `app.module.ts` file and I tried on the template as shown above without any success. Any idea if I am doing it wrong?

Thank you,
Ernesto

**Comment by Thegrep01** [comment]
@ermamud Hello, i did not find this problem, probably in our demo we use clearIfNotMatch with formcontrol and all works good

**Comment by ABerzhanin** [comment]
@Thegrep01  it happens when  use both params:  [showMaskTyped]="true"   [clearIfNotMatch]="true"

**Comment by fair-man** [comment]
Hello. The defect is relevant, correction is required. 

params: [showMaskTyped]="true" [clearIfNotMatch]="true"

**Comment by fair-man** [comment]
![not_reset_value](https://user-images.githubusercontent.com/11162127/66499003-a8080480-eac7-11e9-9f17-ab390cda4a0f.gif)
