### ISSUE TITLE
Comma number gives NaN in model with dot_separator.2

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#305]
With #302 is fixed, now a new issue appears:

If I enter for example 5320,32 in a textbox with `dot_separator.2` it is displayed as 5.320,32 
The model however contains `NaN`

When using `coma_separator.2` everything works fine

**Comment by basvdijk** [comment]
@Thegrep01 Do you have any estimate on when this bug could be fixed?

**Comment by Thegrep01** [comment]
@basvdijk Hello could you provide a bit more details, because i did not find this problem

**Comment by basvdijk** [comment]
@Thegrep01 I am using the textbox like:
```
<input type="numeric" [(ngModel)]="data2" mask="dot_separator.2" [ngModelOptions]="{standalone: true}" >
```

As soon as I enter a `,` the value becomes NaN. I have feeling this has something to do with a number containing a comma can not be parsed. So before parsing, first the comma need to be changed with a dot. I noticed that `parseFloat(',323')` gives `NaN`

**Comment by Thegrep01** [comment]
@basvdijk ngx-mask works with input type text

**Comment by basvdijk** [comment]
Unfortunately I have the same `NaN` error with a text input: 
```html
<input type="text" [(ngModel)]="data2" mask="dot_separator.2" [ngModelOptions]="{standalone: true}" >
```

When I use `coma_separator.2`:
```
```html
<input type="text" [(ngModel)]="data2" mask="coma_separator.2" [ngModelOptions]="{standalone: true}" >
```
Everything works fine. The weird thing is when I checkout the ngx-mask code the tests run fine. As soon as I use it in our project we have this `NaN` issue only with `dot_separator.2`. Looks like some conversion to a number with a comma breaks or something.

**Comment by basvdijk** [comment]
@Thegrep01 why is this issue closed? Was it fixed?

**Comment by EdgarSalazar** [comment]
Error persists.

**Comment by EdgarSalazar** [comment]
`NaN` is happening when using Angular Reactive Forms, when serializing the masked `FormControl` using `this.formGroup.getRawValue()` or simply getting the value from `this.formgrou.get('maskedControl').value`, both return NaN

**Comment by jesusvillalbam** [comment]
Still happening...

**Comment by NepipenkoIgor** [comment]
@basvdijk @edgarfroes @jesusvillalbam Thank you that using ngx-mask . Please provide environment or open issue with right template and stackblitz example. Seems like no issue here . You need to use `separator.2` and `thousandSeparator=","` . Please look on example https://stackblitz.com/edit/angular-ivy-yy5kwm?file=src%2Fapp%2Fapp.component.ts,src%2Fmain.ts

**Comment by kapik** [comment]
Hey @NepipenkoIgor  ! 👋

I would like to reopen this issue.

Here is the example that does not work: https://stackblitz.com/edit/angular-ivy-jhgzz6

Attention, I use `Angular@13` and `NgxMask@13` and this example can't be loaded on Stackblitz but it is indeed this case that doesn't work: as soon as we add a comma, the result is `NaN`.
I know it's not the latest version but my current project is on `Angular@13` 😉
