### ISSUE TITLE
Console is flooded with tables

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#306]
When using the plugin, the console gets flooded with tables:

![image](https://user-images.githubusercontent.com/644550/52569297-274a1900-2e11-11e9-8ecb-bd8765809c95.png)

**Comment by Thegrep01** [comment]
@basvdijk Hello, sorry today will be updated

**Comment by colotiline** [comment]
7.3.6 (https://www.npmjs.com/package/ngx-mask) doesn't seemed to be fixed.
