### ISSUE TITLE
Non-decimal value isn't shown with decimals, when mask describes decimals

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#307]
When using for example the `dot_separator.2` mask, with a non-decimal value e.g. 12. It is displayed as 12 instead of 12.00 (with two zeroes, as defined by the mask)

**Comment by ValeriaKochegarova** [comment]
@basvdijk  we fixed this you can use it in the latest version

**Comment by Thegrep01** [comment]
#267

**Comment by ValeriaKochegarova** [comment]
@basvdijk we  fixed this you can try to use  it in the latest version

**Comment by basvdijk** [comment]
Currently not fixed in latest development branch. The model is set to `123.10` which makes no sense for `123.1`. The thing is that the textbox itself initially should show `123.10` when the model still is `123.1`

![image](https://user-images.githubusercontent.com/644550/55958393-cc923980-5c68-11e9-805c-ea3d8a44831a.png)

**Comment by Hoogieee** [comment]
Experiencing the same issue in version 8.1.7.
Model value: 10.10
Text input: 10.1

A *very ugly* workaround I found was to create a custom pipe and whichs adds the missing trailing zeros. So in the example above the model value would become 10.100 and the input text would display it as 10.10.

Would prefer a proper solution of course, so any more information is appreciated.
