### ISSUE TITLE
coma_separator with 4 decimals does not work

### ISSUE THREAD

**Issue by galan83** [JsDaddy/ngx-mask#309]
When I  comma_separator defining 2 decimals, everything works like a charm, but if I need 4 decimals, mask works ok, but the form returns the value without any decimal.

e.g.
 <input matInput placeholder="Price" mask="coma_separator.4" prefix="$" formControlName="price" />

If I write 1,000.2523, the form control will store 10002523 as its value.

**Comment by basvdijk** [comment]
Could this be related to #302 ?

**Comment by galan83** [comment]
I think so.

**Comment by basvdijk** [comment]
@galan83 you can grab the latest version of ngx-mask which solves this issue

**Comment by galan83** [comment]
Hi again, thank you for your answers. I'm using last version of the library: 7.4.2

**Comment by galan83** [comment]
I've seen this in mask.service.ts:

`if ((this.maskExpression === 'coma_separator.2' && this.dropSpecialCharacters === true)) {
      this.maskSpecialCharacters = this.maskSpecialCharacters.filter((item: string) => item !== '.');
  }`

I think that hardcoded 2 is the problem.

**Comment by basvdijk** [comment]
When I look at it, I think it should be `comma` instead of `coma` https://en.wikipedia.org/wiki/Comma

**Comment by malbarmawi** [comment]
When this gone to publich I still have this problem 🐞 , at 7.4.3
