### ISSUE TITLE
Masking Format starting with number 9 is not working properly with version 7.4.2

### ISSUE THREAD

**Issue by swathianupuram** [JsDaddy/ngx-mask#311]
we have been using ngx-mask for a while in our project. With version 6.3.8 all our mask patterns were worked fine but post upgrading to 7.4.2 version Masking is not working properly. Can you please have a look at this and let us know if we have any workaround for this.

Please validate the fields Telephone number 1, ISBN, Date and Format fields in the below links. we could see that the field telephone number 2 is working properly. Not sure what we have missed here. Please let us know.
version 6.3.8: **everything is working fine**
https://stackblitz.com/edit/ngx-mask-issue-mbqo5w?file=package.json

version 7.4.2: **Mask Pattern starts with 9 not working**
https://stackblitz.com/edit/ngx-mask-issue-jl2fnm?file=package.json

**Comment by brunnoDatum** [comment]
Same problem! If I change the '9' for '0' it works, but then when I have spaces after a special character, it doesn't work fine in firefox. Like if I try to backspace and has this space after a special character, it doesn't work.

**Comment by MarceloPetrucio** [comment]
Same problem! 

I want to use the mask "000.000.000-99", but it does not work because of the number 9.

I would also like to make a dynamic phone mascara, for this I imagine that I need the number 9 to do this test.
mask: "(000) 90000-0000"

I use the chrome, any suggestions?

**Comment by ValeriaKochegarova** [comment]
@swathianupuram in version  6.3.8  this case works wrong , because at least one number should not  be optional.

**Comment by cleomarbarrosjr** [comment]
is this solved? I'm still having this problem on version 8.0.1

when using 9 anywhere it breaks the mask.

Example
mask= '000.99.99.99'

value= 123...
