### ISSUE TITLE
Custom pattern optional character

### ISSUE THREAD

**Issue by ramzanh** [JsDaddy/ngx-mask#312]
I'm trying to create mask for optional negative decimal number.
This doesn't work: https://stackblitz.com/edit/angular-9mdtqs
Any symbol can be written to the first place. `optional` boolean option does nothing

**Comment by ValeriaKochegarova** [comment]
@Yokhtop  Hey, what do you mean with "optional negative decimal number"? Can you give actual and expected results

**Comment by Yokhtop** [comment]
@ValeriaKochegarova 
I'm trying to set signed number mask, it may be negative or positive.
```
<input mask="V0*.00" 
      [patterns]="customPatterns" 
      [dropSpecialCharacters]="false">
```
```
customPatterns = {
    'V': {pattern: new RegExp('-?')},
    '0': {pattern: new RegExp('[0-9]')}
  }
```
The solution is from here: [How to mask optionally negative number?](https://github.com/JsDaddy/ngx-mask/issues/175#issuecomment-426191403)

**Actual result:**
Any symbol can be written to the first place, not only '-'. 
When number is positive it doesn't accept the decimal separator after the first symbol, for example: 
`1.23` doesn't work.
`12.34` works fine.

**Expected result:**
First place accepts only number or `-`. Input accepts numbers like `1.23`

**Comment by ValeriaKochegarova** [comment]
@Yokhtop you should write  in component:
customPatterns = 'V': { pattern: new RegExp('-') };

**Comment by Yokhtop** [comment]
@ValeriaKochegarova Thanks, but anyway it doesn't work. See updated stackblitz example above.

**Comment by ValeriaKochegarova** [comment]
@Yokhtop  add in your component :" '0': { pattern: new RegExp('[0-9]')" and summary you will have smth like this:  
customPatterns = { 'V': { pattern: new RegExp('-') } ,
                                '0': { pattern: new RegExp('[0-9]')
                  }
 };

**Comment by Yokhtop** [comment]
@ValeriaKochegarova The pattern above is always negative number, but I'm trying to create a mask, that accepts negative numbers as well as positive numbers.

**Comment by ValeriaKochegarova** [comment]
@Yokhtop  please update new mask version and add in your component 
customPatterns = {
    V: { pattern: new RegExp("-?") },
    0: { pattern: new RegExp("[0-9]") }
  };

**Comment by Yokhtop** [comment]
@ValeriaKochegarova, see updated example. 
https://stackblitz.com/edit/angular-9mdtqs

**Comment by sollenne** [comment]
Why is this closed? I'm seeing the same issue... Check out his stackblitz link

**Comment by victorskg** [comment]
I'm having the same issue right now, the 'V': {pattern: new RegExp("-"), optional: true} doesn't work.

**Comment by victorskg** [comment]
@ramzanh Did u find any solution?

**Comment by mamontgo** [comment]
This seems to work as a workaround:
` customPatterns = {
   '0': { pattern: new RegExp('-|[0-9]') }, 
   '9': {
        pattern: new RegExp('[0-9]')
    }
  };`

`<input mask="09*.99" 
      [patterns]="customPatterns" 
      [dropSpecialCharacters]="false">`

**Comment by martamoshkin** [comment]
optional flag is not working. Problem is actual. Any solutions?

**Comment by andriikamaldinov1** [comment]
@martamoshkin @mamontgo @victorskg @sollenne @ramzanh @ValeriaKochegarova 
Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://jsdaddy.github.io/ngx-mask/#11
For this case you can use [allowNegativeNumbers]="true"
