### ISSUE TITLE
Mask with space do not backspace on Firefox

### ISSUE THREAD

**Issue by brunnoDatum** [JsDaddy/ngx-mask#313]
When I have spaces after a special character, it doesn't work fine in firefox. Like if I try to backspace and has this space after a special character, it doesn't work.

Mask: (000) 000-0000

In firefox if I backspace then it get stuck on the space after the ). You need to move the cursor to the ) and then works.

<input type="tel" class="form-control" id="billMobilePhoneNumber1" autocomplete="off" formControlName="mobilePhoneNumber1" mask="(000)000-0000">

**Comment by adamcoard-maximus** [comment]
The error occurs in IE (Edge) as well as FireFox. Chrome works fine and backspaces through the characters.  

These bugs occur on the demo in the phone number input: https://jsdaddy.github.io/ngx-mask/

**Comment by brunnoDatum** [comment]
I noticed safari works fine too. So it is firefox and Edge.

**Comment by NepipenkoIgor** [comment]
@brunnoDatum @adamcoard-maximus Thank you and you could try latest version of ngx-mask

**Comment by CoreyAdler** [comment]
Hey, I just updated to 7.9.6 and I'm seeing this issue in Edge. It's working perfectly in Chrome and Firefox.
