### ISSUE TITLE
feat: shall we add prettier as a code formatter?

### ISSUE THREAD

**Issue by sheikalthaf** [JsDaddy/ngx-mask#315]
Hi @NepipenkoIgor ,

Just gone through the source code and found that their is no code formatter in the source. This will be very hard to some to contribute in the repo. Please add any code formatter to the repo.

If you want i will add ***prettier*** as a code formatter and create a PR

Thanks for the awesome work

**Comment by NepipenkoIgor** [comment]
@sheikalthaf  we have just added prettier. Thank you for suggestion .

**Comment by sheikalthaf** [comment]
@NepipenkoIgor great work 👍
