### ISSUE TITLE
Unexpected value 'NgxMaskModule'

### ISSUE THREAD

**Issue by digitalmedia34** [JsDaddy/ngx-mask#32]
I am getting unexpected value 'NgxMaskModule; in my AppModule. This started to happen when I got the latest code. Did something changed? Any ideas?

I am using angular2

Thanks

![image](https://user-images.githubusercontent.com/5529666/29722499-062b5d38-898f-11e7-91c1-b11bd4572e54.png)

**Comment by digitalmedia34** [comment]
Update, removed the directive cleaned cache and now it doesn't throw error but the mask does not work. Any ideas on how to debug it?

**Comment by digitalmedia34** [comment]
It seems like it does not work with nested ngmodules. 
But now im getting some other weird error: More than one custom value accessor matches form control with unspecified name attribute

**Comment by LimarenkoDenis** [comment]
@digitalmedia34, I think it is not the problem of this library, just import module properly, or if you want to use the directive in different modules(nested modules or share) try to use this approach https://angular.io/guide/ngmodule#shared-modules.
Also, take a look at
 https://github.com/angular/angular/issues/15763

**Comment by NepipenkoIgor** [comment]
@LimarenkoDenis Thanks. @digitalmedia34 What env does you use ?

**Comment by dsouzas** [comment]
I've got the same issue adding the module NgxMaskModule without call forRoot().

After include NgxMaskModule.forRoot() into imports in app.module, the error changed to "Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.".

**Comment by NepipenkoIgor** [comment]
@dsouzas Could you show package.json ? Do you use angular-cli ???

**Comment by dsouzas** [comment]
Yes, I'm using angular-cli.

That's my package.json:

```
{
  "name": "testapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.4",
    "@auth0/angular-jwt": "^1.0.0-beta.9",
    "angular2-image-upload": "^0.6.6",
    "bootstrap": "^4.0.0-beta",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "ng2-ui-auth": "^7.0.2",
    "paypal-checkout": "^4.0.130",
    "resumablejs": "~1.0.2",
    "rxjs": "^5.1.0",
    "shufflejs": "^5.0.1",
    "smartcrop": "1.1.1",
    "swiper": "^4.0.0-beta.1",
    "turn-js": "file:libs/turn-js",
    "web-animations-js": "^2.3.1",
    "xcomponent": "^5.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.88",
    "codelyzer": "~3.0.1",
    "gulp": "^3.9.1",
    "gulp-debug": "^3.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.6.1",
    "gulp-run": "^1.7.1",
    "gulp-shell": "^0.6.3",
    "gulp-tsc": "^1.3.2",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "load-gulp-tasks": "^0.1.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

**Comment by NepipenkoIgor** [comment]
@dsouzas I tried  your config and no problem with latest build. Could you check and give feedback ?

**Comment by dsouzas** [comment]
Works like a charm!

Thank you!

**Comment by NepipenkoIgor** [comment]
@dsouzas and you )

**Comment by renandegrandi** [comment]
i have the same problem with version 2.4.4 and @angular/cli 1.6.5
