### ISSUE TITLE
Get raw value of field using number mask

### ISSUE THREAD

**Issue by luisaureliocasoni** [JsDaddy/ngx-mask#324]
Hello,

I have the following issue: I am using text fields with number mask, of following way: `mask='9'`. But I want to consider invalid the empty fields. But when the validator is accessing the masked empty field, the value attribute is 0. 

I do not want to consider empty values a zero. I want to consider empty values as invalid. I have tried to put the `Validators.required` validator before the custom validator, but the empty field pass. 

Any way to accessing the raw field value? I need this.

Regards,

Luis

**Comment by bryanmartinez01** [comment]
I am having the same problem, the value of the model is 0 instead of empty.

**Comment by marekozw** [comment]
Same thing here.

Consider the scenario:
1. fill the input with e.g. '111 111 111'
2. CTRL+A
3. Backspece/Dlete

No validation message is present. The form still thinks the value is '111 111 111'.

**Comment by marekozw** [comment]
It apears that the problem is no longer valid since version @7.6.0.

@luisaureliocasoni, @bryanmartinez01 could you check if upgrading to 7.6.0 helped you as well?

**Comment by luisaureliocasoni** [comment]
> 
> 
> It appears that the problem is no longer valid since version @7.6.0.
> 
> @luisaureliocasoni, @bryanmartinez01 could you check if upgrading to 7.6.0 helped you as well?

Nope. The issue persists in Firefox.

**Comment by bryanmartinez01** [comment]
> It appears that the problem is no longer valid since version @7.6.0.
> 
> @luisaureliocasoni, @bryanmartinez01 could you check if upgrading to 7.6.0 helped you as well?

The other problem (selecting all then pressing backspace) was gone, but still, after clearing the text input, the value of the model is 0 not empty.

**Comment by bryanmartinez01** [comment]
> It appears that the problem is no longer valid since version @7.6.0.
> 
> @luisaureliocasoni, @bryanmartinez01 could you check if upgrading to 7.6.0 helped you as well?

The other issue (selecting all then pressing backspace) was fixed, but still, after clearing the text input, the value of the model is 0 not empty.

**Comment by Thegrep01** [comment]
@bryanmartinez01 could you provide an example cause i did not find this problem

**Comment by bryanmartinez01** [comment]
> @bryanmartinez01 could you provide an example cause i did not find this problem

I put a change event listener in the text field where I used ngx-mask. I am logging the value of the field everytime the change event is triggered, I get 0 instead of empty.

`<input type="text" class="form-control form-control-sm col-sm-2" [(ngModel)]="sampleModel" (change)="checkSample($event)" mask="999">`

and in my checkSample(ev) 
`console.log(this.sampleModel);`

**Comment by bryanmartinez01** [comment]
@Thegrep01 I think I found the problem. The ngx-mask is working fine when the initial value is empty. But when the initial value of the model is a number, emptying the text input will set the value of the model to 0 not empty.

`sampleModel = null;`
the value of the `sampleModel` after emptying the text input will be empty

`sampleModel = 1; //or any number`
the value of the `sampleModel` after emptying the text input will be 0

**Comment by luisaureliocasoni** [comment]
> 
> 
> @Thegrep01 I think I found the problem. The ngx-mask is working fine when the initial value is empty. But when the initial value of the model is a number, emptying the text input will set the value of the model to 0 not empty.
> 
> `sampleModel = null;`
> the value of the `sampleModel` after emptying the text input will be empty
> 
> `sampleModel = 1; //or any number`
> the value of the `sampleModel` after emptying the text input will be 0

I think that it is the problem. In my system, the input always is filled by previous value.

**Comment by bryanmartinez01** [comment]
As @luisaureliocasoni said, we do not want to consider empty value as zero.

**Comment by kluevandrew** [comment]
The same problem still affects me, there is the only one way, change the library
