### ISSUE TITLE
Decimal character is removed from NgModel when using dot_separator

### ISSUE THREAD

**Issue by BasOnTech** [JsDaddy/ngx-mask#326]
When I checkout the repo and run the app with `ng serve`, there is a bug with the decimal in the `dot_separator` example

![image](https://user-images.githubusercontent.com/37171897/54087805-32805e00-4357-11e9-98b3-834ea4fae64e.png)

As you can see in the screenshot the textfield contains the value `1.239.348.534,3847` 
while the model contains `12393485343847` 
instead of `1239348534.3847`

It looks like the `.` decimal character is removed somewhere during the conversion steps.

**Comment by ValeriaKochegarova** [comment]
@BasOnTech we fixed  this you can use it in the latest version
