### ISSUE TITLE
Field is losing pristine property

### ISSUE THREAD

**Issue by lucianalml** [JsDaddy/ngx-mask#33]
Hi! First, thank you for your lib! It's being very useful...
I am only having a problem with obligatory fields validation because when I use a mask, the pristine property is set to false....

Thanks,

Luciana

**Comment by NepipenkoIgor** [comment]
@lucianalml thanks , i will try to solve this issue

**Comment by NepipenkoIgor** [comment]
@lucianalml Could you provide repo with for your issue ?

**Comment by lucianalml** [comment]
Hi!!
Of course! I just created that repo:
https://github.com/lucianalml/example-mask

At firts I was using 1.0.3 which was with the pristine problem...
I trie to update to 2.0.3 but I had problems importing in app.module:
NgxMaskModule.forRoot(options) 
NgxMaskModule.forRoot(),

Thanks,

Luciana

**Comment by NepipenkoIgor** [comment]
@lucianalml Please, try latest version

**Comment by gerardcm** [comment]
Hi @NepipenkoIgor,

Again, thanks for the lib indeed!

I'm getting the exact same issue while using version 2.2.2 was this solved? has this been reintroduced?

Rgds

**Comment by mtpultz** [comment]
Hi @NepipenkoIgor I'm using v7.8.9, and I'm still getting a validation error where I have to after patching the form set each masked field to be pristine.
