### ISSUE TITLE
NgModel value contains comma when dot_separator is used

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#330]
With the fix of #326 (Thanks for fixing so fast!) a new issue occurred. As shown in the screenshot below, when I enter `10.923,9093` the NgModel contains `10923,9093` instead of `10923.9093` which is not a valid `float`

![image](https://user-images.githubusercontent.com/644550/54131952-aa13c300-4413-11e9-9f0c-d8b1c43df3cc.png)

**Comment by Thegrep01** [comment]
@basvdijk okay we fix this soon

**Comment by basvdijk** [comment]
@Thegrep01 Great! 👍

**Comment by Serge0111** [comment]
@basvdijk Hey, try new version 7.6.3, it's been fixed.

**Comment by basvdijk** [comment]
Thanks, but gives still not working:
![image](https://user-images.githubusercontent.com/644550/54269991-b49e9b80-457e-11e9-9aaf-e46ff0a0596a.png)

The model should contain `0.83` and not `0,83`
