### ISSUE TITLE
Optional characters at the end not working

### ISSUE THREAD

**Issue by Gustav0ar** [JsDaddy/ngx-mask#333]
Hi,

I'm having trouble with optional characters with both custom pattern and optional number using "9" at the end of the string. The optional characters aren't optional, they stay mandatory and it is causing control validation error. You can look at the example I did here: 

https://stackblitz.com/edit/angular-cmmj4g

Any chance for a fix for this or a way to make it work?

**Comment by Thegrep01** [comment]
@Gustav0ar Hello we will fix it today

**Comment by Gustav0ar** [comment]
@Thegrep01 Hi, I just tested with version 7.6.4 and there are still scenarios that it isn't working properly.
It should not give validation error when non of the optional characters aren't entered, and it does at the moment in all cases. Other scenario that I tested that it isn't working is when I type just some optional characters but not all, and it still gives error...

Look at the updated examples: https://stackblitz.com/edit/angular-cmmj4g
