### ISSUE TITLE
IE11 typeerror object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by thibaut129** [JsDaddy/ngx-mask#337]
Hi,

Recently with 7.4.2 I have this error on IE : 
![image](https://user-images.githubusercontent.com/10886653/54213522-cdf30980-44e4-11e9-91e0-d42b518af373.png)

Do you change something in this version ? 

Thx

**Comment by AlexeyDolya** [comment]
@thibaut129 in which case it happens?

**Comment by thibaut129** [comment]
On loading component. I don't have the problem if I go back on 7.0.1 because you don't use includes in this version....

**Comment by AlexeyDolya** [comment]
@thibaut129 look #373, coming soon updated version

**Comment by AlexeyDolya** [comment]
Looks like the newest version uses Array.includes which is not supported in IE11,

Fixed the problem with this polyfill here : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill
