### ISSUE TITLE
Latest 7.6.3 version is broken

### ISSUE THREAD

**Issue by Gustav0ar** [JsDaddy/ngx-mask#340]
Hi,

I updated to latest version 7.6.3 and it is totally broken. All masks give validation error.
Look at the following example:

https://stackblitz.com/edit/angular-cmmj4g-ur9enw

**Comment by Thegrep01** [comment]
@Gustav0ar we fix this in 7.6.4

**Comment by danielephsa** [comment]
Hi @Thegrep01 ! When the 7.6.4 will be available? I just tried to update the 7.6.3 and it says that this version is not available. Thanks!

**Comment by NepipenkoIgor** [comment]
@danielephsa  I have just published

**Comment by danielephsa** [comment]
That's awesome! Thanks @NepipenkoIgor !!!
