### ISSUE TITLE
NgModel value contains dot when there is no decimal for dot_separator

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#341]
Related to #330 this still gives errors:
![image](https://user-images.githubusercontent.com/644550/54269833-62f61100-457e-11e9-86ca-2da31bfdd7e2.png)
When I enter `1239` in the textbox it is formatted as `1.239` this is correct.
However the model contains `1.239` as well which should be `1239`

**Comment by Thegrep01** [comment]
@basvdijk Hello, probably it is not a bug. the field has attribute `[dropSpecialCharacters]="false"`

**Comment by Thegrep01** [comment]
@basvdijk if you change it on true or even remove this attribute you will get this
<img width="670" alt="Снимок экрана 2019-03-13 в 12 01 52" src="https://user-images.githubusercontent.com/38587958/54270352-ecf6a780-4587-11e9-8c48-4020df84e83a.png">

**Comment by basvdijk** [comment]
It is the code from the repo, where `[dropSpecialCharacters]="true"` is defined
```html
              <div class="flex-row">
                <div class="flex-cell-padding">
                  <mat-form-field>
                    <input matInput placeholder="Separator" mask="dot_separator" [dropSpecialCharacters]="true"
                      [formControl]="dotSeparatorForm" [(ngModel)]="dotSeparatorFormModel">
                    <mat-hint><b>Mask: </b>dot_separator</mat-hint>
                  </mat-form-field>
                </div>
                <div class="flex-cell">
                  <p><b>FormControl:</b> {{ dotSeparatorForm.value ? dotSeparatorForm.value: 'Empty' }}</p>
                  <p><b>NgModel:</b> {{ dotSeparatorFormModel ? dotSeparatorFormModel: 'Empty' }}</p>
                </div>
              </div>
```

**Comment by Thegrep01** [comment]
@basvdijk Yes, i change it in the last commit and we update demo soon

**Comment by basvdijk** [comment]
Ok :) For all my bug reports, I checkout the current branch and run `ng serve`. I am not checking it on the website of the library.
