### ISSUE TITLE
NgModel value contains comma when dot_separator.2 is used

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#342]
![image](https://user-images.githubusercontent.com/644550/54269991-b49e9b80-457e-11e9-9aaf-e46ff0a0596a.png)

The model should contain `0.83` and not `0,83` when using `dot_separator.2`

Maybe useful for unit testing:
`dot_separator.2`:
12 -> 12
12,34 -> 12.34
12.345 -> 12345
12.345,67 -> 12345.67
0,12 -> 0.12

**Comment by Serge0111** [comment]
@basvdijk Hey, Did specify the option  [dropSpecialCharacters]="true", because without it it doesn't work.

**Comment by basvdijk** [comment]
@Serge0111 Looks fixed in latest version 👍
