### ISSUE TITLE
Leading zero number gives wrong formatting in textbox and NgModel

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#343]
![image](https://user-images.githubusercontent.com/644550/54270865-a6517f00-4580-11e9-9815-aa3675a4f88d.png)

Leading zero should be stripped off when next character isn't a comma. Currently `01.234.567` is possible as an entry. The textfield should show `1.234.567` and the NgModel `1234567`

**Comment by Thegrep01** [comment]
@basvdijk we fix this in 7.6.4

**Comment by basvdijk** [comment]
@Thegrep01 great :)
