### ISSUE TITLE
Cursor jumps around when adding numbers to the beginning of textbox

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#344]
Run the app and type `0,12` in the second field of thousand separator (yellow line)
![image](https://user-images.githubusercontent.com/644550/54272555-3b09ac00-4584-11e9-8109-4cda26d44fa5.png)

The result is:
![image](https://user-images.githubusercontent.com/644550/54272495-1c0b1a00-4584-11e9-9842-82adbe4e7c58.png)

Now move the cursor to the beginning of the textfield and try to add `345` in order to get `3450,12`.

You'll notice that because of cursor jumping the result will be `30,1245` instead of `3450,12`.

![image](https://user-images.githubusercontent.com/644550/54272738-8ae87300-4584-11e9-80ff-9e9dd39f7a81.png)

**Comment by ValeriaKochegarova** [comment]
@basvdijk  try to use in new version (v 7.8.10)
