### ISSUE TITLE
Initial cursor position with showMaskTyped enabled

### ISSUE THREAD

**Issue by joeystdio** [JsDaddy/ngx-mask#349]
When showMaskTyped is enabled I need to click at the beginning of an input field to set the cursor at this position. Wouldn't it be more intuitive to just set the cursor to the beginning of the input field of no value is already set? 
Now it gives the impression that you start typing after the mask if that's where you clicked.

**Comment by ValeriaKochegarova** [comment]
@joeystdio we fixed this you can use it in the latest version

**Comment by joeystdio** [comment]
Thank you for the attempt, I tried the latest version but it's not working. Attached you find a little screen recording about the behaviour. Also trying to clear the field is impossible with the keyboard. You really need to select all then press delete to be able to clear the field.

[weird-mask-behaviour.mov.zip](https://github.com/JsDaddy/ngx-mask/files/2974012/weird-mask-behaviour.mov.zip)

**Comment by ValeriaKochegarova** [comment]
@joeystdio  we  fixed this you can try to use  it in the latest version

**Comment by tonioros** [comment]
I'm using the latest version (8.0.1) and have same issue, when i click to specific character on input, it change cursor position to first character.

**Comment by silvl** [comment]
Is there any update on this issue?

**Comment by Scerbakova** [comment]
2024 the problem exists
