### ISSUE TITLE
Prefix not showing in model or form control

### ISSUE THREAD

**Issue by ljjolic** [JsDaddy/ngx-mask#352]
New to ngx-mask 
prefix is not showing in angular formcontrol for reactive forms

**Comment by Thegrep01** [comment]
@ljjolic yes it is only decorates your input

**Comment by ljjolic** [comment]
Is there a way to have it set in the formcontrol ?

**Comment by Thegrep01** [comment]
@ljjolic no

**Comment by ljjolic** [comment]
Would be nice to have a flag to propagate the prefix to formcontrol in futur

thx
