### ISSUE TITLE
Validation error when dropSpecialCharacters is "false"

### ISSUE THREAD

**Issue by robertons** [JsDaddy/ngx-mask#356]
I suggest change the part of the code to validate the field when dropSpecialCharacters is false:

[https://github.com/JsDaddy/ngx-mask/blob/develop/src/app/ngx-mask/mask.directive.ts](url)

`const length: number =
                    this._maskValue.length - this._maskService.checkSpecialCharAmount(this._maskValue) - counterOfOpt;` 

`const length: number =
                    this._maskService.dropSpecialCharacters ? 
                    this._maskValue.length - this._maskService.checkSpecialCharAmount(this._maskValue) - counterOfOpt : 
this._maskValue.length ;` 

In my project I changed ng-mask.js, line 907:

`var length_1 = this._maskValue.length - this._checkSpecialCharAmount(this._maskValue);`

for:

`var length_1 = this._maskService.dropSpecialCharacters ? this._maskValue.length - this._checkSpecialCharAmount(this._maskValue) : this._maskValue.length;`

**Comment by PauloPeres** [comment]
Same error here...
<input type="text" formControlName="dob" mask="00/00/0000" dropSpecialCharacters="false" />

**Comment by devsezer** [comment]
`<input class="form-control form-control-sm" type="text" formControlName="dob" [dropSpecialCharacters]="false" [mask]="'00.00.0000'" mdbValidate />`

Same error

**Comment by dalepo** [comment]
Thank you @Thegrep01
