### ISSUE TITLE
mask does not recognize decimals

### ISSUE THREAD

**Issue by maybe525** [JsDaddy/ngx-mask#357]
I want to use the following mask:

            <input  type="text"
                    class="form-control"
                    mask="dot_separator.2"
                    [formControlName]="valueControlName">

If I type values in the form everything is fine.
The typed value shows correctly as 1.234,50 and is stored as number 1234.50
When I now reload the form the value shows as 12.345
The value is shows as 1234.5 in the model.
It seems that the decimal dot is not interpreted by the mask.
Anybody knows what I'm doing wrong?

I importat the module right in the specific module where I want to use it (Not the AppModule):

import {NgModule, ModuleWithProviders} from '@angular/core';
import {CommonModule} from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { CurrencyListComponent } from '.';
import { CurrencyListService } from './currency-list.service';
import { NgxMaskModule } from 'ngx-mask';
import { CurrencyMaskModule } from 'ngx-currency-mask';
import { CurrencyMaskConfig, CURRENCY_MASK_CONFIG } from 'ngx-currency-mask/src/currency-mask.config';

export const CustomCurrencyMaskConfig: CurrencyMaskConfig = {
    align: 'left',
    allowNegative: true,
    allowZero: true,
    decimal: ',',
    precision: 2,
    prefix: '',
    suffix: '',
    thousands: ' '
};

@NgModule({
        exports: [
        ...
        ],
        declarations: [CurrencyListComponent],
        imports: [
            CommonModule,
            ReactiveFormsModule,
            FormsModule,
            NgxMaskModule.forRoot({}),
            CurrencyMaskModule
        ],
       providers: [CurrencyListService]
})
export class CurrencyListModule {
    static forRoot(): ModuleWithProviders {
        return <ModuleWithProviders> {
            ngModule: CurrencyListModule,
            providers: [
                CurrencyListService,
                CurrencyListComponent
            ],
        };
    }

The version in package.json is:

    "ngx-mask": "^7.6.4",

**Comment by Thegrep01** [comment]
@maybe525 check the next version
