### ISSUE TITLE
Using ngx-mask in custom form component gives error

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#358]
When I use `ngx-mask` in a custom form element it gives:
![image](https://user-images.githubusercontent.com/644550/54496555-f8800080-48f0-11e9-834c-26322f687ce4.png)

I've made a fork of the `ngx-mask` repo which reproduces the this error.
https://github.com/basvdijk/ngx-mask/

You can also have a look at my commit which added a custom form component:
https://github.com/basvdijk/ngx-mask/commit/9059d1b9579d85bfb3414de9ebe47df25b891e0a

If this is not a bug, could you provide a code example where the `ngx-mask` directive is used within a custom form component?

**Comment by basvdijk** [comment]
Any update on this one?

**Comment by basvdijk** [comment]
Is it possible to give an estimate on when this is solved? In order to use ngx-mask in our project we need to use in our custom components. If it will take weeks we kinda have to look into another solution. Thanks :)

**Comment by NepipenkoIgor** [comment]
@basvdijk Hi. Thanks for using ngx-mask. We will try to solve this in few days

**Comment by basvdijk** [comment]
@Serge0111 is possible that you provide an example of this interface and validate function?

**Comment by Serge0111** [comment]
<img width="847" alt="Screenshot at Apr 09 8-47-46 PM" src="https://user-images.githubusercontent.com/39799860/55822700-d56bf980-5b08-11e9-958e-b8d45f750f2a.png">

**Comment by Serge0111** [comment]
in your app-input component add Validator interface from @angular/forms and validate function and error will be fixed. For more detailed info about validate function look here:
https://angular.io/guide/form-validation

**Comment by basvdijk** [comment]
This seem to fix it, thanks!
