### ISSUE TITLE
Mask doesn't work on paste for separators 

### ISSUE THREAD

**Issue by RichMcL** [JsDaddy/ngx-mask#359]
You can see this on the demo page: https://jsdaddy.github.io/ngx-mask/

Named masks, like 'comma_separator', don't trigger on paste. Effectively, any mask that has a shortcut name (e.g. 'percent', 'comma_separator') has this issue.

**Comment by Thegrep01** [comment]
@RichMcL Hello,  i found this problem only with `percent` mask

**Comment by RichMcL** [comment]
Hey @Thegrep01, I included a screenshots of the behavior I'm seeing. It allows me to paste text that I can't explicitly type. Recreated in Chrome, Firefox, and Safari.
![image](https://user-images.githubusercontent.com/667290/54606074-282e2600-4a21-11e9-8303-8ccdf9b601df.png)

![image](https://user-images.githubusercontent.com/667290/54606235-9a066f80-4a21-11e9-9163-2b5daf7ec5d0.png)

**Comment by Thegrep01** [comment]
@RichMcL check new version

**Comment by RichMcL** [comment]
Looks good, thanks!
