### ISSUE TITLE
Dynamic form switch

### ISSUE THREAD

**Issue by kiteninja** [JsDaddy/ngx-mask#360]
Hi,

I am getting an error when dynamically assigning the form on the page where there is a mask assigned to an input element. I am currently using angular@7.2 with ngx-mask@7.6.5 but I have tried it briefly with the previous versions of ngx-mask and getting the same error.

Simplified form of the issue is at the link below.
https://codesandbox.io/s/9y4y0yrlzo

What I have there in the example are two contact forms in an array where I switch back and forth using a button. When the input contains a value switching to that form throws this error:

`Error: Uncaught (in promise): Error: There is no FormControl instance attached to form control element with name: 'ssn'`

The form is pretty simple:
`<form [formGroup]="activeForm">`
`  <div class="form-group"><input formControlName="name" type="text" /></div>`
`  <div class="form-group">`
`    <input formControlName="ssn" type="text" mask="000-00-0000" />`
`  </div>`
`</form>`
`<button (click)="switchClicked()">Switch contact form</button>`

And here is the code that switches the forms:
`  switchClicked() {`
`    this.activeFormIndex = (this.activeFormIndex + 1) % 2;`
`    this.activeForm = this.contactForms[this.activeFormIndex];`
`  }`

If no value is assigned to the control or if the mask is removed there is no error.
Let me know if more info is needed or if there is a better alternative to this method.

Kind regards.
AG.

**Comment by ValeriaKochegarova** [comment]
@kiteninja you should change formControlName="ssn" to  [formControl]="activeForm.controls['ssn']"

**Comment by kiteninja** [comment]
> @kiteninja you should change formControlName="ssn" to [formControl]="activeForm.controls['ssn']"

Hi Valeria,
Appreciate the response. This got rid of the error message but the problem is still there. Switching the form still does not switch the references to the different instances of the SSN. You can test it in the original example I had posted:
https://codesandbox.io/s/9y4y0yrlzo
