### ISSUE TITLE
Error on mask when within a matform

### ISSUE THREAD

**Issue by Sandstoneblade** [JsDaddy/ngx-mask#361]
When I have a mask on a matinput inside a form with optional fields (A?) as in #68, any input or predefined value results in a Mask Error.
This almost seems to be an inverse of issue #293.
[Sample snippet](https://stackblitz.com/edit/angular-kuyumg?file=src%2Fapp%2Fapp.component.ts)

**Comment by ValeriaKochegarova** [comment]
@Sandstoneblade we fixed this you can try to use it in the latest version
