### ISSUE TITLE
Formcontrol is invalid when editing form

### ISSUE THREAD

**Issue by jehanraj** [JsDaddy/ngx-mask#362]
When editing reactive form with value makes formcontrol invalid. Also makes input field as required for valid form, need options to set non required input.

**Comment by Thegrep01** [comment]
@jehanraj check new version

**Comment by jehanraj** [comment]
@Thegrep01  Thank you for the quick response. Still i am getting the error.
When validation is false, formcontrol value is null. When validation is true, formcontrol has value but it shows mask error which makes form invalid.

**Comment by mtpultz** [comment]
@Thegrep01 this is still an issue in the lastest release v7.8.9

**Comment by mtpultz** [comment]
@jehanraj step your version back to v6.5.18 and it should start working.  I moved backwards from the most recent release through v7.x until I found release that worked in this particular case.
