### ISSUE TITLE
Question [mask]

### ISSUE THREAD

**Issue by nico281** [JsDaddy/ngx-mask#364]
Hi, how are you? I'm working on a project with dynamic forms.
It's possible to set mask binding a variable [mask] = "formatMask"?  
I have a input type date and depends on different format types and it could be nice to me to handle it dynamically. 

Cheers!!

**Comment by nico281** [comment]
> Hi, how are you? I'm working on a project with dynamic forms.
> It's possible to set mask binding a variable [mask] = "formatMask"?
> I have a input type date and depends on different format types and it could be nice to me to handle it dynamically.
> 
> Cheers!!

the idea es to mask the date formats  "MMMM DDD YYYY" etc

**Comment by Thegrep01** [comment]
@nico281 could you provide an example

**Comment by nico281** [comment]
Basically, i'm working on a form designer and that handle an input type date. I can configure the format displayed on that input dynamically, so i can have **DD MMMM YYYY**  ej **"06 March 2019".** or
**DD MM YY** **"01 03 19"**. 
The problem that i'm having is that i need to have partial dates. Maybe i don't care the days so i want to enter month and year, having a format for example **"?? MMMM YYYY**" resulting "?? March 2019".
**(?? are the unknown days")**

This is a optional that i need to handle so my idea was to in those cases enter manually the date masking the input. I need to mask taking on account the original format, so for example if i want to add manually a date using a mask, at least i need to respect the format. the case of **"?? MMMM YYYY"** the first two characters need to be two question marks, the second four chars need to handle only letters and so on.

**Comment by Thegrep01** [comment]
@nico281 Thanks for your suggestion, we think about implementation this feature in future
