### ISSUE TITLE
Mask form validation always true

### ISSUE THREAD

**Issue by archigo** [JsDaddy/ngx-mask#367]
I just updated to 7.6.6 from 7.3.6.
I have a mask on an input:
  <input type="text" mask="0{7}" formControlName="xxx"/>
as soon as i edit this field, there will be a validation error {Mask error: true} no matter what.

This did not happen in 7.3.6.

**Comment by AlexeyDolya** [comment]
@archigo validation is enabled by default, you can disable it by setting the 'false' flag, for example:  <input type='text' mask="00 00" [validation]="false">

**Comment by archigo** [comment]
Yes, but the mask should not be throwing an error when the input has a 7 number value. It does.

Unless i misunderstand how the mask works? It is behaving as expected visually.

**Comment by AlexeyDolya** [comment]
@archigo could you provide the example?

**Comment by archigo** [comment]
[mask-test.zip](https://github.com/JsDaddy/ngx-mask/files/2996674/mask-test.zip)

**Comment by AlexeyDolya** [comment]
@archigo
