### ISSUE TITLE
Issue with mixed numeric required and non required mask

### ISSUE THREAD

**Issue by aobara** [JsDaddy/ngx-mask#372]
Hi, I'm trying to use ngx-mask for a credit-card form using the following mask "0000  9999"

For that mask the component doesnt let me input after the numeric required values. Works fine for "0000 0999" but seems that is not working properly with mixed numeric required and non required patterns

**Comment by AlexeyDolya** [comment]
@aobara try to add 'dropSpecialCharacters=[true]' option to your input field and everything will be correct
