### ISSUE TITLE
ngx-mask has stopped working in IE11.

### ISSUE THREAD

**Issue by amitger07** [JsDaddy/ngx-mask#373]
It worked earlier. Not sure what the issue is, would love to hear from you. Thanks

**Comment by keanan-meier** [comment]
Had same problem here,

Looks like the newest version uses Array.includes which is not supported in IE11,

Fixed the problem with this polyfill here : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill

**Comment by AlexeyDolya** [comment]
@amitger07 coming soon updated version

**Comment by sambernet** [comment]
Looks like this issue wasn't really solved or I am missing something here...

While investigating our issues with IE11 and `ngx-mask` I found:
- Current state is that `ngx-mask` is completely broken in IE11 (tested versions `7.9.2` and `7.9.9`)
- `Array.prototype.includes` is used in a few places throughout the code
- [this commit](https://github.com/JsDaddy/ngx-mask/commit/7a3aec4681d0c7121822d1a6baf51c6e53ab2875) (also linked above) added the missing polyfill required for IE11 to support `Array.prototype.includes`.
- But then [another commit by same author](https://github.com/JsDaddy/ngx-mask/commit/4b19eab1d2c2e64325065cf7769396783c8e2bcf) (on the very same day) that was intended to update dependencies ended up commenting out **all polyfills** (not only IE specific ones).

@AlexeyDolya @NepipenkoIgor: I'd suggest to reopen this issue - or should I create a new one??
