### ISSUE TITLE
Que: percent mask

### ISSUE THREAD

**Issue by techtic-harshad** [JsDaddy/ngx-mask#374]
Can you please suggest me how we can implement percent as "12.99%" mean fractional percentage, because currently i am able to implement percent mask as 99% and etc but not allow fractional percentage.
```
<input matInput placeholder="Percent valid mask" mask="percent" sufix="%" [formControl]="percent">
```
version use is 7.7.0.

thanks in advance for your support.

**Comment by AlexeyDolya** [comment]
@techtic-harshad 
try the updated version
