### ISSUE TITLE
Support for custom pattern of values that are not allowed for comma separator mask

### ISSUE THREAD

**Issue by cristianmaxim** [JsDaddy/ngx-mask#375]
The current implementation has a specific list of values that are filtered out from the value. ([Reference](https://github.com/JsDaddy/ngx-mask/blob/bf37b66a46731b075286b3d99a1ae5c9d5110bd4/src/app/ngx-mask/mask-applier.service.ts#L74))

Expected behavior:
Allow for a custom pattern to be supplied to the directive

**Comment by AlexeyDolya** [comment]
@cristianmaxim the separator was developed specifically for such cases, perhaps in the future we will add functionality with this feature
