### ISSUE TITLE
The input element's type ('number') does not support selection

### ISSUE THREAD

**Issue by NataD** [JsDaddy/ngx-mask#376]
there are issues regarding the problem I have, however, I have not managed to find a solution. I need input type to be "number" (due to the appearance of numeric keyboard on mobile), however, it seems impossible to use mask on input type="number". For now I am using input type="text" and adding a mask ="0*", however, this is only temporary solution, and I would want to use input type=number". How it can be achieved?

**Comment by Serge0111** [comment]
Hi @NataD, Do you want to prevent from typing dots with this  mask ="0*", or what are you trying to achieve??

**Comment by NataD** [comment]
Hi @Serge0111, I am trying to keep the features that input type="number" provides (like opening of numeric keyboards on mobiles). In the form, I already use masks on other inputs (such as phone or postcode), and it seems to give a problem with input type="number". 
As for a mask="0*", I have to use it to make input type="text" to behave as input type="number" (to prevent letters or other symbols from being typed in the input)

**Comment by AlexeyDolya** [comment]
@NataD unfortunately the mask cannot work with input type 'number' because input type 'number' can only contains numbers, not symbols and so musk will not work with it.

**Comment by JamboProduction** [comment]
Just make input as `type="tel"` and now you have number pad :)

**Comment by MNorgren** [comment]
This would be so nice. @AlexeyDolya , there is use cases. I need my form for numeric fields (i.e. - Prices) to be of numeric type, not of string type.

type="number" would make the form value `50.5` as opposed to `"50.5"`
