### ISSUE TITLE
Required validation Not working

### ISSUE THREAD

**Issue by jehanraj** [JsDaddy/ngx-mask#377]
When clearing input filed sets field value as 0 in the edit form. Hence required validation and mask validation are not working. Need Help.

**Comment by jehanraj** [comment]
@Thegrep01  @NepipenkoIgor  @ValeriaKochegarova  Please help... #377

**Comment by AlexeyDolya** [comment]
@jehanraj can you give an example?

**Comment by jehanraj** [comment]
Its same as #380

**Comment by AlexeyDolya** [comment]
@jehanraj Try to initialize ngModel with empty string, this will work.

**Comment by AlexeyDolya** [comment]
@jehanraj 
try the updated version

**Comment by ThicoMart** [comment]
I think this is still happening in last version (11.1.4).

Set my input with required property and the validation gets kind of crazy.

HTML:

```
<input matInput [(ngModel)]="user.dddphone" mask="(00)" #dddphone="ngModel" required>

               <div *ngIf="dddphone.errors.required">
                  {{ dddphoneRequired }}
                </div>
                <div *ngIf="dddphone.invalid">
                  {{ dddphoneMinLength }}
                </div>
```

Only the dddphone.invalid fires, and only when I delete just one charactere. When the input is empty it doen't mark as invalid.

Without the mask property in the input, everything works fine.
