### ISSUE TITLE
Optional parameters dont seem to be working

### ISSUE THREAD

**Issue by digitalmedia34** [JsDaddy/ngx-mask#379]
Maybe I am doing something wrong, but when I do a mask like 99.999 it doesnt let me enter values after 'comma'. See example:

https://stackblitz.com/edit/angular-cmmj4g-m9slvu
https://angular-cmmj4g-m9slvu.stackblitz.io

Do I need to add something special?

Thanks

**Comment by Serge0111** [comment]
Hi @digitalmedia34, this mask '99.999' means  that you can enter nothing except '.' , which is wrong. You can do mask like '09.099', which means at least 1 symbol before and after dot should be entered, but others are optional. Does that make sense?

**Comment by digitalmedia34** [comment]
Hi @Serge0111 thank you for your reply. It makes sense what you are saying but according to documentation 9s are optional so I could enter just '.' or #.## 8.55. The latter is not letting me enter it.
