### ISSUE TITLE
Negative numbers on thousand separator is not worrkring

### ISSUE THREAD

**Issue by cnthiesen** [JsDaddy/ngx-mask#381]
Hi, I have an issue with the thousand separator mask and negative numbers. 

Have this function in my component
```
getIncome() {
  const testValue = 5 - 1000;
  return testValue; 
  // testValue output is -995
}

```
Have this expression in my template 
```
<div>
{{ getIncome() | mask: 'dot_separator' }} 
   // expression outputs -99
   // should output  -995
</div>
```

The output is cutting off the last number from a negative number. I looked through the documentation and issues and I can't find any issues or fixes related to this.
H

**Comment by ValeriaKochegarova** [comment]
@cnthiesen you should write like this <div mask="dot_separator">{{ getIncome()}}</div>

**Comment by sollenne** [comment]
Again they close this issue without a resolution. good job.

**Comment by ftuyama** [comment]
I still can't use negative numbers on version 8.0.5

**Comment by chimung** [comment]
#677 I think it is not working after try new input [allowNegativeNumbers]
stackblitz: https://stackblitz.com/edit/chimung-angular-8-ngx-mask

**Comment by ColinMorris83** [comment]
Change the ngx-mask version to 9.0.0 in the stackblitz and try again. It's fixed, the only thing broke is the pipe as that doesn't cater for negative numbers currently.

**Comment by chimung** [comment]
Hi @ColinMorris83 , but it seem has peer deps on angular 9. Does it working correctly in angular 8 ? Thanks for quick response.

**Comment by ColinMorris83** [comment]
I think most likely it needs to be angular 9 as that will use typescript 3.8, same version used to build the library. You can try with 8 though
