### ISSUE TITLE
Related to issues 379

### ISSUE THREAD

**Issue by digitalmedia34** [JsDaddy/ngx-mask#382]
According to documentation 9s are optional so I could enter just '.' or #.## 8.55. The latter is not letting me enter it.

Also with this pattern 09.099 the mask works but the values do not. For example, it allows to enter 5.90 but the value becomes 59.0

https://stackblitz.com/edit/angular-cmmj4g-m9slvu

**Comment by ValeriaKochegarova** [comment]
@digitalmedia34 if i right understand you , you should change your mask like : mask="9.0999"

**Comment by digitalmedia34** [comment]
No because I want the option of having 4.50 or 43.50. If it's two digits before decimal its k to enter period but then the model gets it incorrectly. Please see my examples

**Comment by ValeriaKochegarova** [comment]
@digitalmedia34 you can do  the second symbol - optional

**Comment by digitalmedia34** [comment]
Right but the model doesn't reflect it

**Comment by ValeriaKochegarova** [comment]
@digitalmedia34 you have a mistake in regular expression , please  follow documentation  'default patterns'
