### ISSUE TITLE
Caret / text cursor moves erratically with seperator masks

### ISSUE THREAD

**Issue by archigo** [JsDaddy/ngx-mask#386]
`<input  type="text"  mask="comma_separator.2" />`

![image](https://user-images.githubusercontent.com/6784093/55216365-d6de1d80-51fc-11e9-835e-9dc764fcee61.png)

If i repeatedly press "9", without doing anything else, i get this:

![image](https://user-images.githubusercontent.com/6784093/55216388-e8272a00-51fc-11e9-9144-ec1f6525380e.png)

I would expect all my keypresses to come after each other, with no "5" in between the "9"'s.

**Comment by ValeriaKochegarova** [comment]
@archigo try to use in new version (v 7.8.10)

**Comment by archigo** [comment]
Is this version available? npm upgrade ngx-mask gives me 7.8.9.
