### ISSUE TITLE
Dynamic prefix is not working properly

### ISSUE THREAD

**Issue by akvaliya** [JsDaddy/ngx-mask#389]
I have a tel input in which i want to change masking on country change.

Dynamic mask working fine with latest version. 

But dynamic prefix is not working properly. It applies after change in input. Like you clear input or change country then prefix of last selected country will be applies

Please reefer produced this issue in stackblitz. [https://stackblitz.com/edit/angular-vjftzv](https://stackblitz.com/edit/angular-vjftzv) .

Let me know how can i resolve this issue.

**Comment by ValeriaKochegarova** [comment]
@akvaliya you should add in input  onfocus="this.value=''" and also change the mask: "999-999-9999" to the mask: "099-099-0999" because first symbol could not be optional and the same situation in the mask: "9999 999999" and the mask: "99-9999-9999"

**Comment by akvaliya** [comment]
How does this resolve issue of dynamic prefix? Have you read my issue clearly.  Please check stackblitz that i have provided. I want to change prefix on dropdown change by using property binding. onfocus will call only after i focus on input.

This does not resolve my issue at all. It's clearly a bug as shown in stackblitz  that i provided.

**Comment by akvaliya** [comment]
Please reopen this issue as this is not a solution

**Comment by ValeriaKochegarova** [comment]
@akvaliya  please check new version
