### ISSUE TITLE
compile AOT

### ISSUE THREAD

**Issue by jadir-junior** [JsDaddy/ngx-mask#39]
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function,
            resolving symbol Injectable in
*****/node_modules/ngx-mask/node_modules/@angular/core/core.d.ts,
            resolving symbol ɵe in

**Comment by NepipenkoIgor** [comment]
@jadir-junior Could you show package.json ? Do you use angular-cli ???

**Comment by NepipenkoIgor** [comment]
@jadir-junior Could you try latest version ?
