### ISSUE TITLE
NPM package is broken: Could not resolve ngx-mask relative to [object Object]..

### ISSUE THREAD

**Issue by michellecolin** [JsDaddy/ngx-mask#392]
Hey, i've just downloaded the ngx-mask module. Followed the instructions and i was getting this error:
Could not resolve ngx-mask relative to [object Object]..
src/app/shared/shared.module.ts(13,31): error TS2307: Cannot find module 'ngx-mask'.

After investigating i realised that the module installed by npm is not downloading the module code.

This is the ngx-mask folder's content:

![Screen Shot 2019-04-01 at 15 25 22](https://user-images.githubusercontent.com/3909469/55350399-66502e80-5492-11e9-8866-d5d30f64a813.png)

I was using this for a while, today we've downloaded our packages from scratch and then we caught this error.

Can anyone shed a light? 
Thanks

**Comment by Gustav0ar** [comment]
I have the same issue, looks like the package is missing all the library code, in other words, it is broken

**Comment by shobhit-github** [comment]
I am also getting that same issue

**Comment by jvmguerra** [comment]
We locked the version to 7.3.1 and it worked fine

**Comment by Gustav0ar** [comment]
> We locked the version to 7.3.1 and it worked fine

Problem only exists with version 7.8.7

**Comment by michellecolin** [comment]
Yes, i locked my project to ngx-mask 7.8.6 version. And it's working fine.
But this is a temporary fix, since the new package is still broken and the ngx-mask team should be aware of the problem ;)

**Comment by NepipenkoIgor** [comment]
@michellecolin @Gustav0ar @shobhit-github @jvmguerra  @rafaelcneves You could try latest version . v7.8.8
