### ISSUE TITLE
Help: How to use [validation]=false ?

### ISSUE THREAD

**Issue by Gururaj26** [JsDaddy/ngx-mask#394]
My input looks like 
`<input type="text" class="Enter Zipcode" placeholder="Enter Zipcode" mask="00000-0000" formControlName="zipcode" [validation]="false">`

I just wanted to use mask as a input mask but seems like mask pattern throws formValidation error `mask error` if input doesn't satisfy the value entered. This happens only in the production build.

Additional: when i use `validation=false` angular throws template parse error.

> Can't bind to 'validation' since it isn't a known property of 'input'. ("text" class="Enter Zipcode" placeholder="Enter Zipcode" mask="00000-0000" formControlName="zipcode" [ERROR ->][validation]="false">

Any Help Would be appreciated.

**Comment by ValeriaKochegarova** [comment]
@Gururaj26 what mask version do you use ?

**Comment by Gururaj26** [comment]
@ValeriaKochegarova I am using 7.3.6, I tried installing 7.8.7 but it is showing error `error TS2307: Cannot find module 'ngx-mask'`. Thank you for your fast reply

**Comment by Gururaj26** [comment]
@ValeriaKochegarova Issue seems to be solved for me, but I had to downgrade it to `7.8.6` to make [validations]="false" to work.

Probable Bug: ` Current version in npm ngx-mask@7.8.7 doesn't seem to be installing properly ( missing src files on npm install`

Thanks.

**Comment by ValeriaKochegarova** [comment]
@Gururaj26 yes , thanks, here is this bug  #392
