### ISSUE TITLE
Cannot find module 'ngx-mask'.

### ISSUE THREAD

**Issue by haiderali-456** [JsDaddy/ngx-mask#395]
After importing the ngx-mask in my App.module.ts it throws Cannot find module 'ngx-mask'. pls help me regarding this, i installed ngx-mask version is 7.8.5

**Comment by aaa123eee** [comment]
same error after trying to update to v.7.8.7

**Comment by haiderali-456** [comment]
@aaa123eee Thanks, after install 7.0 working fine
