### ISSUE TITLE
Error in Angular Universal with ngx-mask

### ISSUE THREAD

**Issue by izmaylovdev** [JsDaddy/ngx-mask#399]
SSR broke after adding ngx-mask, error:
```
ReferenceError: KeyboardEvent is not defined
    at eval (webpack:///./node_modules/ngx-mask/fesm5/ngx-mask.js?:1027:88)
    at eval (webpack:///./node_modules/ngx-mask/fesm5/ngx-mask.js?:1075:2)
    at Object../node_modules/ngx-mask/fesm5/ngx-mask.js 
```
Version 7.8.9

**Comment by DBaker85** [comment]
I also have this problem. Adding NGX-mask breaks our whole solution

```
Description: An unhandled exception occurred. 

Exception Details: 
KeyboardEvent is not defined
ReferenceError: KeyboardEvent is not defined
   at ***\server.bundle.js:199960:88
   at Module.extendStatics (***\server.bundle.js:200008:2)
   at __webpack_require__ (***\server.bundle.js:20:30)
   at Object.ngx-mask (***\server.bundle.js:126715:18)
...
```

**Comment by bpop-bc** [comment]
The problem comes from the fact that there is no implementation of the `KeyboardEvent` on the server. There is [issue](https://github.com/valor-software/ngx-bootstrap/issues/61) about the same problem regarding `ngx-bootstrap`.  Assigning the event to `any` does the job but I'm not sure that this is the right solution.

**Comment by rms-bc** [comment]
Hi, I am also facing this issue, and it will prevent me from using this lib, unfortunately :/
Do you have an ETA on this fix?

Thanks for the great work!

**Comment by TimHarker** [comment]
I got this working by Exporting out of my main app.module and importing into the modules that used it.

Subset of main app.module...
`import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { NgxMaskModule } from 'ngx-mask'

@NgModule({
  imports: [
    NgxMaskModule.forRoot()
  ],
  exports: [NgxMaskModule],
  bootstrap: [AppComponent]
})
export class AppModuleShared {
}`

Subset of module that uses it...
`import { NgModule } from '@angular/core';
import { NgxMaskModule } from "ngx-mask";

@NgModule({
  imports: [
    NgxMaskModule
  ]
})

export class HomeModule { }
`

Notice no .forRoot() on import.

**Comment by bpopnikolov** [comment]
Hello are there any plans to merge #424? Seems like there  are people who already tried this in prod and it works for them as well. This is the only solution I could come up with other than replacing the type of the event with `any` or messing up with the webpack's config.

**Comment by NepipenkoIgor** [comment]
@bpopnikolov Hi. I will check . I will able to do this today or tomorrow

**Comment by NepipenkoIgor** [comment]
@izmaylovdev @DBaker85 @bpop-bc @rms-bc @bpopnikolov Pleas try latest version
