### ISSUE TITLE
Mask error after input value has been patched and not entered manually

### ISSUE THREAD

**Issue by mtpultz** [JsDaddy/ngx-mask#400]
I'm using Angular v6.1.10 with ngx-mask v7.8.9 where the mask is for a phone number on an input.  The input when patched using HTTP response data sets the field to be invalid with a mask validation error of `{ 'Mask error': true }`, and the form control is not required.

```html
<input type="text" mask="(000) 000-0000" formControlName="phone">
```

```js
this.form = this.fb.group({
  phone: [
    this.phone, [FormControlValidators.phone]
  ],
  fax: [
   this.fax, [FormControlValidators.phone]
  ]
});
```

I tracked this into the `MaskDirective` where it checks for [special characters](https://github.com/JsDaddy/ngx-mask/blob/develop/src/app/ngx-mask/mask.directive.ts#L176), which if not found will do a [comparison on the value length](https://github.com/JsDaddy/ngx-mask/blob/develop/src/app/ngx-mask/mask.directive.ts#L180).  

The `value` in the comparison viewed in console is the masked value and not the raw number that you get when you manually type the phone into the input.  

**When Value Patched**
1. The response data that is patched is 2509876543
1. The `value` for comparison contains mask (250) 987-6543 on L180 which causes the error, and
1. Validity of the model fails with `{ 'Mask error': true }` on L181

**When Value Manually Entered**
1. The entered data is 2509876543
1. The `value` for comparison doesn't contain mask 2509876543 on L180, and
1. Validity of the model passes

It doesn't seem to matter if the form controls are disabled or enabled, whether I `patchValue` or set the form group directly during initialization, or invoke `markAsPristine` or `updateValueAndValidity` afterwards.  It only works if I manually enter the value provided from the response into the input, or when the user enables the form for editing I invoke this to get it to reset when it thinks is the model: 

```
this.form.setValue(this.form.getRawValue());
this.form.get('phone').markAsPristine();
this.form.get('fax').markAsPristine();
```

**Comment by mtpultz** [comment]
Appears to work in v6.5.18, but once I move into v7.x it stops.  I'd compare the code of the different versions and submit a PR, but the repository isn't tagged with releases.

**Comment by Thegrep01** [comment]
@mtpultz if you need to disable mask validation use `[validation]="false"`

**Comment by mtpultz** [comment]
Hi @Thegrep01, it doesn't seem to be directly related to validation, but the lack of using my own validations on the form simply emphasizes the issue.  

It feels like the `ngx-mask` validation should still apply since the patched value will be masked as a phone number for a 10-digit number, and stepping back the version of `ngx-mask` does resolve the issue without using the validation input binding.

When the input is optional and the form control is patched the check tries to compare the length of the patched value but it contains the masked characters `(250) 848-1234` to the length of `2508481234`, which will always fail since the value for comparison should be `2508481234` with no mask, but if you delete the last digit and add it back the check corrects itself by comparing the lengths of `2508481234` to `2508481234`, which is expected.

**Comment by Thegrep01** [comment]
@mtpultz try v7.91+

**Comment by jeffnwarner** [comment]
I seem to be having this issue as well. When I create a form with a patched in value I can't save until I manually edit the field.
