### ISSUE TITLE
'showMaskTyped', full selection, 'DEL' button does not work

### ISSUE THREAD

**Issue by vaclav-antosik** [JsDaddy/ngx-mask#401]
Using version "ngx-mask": "^7.7.2".

![image](https://user-images.githubusercontent.com/8505433/55534048-8874c700-56b3-11e9-9c99-1368538024b8.png)

1. Write date into "input". (You can observe value changes in console.)
2. Select whole date. Selection must be from beginning into end.
3. Press "delete" button.
4. Model is not updated. (You can observe no log in console about value changes.)

This is happening only if showMaskTyped = true.
Demo app: [ngMaskBug.zip](https://github.com/JsDaddy/ngx-mask/files/3042021/ngMaskBug.zip)

**Comment by Serge0111** [comment]
hi @vaclav-antosik, try new version, 7.9.0.
