### ISSUE TITLE
When mask is "comma_separator.2", Input with numeric mask won't bind back correct value to model when value of field is blank

### ISSUE THREAD

**Issue by Rodigee** [JsDaddy/ngx-mask#402]
Releated to Issue #380, when the user enters a numeric value matching the mask the component model is updated with that value, however when the user empties the input so that the value should be "" it is instead 0.00.

This bug was fixed in #380 but is still a problem when the mask is "comma_separator.2"

`<input formControlName="TransportDollarsPerMile" 
class="form-control" 
id="transportDollarsPerMileId"
 type="text" placeholder="$" prefix="$" mask="comma_separator.2" />`

When I clear out the input box, group.get('TransportDollarsPerMile') is 0.00. It should be null or "" so my angular required field validator can work.

I'm on 7.8.9

I looked at the changeset for the fix for #380, 54d88bfb6e66f1bc254be0d2b52c8dacf281b30c,  and I saw we wouldn't hit the newly changed code if the mask was comma_separator.2. The problem is we're calling Number(''), which returns 0.

I tried changing the mask to comma_separator.3 but still got this issue.

**Comment by bryanmartinez01** [comment]
I also encountered this problem when using the separators.

**Comment by NepipenkoIgor** [comment]
@bryanmartinez01 @Rodigee  Thank you. We will check this

**Comment by Thegrep01** [comment]
@Rodigee check this fix in 7.8.11 version

**Comment by ashley-austincoder** [comment]
@Thegrep01 thank you for fixing this issue! When will version 7.8.11 be in production? I'm working with @Rodigee trying to test this fix but there is no matching version found for 7.8.11 yet.

**Comment by Rodigee** [comment]
d9812c8 and 7e4dad didn't fix the bug I was having. I created a pull request for a possible fix: https://github.com/JsDaddy/ngx-mask/pull/428 I wasn't able to deploy the dev environment for ngx-mask so the change should be tested before being merged.

**Comment by hhnaing** [comment]
still having this issue, anyone managed to solve this?
