### ISSUE TITLE
Clearing mask does not work

### ISSUE THREAD

**Issue by larini** [JsDaddy/ngx-mask#403]
My component needs to clear the mask in some situation, but when bind the mask to a variable and clearing this variable, the mask remains unchangeable.

code:

      <input
        [mask]="mask"

in .ts:

      this.mask = '';

**Comment by Thegrep01** [comment]
@larini Hello, what version of ngx-mask do you use ? i did not find this problem, could you provide more complex example

**Comment by larini** [comment]
@Thegrep01 Hello, It´s the 7.8.6 version. The code is nothing more than that. Just bind the mask to a variable.
This seams to be the returns at "public set maskExpression", "public set patterns" and "public set shownMaskExpression".
And I put a
        if (!maskExpression) {
          return inputValue;
        }
at public applyMask
