### ISSUE TITLE
IP Address Mask of 099.099.099.099 with showMaskTyped=true not working as expected

### ISSUE THREAD

**Issue by woolyninja** [JsDaddy/ngx-mask#408]
If I have the following input the mask isn't working as it does when showMaskTyped=false.

<input type="text" mask="099.099.099.099" [showMaskTyped]="true">

Once I hit the first . it then stops working as it should.

**Comment by ValeriaKochegarova** [comment]
@woolyninja we fixed this, you can try to use it in the latest version (7.9.6)

**Comment by ValeriaKochegarova** [comment]
For this issue we created  new mask its called IP , in our doc you can see how to use it

**Comment by woolyninja** [comment]
I'll check it out, thank you
