### ISSUE TITLE
Sufix directive not working on Safari

### ISSUE THREAD

**Issue by bpop-bc** [JsDaddy/ngx-mask#410]
When applying the `sufix` directive on a `<input />` you are not able to change the value of the input or delete the current value. The issue is present only on the Safari browser.

**Safari version**:  _11.1.1_
**Angular version**: _7.1.4_
**ngx-mask version**: _7.8.9_

_my-component.html_
```
<input type="text" inputmode="numeric" [(ngModel)]="inputValue" (ngModelChange)="change($event)" [disabled]="disabled" required [mask]="customMask" [sufix]="customSufix" />
```
_my-component.ts_
```
  ...

  @Input() public customMask: string;
  @Input() public customSufix: string;

  ...
```

**Comment by ValeriaKochegarova** [comment]
@bpop-bc it will be available in 7.8.12 version
