### ISSUE TITLE
Delete is not working on Dot, Comma and Separator Mask's 

### ISSUE THREAD

**Issue by Cous21** [JsDaddy/ngx-mask#411]
When i tried to delete the values on the field with Dot,Comma or Separator mask's, just delete only the first value and going back to the last again.

Examples:
![image](https://user-images.githubusercontent.com/17300131/55826122-a9874e80-5add-11e9-8ff5-37a5080e9881.png)

After use Delete:
![image](https://user-images.githubusercontent.com/17300131/55826152-befc7880-5add-11e9-94ea-4a9860923ca9.png)

Version: ngx-mask: "^7.8.6".

**Comment by Thegrep01** [comment]
@Cous21 could you provide more complex example

**Comment by Thegrep01** [comment]
@Thegrep01 please try new version 7.8.11
