### ISSUE TITLE
IP Address mask not displaying error in FormControl

### ISSUE THREAD

**Issue by raichshlv** [JsDaddy/ngx-mask#412]
```
            <input
              type="text"
              [formControl]="subnetControl"
              mask="099.099.099"
              [validation]="true">
```
Whenever I type a single number, the Form Control displays as valid. Only happens when there are 9's in the mask. I need this feature so that a user can enter a subnet address (which could be 0.0.0 or 127.0.0 or 192.168.0 etc.).

**Comment by Thegrep01** [comment]
@raichshlv  Hello, try new `mask="IP"` in 7.9.0v. But you have a mistake, if i am right ip addres looks like thi 0.0.0.0 not like 0.0.0

**Comment by raichshlv** [comment]
> @raichshlv Hello, try new `mask="IP"` in 7.9.0v. But you have a mistake, if i am right ip addres looks like thi 0.0.0.0 not like 0.0.0

You are correct - it's not an IP, it's a subnet, the endpoint is set in a different place, together forming an IP. 
Seeing that you have now added an  "IP" mask, and my issue is quite specific, I guess that I am going to use `mask="099.099.099" [validation]="false"` to mask the input and a RegExp inside Validators.pattern() to validate that it is valid.
