### ISSUE TITLE
Mask shows undefined when using dot_separator.2 and empty textbox after erasing

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#414]
When I use the `dot_separator.2` and the model is contains 123456.789 it will show up fine. However when I erase the field with backspace, the mask shows `undefined` when the field is empty:

![image](https://user-images.githubusercontent.com/644550/55884902-33e8b480-5ba9-11e9-8e9f-497dda943e3e.png)

The happens when I define the model as a string which is empty e.g.

```
TS
public testData: string = ''

HTML
  <input
    type="text"
    [(ngModel)]="testData"
    [required]="isRequired"
    mask="dot_separator.2"
    [dropSpecialCharacters]="true"
  />
```

**Comment by Serge0111** [comment]
hi @basvdijk, try new version 7.9.0 and let us know if the bug still appears.

**Comment by basvdijk** [comment]
@Serge0111 it looks like this is still a bug is still there. This issue could be that the model is set to '' (empty string) while the masking is for numbers
