### ISSUE TITLE
When entering just a comma it results in NaN

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#415]
When I check out the repo and run it, you'll get `NaN` when you enter just a comma in the text field instead of `null` could be related to #415 was well

![image](https://user-images.githubusercontent.com/644550/55888507-c429f800-5baf-11e9-90df-488885849e23.png)

**Comment by ValeriaKochegarova** [comment]
@basvdijk we fixed this, you can try to use in the latest version
