### ISSUE TITLE
Backspace is not working in IE

### ISSUE THREAD

**Issue by rakeshnayak360** [JsDaddy/ngx-mask#417]
I have used mask="(999-9999-999)". When i type 123-4567-897 and try to remove 3, it is removing 4567897 also. 

 And when i type 123-4 and try to remove 4 by pressing backspace, it is not removing 4 .

**Comment by rakeshnayak360** [comment]
> I have used mask="(999-9999-999)". When i type 123-4567-897 and try to remove 3, it is removing 4567897 also.
> 
> And when i type 123-4 and try to remove 4 by pressing backspace, it is not removing 4 .

**Comment by Serge0111** [comment]
Hi @rakeshnayak360 , this mask means that you can have inputvalue like this '---' which is wrong of course, try the following mask '(099-0999-099)' and it should work well).

**Comment by rakeshnayak360** [comment]
hi @Serge0111 thanks for the reply. I followed the same method you mentioned in above comment.  But I am facing same issue only when i add [showMaskTyped] = "true". Curosor will not move after i press backspace. Can you share the sample code which runs in all browser especially IE 11. Here is the screenshot of cursor not going back on press of backspace.
![image](https://user-images.githubusercontent.com/19386889/56197874-62f2a080-6057-11e9-9b70-323c89eb8b73.png)

**Comment by MaximoB** [comment]
I am using Chrome and showMaskTyped is not working properly if you change the cursor to be anywhere that is not the end of the text.

**Comment by Serge0111** [comment]
hi @rakeshnayak360, backspace works in new version for IE, but be sure you add polyfills core-js to your angular project.

**Comment by rakeshnayak360** [comment]
Newer version 7.9.8 doesnt work in IE 11. 
[polyfills core-js  is already added to my project]

**Comment by Serge0111** [comment]
hi@rakeshnayak360, could you provide please screenshot with console?

**Comment by rakeshnayak360** [comment]
https://user-images.githubusercontent.com/19386889/57368350-992fc580-71a8-11e9-9596-2246a050773d.png

**Comment by tacobarry** [comment]
I have the same problem like @rakeshnayak360 on ie10 and ie11
