### ISSUE TITLE
Race condition when entering numbers with comma quickly

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#418]
When quickly entering numbers with a comma e.g. `1,23` or `0,12` a race condition kicks in. The result is that the first number is missing as shown in this screenshot.

![image](https://user-images.githubusercontent.com/644550/55935646-655a9200-5c34-11e9-86ed-1d514586882f.png)

It might take a few tries to trigger this bug, but it is reproducible. I noticed this bug since

**Comment by ValeriaKochegarova** [comment]
@basvdijk if i got you right , i tried to reproduced everything is working

**Comment by basvdijk** [comment]
@ValeriaKochegarova This is still an issue, when typing 0,23 very fast you end up with 2,3 for example

**Comment by ValeriaKochegarova** [comment]
@basvdijk sorry, but i still cannot reproduce this bug.

**Comment by basvdijk** [comment]
@ValeriaKochegarova 
- Checkout - checkout https://github.com/basvdijk/ngx-mask if you checkout this repo
- Type quickly in the textbox at the top to reproduce this error
