### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol config in /ngx-mask/build/config.d.ts, resolving symbol NgxMaskModule.forRoot

### ISSUE THREAD

**Issue by 2n2n** [JsDaddy/ngx-mask#42]
I tried to run ng serve from the repository but it's not working.
Versions.

```
@angular/cli: 1.4.8
node: 8.7.0
os: darwin x64
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.8
@angular/compiler-cli: 4.4.6
typescript: 2.5.3
```

`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol config in ../app/node_modules/ngx-mask/build/config.d.ts, resolving symbol NgxMaskModule.forRoot in ../app/node_modules/ngx-mask/build/ngx-mask.module.d.ts, resolving symbol HrModule in ../app/src/app/hr/hr.module.ts, resolving symbol HrModule in ../app/src/app/hr/hr.module.ts`

**Comment by rafaelcneves** [comment]
The same error here.. Any progress?

**Comment by rafaelcneves** [comment]
I solved using angular 4.4.4

**Comment by JuliaRakitina** [comment]
no does not work with angular 4.4.4

  "dependencies": {
    "@agm/core": "1.0.0-beta.1",
    "@angular/animations": "4.4.4",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/flex-layout": "2.0.0-beta.9",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/router": "4.4.4",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "2.0.0",
    "@swimlane/ngx-datatable": "9.3.1",
    "angular-calendar": "0.21.2",
    "angular-tree-component": "5.0.0",
    "chart.js": "2.7.0",
    "core-js": "2.5.1",
    "d3": "4.11.0",
    "dragula": "3.7.2",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "leaflet": "1.2.0",
    "moment": "2.18.1",
    "ng2-charts": "1.6.0",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.2.1",
    "ng2-validation": "4.2.0",
    "ngx-quill": "1.3.5",
    "perfect-scrollbar": "0.8.1",
    "rxjs": "5.4.3",
    "screenfull": "3.3.1",
    "zone.js": "0.8.10",
    "@angular/platform-server": "^4.4.6",
    "angular2-jwt": "^0.2.3",
    "angular2-toaster": "^4.0.1",
    "ng2-archwizard": "^1.7.0",
    "ng2-translate": "5.0.0",
    "ngx-mask": "^2.0.3",
    "quill": "1.2.4"
  },
  "devDependencies": {
    "@angular/cli": "1.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/language-service": "4.4.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by loginova-anna** [comment]
had the same problem, installed latest everything - got a bit another error:
```
Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an ex
ported function, resolving symbol Injectable in C:/Users/aloginova/sources/repos/FrontAng2-new/node_modules/ngx-mask/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in C:/Users/aloginova/sources/r
epos/FrontAng2-new/node_modules/ngx-mask/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in C:/Users/aloginova/sources/repos/FrontAng2-new/node_modules/ngx-mask/node_modules/@angular/core/core.d.t
s
```

**Comment by NepipenkoIgor** [comment]
@loginova-anna @rafaelcneves  @2n2n Hi, i tested last build and it works fine for angular v5 and v4 and aot compilation. Please try and give me feedback

**Comment by khan8698** [comment]
@NepipenkoIgor which version is working correctly with angular version 4.4.6. i am currently facing this issue and cannot update angular version for now.
