### ISSUE TITLE
comma_separator allows non numeric characters

### ISSUE THREAD

**Issue by larnust** [JsDaddy/ngx-mask#422]
I've not tried every unicode character, but for some reason comma_separator allows the following characters:
£ ¬ \ '

You can't add them after a decimal place.

Is there a work around available while this is fixed? thank you

**Comment by larnust** [comment]
for now i've created a directive so that on keydown I can only allow numeric chars, tab, arrow keys, decimal etc and only allow decimal points if it's not the first character... and use this alongside the mask so that I get comma separation and can guarantee the input contains only numbers.

Looking forward to a fix so I can remove my directive. Thanks

**Comment by ValeriaKochegarova** [comment]
@larnust we fixed this, you can try to use in the latest version
