### ISSUE TITLE
IE TypeError: Object doesn't support property or method 'include'

### ISSUE THREAD

**Issue by eehaddad** [JsDaddy/ngx-mask#425]
This is related to this closed issue: https://github.com/JsDaddy/ngx-mask/issues/337

In IE11 after I enter the second character in a masked input field I am presented with this error. 
TypeError: Object doesn't support property or method 'include' 

On versions prior to 7.8.9 I get the error either on load or as soon as I click into the input. 

I was on version 7.8.9 and updated to the latest (7.9.1) but still had the same issue. 
7.0.1 seems to be the last version that doesn't have this issue. 

Here are a coupe of the masks having this issue -- basic stuff

`<input type="text"
      id="firstName"
      name="firstName"
      formControlName="firstName"
      maxlength="50"
      mask="S*"
      required/>`

` <input type="text"
        name="dateOfBirth"
        id="dateOfBirth"
        placeholder="MM/DD/YYYY"
        formControlName="dateOfBirth"
        mask="M0/d0/0000"
        [dropSpecialCharacters]="false"
        required>`

![image](https://user-images.githubusercontent.com/15235097/55983810-d7d96b00-5c50-11e9-81e7-c5b5986ffee5.png)

**Comment by ValeriaKochegarova** [comment]
@eehaddad Did you try to add polyfill https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill

**Comment by eehaddad** [comment]
Thank you! 

I already had es6 object and array polyfills in my polyfills.ts but adding es7 did the trick.

for others that run into this, add the following in your polyfills.ts file under 
_"/** IE9, IE10 and IE11 requires all of the following polyfills. **/"_ 

```
import 'core-js/es7/object';
import 'core-js/es7/array';
```

Thanks again!

**Comment by ValeriaKochegarova** [comment]
@eehaddad we fixed this, you can try to use in the latest version
