### ISSUE TITLE
comma_separator/dot_separator with limited decimal precision is converted to string

### ISSUE THREAD

**Issue by LuisAlonsoCalderon** [JsDaddy/ngx-mask#426]
When I bind a value and try to use a comma_separator or a dot_separator with a limited decimal precision like in these examples:
```
<input type='text' [(ngModel)]="value" prefix="$ " mask="dot_separator.2">
<input type='text' [(ngModel)]="anotherValue" prefix="$ " mask="comma_separator.2">
```
The binded values will be converted into strings so the sum of both values will be the appended string.

This doesn't happen if `mask="dot_separator.0"` or if you don't limit the decimal precision at all

**Comment by Thegrep01** [comment]
@LuisAlonsoCalderon the mask works by default with strings, when you init your ngModel by default value enter any number
