### ISSUE TITLE
Question: Percent - only allow 2 decimals

### ISSUE THREAD

**Issue by lizelleboshoff** [JsDaddy/ngx-mask#427]
Hi,
Is there a way to only allow 2 decimals to be entered for a percent mask?

Thank you

**Comment by AlexeyDolya** [comment]
We added this feature, now you can specify precent.X,
to specify the number of characters after the point (including the point).
Example: ` <input matInput mask = "percent.5" sufix = "%" [formControl] = "percent">`
Wait for the update.

**Comment by lizelleboshoff** [comment]
Thank you very much for the enhancement.

I still have a problem where the user can type 1.005%.  The percent.X only specifies how many characters you can fill in.  It does not specify the decimal numbers?

**Comment by cosminailoaieassist** [comment]
Working only with [formControl].
mask = "percent.X" ain't working with [(ngModel)].
At Least for me. Maybe I'm doing something wrong. 

`								<input
                                                                         type="text"
									[(ngModel)]="newCommission"
									class="form-control"
									data-toggle="input-mask"
									suffix="%"
									mask="percent.2"
									[validation]="true"
								/>`
