### ISSUE TITLE
Weird behavior with backspace & custom patterns

### ISSUE THREAD

**Issue by asterius321** [JsDaddy/ngx-mask#432]
Hello,

I created a custom pattern for french dates : 
    static dateMask = "d0/m0/y000";
    static dateMaskPattern = {
        '0': { pattern: new RegExp(/[0-9]/)},
        'd': { pattern: new RegExp(/[0-3]/)},
        'm': { pattern: new RegExp(/[0-1]/)},
        'y': { pattern: new RegExp(/[1-2]/)},
    };

Now, If I enter 29/12/2019, and delete the first digit, the input becomes 12/01/
This is a weird behavior for the end user that expect to have just one digit to add in front of the date.
I suppose the logic applied here is:

- 29/12/2019 => 91/22/019 after the first digit deletion
- 91/22/019 => 12/20/19 after removal of the 9, which is not in [0-3]
- 12/20/19 => 12/01/9  after removal of the first 2, which is not in [0-1]
- 12/01/9 => 12/01/ lastly after removal of the last 9, which is not in [1-2]

Is there any way to avoid this? Maybe cleaning the input only on blur, to let the ability for the user to add the missing digit? Validate only the typed char, instead of all chars at once?

Thanks in advance for your answer!

**Comment by Serge0111** [comment]
Hi @asterius321, Why don't you try to use the following mask d0/M0/0000?

**Comment by asterius321** [comment]
Well, the problem will be the same, we will just end up on 12/01/9

**Comment by ValeriaKochegarova** [comment]
@asterius321 you can use the following mask : dateMask = "d0/M0/0000";
dateMaskPattern = {
0: { pattern: new RegExp(/[0-9]/)},
d: { pattern: new RegExp(/[0-3]/)},
M: { pattern: new RegExp(/[0-1]/)},
y: { pattern: new RegExp(/[1-2]/)},
};
}
