### ISSUE TITLE
Handle undefined or null mask

### ISSUE THREAD

**Issue by asterius321** [JsDaddy/ngx-mask#433]
Hello,

I have a generic component that add validators, embed errors notifications, set mask, and do other stuffs about just an input component.

Specifically, my component get the input type and mask through the @Input variables.
In the case I provide an input type="number", and do not specify a mask (which is then null/undefined), I get the following javascript error: 

DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective.onFocus (http://localhost:4200/modules-screens-screens-module.js:2480:31)

Is it possible to totally deactivate the mask when its content is null or undefined?

Thanks!

**Comment by Thegrep01** [comment]
@asterius321 Hello, frist of all mask work only with input type text

**Comment by asterius321** [comment]
Ok, I understand It does not provide many benefits on number input types (though...).
But it still seems strange to me that the directive effectively do something when no mask is provided...
Could be great if no error could be generated in this case.

**Comment by raphaelramalho** [comment]
I have the same problem, a custom input that I pass the mask via @Input, but when not passing a value is shown "undefined" in the input field;

**Comment by MBogdan18** [comment]
Any updates on this? Came across this same issue.

**Comment by ViniciusDBarth** [comment]
I have the same problem

**Comment by ViniciusDBarth** [comment]
Propably not the best solution, but I solved this problem, creating new patterns, and one of the patterns accepts anything.

    NgxMaskModule.forRoot({
      patterns:{
        '&': { pattern: new RegExp('.*')},
        'A':{ pattern: new RegExp('[a-zA-Z]')},
        'a':{ pattern: new RegExp('[a-z]')},
        '0':{ pattern: new RegExp('[0-9]')}
      },
    }),

So when I need an input without mask, i use " *&" as mask.

**Comment by Gianluska** [comment]
Still not working for me, can you show how did you do it?

> Propably not the best solution, but I solved this problem, creating new patterns, and one of the patterns accepts anything.
> 
> ```
> NgxMaskModule.forRoot({
>   patterns:{
>     '&': { pattern: new RegExp('.*')},
>     'A':{ pattern: new RegExp('[a-zA-Z]')},
>     'a':{ pattern: new RegExp('[a-z]')},
>     '0':{ pattern: new RegExp('[0-9]')}
>   },
> }),
> ```
> 
> So when I need an input without mask, i use " *&" as mask.

**Comment by ViniciusDBarth** [comment]
That's all did.
This code you add in your app.module.ts in the imports. This code creates new patterns for your mask.

NgxMaskModule.forRoot({
  patterns:{
    '&': { pattern: new RegExp('.*')},
    'A':{ pattern: new RegExp('[a-zA-Z]')},
    'a':{ pattern: new RegExp('[a-z]')},
    '0':{ pattern: new RegExp('[0-9]')}
  },
}),

As you can see one of the patterns that I created is '&', and this patters accepts anything, so when you need an input without mask, you only have to use this pattern as a mask. like this

<input type='text' mask='*&'>
