### ISSUE TITLE
Thousand separator with decimals at the same time

### ISSUE THREAD

**Issue by prosto-artem** [JsDaddy/ngx-mask#434]
Hello! 
First of all thanks for this great mask tool!
I'm trying to use thousand separator with decimals at the same time, but facing a few problems.

I've tried a few different methods to achieve a certain result, but all of them have failed.

If i'm using 'separator' mask, i can't put decimals in input, but if i add '.2'  or ',2' to the 'separator', input will freeze after 1 symbol. 
There was another issue like that before => [this one](https://github.com/JsDaddy/ngx-mask/issues/277). And it was closed with reply that this functionality is added to this plugin, but i can't find a proper documentation on how to use that, and also when i opened test files, there is no case of checking if that is working correctly.

I've created a [stackblitz](https://stackblitz.com/edit/ngx-mask-separator), which can demonstrate the problem to you

- @angular/common: 7.2.13
- @angular/compiler: 7.2.13
- @angular/core: 7.2.13
- @angular/forms: 7.2.13
- @angular/platform-browser: 7.2.13
- @angular/platform-browser-dynamic: 7.2.13
- @angular/router: 7.2.13
- core-js: 2.6.5
- ngx-mask: 7.9.2
- rxjs: 6.4.0
- zone.js: 0.9.0

**Comment by stylerhun** [comment]
I have the same problem. 
If you use mask="separator." or mask="spearator.2" then only one character can be written into the input. 

`"@angular/animations": "^7.2.4",
    "@angular/cdk": "^7.3.6",
    "@angular/common": "^7.2.11",
    "@angular/compiler": "^7.2.11",
    "@angular/core": "^7.2.11",
    "@angular/forms": "^7.2.11",
    "@angular/http": "^7.2.11",
    "@angular/material": "^7.3.6",
"@angular/platform-browser": "^7.2.11",
    "@angular/platform-browser-dynamic": "^7.2.11",
    "@angular/platform-server": "^7.2.11",`

**Comment by prosto-artem** [comment]
I fixed the problem locally, but i push changes to a new branch and create pull request because i don't have permissions.

'Remote: Permission to JsDaddy/ngx-mask.git denied to prosto-artem. unable to access 'https://github.com/JsDaddy/ngx-mask.git/': The requested URL returned error: 403'

@ValeriaKochegarova , @NepipenkoIgor

**Comment by prosto-artem** [comment]
[PR #440](https://github.com/JsDaddy/ngx-mask/pull/440)

**Comment by manticorra** [comment]
The problem has not gone.

When I use "dot_separator.2" all works fine, when i use "separator.2" I have error before I enter thousands. 

I used version 8.0.0

#440
