### ISSUE TITLE
[help wanted] Mask with two or more patterns

### ISSUE THREAD

**Issue by betodasilva** [JsDaddy/ngx-mask#435]
Hey,

I want to create a mask for vehicles plates but in South America we have two patterns 
'AAA-9999' and 'AAA9A99'.

How can I accomplish that with ngx-mask?

Thanks in advance

**Comment by ValeriaKochegarova** [comment]
@betodasilva  you can use mask like : mask="AAA-0999" for case AAA-9999 and mask="AAA0A99" for case AAA9A99
