### ISSUE TITLE
Cursor shifting to the right after backspace removes a separator

### ISSUE THREAD

**Issue by suarezquiroz** [JsDaddy/ngx-mask#436]
when the cursor is after the second or third digit, if after backspace the mask removes a separator, the cursor shifts one position to the right of the next digit

![image](https://user-images.githubusercontent.com/17535458/56219508-7b00fa80-602c-11e9-824d-d5f34b6dca63.png)

After pressing Backspace:

![image](https://user-images.githubusercontent.com/17535458/56219546-8e13ca80-602c-11e9-963e-4ec29818c704.png)

**Comment by ValeriaKochegarova** [comment]
@suarezquiroz you can try to use it in the latest version

**Comment by SabikAbtahee** [comment]
This is issue still exists in the latest version. Is it actually solved?
