### ISSUE TITLE
percent.X does not limit decimal precision

### ISSUE THREAD

**Issue by lizelleboshoff** [JsDaddy/ngx-mask#438]
Thank you for adding the percent.X functionality.  It however seems that it actually just limits the number of characters that you can enter and not the decimal precision.

if you have percent.5 it limits the decimals to 2 like expected. 
50.22% (a total of 5 characters)

The problem is that you can enter 1.005% (a total of 5 characters).
I would have expected the precent.X, to specify the number of characters after the point .

Thank you.

**Comment by ValeriaKochegarova** [comment]
@lizelleboshoff in our mask "." means that after dot you can enter 5 symbols , when you  use mask ="percent.5" it will display like .12345 
example 12.12345 , you can try to use the 7.9.5 mask version
