### ISSUE TITLE
Getting date with number while using date mask 

### ISSUE THREAD

**Issue by ayaz76** [JsDaddy/ngx-mask#439]
Hi Team ,

I am using date mask but getting value like this 11112019 i want in dd/mm/yyyyy or any date related format..
Can you help me with this.

Example :

 <input class="form-control input-md"  mask="d0/M0/0000"
                          [showMaskTyped]="true" [(ngModel)]="model.birthdate" #birthdate="ngModel" id="birthdate"
                          placeholder="dd/mm/yyyy" name="birthdate" />

Any help appriciate..

Thanks

**Comment by DovakhinMRK** [comment]
@ayaz76  Hi there, I think you are missing  "dropSpecialCharacters="true"", and you should provide them like this: "[specialCharacters]="[ '/' ]"". Check readme for more info. Have a nice day

**Comment by ayaz76** [comment]
Hi @DovakhinMRK ,

Perfectly working as you suggested..
I appreciate your help


With regards,
Ayaz

**Comment by mattiLeBlanc** [comment]
Does this not work with FormGroup? I tried the suggestion but I still get the date in my FormControl as 30122022.
