### ISSUE TITLE
angular 5

### ISSUE THREAD

**Issue by Tolitech** [JsDaddy/ngx-mask#44]
Hello.
is there any idea for the component to be compatible with angular 5?

when we update angular-cli to version 1.5 and we use the new angular 5, even in a totally blank project, the ngx-mask component informs error:

WARNING in ./node_modules/ngx-mask/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression........

Thanks.

**Comment by NepipenkoIgor** [comment]
@Tolitech Yes, i am going to update ngx-mask on weekend

**Comment by ThalesMatoso** [comment]
The same problem here, after upgrading to angular 5 and running with the --aot flag, I have this problem.

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. NgModule in / var / www / lb-manager / node_modules / ngx-mask / node_modules / @ angular / ngx-mask / core / core.d.ts, resolving symbol NgxMaskModule in /var/www/lb-manager/node_modules/ngx-mask/build/ngx-mask.module.d.ts, resolving symbol NgxMaskModule in / var / www / lb- manager / node_modules / ngx-mask / build / ngx-mask.module.d.ts

is there any forecast?

**Comment by NepipenkoIgor** [comment]
@ThalesMatoso @Tolitech Hi, i tested last build and it works fine for angular v5 and aot compilation. Please try and give me feedback

**Comment by Tolitech** [comment]
it's working now.
thank you.

**Comment by NepipenkoIgor** [comment]
@Tolitech  and you

**Comment by ThalesMatoso** [comment]
Yes, its work
