### ISSUE TITLE
Mask shows undefined when using dot_separator.2 and empty textbox after erasing

### ISSUE THREAD

**Issue by basvdijk** [JsDaddy/ngx-mask#441]
Note to devs: Is there a way to not immediately close the issue when you think it is fixed? I noticed that often the issue is closed, with the bug still unsolved. When replying to a closed issue I do not receive any replies to my comments on the closed issues. Therefore I put it up as a new issue. The original was #414

-----

When I use the `dot_separator.2` and the model is contains 123456.789 it will show up fine. However when I erase the field with backspace, the mask shows `undefined` when the field is empty:

![image](https://user-images.githubusercontent.com/644550/55884902-33e8b480-5ba9-11e9-8e9f-497dda943e3e.png)

The happens when I define the model as a string which is empty e.g.

```
TS
public testData: string = ''

HTML
  <input
    type="text"
    [(ngModel)]="testData"
    [required]="isRequired"
    mask="dot_separator.2"
    [dropSpecialCharacters]="true"
  />
```

**Comment by ValeriaKochegarova** [comment]
@basvdijk i tried to reproduced everything is working

**Comment by Serge0111** [comment]
hi @basvdijk , sorry for closing), i did it automatically. Could you provide a repo with that issue so can help you.

**Comment by NepipenkoIgor** [comment]
@basvdijk  Please add more explanations  and conditions . We usully testing in different environments with different conditions.

**Comment by basvdijk** [comment]
@NepipenkoIgor @Serge0111 
- checkout https://github.com/basvdijk/ngx-mask if you checkout this repo
- enter something in the top textbox
- remove the content
- The result is 'undefined'

**Comment by ValeriaKochegarova** [comment]
@basvdijk in your file app-input.component.html in <input> there is a [placeholder]="placeholder" , as i can see 'placeholder' is not a variable and that is why  every time shows you in textbox 'undefined' , you should remove "[]" placeholder="placeholder" and everything is working correct , also i tried with your other example 
`TS
public testData: string = ''

HTML
  <input
    type="text"
    [(ngModel)]="testData"
    [required]="isRequired"
    mask="dot_separator.2"
    [dropSpecialCharacters]="true"
  /> `
and result is the same like the first example
![Screen Shot 2019-05-03 at 5 00 01 PM](https://user-images.githubusercontent.com/32837526/57142399-1207d980-6dc5-11e9-94d7-99b49718deb1.png)

**Comment by basvdijk** [comment]
@ValeriaKochegarova great find, thanks!
