### ISSUE TITLE
ng mask example page does not allow data to be entered into inputs in chrome/edge

### ISSUE THREAD

**Issue by gfisher42** [JsDaddy/ngx-mask#442]
None of the inputs on the NG Mask example page work across multiple browsers.  It also doesn't work from an iPhone 7.  Is the library broken?

**Comment by gfisher42** [comment]
While there may be an issue on the page itself, I just tried to implement a mask using this library in Angular 6 and generated the same issue on my page.

**Comment by Thegrep01** [comment]
@gfisher42 @zaalbarxx fixed
