### ISSUE TITLE
clearIfNotMatch option does not work together with prefix option

### ISSUE THREAD

**Issue by nmorozov** [JsDaddy/ngx-mask#443]
Example:
`<input matInput formControlName="phone" type='text' [clearIfNotMatch]="true" mask="(000) 000-0000" prefix="+7"/>`

When I enter the correct phone number and the input field loses focus, the phone number is cleared. Without prefix attribute all works properly.

**Comment by Serge0111** [comment]
hi @nmorozov, we fixed that, try new version.
