### ISSUE TITLE
How can I set a mask for only a few characters

### ISSUE THREAD

**Issue by Nekiess** [JsDaddy/ngx-mask#445]
How can I set a mask for only a few characters and leave the rest free? 
For example, mask = '(099) .... Here I can type whatever I want including *, (,), -'
.
I tried to mask '(099) AAAAAAAAAA' but I can not type special characters at this point.
.
In this way the value typed could be as "(061) *-/asadfas  df " or " (061) ---()asadas" no matter what would come after the value informed of the mask (099)

**Comment by ValeriaKochegarova** [comment]
@Nekiess you should add [specialCharacters]="[ ]" that can you allow to add special characters. 
example: 
<input mask="(000)0/00-00-00" 
[specialCharacters]="['(', ')', '-' , '/' ]"
 >
