### ISSUE TITLE
Separator thouthands 'mask="separator"' with precision.

### ISSUE THREAD

**Issue by shonns** [JsDaddy/ngx-mask#448]
In my case, i need devide my input by thousands (space between thousands) with precision 2 signs after comma.
But mask does not allow to do it, when i use mask="separator.2".
Can u fix it? 
Thank you.

**Comment by prosto-artem** [comment]
#440

**Comment by ValeriaKochegarova** [comment]
@shonns you can try to use it in the latest version

**Comment by prosto-artem** [comment]
> @shonns you can try to use it in the latest version

it's gonna be available in 7.9.5, the latest version is not published yet
