### ISSUE TITLE
Error When Used in FormArray, datepicker angular material and ngx-mask

### ISSUE THREAD

**Issue by silvergama** [JsDaddy/ngx-mask#449]
ERROR Error: More than one custom value accessor matches form control with path: ' ->  -> ' 

`<div [formGroup]="form">
    <div formArrayName="faseConstrucao" *ngFor="let faseConstrucao of getFaseConstrucaoControl.controls; let i = index">
        <div [formGroupName]="i">
            <mat-form-field>
                <input matInput [matDatepicker]="picker" placeholder="Lançamento" [formControlName]="lancamento"
                    mask="00/00/0000">
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                <mat-datepicker #picker></mat-datepicker>
            </mat-form-field>
            <mat-form-field>
                <input matInput [matDatepicker]="picker2" placeholder="Encerramento" [formControlName]="encerramento"
                    mask="00/00/0000">
                <mat-datepicker-toggle matSuffix [for]="picker2"></mat-datepicker-toggle>
                <mat-datepicker #picker2></mat-datepicker>
            </mat-form-field>
        </div>
    </div>
</div>`

**Comment by ValeriaKochegarova** [comment]
@silvergama could you provide a full example ?

**Comment by silvergama** [comment]
Ex: https://stackblitz.com/edit/angular-kmcusk

In app.component.html Add formControlName="date" in input to show error:  More than one custom value accessor matches form control with unspecified name attribute

**Comment by ValeriaKochegarova** [comment]
@silvergama Unfortunately we cannot do this  #50

**Comment by aemonge** [comment]
Is this bug still unfix-able ?

**Comment by ValeriaKochegarova** [comment]
@aemonge please check this #50

**Comment by aemonge** [comment]
Hi @ValeriaKochegarova , thanks for the link. But I already posted there another question related to this.

Basically over-there, the official solution is not to use ngMask.... so that's why I use this ticket  to ask if there's a plan to fix the bug or should we follow the #50 guidelines and avoid the library at all.

**Comment by LuanMaik** [comment]
Did anything change? Any implementation? Any workaround?

**Comment by bcordes1** [comment]
@LuanMaik it's open source project from my reading and the maintainers have chosen to not fix it or say that it's impossible to fix. Current suggestion is to use a custom directive with a native adapter as seen in #50 .

**Comment by aintnomoreloyalty** [comment]
Hey guys, any news on this? I guess I found a "hacky" solution. If anyone still has that issue please let me know so I'll share it with you!

**Comment by phillip389** [comment]
Based on an existing solution:

[https://stackoverflow.com/questions/60818529/angular-input-with-ngx-mask-matdatepicker-and-reactive-form](url)

Hi I have a working solution:

The matDatePicker input is hidden and linked to the masked input to the hidden datepicker which binds to the formControl and bind matInput the the masked input field.

ngModelOptions is important, as there is an error thrown when using ngModel used within a form

        ngModel cannot be used to register form controls with a parent formGroup directive.

HTML:
   
      <input #dateInput type="hidden" id="reservationDate" formControlName="date" required [matDatepicker]="datePicker" [min]="today" /> 

      <input #maskedInput matInput (input)="dispatch(dateInput)" placeholder="Pick a date"
              [(ngModel)]="dateInput.value" [ngModelOptions]="{ standalone: true }" mask="00/00/0000"  [dropSpecialCharacters]="false" />

      <mat-datepicker-toggle  matSuffix [for]="datePicker"></mat-datepicker-toggle>

      <mat-datepicker #datePicker></mat-datepicker>


Component: 


      dispatch(input: HTMLInputElement) {
        input.dispatchEvent(new Event('input'));
      }


<img width="403" alt="Screenshot 2023-12-24 at 10 06 15 AM" src="https://github.com/JsDaddy/ngx-mask/assets/2860261/0f4e18c6-e63c-4d6b-a300-dad9cccc46eb">

<img width="486" alt="Screenshot 2023-12-24 at 10 06 56 AM" src="https://github.com/JsDaddy/ngx-mask/assets/2860261/125476d1-fbf4-45fd-aade-183283ae596e">
