### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jet8a** [JsDaddy/ngx-mask#452]
7.9.3 version

InputComponent.html:9 ERROR TypeError: Cannot read property 'length' of undefined
    at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective.onFocus (ngx-mask.js:841)
    at Object.eval [as handleEvent] (InputComponent.html:9)
    at handleEvent (core.js:23107)
    at callWithDebugContext (core.js:24177)
    at Object.debugHandleEvent [as handleEvent] (core.js:23904)
    at dispatchEvent (core.js:20556)
    at core.js:21003
    at HTMLInputElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1693)
    at HTMLInputElement.globalZoneAwareCallback (zone.js:1719)
View_InputComponent_0 @ InputComponent.html:9
proxyClass @ compiler.js:18239
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
dispatchEvent @ core.js:20560
(anonymous) @ core.js:21003
(anonymous) @ platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1693
globalZoneAwareCallback @ zone.js:1719
InputComponent.html:9 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 8, nodeDef: {…}, elDef: {…}, elView: {…}}
View_InputComponent_0 @ InputComponent.html:9
proxyClass @ compiler.js:18239
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15777
dispatchEvent @ core.js:20560
(anonymous) @ core.js:21003
(anonymous) @ platform-browser.js:993
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17290
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1693
globalZoneAwareCallback @ zone.js:1719

_Originally posted by @jet8a in https://github.com/JsDaddy/ngx-mask/issues/419#issuecomment-487850535_

**Comment by ValeriaKochegarova** [comment]
@jet8a  could you provide an example ?

**Comment by jet8a** [comment]
> @jet8a could you provide an example ?

https://stackblitz.com/edit/angular-kd9jf5
please try changing the input value

**Comment by Thegrep01** [comment]
@jet8a Hello, I checked your example and it is problem with your code, add this
<img width="183" alt="Снимок экрана 2019-05-06 в 11 57 39" src="https://user-images.githubusercontent.com/38587958/57215663-444c4d80-6ff6-11e9-9a09-44f07b188123.png">

**Comment by jet8a** [comment]
Thank you very match, it worked

**Comment by Qesperson** [comment]
> @jet8a Hello, I checked your example and it is problem with your code, add this <img alt="Снимок экрана 2019-05-06 в 11 57 39" width="183" src="https://user-images.githubusercontent.com/38587958/57215663-444c4d80-6ff6-11e9-9a09-44f07b188123.png">

It worked! Thanks
