### ISSUE TITLE
How to stop keypress when cursor is at the end of the text box

### ISSUE THREAD

**Issue by rakeshnayak360** [JsDaddy/ngx-mask#464]
When the cursor is at end of the textbox, masking is allowing to type. How to avoid it. Screen shot given below.

![image](https://user-images.githubusercontent.com/19386889/57363584-00e11300-719f-11e9-9253-408a7f62f8e7.png)

**Comment by AlexeyDolya** [comment]
please provide the code example

**Comment by rakeshnayak360** [comment]
HTML:
mask="000-000000-000" showMaskTyped="true"

**Comment by AlexeyDolya** [comment]
@rakeshnayak360 
Duplicate of #235
