### ISSUE TITLE
when [showMaskTyped] = "true", cursor is moving on non matching keypress

### ISSUE THREAD

**Issue by rakeshnayak360** [JsDaddy/ngx-mask#466]
HTML:
<input type="text" mask="000-00000-000" [showMaskTyped] = "true" />

Cases:
When i type special characters [*/-+], or any alphabets the cursor is moving towards right. 

How to avoid it?

**Comment by rossTyler** [comment]
I also need to avoid this issue

**Comment by redq81** [comment]
Also got this bug. Fix it please.
