### ISSUE TITLE
month not working properly in version 7.9.9

### ISSUE THREAD

**Issue by muniraji2i** [JsDaddy/ngx-mask#470]
I working at the angular platform in 6.2.8 version.
While entering date **22/2/2018** in month field 0 added (**22/02/2018**) by default in version 7.4.3
I update the version to 7.9.9 for the purpose of decimal in comma seperatorwhich is  working at 7.9.9
Now the 0 can not add  by default.

`<input type="text" mask="d0/m0/0000">`
I used this mask

**Comment by muniraji2i** [comment]
<input type="text" mask="d0/m0/0000">
I used this mask

**Comment by Thegrep01** [comment]
@muniraji2i you should use this mask d0/M0/0000

**Comment by muniraji2i** [comment]
if I use d0/M0/0000 mask I can able to enter 22/02/1997.....If I tried to enter 2 , I can't complete month...I just want to type 22/2/1997 and output should be 22/02/1997...0 added by default in version 7.4.3...
