### ISSUE TITLE
Problem setting data in field with observable valueChanges

### ISSUE THREAD

**Issue by arthurfrancioni** [JsDaddy/ngx-mask#471]
I have a field where has a observable, and when I set value in this field with "emitEvent: false" the observable is called.

This happens when I wrap the values inside an http callback or settimeout.

I could not call the ValueChange when I set emitEvent: false

Repo: https://stackblitz.com/edit/angular-jcub7p

**Comment by NepipenkoIgor** [comment]
@arthurfrancioni  Hi. Thank you for using ngx-mask package. With latest version everything works as expected.
You could try https://stackblitz.com/edit/angular-ivy-mask-f5v6mm?file=src%2Fapp%2Fapp.component.ts. If you steel have an issue  please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
