### ISSUE TITLE
Problem in commma seperator using with decimal

### ISSUE THREAD

**Issue by muniraji2i** [JsDaddy/ngx-mask#472]
`<input type="text" mask="comma_seperator.2">`
While I enter input **7777777.8**  mask cannot add 0 by default like **77,77,777.80**
And also while i enter **777777.**(only dot) after dot cannot add 00 by default like **7,777.00**

**Comment by FrutasLuna** [comment]
I found the same error, I could not make it work with a dot for decimal and with a comma for thousands separator.

**Comment by NepipenkoIgor** [comment]
@muniraji2i @FrutasLuna Please try version 7.9.10.
