### ISSUE TITLE
mask type credit card number error

### ISSUE THREAD

**Issue by christiantigre** [JsDaddy/ngx-mask#473]
I'm trying create a input type credit card, but the input show a simple input text.
I need the number 4567/5654/9878/9899 or 4567 5654 9878 9899
<input mask="____/____/____/____" name="card_number">
<input mask="____ ____ ____ ____" name="card_number">

**Comment by muniraji2i** [comment]
`<input    type="text" mask="0000/0000/0000">`

Use this mask

**Comment by NepipenkoIgor** [comment]
@christiantigre 
You could use `mask="0000 0000 0000 0000"` or `mask="0000/0000/0000/0000"` on your input element
