### ISSUE TITLE
IE11 Error: For input field that already has value, cursor will auto jump to the beginning when user click out and then click back into a input field (at the end position)

### ISSUE THREAD

**Issue by Annie-Huang** [JsDaddy/ngx-mask#474]
Scenario:
Simple input field with mask: <input type='text' mask='999999999'>
This only happens in IE. Chrome and firebox work fine.

1. Click into the empty input field and enter 111.
2. Click outside the input field
3. Click back into the input field on the right side of 111.

Result: Cursor stayed on the right side of 111 and then auto jump to the left side.

![error](https://user-images.githubusercontent.com/26481566/57853089-2ff32680-7828-11e9-8a7a-69569ea418bb.gif)

Repo: 
https://github.com/Annie-Huang/my-second-angular-app/tree/test-ngx-mask-7.9.9

**Comment by Annie-Huang** [comment]
Sorry I should say I want the cursor to stay in wherever i click within the word: beginner, middle, end.

Highline characters will also make cursor move to the beginning.

**Comment by duxor** [comment]
Same problem for me

**Comment by NepipenkoIgor** [comment]
@Annie-Huang @duxor  Could you try latest version ?

**Comment by Annie-Huang** [comment]
Hi @NepipenkoIgor . When this happened, IE is with version of 11.0.9600.19377. Now IE has upgraded into 11.437.17763.0. And the problem is resolved without we upgrading the new version of ngx-mask. But not sure for Chronmium version for  @duxor though.

**Comment by duxor** [comment]
@Annie-Huang @NepipenkoIgor Works for me with latest version. Thanks

> Hi @NepipenkoIgor . When this happened, IE is with version of 11.0.9600.19377. Now IE has upgraded into 11.437.17763.0. And the problem is resolved without we upgrading the new version of ngx-mask. But not sure for Chronmium version for @duxor though.

@Annie-Huang @NepipenkoIgor Works for me with latest version. Thanks
