### ISSUE TITLE
Mask fails when using some symbols as a suffix

### ISSUE THREAD

**Issue by docker1** [JsDaddy/ngx-mask#475]
I use the Rouble character as a suffix, separator.2 as a mask. The suffix duplicates after entering (or backspacing) a new character (see example below). The same problem with the Euro character.

![123](https://user-images.githubusercontent.com/20402849/57866969-efd07b80-7808-11e9-8356-a58a59f65490.gif)

**Comment by NepipenkoIgor** [comment]
@docker1  Could you provide stackblitz with latest ngx-mask version  ???

**Comment by dintecom** [comment]
Please look at the repeat mask example: https://stackblitz.com/edit/angular-h75a6c .
In case of using an optional pattern, try to erase a dot in the suffix.

**Comment by dintecom** [comment]
Version 8.0.1 not fix this bug (https://github.com/JsDaddy/ngx-mask/pull/508).
Updated example: https://stackblitz.com/edit/angular-h75a6c

**Comment by isysenko** [comment]
![Запись экрана 2019-09-19 в 15 35 32](https://user-images.githubusercontent.com/33220782/65244787-f98a2880-daf3-11e9-90f7-fc28a0d5d833.gif)
@docker1 Hi, will be fixed in the new mask version
