### ISSUE TITLE
Error el objeto no acepta la propiedad o el metodo 'includes'

### ISSUE THREAD

**Issue by NestorLopz94** [JsDaddy/ngx-mask#478]
Al usar ngx-mask en explorer 11 no funciona y marca el siguiente error 

![image](https://user-images.githubusercontent.com/51098363/58440233-48700600-809e-11e9-91d9-2720ecee3b27.png)

En otros navegadores funciona bien solo en explorer no, me pueden especificar si me falta algo por agregar o el porque del error

**Comment by NepipenkoIgor** [comment]
Hi @NestorLopz94 . Do you add poliffils to you app ? For example core-js ?  
And also could you provide english comments ?

**Comment by NestorLopz94** [comment]
Hello, If I have added polyfills.ts in my application. 

![image](https://user-images.githubusercontent.com/51098363/59786581-2e84a600-928d-11e9-8584-2b03b69dabc2.png)

**Comment by NepipenkoIgor** [comment]
@NestorLopz94 and how look your polyfills.ts?

**Comment by NestorLopz94** [comment]
only has imported zone.js

![image](https://user-images.githubusercontent.com/51098363/60212136-1f21d180-9826-11e9-849c-f0cb840d0d7c.png)

**Comment by NepipenkoIgor** [comment]
@NestorLopz94  Please use polyfills , for example core-js 
`import 'core-js/es7/array`
or
`import 'core-js/features/array/includes`

and also for add similar polyfills for string
