### ISSUE TITLE
On masking reactiv forms input return false

### ISSUE THREAD

**Issue by emilalsgndr** [JsDaddy/ngx-mask#479]
<input 
        type="text" 
        placeholder="Təqribi məbləğ" 
        name="scale_of_project" 
        id="scale_of_project" 
        mask="000 000 000 000"
        formControlName="scale_of_project"/>

form(input) always return valid false. After (988 3213 312 313) input all characters write return true. Why this is required ?

**Comment by emilalsgndr** [comment]
`      <input 
        type="text" 
        placeholder="Təqribi məbləğ" 
        name="scale_of_project" 
        id="scale_of_project" 
        mask="000 000 000 000"
        formControlName="scale_of_project"
      />`

**Comment by bncunha** [comment]
Hello!

According documentation, mask with 0 means that digits is required and ngx-mask validate this for default.

![image](https://user-images.githubusercontent.com/21287627/58637394-ca437780-82c8-11e9-8180-e2d12d4f32df.png)


You can tell to don't validate, putting [validation]="false":

`<input type="text" mask="000 000 000 000" formControlName="scale_of_project" [validation]="false"/>`

You can test here, https://stackblitz.com/edit/angular-iqfbtv

**Comment by emilalsgndr** [comment]
Hi.
Thanks for comment.
If you change mask="000 000 000 000" to mask="999 999 999 999" on https://stackblitz.com/edit/angular-iqfbtv  this is not working. Also i want this input field must be required.

**Comment by bncunha** [comment]
I do not understand your doubt very well.
If you want the field to be required then the form must be invalid, or do you want at least 1 character to be required?

**Comment by emilalsgndr** [comment]
mask="999 999 999 999" i use this. on your stackblitz demo. I need input must required but mask pattern is optional. just https://stackblitz.com/edit/angular-iqfbtv here change masking patter to this(mask="999 999 999 999") and try write four or more digit  thats not write after third digit.

**Comment by bncunha** [comment]
I had the same problem. I realized that, when the digit 9 is in beginning happen some bug. Try to put a required validator in your Form Control, and the mask like `mask="999 999 999 999"`

I updated the example: https://stackblitz.com/edit/angular-iqfbtv

**Comment by ValeriaKochegarova** [comment]
@emilalsgndr its not impossible to use mask like this mask="999 999 999 999", because always first numbers should be required mask="099 099 099 099".
