### ISSUE TITLE
Validation with ng.dirty with mask field getting dirty

### ISSUE THREAD

**Issue by Glaycow** [JsDaddy/ngx-mask#48]
I'm using anglar 5, in some input I'm using ngx-mask, it's doing some validations the inputs that contain the masks are getting dirty.

**Comment by NepipenkoIgor** [comment]
@Glaycow Could you provide code example

**Comment by vgildeev** [comment]
@NepipenkoIgor I'm having the same issue too with both ReactiveForms and Template-Driven forms, here is a live demo https://stackblitz.com/edit/ngx-mask-issue-48

**Comment by NepipenkoIgor** [comment]
@vgildeev Thanks for the demo, i will investigate this

**Comment by eatinasandwich** [comment]
I'm experiencing this issue currently. On version 8.1.6. The form loads and the masked control is immediately dirty.

**Comment by randallmeeker** [comment]
I'm also getting it in 8.1.7. I have to run a reset after the form loads.

**Comment by geissondaSilva** [comment]
39 / 5000
I also have this problem in 8.2.0

**Comment by ye-fujin** [comment]
one possible workaround might be to create a component with a control value accessor and an input with ngx-mask.
make the form control pristine by using markAsPristine in the writeValue method after setting the form control value
