### ISSUE TITLE
prefix is not working fine. 

### ISSUE THREAD

**Issue by musman92** [JsDaddy/ngx-mask#480]
if you try this input 
<input type="text" mask="00-00" prefix="" [showMaskTyped] = "true" />
when you click in put it give below error. it happens when i pass  prefix empty or null
![image](https://user-images.githubusercontent.com/8155538/58669535-02dd6280-8356-11e9-8f0e-e6778000e332.png)

**Comment by NepipenkoIgor** [comment]
@musman92 Please try latest version of ngx-mask. We tested and no errors . If you still have error please provide more information , config etc .
