### ISSUE TITLE
ngx-mask "percent.X" giving validation error while typing anything in the input

### ISSUE THREAD

**Issue by sanyam9999** [JsDaddy/ngx-mask#481]
For Version: 7.9.9

I am using "Percent.X" mask like this:
<input
          id="percentOwnership"
          name="percentOwnership"
          [(ngModel)]="ownershipDetail.percentOwnership"
          #percentOwnership="ngModel"
          type="text"
          mask="percent.2"
          sufix="%"
        />

And it is giving me error like this:
![Capture](https://user-images.githubusercontent.com/8327707/58700075-bed17880-83bc-11e9-818f-f933d7c5f1eb.PNG)

Moreover, the value I am getting in the model is without decimal point.
For example, if I type 1.2 in the input, the value I receive in the model is 12

Please look into the issue.

**Comment by saif-ssi** [comment]
To get decimal point try to add [dropSpecialCharacters]="false"

**Comment by sanyam9999** [comment]
> To get decimal point try to add [dropSpecialCharacters]="false"

It's working now. Thanks...

**Comment by NepipenkoIgor** [comment]
@sanyam9999 Good and @saif-ssi Thanks
