### ISSUE TITLE
NaN after FormControl.setValue

### ISSUE THREAD

**Issue by jefersonduwe** [JsDaddy/ngx-mask#482]
I have some fields with dot_separator and 4 decimals:
`<input matInput type="text" placeholder="Valor Produto" formControlName="pedido_produto" mask="dot_separator.4">`

If I type some values on them it works fine, but if in some point I have to set a value on them, a calculated field for example, the value turns to NaN.
`this.inputForm.get("pedido_produto").setValue(100.50)`

Actually, after that the displayed value is right, 100,50, but the value returned by the field turns to NaN. And everytime I type a number with decimals (using comma) the value becomes NaN.
Example on StackBlitz: https://stackblitz.com/edit/angular-rqenxd

**Comment by NepipenkoIgor** [comment]
@jefersonduwe Thanks . We will check

**Comment by NepipenkoIgor** [comment]
@jefersonduwe Which version of ngx-mask do you use ?

**Comment by NepipenkoIgor** [comment]
@jefersonduwe Please try version 7.9.10 . If you will have some problems you could reopen issue

**Comment by jefersonduwe** [comment]
Hi @NepipenkoIgor, sorry for not replying earlier.
The version 7.9.10 fixes the problem, thanks.

**Comment by Dok11** [comment]
I had same issue but it in my code was string (by condition) `patchValueToNumber()` to some fields of form
