### ISSUE TITLE
FormControl validation not working

### ISSUE THREAD

**Issue by efdevelopersp** [JsDaddy/ngx-mask#484]
FormControl validation not working when i type an invalid value.

I downloaded the ngx-mask-page source and got it running on localhost:4200. Got this warning on console too:

It looks like you're using ngModel on the same form field as formControl. 
    Support for using the ngModel input property and ngModelChange event with 
    reactive form directives has been deprecated in Angular v6 and will be removed 
    in Angular v7.
    
    For more information on this, see our API docs here:
    https://angular.io/api/forms/FormControlDirective#use-with-ngmodel

**Comment by NepipenkoIgor** [comment]
@efdevelopersp Hi . Сould you clarify ? Which problem you have when you type ? You couldn't input wrong symbol when you using mask .We could validate only length of the mask ( in simple situation and with common patterns )
