### ISSUE TITLE
dot_separator issue

### ISSUE THREAD

**Issue by alliance-ElenaKenten** [JsDaddy/ngx-mask#485]
Different separator symbols on setting and getting values.
E.g.: 
I type "12345,67" -> 
I see "12.345,67" -> 
I get from field "12345.67" -> 
I try to set back the data which I just get and see "1.234.567" -> 
to see (and get from field again) proper value, I have to change "12345.67" to "12345,67" while setting value to a field

**Comment by NepipenkoIgor** [comment]
@alliance-ElenaKenten Which mask did you use ?

**Comment by alliance-ElenaKenten** [comment]
Hello @NepipenkoIgor, 
ngx-mask: 7.9.6,
I use NgxMaskModule
mask="dot_separator.2" inside angular reactive form input

**Comment by NepipenkoIgor** [comment]
@alliance-ElenaKenten  Do You use copypast or  setValue from component when try set back data ?

**Comment by alliance-ElenaKenten** [comment]
@NepipenkoIgor I use setValue

**Comment by NepipenkoIgor** [comment]
@alliance-ElenaKenten could you try latest version of ngx-mask .  It's seems like works as expected
