### ISSUE TITLE
Module not found: Error: Can't resolve 'ngx-mask/app/ngx-mask/mask-applier.service'

### ISSUE THREAD

**Issue by eehaddad** [JsDaddy/ngx-mask#486]
Hello all, 

I'm on 7.9.9 and trying to use the service but keep running into this error message.

here is how I am attempting to implement it in the ts. 

`import { MaskApplierService } from 'ngx-mask/app/ngx-mask/mask-applier.service';

constructor ( private readonly maskService: MaskApplierService ){}

maskedString = this.maskService.applyMask('string', 'mask');`

I may be missing something obvious but I just can't see it.
Your feedback is greatly appreciated. thank you!

**Comment by fedotxxl** [comment]
Worked for me - https://github.com/JsDaddy/ngx-mask/issues/323#issuecomment-490484519
