### ISSUE TITLE
Cannot find name 'IConfig'.

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [JsDaddy/ngx-mask#489]
Using Angular 8

I'm facing this error message when I add these 2 lines on app.module.ts:

```
import {NgxMaskModule} from 'ngx-mask';
export const options: Partial<IConfig> | (() => Partial<IConfig>);
```

Error Message:
```

ERROR in ./src/app/app.module.ts 16:20
Module parse failed: Unexpected token (16:20)
You may need an appropriate loader to handle this file type.
| import { LoginPageComponent } from './login-page/login-page.component';
| import { NgxMaskModule } from 'ngx-mask';
> export const options;
| let AppModule = class AppModule {
| };
ℹ ｢wdm｣: Failed to compile.
    
    ERROR in src/app/app.module.ts(22,14): error TS1155: 'const' declarations must be initialized.
    src/app/app.module.ts(22,31): error TS2304: Cannot find name 'IConfig'.
    src/app/app.module.ts(22,57): error TS2304: Cannot find name 'IConfig'.
```

**Comment by NepipenkoIgor** [comment]
@danilobatistaqueiroz Hi. We will check

**Comment by mahendra-virtueinfo** [comment]
import {NgxMaskModule, IConfig} from 'ngx-mask';

export let options: Partial<IConfig> | (() => Partial<IConfig>);

**Comment by mahendra-virtueinfo** [comment]
ERROR in Error during template compile of 'AppModule'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'options'
    'options' is not initialized at app/app.module.ts(6,14).
src/app/app.module.ts(6,14): error TS1155: 'const' declarations must be initialized.

**Comment by Edmundoacosta** [comment]
Try with:

`export const options: Partial<IConfig> | (() => Partial<IConfig>) = {}`

it works for me

**Comment by mumvock** [comment]
> 
> 
> Try with:
> 
> `export const options: Partial<IConfig> | (() => Partial<IConfig>) = {}`
> 
> it works for me


After your suggestion, there are still two problems for me:
```
ERROR in src/app/app.module.ts(9,31): error TS2304: Cannot find name 'IConfig'.
src/app/app.module.ts(9,57): error TS2304: Cannot find name 'IConfig'.
```

**Comment by mahendra-virtueinfo** [comment]
Why this 'options' required can I know?

That is causing and stopping me to create a production build?

Thank you!

**Comment by jongbonga** [comment]
Input form not working

**Comment by PayalMonga** [comment]
This is working fine for me:
import { NgxMaskModule, IConfig } from 'ngx-mask'
export const options: Partial<IConfig> | (() => Partial<IConfig>) = {};

**Comment by kaushikparmar** [comment]
Following worked for me.

const options: Partial<IConfig> | (() => Partial<IConfig>) = {} = {};
