### ISSUE TITLE
dropSpecialCharacters cause matInput to be invalid

### ISSUE THREAD

**Issue by ljjolic** [JsDaddy/ngx-mask#492]
mat-form-field

   input matInput formControlName="phoneNumber" [required]="globalRequiredFlag"
        mask="000-000-0000" [dropSpecialCharacters]="false"
/mat-form-field

If i remove the "dropSpecialCharacters" flag every thing is fine. When I use it the formControl becomes invalid and the field is red

**Comment by NepipenkoIgor** [comment]
@ljjolic We will check.

**Comment by ljjolic** [comment]
Updated version -> problem resolved with new version
