### ISSUE TITLE
Mask doesn't let angular to fill input programmatically

### ISSUE THREAD

**Issue by caseyryan** [JsDaddy/ngx-mask#493]
Hi! 
I've got a tag like this:
`<textarea mask="00000000000000000"  id="set_acc" #set_acc required >{{ settlementAccount }}</textarea>`

As you can see it's filled in programmatically. But when I have mask applied to it like this, no text appears in the textarea. Even though the mask does work when I type in a text manually. And the field is filled in normally when no mask is applied to it. Also the mask works alsmost fine when I set it with a pipe like this:
`<textarea  id="set_acc" #set_acc required >{{ settlementAccount | mask:"00000000000000000" }}</textarea>`
But there is also a problem with this approach. The mask is only applied once, when the text is added. If I clean it and type a new text manually, no mask is applied to it

**Comment by isysenko** [comment]
@caseyryan you can use mask that way:
component.html
<textarea mask="00000000000000000" id="set_acc" [(ngModel)]="settlementAccount"></textarea>

**Comment by NepipenkoIgor** [comment]
@caseyryan please try latest version 9.1.0
