### ISSUE TITLE
[HiddenInput]=true, retains value even on resetting the reactive form

### ISSUE THREAD

**Issue by revshri** [JsDaddy/ngx-mask#494]
Hi,

I have a component which needs a mask of the format " XXX-XX-XXXX " and should be a secured input field, Hence I have used it as shown below.

```
Component.html

<form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
    <div class="form-group">
        <label>Enter</label>
        <input matInput [hiddenInput]=true mask="XXX-XX-XXXX" type="text" 
                    formControlName="enterValue" class="form-control" />
    </div>
    <div class="form-group">
        <label>Verify</label>
        <input matInput [hiddenInput]=true mask="XXX-XX-XXXX" type="text" 
                    formControlName="verifyValue" class="form-control" />
    </div>
    <div>
        <button class="btn btn-primary" type="submit">Submit</button>
        <button class="btn" (click)="reset()">Reset</button>
    </div>
</form>

Component.ts
reset() {
    this.registerForm.reset();
  }
```

Once the form is sent to reset(), all the formcontrol values are null, the properties like dirty : false,
pristine : true is all working fine. The issue here is the input control seems to clear visually, but when you start typing,  the previous value of hiddeninput is retained and the first digit of the value is not overridden. How to reset the [HiddenInput] value to prevent the retaining of HiddenInput's previous value?

Please note that I have tried restting the form controls manually to " null , '', ' ' " (null, emptystring, single space sting). And on removing [HiddenInput] and mask control from the input, the forms seems to working fine on reset(), that is the previous values are not retained.

Somebody, please help in sorting out this issue.

**Comment by Ignashevic** [comment]
Same issue here, in an angular project I use the [HiddenInput] attribute in a input text and same happened. Any suggestion?

**Comment by aemonge** [comment]
No suggestions yet ?

**Comment by Thegrep01** [comment]
@revshri will be fixed in ver. 8.1.1
