### ISSUE TITLE
Separator mask not working well with decimals

### ISSUE THREAD

**Issue by humpedli** [JsDaddy/ngx-mask#500]
Hello, currently I have the following problem:

`{{ 318.9 | mask: 'separator' }}` --> `318.` (Expected: **318.9**)
`{{ 318.9 | mask: 'separator.2' }}` --> `318.` (Expected: **318.9**)
`{{ 12318.9 | mask: 'separator' }}` --> `12 318.` (Expected: **12 318.9**)
`{{ 12318.9 | mask: 'separator.2' }}` --> `12 318.` (Expected: **12 318.9**)

Version: **ngx-mask@8.0.0**

What am I doing wrong?

**Comment by ValeriaKochegarova** [comment]
@humpedli could you provide a full example ?

**Comment by humpedli** [comment]
@ValeriaKochegarova what do you mean by full example? There are 4 examples in my previous message, please tell me what else should I put here, thank you.

**Comment by isysenko** [comment]
@humpedli Hi, will be fixed in the new mask version
