### ISSUE TITLE
How can I set minDate and max date in mask="d0/M0/0000 ?

### ISSUE THREAD

**Issue by muniraji2i** [JsDaddy/ngx-mask#501]

**Comment by ValeriaKochegarova** [comment]
@muniraji2i unfortunately, now its not impossible to set min/max date , but in future we will add. Thanks

**Comment by jain-isha02** [comment]
Can we set Max and Min date with NGX mask now ???

**Comment by abdulrahmanriyaz** [comment]
Hello, Can you please share how can we set the max date so that future dates are not allowed? 

Or in my case I want to restrict the user to not be able to add a future year
