### ISSUE TITLE
Input with mask is still dirty after reset form

### ISSUE THREAD

**Issue by objecteer** [JsDaddy/ngx-mask#502]
I used ngx-mask 8.0.0 with Angular 8.0.3 and Angular Material 8.0.1. My problem is that when I tried to clear form status by executing command form.reset, the status of input fields with mask are still dirty.

HTML
`<form testForm="ngForm">`
`  <mat-form-field>`
`    <input matInput mask="comma_separator.2" [(ngModel)]="value" name="value">`
`  </mat-form-field>`
`</form>`

TS
`resetForm() {
  testForm.reset({
    value: 0.0
  });
}`

**Comment by isysenko** [comment]
@objecteer You can clean fields that way:
component.html:
<form>
	<mat-form-field>
		<input matInput mask="comma_separator.2" [(ngModel)]="value" name="value">
	</mat-form-field>
</form>
<button (click)="resetForm()">btn</button>

component.ts
public value: string = '';
public resetForm(): void {
	this.value = '';
}

Is it a suitable solution?
