### ISSUE TITLE
It would be interesting to have an option so that the mask characters are not cleared by ngModel or formControl

### ISSUE THREAD

**Issue by FernandoZueet** [JsDaddy/ngx-mask#503]
It would be interesting to have an option so that the mask characters are not cleared by ngModel or formControl.

Example: `<input type='text'" [(ngModel)]="test" mask="(000) 000 00 00" >`

**output variable test:** 0000000000

**output proposed:** (000) 000 00 00

**Comment by NepipenkoIgor** [comment]
@FernandoZueet please use dropSpecialCharacters . You can read about this options in documentation
