### ISSUE TITLE
How would i do an email mask?

### ISSUE THREAD

**Issue by TimWarp** [JsDaddy/ngx-mask#51]
for example billy@whizz.com

**Comment by schirato** [comment]
Hi, when set **type=email** this is error is show **Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.** and may field in desktop is crashed after input any value and try remove value inputed.

**Comment by AlphaCreative** [comment]
This issue needs reopened.  We are experiencing the same problem as @schirato.
`
                                <input type="email" matInput placeholder="Email" required [(ngModel)]="email" mask="A*@A*.SSS" />`

**Comment by NepipenkoIgor** [comment]
@schirato You should use `type='text'` not email or number . This is normal behavior.

**Comment by NikolaiKaleda** [comment]
Hello! And how to add a point to the mailbox? For example, a test.test@test.com
