### ISSUE TITLE
After pasting a value on Safari in an input with mask the cursor jumps at the start.

### ISSUE THREAD

**Issue by bpopnikolov** [JsDaddy/ngx-mask#511]
When you paste value in an input with a mask on Safari the cursor jumps back at the start of the input. 

![](https://media.giphy.com/media/RLzhjIYPhyFHrO14d5/giphy.gif)

[demo](https://stackblitz.com/edit/angular-1c6shv)
angular version: 7.2
ngx-mask version: 8.0.1

**Comment by bpopnikolov** [comment]
I think that I have found the issue and the fix is in the following [PR](https://github.com/JsDaddy/ngx-mask/pull/520). Please consider approving it if the fix is the correct one.

**Comment by AndonMitev** [comment]
I have similiar problem. When i fill the input and try to set cursor somewhere in the middle of the entered value, cursor set on first character every single time

**Comment by bpopnikolov** [comment]
Yes, this bug exists on mobile. You are not able to place the cursor somewhere in the middle of the input.

I will investigate and try to open a PR but I feel like it is more complicated to fix. 

Can you open another issue for this pls? As it is not safari specific.

**Comment by isysenko** [comment]
@bpopnikolov Hi, will be fixed in the new version
