### ISSUE TITLE
dot_seperator is unable to handle short decimal numbers. (eg. 1.1 becomes 11)

### ISSUE THREAD

**Issue by MortPed** [JsDaddy/ngx-mask#512]
The issue is is mask-appliers.service line 109  `inputValue.indexOf('.') > 3`

**Comment by codephined** [comment]
I'm having a similar issue.  All of my model values strip out the decimal.
Mask instruction:
`mask="000.00"`
Input value:
`111.12`
Model value:
`11112`

Am I doing something wrong here?

**Comment by xakeppok** [comment]
Hi, give a real example

**Comment by xakeppok** [comment]
Hi, cant reproduce, give a real example
