### ISSUE TITLE
mask with readonly input

### ISSUE THREAD

**Issue by muratkurtun** [JsDaddy/ngx-mask#514]
Hi,
I try to use mask with readonly input.
`<mat-form-field>`
`<input class="detail" matInput type="text" placeholder="XXX" value="{{value?.value}}" mask="dot_separator.2">`
` </mat-form-field>`
but value  disappear.
How can use mask with readonly field?
Thanks.

**Comment by isysenko** [comment]
@muratkurtun I close this issue because you can find an example of using mask with readonly input in the referenced issue
