### ISSUE TITLE
Incorrect work of 'separator' mask

### ISSUE THREAD

**Issue by Zverit** [JsDaddy/ngx-mask#519]
1. Enter a few numbers.
2. Put the cursor in the middle
3. Enter a point

Expected result: the point is not entered

Actual result: a point appears. Input becomes incorrect: when entering numbers at the beginning of the input, characters are erased at the end of the input.

![thousand_separator_issue](https://user-images.githubusercontent.com/1945239/61203724-e32aaf80-a6f3-11e9-88df-630c73624b53.png)

**Comment by xakeppok** [comment]
If u need dots try dot_separator

**Comment by Zverit** [comment]
No, I don’t need extra points in random place in 'separator'

**Comment by xakeppok** [comment]
Hi, try new version that will come out soon
