### ISSUE TITLE
Runtime exception when building AOT

### ISSUE THREAD

**Issue by pfrendo** [JsDaddy/ngx-mask#52]
A `.map` of undefined on `maskSpecialCharacters` when trying to create a regex in the constructor.

**Comment by LimarenkoDenis** [comment]
@pfrendo can you provide the example?

**Comment by caducabral** [comment]
When setting up a variable in constructor:

`
public _mask: string;

constructor() {
        this._mask = '000.000.000';
 }`

then in html using like that: 

`<input [mask]='_mask' />`

Everything is correct in the confs files like .module.ts. ng serve ok. But when do ng build --prod im having the same problem of @pfrendo. 

Version of Angular-cli is 1.4.9, Typescript: 2.5.3 and ngx-mask: 2.1.11

**Comment by pfrendo** [comment]
It seems to be like the default configuration isn't being picked up

**Comment by pfrendo** [comment]
@LimarenkoDenis I am working on a fix for this

**Comment by pfrendo** [comment]
PR HERE @LimarenkoDenis  @caducabral 

https://github.com/JsDaddy/ngx-mask/pull/53

**Comment by NepipenkoIgor** [comment]
Done
