### ISSUE TITLE
Pin the mask to the right

### ISSUE THREAD

**Issue by jefersonduwe** [JsDaddy/ngx-mask#523]
Is there a way to "Pin the mask to the right"? Allowing the following behaviour:

Typed | Displayed
------- | -----------
1 | 0,01
12 | 0,12
123 | 1,23
1234 | 12,34
12345 | 123,45
123456 | 1.234,56

The mask preferably would be "dot_separator.2".
And if possible it would be good to always show the decimals after the comma, even when they end with zeros.

**Comment by NepipenkoIgor** [comment]
@jefersonduwe  Thank you for using ngx-mask. For pin mask to right you could use css  `    text-align: right;` . If you have another issues , bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
