### ISSUE TITLE
Issue in french language with the comma and point in float

### ISSUE THREAD

**Issue by hamzaDeveloppementWeb** [JsDaddy/ngx-mask#524]
Hello ! 
 I've been using your tools that I find very practical but I'd like to know if there's a way to bind the decimal separator to the app localization somehow ? (So that an english speak will use a dot and a french one a comma)
It'd help me a lot.

Thanks !

**Comment by AlexeyDolya** [comment]
@hamzaDeveloppementWeb 
at the moment, we did not plan to implement such functionality, perhaps this will appear in new versions
