### ISSUE TITLE
Wrong cursor position

### ISSUE THREAD

**Issue by AndonMitev** [JsDaddy/ngx-mask#527]
When i fill the input and try to set cursor somewhere in the middle of the entered value, cursor set on first character every single time
**Browsers: Chrome**

**Comment by xakeppok** [comment]
Hi, cant reproduce. Give a real example

**Comment by AndonMitev** [comment]
Where you are testing? Envoirment?

**Comment by AndonMitev** [comment]
Reproducible with latest version of the mask and check IE11

**Comment by koopman-mark** [comment]
I am having the same issue.  Just added ngx-mask to my project today.  It is recreatable on the demo site: https://jsdaddy.github.io/ngx-mask-page/main#show-mask

Go to the "showMaskTyped (boolean)" example, enter a value, and press tab to leave the input field.  Then click on the right side of the input field, and the cursor briefly appears on the right side, and then jumps to beginning of the field.
