### ISSUE TITLE
Use showMaskTyped but hide pattern

### ISSUE THREAD

**Issue by AndonMitev** [JsDaddy/ngx-mask#528]
Hello i have following input placeholder __-_______. This input will be filled only with digits so i use 00-0000000. After my third digit rest of them come optional so i try following pattern 00-00?0?0?0?0?0? and all working well except i have showMaskTypes to true and placeholder becomes __-__?_?_?_?_?_?. What is the workaround for this behavior

**Comment by Thegrep01** [comment]
@AndonMitev Hi! for now showMaskTyped not working with optional characters

**Comment by Saucistophe** [comment]
It is now! https://github.com/JsDaddy/ngx-mask#placeholdercharacter-string

**Comment by NepipenkoIgor** [comment]
@AndonMitev @Saucistophe Hi Thank you for using ngx-mask . If issue still actual please  recreate issue with new template .
