### ISSUE TITLE
Not able to delete mask placeholder in IE

### ISSUE THREAD

**Issue by AndonMitev** [JsDaddy/ngx-mask#529]
Browsers : **IE11**
I have following input state 22-22.
I can delete last two 2 but once i reach **-** backspace is not working just in **IE11**

**Comment by NepipenkoIgor** [comment]
@AndonMitev  Hi . Thank you for using ngx-mask. Currently we not focusing on IE as a rest of community. If issue critical for you please recreate it with new issue template
