### ISSUE TITLE
Shift and left arrow key is not selecting

### ISSUE THREAD

**Issue by AndonMitev** [JsDaddy/ngx-mask#530]
I have following input state 22-22. When i try to select from **right** to **left** with shift and left arrow key, just skip char after char but do not select them

**Comment by isysenko** [comment]
@AndonMitev What browser are you using?

**Comment by AndonMitev** [comment]
Reproducible on All

**Comment by isysenko** [comment]
@AndonMitev Please make sure you use the latest mask version and use it correct, because this bug isn't reproducible.

**Comment by rvmladenov** [comment]
8.0.5 seems to fix the issue
