### ISSUE TITLE
Toggle 'Secure Input' property on blur/focus

### ISSUE THREAD

**Issue by ChaudhryAtif** [JsDaddy/ngx-mask#535]
`<input matInput placeholder="Secure input" [hiddenInput]="true" mask="XXX-XX-0000">`

This will obscure/secure the input as its typed and show just the last 4.

Is it possible to enable secure input on blur, and disable it on focus?

I tried using `(blur)` event and `#elementReference` property to toggle hiddenInput, but that didn't work.

**Comment by aemonge** [comment]
Or as an alternative can we maybe implement a delayed change for the masked values

**Comment by AlexeyDolya** [comment]
@ChaudhryAtif 
We did not plan to implement this functionality, since this is a rather special case. It would be more practical to make this implementation directly in your component.
