### ISSUE TITLE
dot_separator problem when using string type

### ISSUE THREAD

**Issue by viniciusi** [JsDaddy/ngx-mask#536]
[x] Bug
ngx-mask v8.0.2
Angular v8.2.0

In version 7.9.10 I had a problem with number between 1,0 and 999,99 using dot_separator.2.
The problem occurred while trying  to set a value using a string type.

eg.
Input: 1.11 Masked: 111
Input: 11.11 Masked: 1.111
Input: 111.11 Masked: 11.111

In the latest version (8.0.2) the problem is with number between 100,01 and 999,99.

eg.
Input: 1.11 Masked: 1,11
Input: 11.11 Masked: 11,11
Input: 111.11 Masked: 11.111

Example:
[https://stackblitz.com/edit/angular-6ud5xt](https://stackblitz.com/edit/angular-6ud5xt)

**Comment by hunterTR** [comment]
comma_separator.2  doesn't mask as expected as well. 
Input is : 1000.5
expected : 1,000.50 string
current output: 1,000.5 

if I convert it manually to string by myself. Then it keeps commas when form is submitted.

**Comment by arman-g** [comment]
> 
> 
> comma_separator.2 doesn't mask as expected as well.
> Input is : 1000.5
> expected : 1,000.50 string
> current output: 1,000.5
> 
> if I convert it manually to string by myself. Then it keeps commas when form is submitted.

I confirm this in version 8.0.3.
Input is : 10.50
expected for a view : 10.50
expected as a value : 10.5
Output for a view : 10.5 - not correct.

`<input type="text" class="form-control" formControlName="amountDue" id="amountDue" prefix="$" mask="comma_separator.2" placeholder="$" />`

**Comment by isysenko** [comment]
@viniciusi, @arman-g Hi, bug will be fixed in the new mask version.
Input is : 10.50
Output for view : 10.50
Output as a value : 10.50

**Comment by enricooliva** [comment]
I observe this strange behavior when using mask = dot_separator type = text
Input 15.000,99
press delete 15.000,9
press delete 15.000,
press delete 1.500, 
press delete 1,50 <---error

**Comment by andrii-zozulia** [comment]
> comma_separator.2 doesn't mask as expected as well.
> Input is : 1000.5
> expected : 1,000.50 string
> current output: 1,000.5
> 
> if I convert it manually to string by myself. Then it keeps commas when form is submitted.

@isysenko mask pipe works the same (ngx-mask@8.0.6)
`{{ num | mask: 'comma_separator.2' }}

**Comment by Thegrep01** [comment]
can not reproduce in 8.0.9
