### ISSUE TITLE
Form becomes valid (on first character) even though mask is partially matched

### ISSUE THREAD

**Issue by ChaudhryAtif** [JsDaddy/ngx-mask#537]
If the mask is `'000-00-0000`, then the form should stay invalid until I type all 10 characters, but it becomes valid on first character entry. Shouldn't it show mask error until it is matched? I don't see the error at all.

https://stackblitz.com/edit/angular-hdirbj?file=src/app/app.component.html

**Comment by isysenko** [comment]
@ChaudhryAtif Please update mask version to latest. You use 6.1.2 but this validation isn't available in versions earlier than 7.6.0

**Comment by ChaudhryAtif** [comment]
In my code, I am using 7.9.10, but I didn't realize demo had 6.1.2.

I'll do some local testing and report back. Thank you for the reply!
