### ISSUE TITLE
comma_separator.2 missing the last 0 after the decimal point

### ISSUE THREAD

**Issue by arman-g** [JsDaddy/ngx-mask#538]
ngx-mask version 8.0.3.
angular 7.2.15

Input is : 10.20
expected for view : 10.20
expected as a value : 10.2
Output for view : 10.2 - incorrect.

This is happening only if the last number after the decimal point is 0.

`<input type="text" class="form-control" formControlName="amountDue" id="amountDue" prefix="$" mask="comma_separator.2" placeholder="$" />`

**This is also true for** mask="0*.00"
Input is : 100.50
expected for view: 100.50
expected as a value: 100.5
Output for view: 100.5 - incorrect
Output as a value: 100.50 - incorrect but its not a big issue.

`<input type="text" class="form-control" formControlName="amountDue" id="amountDue" prefix="$" mask="0*.00" [dropSpecialCharacters]="false" placeholder="$" />`

**Comment by Thegrep01** [comment]
@arman-g Hi will be fixed in the new version

**Comment by dushyant** [comment]
Is this really fixed in latest version 11.1.4?
