### ISSUE TITLE
How to install ngx?

### ISSUE THREAD

**Issue by rever96** [JsDaddy/ngx-mask#541]
I saw the demo https://jsdaddy.github.io/ngx-mask-page/mask-component and it's working perfectly.
I wanna use it! lets follow the npmjs instructions: https://www.npmjs.com/package/ngx-mask.
`export const options: Partial<IConfig> | (() => Partial<IConfig>);`
error: "const must be init", that's right.... nobody talk about that. what i'm missing?
my setup:
npm 6.8.0
Angular CLI: 7.3.9
Node: 8.12.0
OS: linux x64
Angular: 7.2.15

**Comment by FrolovIgor** [comment]
I have same problem
not sure if this is correct, but I just initialized the variable as null and it worked

export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

**Comment by Thegrep01** [comment]
duplicate #542
