### ISSUE TITLE
'const' declarations must be initialized. (export const options: Partial<IConfig> | (() => Partial<IConfig>);)

### ISSUE THREAD

**Issue by rkodi** [JsDaddy/ngx-mask#542]
on app.module.ts where the declaration 

export const options: Partial<IConfig> | (() => Partial<IConfig>);
'const' declarations must be initialized.

on this link, they have assigned it to be null, would this work?

export const options: Partial | (() => Partial) = null;

https://github.com/JsDaddy/ngx-mask/issues/128#issuecomment-509493143

**Comment by bostondevin** [comment]
> export const options: Partial | (() => Partial) = null;
> 
> fix the issue

I get this errror with that

Generic type 'Partial' requires 1 type argument(s).

**Comment by Chanonsersa** [comment]
@bostondevin 

> > export const options: Partial | (() => Partial) = null;
> > fix the issue
> 
> I get this errror with that
> 
> Generic type 'Partial' requires 1 type argument(s).

change to

export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

**Comment by victoramaro88** [comment]
export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

**Comment by victoramaro88** [comment]
export const options: Partial'<'IConfig'>' | (() => Partial'<'IConfig'>') = null;

just remove this: " ' " in "<" and ">"
