### ISSUE TITLE
how to mask the full input but the last four number

### ISSUE THREAD

**Issue by aemonge** [JsDaddy/ngx-mask#546]
I would like to mask all the numbers but the last two. Like the following example:
```
IN:
123451234
    *****1234
12341234
   ****1234
```

I've tried the following unsuccessfully:

              <input matInput 
                mask="\(X\)*0000"
                [hiddenInput]="true"

              <input matInput 
                mask="X*0000"
                [hiddenInput]="true"

              <input matInput 
                mask="X{,}0{4}"
                [hiddenInput]="true"

**Comment by AlexeyDolya** [comment]
@aemonge try <input [hiddenInput]="true" mask="XXXXX00">

**Comment by aemonge** [comment]
@AlexeyDolya that works with a seven digit input. I mean, if you input `12345678` you get the expected last two numbers to be the only ones visibles. 

But, if you input a six o five digit number `12345`; you won't get the expected behaviour; you wouln't see the last two digits, it will be masked.

The issue/improvment is to be able to apply mask from right to left, the same way is now working from left to right.

**Comment by reinaldorauch** [comment]
Not sure if I can add this request to this but if you also make the number with separators mask works like this:

Number: 123,56
mask="separator.2"
thousandSeparator="."

1st digit: 1
input value: 0,01

2nd digit: 2
input value: 0,12

3rd digit: 3
input value: 1,23

and so on until complete the 123,56 formatted number

**Comment by niknokseyer** [comment]
Were you able to get something working for this @aemonge?

**Comment by aemonge** [comment]
Yes, but unfortunately I don't have the working code

**Comment by ArturV93** [comment]
Not the best solution, but you can use OR statement for mask.

<input [hiddenInput]="true" mask="XXX00 || XXXX00 || XXXXX00">

**Comment by moliveiragranja** [comment]
> Not the best solution, but you can use OR statement for mask.
> 
> <input [hiddenInput]="true" mask="XXX00 || XXXX00 || XXXXX00">

Perhaps the only solution, specially if you can´t update the package. And very readable for future mantainers.
