### ISSUE TITLE
How to use ngx-mask to mask input with custom symbol in case of secure input or in general use?

### ISSUE THREAD

**Issue by pg99696** [JsDaddy/ngx-mask#547]
I was trying to following the documentation to implement custom pattern and custom symbol to implement mask but not able to succeed. Please help in resolving this issue.

**Comment by NepipenkoIgor** [comment]
@pg99696 Hi. Сould you provide more complex example , maybe some snippet or full code?

**Comment by pg99696** [comment]
@Nepipenkolgor, Hi.

Like I want to mask SSN with custom symbol
123-45-6789 -> XXX-XX-XXXX
while giving input to the field.

**Comment by pg99696** [comment]
I was doing 
<input type="text" mask="000-00-000" [pattern]="customPattern">

In component file:
CustomPattern = {'0': {pattern: new Pattern('/d'), symbol: 'X'}};

Please let me know if I am doing anything wrong

**Comment by salcedobrain** [comment]
Hello @pg99696, I hope you are very well today. I think you have to set your pattern like this `pattern: new RegExp('\\d')` and your custompattern var must be equal, I noticed you have `customPattern` on the input but in component you have `CustomPattern`

**Comment by pg99696** [comment]
Hello @salcedobrain , that was wrong typed.
Please find below the correct way of my implementation.
html file:
`<input type="text" mask="000-00-000" [pattern]="customPattern">`
component file:
`customPattern = {'0': {pattern: new Pattern('\\d'), symbol: 'X'}};`

**Comment by codernew02** [comment]
Is there any resolution for above? Having similar issue, unable to apply symbol for secure grid column value using pattern. I have tried to use customMask with pattern to apply symbol but unable to get symbol working
public customMask: [string, pattern];

  public pattern: pattern = {
    X: {
        pattern: new RegExp('\\d'),
        symbol: '*',
    },
  };  

In constructor : this.customMask = ['XXX-XX-XXXX', this.pattern];
Html : <td mat-cell *matCellDef="let element"><span>{{element.secureInput | mask: customMask}}</span></td>

**Comment by ShirleyLii** [comment]
For anyone still has the same issue: 

html file:
`<input type="text" mask="000-00-000" [pattern]="customPattern">`
component file:
`customPattern = {'0': {pattern: new RegExp('\\d'), symbol: 'X'}};`

And do not forget to include FormControl from @angular/forms; Input from @angular/core;  
Also in the module file, you gotta include the formsModule, reactiveFromsModule.

**Comment by j-bee** [comment]
@ShirleyLii it's not working for me. Can you paste a full example?

**Comment by j-bee** [comment]
@salcedobrain  any news about when you plan to fix/implement this? It seems that only the hard-coded custom patterns work, but trying to implement your own fails. Or if I'm wrong please provide a minimum working example via Plunkr or something similar.

**Comment by j-bee** [comment]
So I just wasted around 3 hours trying to get this to work...
What you need is:
component.ts:
` pattern = {
    Y: {
      pattern: new RegExp('\\d'),
      symbol: 'X'
    }
  };`

component.html:
<input type="text" [patterns]="pattern" mask="(YYY-YYY-YYY)" [hiddenInput]="true">

**[hiddenInput]="true" is the key part that was missing in the above explanations and in the documentation.**
JSDaddy - please update README so that no more people get confused about this!

**Comment by ajaynarang** [comment]
> So I just wasted around 3 hours trying to get this to work...
> What you need is:
> component.ts:
> ` pattern = { Y: { pattern: new RegExp('\\d'), symbol: 'X' } };`
> 
> component.html:
> `<input type="text" [patterns]="pattern" mask="(YYY-YYY-YYY)" [hiddenInput]="true">`
> 
> **[hiddenInput]="true" is the key part that was missing in the above explanations and in the documentation.**
> JSDaddy - please update README so that no more people get confused about this!

Still not working for me, I don't see it is hiding input values. Additionally, after clearing the input when you start entering input again it shows previous values.

<mat-form-field  class="w-100 mt1 f4 fw3 input-form-field" [ngClass]="{'mb2': nameFormGroup.get('ssn').invalid}">
			<input
				matInput
				formControlName="ssn"
				#ssn
				type="text"
				placeholder="Social Security Number"

				class="fs-block"

				max="10"
				[patterns]="ssnPattern"
				mask="YYY-YY-YYYY"
				[showMaskTyped]="true"
				[hiddenInput]="true"


			/></mat-form-field>

ssnPattern = { Y: { pattern: new RegExp("\\d"), symbol: "X" } };

**Comment by NepipenkoIgor** [comment]
@ajaynarang @j-bee @pg99696 @ShirleyLii Hi . Thank you for using ngx-mask . Seems like a problem relative to RegExp class . You should pay attention that if you use literal regexp will look `/\d/` and if you use class `new RegExp("\\d") ` and finally `ssnPattern = { Y: { pattern: new RegExp("\\d"), symbol: "X" } };`

**Comment by russcarver** [comment]
This works great! Except when I need a variable number of digits. I need a secure/hidden mask that can be from 1-17 digits.

Here's what I've tried (non-working):

```
<input [patterns]="accountNumberPattern" [hiddenInput]="true" mask="A*">
                 
accountNumberPattern: { A: { pattern: new RegExp('\\d'), symbol: 'X' } }
```

It definitely allows only digits (and more than 17...) but only the first one gets converted to an 'X'

Any ideas?

I don't relish having to do this:

```
<input [patterns]="accountNumberPattern" [hiddenInput]="true" mask="A | AA | AAA | AAAA | ...">
```

**Comment by SafNaaz** [comment]
how to make masking and unhiding using eye icon make work together?

<input [patterns]="accountNumberPattern" [hiddenInput]="true" mask="000-00-0000">
                 
accountNumberPattern: { 0: { pattern: new RegExp('\\d'), symbol: '*' } }

this works fine. 

problem is suppose 

1, I input 123-4 (masked way), on clicking on eye icon, its showing only 4

2, I input 123-45 (masked way),on clicking on eye icon, all fine

3, I input 123-45-6 (masked way), on clicking on eye icon, its showing only 6

3, I input 123-45-67 (masked way), on clicking on eye icon, all good

just for the 2 cases, its behaving weird. might be something to do with separator. but what to do?
