### ISSUE TITLE
question: How to include some special character in the unmasked value?

### ISSUE THREAD

**Issue by diosney** [JsDaddy/ngx-mask#549]
Right now I think that all special values are stripped from the unmasked value or all are allowed, according with `specialCharacters` and `dropSpecialCharacters` settings, but I need that some special characters are escaped in the final unmasked value, and that all the others are filtered.

Example:

mask: +0 (000) 000 000
entered value (with mask): +1 (123) 321 123
unmasked value: 1123321123

What I need: +1123321123 (only + will be allowed to be escaped).

Is there a way to accomplish this now?

**Comment by Thegrep01** [comment]
@diosney You can add + symbol directly in component, our mask cant give you such functionality

**Comment by diosney** [comment]
@Thegrep01 Can you provide an example? I tested several ways both with `specialCharacters` and `dropSpecialCharacters` and either was all or nothing with special characters (both + and spaces or nothing).

**Comment by diosney** [comment]
I ended up using https://www.npmjs.com/package/angular-imask, they have this special syntax to set hardcoded static values encased between `{}`, which solves the  issue.

However, it would be nice to know how to accomplish that with this library for the other people that stumble into this.

**Comment by AymenElmehdhaoui** [comment]
`<input type="text"
                 [specialCharacters]="[ '+', '(' , ')', ' ' ]"
                 [dropSpecialCharacters]="['(' , ')', ' ']"
                 [showMaskTyped]="true"
                 mask="+0 (000) 000 000" />`
