### ISSUE TITLE
Percentage not limited by 100%

### ISSUE THREAD

**Issue by ragmar** [JsDaddy/ngx-mask#550]
Latest version.

`<input [(ngModel)]="percentage" [dropSpecialCharacters]="false" mask="percent.2" suffix="%">`

The following code is doing what I want. Which limit the user to '100%'. But if you write something like '12.34%' Then move the cursor before the '2', after the '.' and type any number, the percentage will be '1256%' which is higher than 100%. I'm expecting not to write the dot or at least limit in 100%

also this happens if you insert a lot of 0s first and then move the cursor and start changing them.

**Comment by Thegrep01** [comment]
@ragmar Hi! will fixed in the new version
