### ISSUE TITLE
Mask change bug, shift not cleared

### ISSUE THREAD

**Issue by wazio** [JsDaddy/ngx-mask#551]
When I'm changing mask from 'AAAA AAAA AAAA' to 'AA AAAA AAAA' after filling input with some value, MaskApplierService._shift Set isn't cleared which results in letters skipped with previous pattern {5, 10}.

If anyone is interested my temporary local solution looks something like that:
I create directive with MaskDirective injection and clear set manually before setting new mask.
```typescript
@Directive({
  selector: 'input[customMask]',
})
export class CustomMaskDirective implements OnInit {
  @Output()
  public customMask: EventEmitter<string> = new EventEmitter<string>();

  constructor(@Host() @Optional() private maskDirective: MaskDirective) {}

  public ngOnInit(): void {
    this.emitMask(initialMask);
  }

  @HostListener('input', ['$event.target.value'])
  public handleInput(value: string): void {
    // choosing mask based on value

    this.emitMask(mask);
  }

  private emitMask(value: string): void {
    // checking if mask has changed

    (this.maskDirective['_maskService']['_shift'] as Set<number>).clear();
    this.customMask.emit(value);
  }
}
```

And in HTML
```html
<input [mask]="inputMask" (customMask)="inputMask = $event" />
````

**Comment by NepipenkoIgor** [comment]
@wazio Thank you for using ngx-mask. It seems like everything works as expected https://stackblitz.com/edit/angular-ivy-mask-bbq864?file=src%2Fapp%2Fapp.component.ts. When mask changed we cut latest letters
