### ISSUE TITLE
Repeat a group of 4 characters with a space between groups

### ISSUE THREAD

**Issue by SenneWouters** [JsDaddy/ngx-mask#552]
Version 8.0.3

I want to create a mask for my input field where the user can enter characters (letters and numbers), and per 4 characters a whitespace should be added. 
Difficulty is that i don't know beforehand how many characters the user will type. So i need some kind of repeating group where a space is added after every 4 characters. 
Is this possible?

**Comment by Thegrep01** [comment]
@SenneWouters now you can't create such mask

**Comment by mwaldheim** [comment]
Can u add this Feature? I need it too for formating international banknumbers (IBAN)
