### ISSUE TITLE
8.0.4 requires Angular 6

### ISSUE THREAD

**Issue by internalsystemerror** [JsDaddy/ngx-mask#553]
During the update for ngx-mask dependencies to Angular 8.2.4, the peer dependencies were set to >=8.2.4.

https://github.com/JsDaddy/ngx-mask/commit/1312f2941699872224fe5e536f30cc46d7b16552#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 This commit however, changes it to be the fixed version 6.0.0 which causes warnings during install:
![image](https://user-images.githubusercontent.com/1626298/64336317-8ef5ca80-cfd4-11e9-879e-bea43ac7972d.png)

I believe the attempt was to set the peerdeps to >=6.0.0.

**Comment by blondie63** [comment]
there's also problems on releases page: https://github.com/JsDaddy/ngx-mask/releases
here you can see very old versions and not last 8.0.4

**Comment by Thegrep01** [comment]
@internalsystemerror  #555

**Comment by internalsystemerror** [comment]
ty
