### ISSUE TITLE
ngx-mask isn't taking the regex pattern.

### ISSUE THREAD

**Issue by sunnyrai31** [JsDaddy/ngx-mask#554]
**html:** 
`<input type="text" class="form-control" mask="A{100}" [patterns]="customPatterns">`
**component.ts**
`customPatterns = {'A': { pattern: new RegExp('\[^a-z\]')}};`
validating only one character input.length {100} got ignored.
working in online editor but not in code base with same implementation.
trying in version **"ngx-mask": "6.1.2",**
because of the mask value.
any suggestion will be appreciated.
Thanks.

**Comment by isysenko** [comment]
@sunnyrai31 Hi, you need to update mask version to latest. And you can use mask that way:
html:
`<input matInput mask="A{100}" [patterns]="customPatterns" [formControl]="formCntrl" />`
component.ts:
`    public customPatterns = {'A': { pattern: new RegExp('\[a-z\]')}};`
I should note that for validation work you need to add form control
