### ISSUE TITLE
How to provide IP address mask in CIDR notation? 

### ISSUE THREAD

**Issue by anvial** [JsDaddy/ngx-mask#56]
Hi, 

Can you provide an expample of IP address CIDR notation mask? 

Thank You! 

PS: For example: 192.168.1.17/24

**Comment by NepipenkoIgor** [comment]
@anvial hi, you could use for example `<input mask="000.000.0.00/00" >`

**Comment by anvial** [comment]
@NepipenkoIgor, your example is valuable only for certain IP. I think ngx-mask can format the IP adresses in general. 

But nevertheless, thank you for reply.
