### ISSUE TITLE
Optional Numbers Not working in Mask

### ISSUE THREAD

**Issue by Friesens-JeffreyR** [JsDaddy/ngx-mask#561]
I'm trying to configure a phone number mask that allows for an optional extension.
I started with 
`<input name="Fax" type="text" mask="(000) 000-0000 999"  class="form-control form-control-sm"  />`

This properly validates the number (555) 555-5555, however when I try to type the extension the first digit of the extension flashes briefly and then disappears.

I also tried my desired state
`<input name="Fax" type="text" [specialCharacters]="[ '(',')',' ', '-', 'E']" mask="(000) 000-0000 E999" class="form-control form-control-sm" />`
which has similar behavior, but does properly add the E.

If I change it to 
`<input name="Fax" type="text" [specialCharacters]="[ '(',')',' ', '-', 'E']" mask="(000) 000-0000 E000" class="form-control form-control-sm" />`

Then extensions work perfectly, however a number without an extension won't work (555) 555-5555.

This feels like a bug, or am I missing something obvious?

**Comment by AndonMitev** [comment]
As well AAAA pattern is required as well

**Comment by isysenko** [comment]
@AndonMitev please read documentation. A - letters (uppercase or lowercase) and digits, it is not optional

**Comment by isysenko** [comment]
@Friesens-JeffreyR Hi, will be fixed in version 8.0.8

**Comment by Friesens-JeffreyR** [comment]
@isysenko That is great news.
