### ISSUE TITLE
Mask of comma_separator.0 allows spaces and other special characters

### ISSUE THREAD

**Issue by ColinMorris83** [JsDaddy/ngx-mask#562]
If I have the mask as comma_separator.0 and start typing in an empty field, it allows unlimited number of spaces, and other special characters can be typed like Alt and 2 on a mac keyboard which will display the euro sign in the input box. This doesn't seem right, surely comma_separator should only accept numbers?

**Comment by isysenko** [comment]
@ColinMorris83 Hi, will be fixed in the new mask version

**Comment by ColinMorris83** [comment]
Thanks, any idea when this will get released?
