### ISSUE TITLE
Ivy compile: this._maskValue is undefined

### ISSUE THREAD

**Issue by ccazacu** [JsDaddy/ngx-mask#565]
If I import the ReactiveFormsModule module before NgxMaskModule, I get this error:
```
ERROR TypeError: "this._maskValue is undefined"
     validate ngx-mask.js: 815
```

only when I compile with Ivy
I can't reproduce in stackblitz because I can't activate Ivy
Clone this code and activate Ivy
https://stackblitz.com/edit/angular-4bd33u

**Comment by douglaslaiber** [comment]
Yes, I updated Angular and started getting this error

**Comment by Thegrep01** [comment]
@ccazacu try latest version of mask
