### ISSUE TITLE
Erasing input when using comma/dot_separator leaves the '.' o ',' and can't be deleted

### ISSUE THREAD

**Issue by ivandres** [JsDaddy/ngx-mask#567]
Hi,

I am using dot_separator.2 and comma_separator.2 in different text fields.

I noticed that if I enter: 2222.22
Shows the correct number: 2,222.22
But then if I delete by pressing the Backspace/Delete key it leaves the '.' or ',' depending on the mask setting I am using.

![Capture](https://user-images.githubusercontent.com/4332735/65469899-16499780-de37-11e9-8e8e-4157136025e0.PNG)

The cursor stay at the beginning of the input. If I move the cursor to be after the ',' and press the backspace/delete key I get the following error:

![Capture](https://user-images.githubusercontent.com/4332735/65469963-4ee97100-de37-11e9-901c-c77ff252ecf8.PNG)

Version: 8.0.6

**Comment by ColinMorris83** [comment]
Yep am noticing lots of strange behaviour with the demo page on the dot_seperator mask. 
e.g. type 222222 will display as 222.222 
Then move cursor to beginning and delete the first two numbers, value then changes to 2,222 so a comma goes in instead of a dot.

**Comment by ivandres** [comment]
You are right, also a bug

**Comment by ColinMorris83** [comment]
> You are right, also a bug

May be worth retesting once latest release comes out as there have been some changes around the seperator masks that might fix some of this.

**Comment by isysenko** [comment]
@ivandres Hi, your issue will be fixed in the new mask version
@ColinMorris83 You need open another issue for bug that you noticed

**Comment by ivandres** [comment]
@isysenko thank you!

**Comment by isysenko** [comment]
@ColinMorris83 your issue also will be fixed in the new mask version
