### ISSUE TITLE
Special character not deleted if specified in custom pattern

### ISSUE THREAD

**Issue by dintecom** [JsDaddy/ngx-mask#571]
Special characters are not removed with Backspase if specified in a custom pattern. Сursor jumps over it instead of deleting it.
![ngx-mask](https://user-images.githubusercontent.com/29774394/65816526-c9fdaf00-e1ca-11e9-9c9f-f85e0f644cda.gif)
This raises an error: `Cannot read property 'toString' of undefined`.

An error occurs on a line when `el.selectionStart` is `0` and `this._inputValue[-1]` is `undefined`:
https://github.com/JsDaddy/ngx-mask/blob/a2da23e07df34fdb6096155dd388c683565f768e/src/app/ngx-mask/mask.directive.ts#L294

Example [StackBlitz](https://stackblitz.com/edit/angular-maa4kj).
There is also an example of special characters not working correctly in prefix, but I'm not sure if this is the same problem.

Both problems appeared in ngx-mask version `8.0.6`, version `8.0.5` is working fine.

**Comment by aaa123eee** [comment]
Same problem with same version, 8.0.5 is ok

**Comment by isysenko** [comment]
@dintecom, @aaa123eee Hi, will be fixed in the new mask version
