### ISSUE TITLE
Mask fails when using not special character as a suffix

### ISSUE THREAD

**Issue by dintecom** [JsDaddy/ngx-mask#576]
When using non-special characters as a suffix, they are duplicated when entering (or deleting) new characters.
![ngx-mask](https://user-images.githubusercontent.com/29774394/66073464-0f9cdd80-e525-11e9-8d55-9d85a252921e.gif)

Partially, the problem disappears if a mask of optional characters (`optional: true`) is used and the first suffix character is special. But when you try to delete a special suffix character with Delete (not Backspace), non-special suffix characters are duplicated.
![ngx-mask-2](https://user-images.githubusercontent.com/29774394/66074178-9dc59380-e526-11e9-95e3-04eef96deeb3.gif)

An example of [StackBlitz](https://stackblitz.com/edit/angular-aqfuen)

**Comment by isysenko** [comment]
@dintecom Hi, will be fixed in the new mask version
