### ISSUE TITLE
Limit the digits in thousands separator

### ISSUE THREAD

**Issue by hydra324** [JsDaddy/ngx-mask#577]
Currently there is no way to limit the number of digits before the decimal point in thousands separator which is mask = comma_separator.2

For example: 12,333.56 should be allowed to type in but 122,333.56 and 1,222,333.56 should not be allowed.

**Comment by Thegrep01** [comment]
@hydra324 Hi! in new version we added this feature check readme

**Comment by hydra324** [comment]
@Thegrep01 Hi!, Thank you for adding this feature. Any idea when the next version will be out?
