### ISSUE TITLE
Runtime exception when building Prod flag

### ISSUE THREAD

**Issue by digitalmedia34** [JsDaddy/ngx-mask#58]
A .map of undefined on maskSpecialCharacters when trying to create a regex in the constructor.

**Comment by digitalmedia34** [comment]
I am able to replicate the issue by running ng build --prod

**Comment by digitalmedia34** [comment]
The issue was fixed in 064a071 (https://github.com/vgildeev/ngx-mask/commit/064a071716a5c433c07d4091de696fa170a49059)

It looks like its a matter of merging the change into master branch

**Comment by thebarada** [comment]
@JsDaddy could you please merge PR

**Comment by NepipenkoIgor** [comment]
@thebarada Done
