### ISSUE TITLE
Error thrown when deleting special character

### ISSUE THREAD

**Issue by ColinMorris83** [JsDaddy/ngx-mask#580]
I have the following setup, essentially user should be able to type a-z plus spaces, hyphens and apostrophes. This is working ok for preventing user to type anything else other than those specified in the regexp.

this.mask = 'N*';
this.dropSpecialCharacters = false;
this.customPatterns = { 'N': { pattern: new RegExp('[A-Za-z \'-]') } };

However, if I type in the text field -c

And then delete the hyphen, the following error is thrown:

TypeError: Cannot read property 'toString' of undefined
    at MaskDirective.a (ngx-mask.js:980)

Is this a bug or am I wiring up the mask wrong?
 
This is also happening on the specialCharacters demo section on https://jsdaddy.github.io/ngx-mask-page/main#
Type in [6 and then delete the [ and the error will be seen in the console.

**Comment by isysenko** [comment]
@ColinMorris83 Hi, will be fixed in the new mask version

**Comment by ColinMorris83** [comment]
This issue still occurs in latest release with deleting special character when it's not the first character.
In my scenario, now typing in --c, if then delete the second hyphen, the error is thrown.

Also if typing c--c and then try and delete the second hyphen, the first c gets deleted and cursor jumps to beginning.

**Comment by ColinMorris83** [comment]
Hi @isysenko 
I had a quick debug of the code and I think there is a bug in the directive, on line 305 of the directive I don't think that line should be there, as it's just overriding the specialCharacters that the user may have passed in.

https://github.com/JsDaddy/ngx-mask/blob/f8108080ad804943958e2f14b1d87d15ab2b3158/src/app/ngx-mask/mask.directive.ts#L305

With that line removed, my use case works perfectly now as long as I specify something like ['='] for the specialCharacters. I think that is another bug in that you can't pass in an empty array for the specialCharacters as it will just set them to the default if its empty, so I have to pass something in there. As long as what I pass in is not an allowed character from the custom pattern regex, then it doesn't matter what it is.
