### ISSUE TITLE
Mask fails when deleting a non-special character as a suffix (Reopen #576)

### ISSUE THREAD

**Issue by artar94** [JsDaddy/ngx-mask#582]
When you try to delete a special suffix character with **Delete** (not Backspace) key, non-special suffix characters are duplicated.

![ngx-mask-3](https://user-images.githubusercontent.com/5181651/66252714-54b05200-e767-11e9-9ed6-22176ce3585d.gif)

An example of [StackBlitz](https://stackblitz.com/edit/angular-1ywquj)

**Comment by isysenko** [comment]
@artar94 Hi, will be fixed in the new mask version
