### ISSUE TITLE
separator logic broken

### ISSUE THREAD

**Issue by stefanvitz** [JsDaddy/ngx-mask#584]
Hi,

the separator logik seams broken.  and from the look into source it looks like dot_separator and coma_separator is a bit hacky. 

e.g. if  i define an input this way:
<input type="text" mask="dot_separator.2" ..> and insert  100000,5 is is formatted as  '100.000,5' and everything is fine,
If i instead use mask="separator.2" 
1.) i cannot insert a coma cause separator wrongly assumes the default decimal marker is a dot (i am using de-CH locale were it is a ,)
2.) if i insert  100000.5 (use a dot instead)  the value is formatted as '100 000.5'  (correct) but after save/reinit the value was changed to '1 000 005'

**Comment by stefanvitz** [comment]
in addition to that i cannot quite understand why there are separator, dot_separator and coma_separator instead of one single separator functiontogether with an separator-char config.

e.g. i would need an ' as separator to format  100'000,50

So i would look into refactoring this part... cause it seams most maskin-directives are lacking essential functionality, 
ngx-mask at least allows most of them but is short on separator functionality,

**Comment by stefanvitz** [comment]
have a look into this approach.
unluckily tests of some touched code-blocks is not that good so i could only guess what the idea of some replacement stuff was....
at least all tests are green so major things should work.

i left to todos so you have a good starting point on two things i were not completly sure about..

**Comment by Thegrep01** [comment]
@stefanvitz Hi! than you, check PR you have some troubles with linting

**Comment by stefanvitz** [comment]
@Thegrep01 thanks. as stated in PR i fixed it and travis build is good.
