### ISSUE TITLE
[hiddenInput] attribute bug, last character disappear

### ISSUE THREAD

**Issue by heecheolman** [JsDaddy/ngx-mask#585]
When `[hiddenInput]="true"`, I was expected MaskInput `ex) 123-***`. But I think It has bug.

[Code Here](https://stackblitz.com/edit/ngx-mask-bug?file=src%2Fapp%2Fapp.component.html)

**Comment by Thegrep01** [comment]
@heecheolman Hi! it is not a bag mask throw away all character as `-` etc, and masking only string value. In your case mask getting as input `1122334455` so result is valid, cause you do not have enough characters
