### ISSUE TITLE
ngx-mask json output

### ISSUE THREAD

**Issue by CaptainStorm21** [JsDaddy/ngx-mask#589]
Hi all, 
I am in complete confusion what am i missing?
https://stackblitz.com/edit/ssn-us

the data gets encrypted perfectly but in json output i get encrypted as well, how do I get formatted data but not with masked with xxx-xx-
For instance, if you enter 123-45-6789
input has xxx-xx-6789 
json outputs xxx-xx-6789 instead of 123-45-6789

Any ideas?
Thanks

**Comment by Thegrep01** [comment]
@CaptainStorm21 Hi i checked your example and i do not understand what you try to do, can you update it
