### ISSUE TITLE
Problem if prefix last char is not a number

### ISSUE THREAD

**Issue by vincentjdc** [JsDaddy/ngx-mask#590]
When the last char of the prefix is not a number and the user types `backspace` when the value is empty, it repeats the number of the prefix.

### To reproduce the bug

1. go to https://stackblitz.com/edit/angular-7e6rvi
2. Put the focus in the "Not OK" field and type `backspace`. The cursor goes between the "2" and the space.
3. Type a number (let say 5) and the field contains now "+32 32 5" which is not the expected value.

### Other notes

1. No problem with the "Ok" field.

Vincent

**Comment by isysenko** [comment]
@vincentjdc Hi, will be fixed in the new mask version(8.1.3)

**Comment by cyberbobjr** [comment]
Hi, still have the issue with version 8.1.7
