### ISSUE TITLE
Ngx mask not working properly in IE11

### ISSUE THREAD

**Issue by muniraji2i** [JsDaddy/ngx-mask#593]
I use mask="000-000-000" for text input but not working properly in IE11 and working in chrome

**Comment by NepipenkoIgor** [comment]
@muniraji2i Hi . Please provide more complex description.

**Comment by muniraji2i** [comment]
**<input type="text" mask="000-000-000" >**

While typing input in chrome It appars like 999-999-999  and restrict user to type more than 9 letters
In IE11 it appears like 99999999 and it allow user to  type more than 9 letters

**Comment by muniraji2i** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/44578411/66808819-a025e580-ef49-11e9-9779-21e79c1fe8ba.png)

**Comment by muniraji2i** [comment]
Is there any hard fix for this error ?

Please provide some solution

**Comment by muniraji2i** [comment]
I face this problem while using version 7.9.3 

It solved by version 7.9.5

**Comment by khalitko** [comment]
I tried 7.9.5 but no cigar, I also can only use 
import 'core-js/es6/object';
import 'core-js/es6/array';

Or it will cause conflicts.

Any other solution?

**Comment by khalitko** [comment]
7.3.6 worked!

**Comment by ColinMorris83** [comment]
For Angular 8, you will need to have the polyfill for array includes, so add this to your polyfills.ts file
import 'core-js/modules/es7.array.includes';

**Comment by gotshoo** [comment]
Adding the es7.array.includes fixed my issue with IE11 and 8.1.7.

**Comment by NepipenkoIgor** [comment]
@gotshoo  @khalitko  Yes for old browsers and JS environments you should use right polyfills . Such as @ColinMorris83  suggested.

**Comment by shailendrakumarsaini** [comment]
> For Angular 8, you will need to have the polyfill for array includes, so add this to your polyfills.ts file
> import 'core-js/modules/es7.array.includes';

thsnks! worked for me
