### ISSUE TITLE
separator.0

### ISSUE THREAD

**Issue by criskrzysiu** [JsDaddy/ngx-mask#598]
validation for mask="separator.0" always return "Mask error": true

`<input  type="text" inputmode="numeric" pattern="[0-9]*" mask="separator.0"/>`

**Comment by AlexeyDolya** [comment]
@criskrzysiu  
Hey. If I understand correctly, you need to ensure that the user can not put a dot and anything after it?

**Comment by criskrzysiu** [comment]
Basically yeah. It works great but it just return validation error. If you
turn off validation it works great.

W dniu wt., 15.10.2019 o 11:53 Alexey Dolya <notifications@github.com>
napisał(a):

**Comment by AlexeyDolya** [comment]
@criskrzysiu what version of ngx-mask do you use?

**Comment by criskrzysiu** [comment]
Latest. 8.1.1

W dniu wt., 15.10.2019 o 12:07 Alexey Dolya <notifications@github.com>
napisał(a):

**Comment by ColinMorris83** [comment]
Please post full example of the html, as <input type="text" inputmode="numeric" pattern="[0-9]*" mask="separator.0"/> isn't going to fire any validation methods without being wired up to a form control.
Also what value are you typing in the input that makes it invalid?

**Comment by NepipenkoIgor** [comment]
@criskrzysiu Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
