### ISSUE TITLE
Question: input mask for unrestricted number of characters

### ISSUE THREAD

**Issue by hydra324** [JsDaddy/ngx-mask#599]
Currently using the mask="C{4}", where C is some custom pattern, will let us restrict the input to four characters.

However, I do not want to restrict the number of characters or in other words, there can be any number of characters. How do I achieve this?

**Comment by ColinMorris83** [comment]
I think like this
`mask="C*"`

**Comment by hydra324** [comment]
Thanks, I will close this issue.
