### ISSUE TITLE
Removing separator

### ISSUE THREAD

**Issue by evgenevna22** [JsDaddy/ngx-mask#602]
ngx-mask v8.1.0
Angular v8.1.0

Hello! I have a problem with to removing separator (dot). When cursor is after the dot and I want to remove the dot, cursor jumps before and after the dot and remove digit before dot. But correct behavior should be like when cursor is after the dot, I’ll remove this dot not digit.
![Без-названия](https://user-images.githubusercontent.com/18423470/66904302-80a3c100-f00c-11e9-93f3-519b79fd8250.gif)

Thanks!

**Comment by ColinMorris83** [comment]
Can you try with 8.12, seems to delete the dot ok in that version, although after deleting the cursor jumps to end of the input, not sure if that is expected behaviour or not.
