### ISSUE TITLE
Mask percent.X not working

### ISSUE THREAD

**Issue by Aptashkin** [JsDaddy/ngx-mask#603]
@lizelleboshoff in our mask "." means that after dot you can enter 5 symbols , when you  use mask ="percent.5" it will display like .12345 
example 12.12345 , you can try to use the 7.9.5 mask version

_Originally posted by @ValeriaKochegarova in https://github.com/JsDaddy/ngx-mask/issues/438#issuecomment-488705071_

Hi
Unfortunately, it's not working in version 8.1.2

**Comment by ivarorn85** [comment]
I'm facing the same issue.

And is there any way to use the percent mask with a comma instead of dot?
Like 3,75 % instead of 3.75 % ?

**Comment by dev01prishusoft** [comment]
Any update on this ?

**Comment by Knochenmark** [comment]
I also just stumbled across this in version 8.1.6. Still not working.

**Comment by isysenko** [comment]
@Aptashkin Bug isn't reproducible. Please update mask version to latest(8.1.7) and try again.

**Comment by fuitattila** [comment]
@isysenko Still not working in v8.1.7.

Used mask is: percent.5
Still can enter below value: 12.11111111111

**Comment by conradoms** [comment]
Hi. Still not working. Any update on this?

**Comment by yehhor** [comment]
any updates on this?
I am using next config:
  `   [mask]="'percent.6'"
              [suffix]="'%'"
`
And I am able to enter 12.312312321321312312312321% (digits after separators are not limited when caret is not in the end)

**Comment by thiagopaiva99** [comment]
any news on this issue? I saw that already have a Pull Request open, there is any chance to merge it? My team is really waiting for that.

**Comment by andrii-oleksyshyn** [comment]
It's still broken in latest version (11.1.4) 😞
