### ISSUE TITLE
mask="comma_separator" not working in version 8.1.2

### ISSUE THREAD

**Issue by daliri72** [JsDaddy/ngx-mask#604]
It's `mask="comma_separator"` working on 8.0.8
when I upgrade to the latest version 8.1.2 it's not working.

**Comment by ColinMorris83** [comment]
It's now just mask="separator"
The readme is wrong currently, check out this one for up to date docs:
https://github.com/ColinMorris83/ngx-mask/tree/ADHOC-angular-cli-lib

**Comment by warrendugan** [comment]
Working replacement: https://stackblitz.com/edit/ngx-mask-currency-example. Trick here is the thousandSeparator paired with the separator mask.

**Comment by wilsonparson** [comment]
This is a breaking change, and should not have been included in a minor version change

**Comment by isysenko** [comment]
@daliri72 , @wilsonparson  Hi! In the latest version (8.1.6) comma_separator and dot_separator were removed and documentation was updated. As was noticed, you can add such separator next way:`  <input
                                      type='text'
                                      mask="separator"
                                      thousandSeparator=","
                                  />`
