### ISSUE TITLE
Properly usage of date masking

### ISSUE THREAD

**Issue by visualcookie** [JsDaddy/ngx-mask#605]
Hey guys.

I'm currently working on a credit card form, where I have the following fields:

- card number
- expiration date
- cvc
- card holder

Now my question is: how does the date masking exactly work? In my template I defined the following now:
```html
<input
  matInput
  [(ngModel)]="expiryDate"
  name="expiryDate"
  placeholder="Valid thru"
  mask="M00/00"
/>
```

But appearently the issue is, when I submit my form now, the value is not as I want it to be. The outputted value should be `expiryDate: { m: '12', y: '22' }`. Right now it returns `expiryDate: "1222"`, which I can't work with appearently.

Did I do something wrong on the setup there?

**Comment by nicolaslawdune** [comment]
Hi,
I got the same issue. I'm working on angular 8.

**Comment by visualcookie** [comment]
@nicolaslawdune Why haven't I figured that out? 😆 Thanks, works now.
