### ISSUE TITLE
Check validation from component

### ISSUE THREAD

**Issue by CrackerakiUA** [JsDaddy/ngx-mask#606]
if we need to check if an input with mask is validated or not, how can we success that? Lets say that we have `<input type='text' mask="00 00" [validation]="true" [(ngModel)]="time">`. Can we use something like `#time` and somehow get if it's valid?

**Comment by zauni** [comment]
With [reactive forms](https://angular.io/guide/reactive-forms) you can get the validation status with one property.

So in your component you have maybe something like this:

```js
timeInput = new FormControl('');
```

```html
<input type="text" mask="00 00" [validation]="true" [formControl]="timeInput">
```

and if you want to know the status you can use this:

```js
console.log(this.timeInput.status); // should log 'VALID' or 'INVALID'
console.log(this.timeInput.valid); // should log true or false
```
