### ISSUE TITLE
Any chance to have this in Vue?

### ISSUE THREAD

**Issue by MatheusRich** [JsDaddy/ngx-mask#607]
Is there a version of this on Vue.js? I want to use this feature in Vue:
```vue
<span>{{phone | mask: '(000) 000-0000'}}</span>
```

**Comment by NepipenkoIgor** [comment]
@MatheusRich  At this moment no. But we think about this

**Comment by MatheusRich** [comment]
If you give me some guidelines, I think I could make a PR on this.

**Comment by NepipenkoIgor** [comment]
@MatheusRich  Hi . Thank you for interesting. But totally  team focus on Angular framework and no plan on Vue at this moment
