### ISSUE TITLE
Input stuck after the first digit with dot_separator or comma_separator

### ISSUE THREAD

**Issue by josevjunior** [JsDaddy/ngx-mask#609]
When uses the dot_separator or comma_separator, the input stuck after the first digit.

![issue-ng-mask](https://user-images.githubusercontent.com/20262017/67256876-a7745400-f45f-11e9-999e-bbef749874af.gif)

Code in template:
`<div class="input-group col-sm-3">
              <input formControlName="ce" type="text" mask="dot_separator" class="form-control input-sm" />
              <div class="input-group-addon">
                %
              </div>
            </div>`

I imported the module with the forRoot() method (Without the optional parameter).

I'm using angular 7.2.0 with ngx-mask 8.2.0

**Comment by tienuit** [comment]
The readme file is now out of date. 
You can use:
`mask="separator" thousandSeparator=","`
Please see this link:
https://stackblitz.com/edit/ngx-mask-currency-example

**Comment by josevjunior** [comment]
Worked!!! Where can I find the up to date documentation? 

I don't if here is the right place to make that question. But, when I set the value in the form, the separator is ignored.

![image](https://user-images.githubusercontent.com/20262017/67299862-90ffe400-f4c3-11e9-9df6-fd30ccc49cf9.png)

**Comment by josevjunior** [comment]
I found a resolution for my problem. I had to use the decimalMarker with thousandSeparador.

`<input formControlName="ce" type="text" mask="separator" decimalMarker="," thousandSeparator="." class="form-control input-sm" />`

Too bad this information is not in the documentation. I had to look in the source code.

**Comment by MikeOne** [comment]
Had the same issue... all fine with 8.0.0 version - broken with 8.1.x version. This was a breaking change so really should have had a major version increase ;-(

**Comment by isysenko** [comment]
@josevjunior , @MikeOne Hi! In the latest version (8.1.6) comma_separator and dot_separator were removed and documentation was updated. As was noticed, you can add such separator next way: `<input type='text' mask="separator" thousandSeparator="," />`
