### ISSUE TITLE
Is it possible to specify 12 hour format?

### ISSUE THREAD

**Issue by Toktik** [JsDaddy/ngx-mask#613]
I would like to be able to have a mask with 12 hour format like HH:MM (AM/PM). Ideally, on keypressing to up or down the AM/PM should change.

Is this possible with ngx-mask?

**Comment by jacob-l** [comment]
Hi @isysenko 
Thanks for adding this issue to the To-Do list. Any ideas when it will be implemented?

**Comment by paras-deshbhratar** [comment]
Even I am also waiting for this feature.
Any updates when this will be released?

**Comment by wcooperscott** [comment]
It's been a full year. Still no update. I am looking for a solution as well.

**Comment by mbabaei0** [comment]
any update ?

**Comment by fiiiiif** [comment]
[NepipenkoIgor](https://github.com/NepipenkoIgor)
I implemented this feature, but I don't have access rights to push my changes. Can you give me access rights so I can prepare a pull request?

**Comment by daniel-barac** [comment]
Any updates on this feature?

**Comment by bianca-patientnow** [comment]
I'm looking for this feature two, can someone give @fiiiiif the access for PR?

**Comment by preetamjakhmola** [comment]
> @isysenko I implemented this feature, but I don't have access rights to push my changes. Can you give them to me so I can prepare a pull request?

can you please share your way to do that or make another repo and share for help.
Thanks in advance

**Comment by Androsid** [comment]
we really need this feature!

**Comment by andriikamaldinov1** [comment]
@Androsid @preetamjakhmola @bianca-patientnow @jacob-l @Toktik @daniel-barac @paras-deshbhratar @jacob-l 
Thanks for your using Ngx-Mask. Please update to latest version.
It example, we add [apm] for 12 hour format -https://stackblitz.com/edit/angular-dzyuwe?file=src%2Fmain.ts

**Comment by egorkel-altexsoft** [comment]
Hi, thx for this feature! But there is a small problem. I can't input 12:01. But instead it allows me to input 00:01.
https://en.wikipedia.org/wiki/12-hour_clock

**Comment by andriikamaldinov1** [comment]
@egorkel-altexsoft Thanks for using Ngx-Mask. Please update to latest version.
All work as expected - https://stackblitz.com/edit/angular-hfrynj?file=src%2Fmain.ts

**Comment by egorkel-altexsoft** [comment]
Nice!
It allows me to enter 12 hours now, but still, it allows me to enter 0 hours, which is not correct for 12-h notation.

![image](https://github.com/JsDaddy/ngx-mask/assets/95917278/35d8c4fc-e90b-4774-8d4f-d35b3ae932aa)

Or I'm wrong?

**Comment by andriikamaldinov1** [comment]
@egorkel-altexsoft what do you expect to see when a user enters 00 ???

**Comment by egorkel-altexsoft** [comment]
Same behavior as for number input when you are not allowed to enter letters. You just can't enter 00.

**Comment by WilliamScott-AdventGX** [comment]
I believe entering 00:00:00 should be allowable. I personally think this issue is complete, but if anyone wanted to add a [doubleZeros]="false" (where default is true), then cool.

**Comment by egorkel-altexsoft** [comment]
Well, if we talk about a 12-hour format then instead of 00:00 user should use 12:00. Or at least there should be an option for a "strict" format.
Or if you think you are good with this feature, can you tell me how I can use such kind of regexp `/^(?:1[012]|0[1-9]):[0-5][0-9]$/` with your library?

**Comment by andriikamaldinov1** [comment]
@egorkel-altexsoft We disabled to enter 00. 
It example - https://stackblitz.com/edit/angular-lukujr?file=src%2Fmain.ts

**Comment by egorkel-altexsoft** [comment]
Awesome! Thank you @andriikamaldinov1 👍

**Comment by tiago-eusebio-dev** [comment]
> @egorkel-altexsoft We disabled to enter 00. It example - https://stackblitz.com/edit/angular-lukujr?file=src%2Fmain.ts

@andriikamaldinov1 how to distinguish between AM/PM?

**Comment by egorkel-altexsoft** [comment]
I'm using additional button to switch between am/pm

**Comment by MitalVaghasiya** [comment]
please give angular15 supported time mask
