### ISSUE TITLE
No longer possible to access initial config

### ISSUE THREAD

**Issue by alfaproject** [JsDaddy/ngx-mask#614]
It looks like `INITAL_CONFIG` or `initialConfig` are no longer exported. Our builds are breaking because of this. ):

**Comment by ColinMorris83** [comment]
Sorry, think this was my last PR that has broke that, will look into it now

**Comment by ColinMorris83** [comment]
PR rasied: https://github.com/JsDaddy/ngx-mask/pull/615

**Comment by alfaproject** [comment]
Awesome, thank you (:
