### ISSUE TITLE
Issue with time input and showMaskTyped

### ISSUE THREAD

**Issue by govoruna** [JsDaddy/ngx-mask#616]
Hi
I have following configuration of input:
[showMaskTyped]="true" [specialCharacters]="[ ':' ]" [dropSpecialCharacters]="false" mask="Hh:m0" placeholder="HH:MM". According to documentation it should allow input of time in 24h format. And it does. The issue is when user starts typing incorrect time. For example try to input 45:45. In this case input will look like this 4:54_. Could you help me please to specify parameters correctly so the underscore symbols placed correctly.
Thank you.

**Comment by govoruna** [comment]
Hi,
Any update on this?

**Comment by NepipenkoIgor** [comment]
@govoruna  Hi. Thank you for Using ngx-mask. It seems like everything works as expected https://stackblitz.com/edit/angular-ivy-mask-gqeg4v?file=src/app/app.component.html
But If you have issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
