### ISSUE TITLE
Cursor jumps around when adding numbers to the beginning of textbox NOT FIXED

### ISSUE THREAD

**Issue by micrac** [JsDaddy/ngx-mask#618]
Unfortunatelly the fix for the issue: 

https://github.com/JsDaddy/ngx-mask/issues/344#issue-420428369

does not work (I see the same results that described in the issue).

 I am using version: "ngx-mask": "^8.1.5"

with Angular 8:
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cdk                      8.2.1
@angular/cli                      8.3.6
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.1
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

Best regards

**Comment by ColinMorris83** [comment]
It seems to work ok in the latest version of the app.

![Screen Recording 2019-10-30 at 15 35 58](https://user-images.githubusercontent.com/25006340/67875202-f12eff80-fb2d-11e9-8f4e-67deb81431eb.gif)

**Comment by micrac** [comment]
If you are talking about on-line example - yes it is working as expected. However I just created fresh project and installed ngx-mask. Then added to app.component.html a single line:

<input mask="separator.2" suffix=" PLN">

Unfortunatelly, in this setup the error persists.

**Comment by ColinMorris83** [comment]
Nope, not online example, I think that is not up to date. I'm testing on local version of the app. ie. check out the project from github, build the library and start the app up.

**Comment by micrac** [comment]
I downloaded the project from npm - may this be the difference? My setup is:

"dependencies": {
    "@angular/animations": "~8.2.13",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/router": "~8.2.13",
    "core-js": "^2.5.4",
    "ngx-mask": "^8.1.5",
    "rxjs": "~6.5.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

and
Angular CLI: 8.3.16
Node: 10.16.0
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.16
@angular-devkit/build-angular     0.803.16
@angular-devkit/build-optimizer   0.803.16
@angular-devkit/build-webpack     0.803.16
@angular-devkit/core              8.3.16
@angular-devkit/schematics        8.3.16
@angular/cli                      8.3.16
@ngtools/webpack                  8.3.16
@schematics/angular               8.3.16
@schematics/update                0.803.16
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

**Comment by NepipenkoIgor** [comment]
@micrac It seems like all works as expected with latest version. Please check  you package-lock.json and ngx-mask actual version in your node_modules.
