### ISSUE TITLE
mask modifies the behavior of ngModelChange

### ISSUE THREAD

**Issue by samherrmann** [JsDaddy/ngx-mask#622]
### Description

Consider the following:

```
<input type="text"
  [ngModel]="value"
  (ngModelChange)="onChange($event)"/>
```

In this setup, `ngModelChange` only emits an event when the user modifies the value in the `<input>`. `ngModelChange` does **not** emit an event when the external `value` bound to `ngModel` changes. This is Angular's default behavior.

Now let's add a mask:

```
<input type="text"
  mask="00/00/0000"
  [ngModel]="value"
  (ngModelChange)="onChange($event)"/>
```

In this setup, `ngModelChange` emits an event every time the external `value` changes.

### Expected Behavior

It is expected that adding a `mask` to an `<input>` does not change the behavior of `ngModelChange`

See reproduction on [StackBlitz](https://stackblitz.com/edit/ng-use-ngx-mask-twcpsr?embed=1&file=src/app/app.component.ts).

**Comment by paullauyc** [comment]
Same issue on reactive form

**Comment by gabrielrbeiro** [comment]
Please reopen, issue still active on reactive form

**Comment by akatakritos** [comment]
For what its worth, we worked around this by changing ngModelOptions to updateOn: 'blur', which seemed acceptable in our use case.

**Comment by shakerica** [comment]
Hello.
So this thing caused me a lot of problems in my project. We need to remove ngx-mask lib.

The most common is that we are subscribing to an BehaviorSubject to set form values and we have .valueChanges in order to detect changes and update our model.
(Well of course if we use ngx-mask emitEvent: false is useless and then the problems appear)

Does anyone found a workaround or a solution for this?

**Comment by NepipenkoIgor** [comment]
@samherrmann @akatakritos  @paullauyc @shakerica Thank you for using our package. For latest version everything works as expected. Also  {emitEvent: false} works for reactive forms as expected too. If you still have an issue please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag

**Comment by jhonattan471** [comment]
I have a reactive-form and need to open it with data (editing some entity). I need to set the values and not trigger the observable valueChanges on the inputs, but ngx-mask triggers it, dont find any option on the documentation to disable...
