### ISSUE TITLE
usa zipcode and placeholder

### ISSUE THREAD

**Issue by redka** [JsDaddy/ngx-mask#623]
Hi @NepipenkoIgor. I need add usa zip code too. And now when I add
`<input
                formControlName="zipCode"
                mask="00000-0?0?0?0?"
                [showMaskTyped]="true"
            />`

I see this
![image](https://user-images.githubusercontent.com/10400996/67980812-d9d43d00-fc27-11e9-84af-9aff232b61e9.png)

So, why doesn't work this mask?
And I have problem with placeholder. Now it is ____, I want for zip: XXXXX-YYYY
Can you help me?
Thank you)

_Originally posted by @redka in https://github.com/JsDaddy/ngx-mask/issues/63#issuecomment-548540389_

**Comment by divjyot3112** [comment]
I've found a solution to this. You can use the following configuration for the mask:
pattern='^[0-9]{5}(?:[0-9]{4})?$' 
mask="00000-0000" 
[validation]="false" 
[showMaskTyped]="true"

**Comment by andriikamaldinov1** [comment]
@redka Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-vq47a6?file=src%2Fmain.ts
