### ISSUE TITLE
Error with float number

### ISSUE THREAD

**Issue by lramondev** [JsDaddy/ngx-mask#624]
My mask setting is as follows.
prefix="R$ " 
```
mask="separator.2"
thousandSeparator="."
decimalMarker=","
```
When I load a float value equal to 2896.99
-expected value = 2.896,99
-but the displayed value = 289.699

what would be the solution for my case?

**Comment by MRMokwa** [comment]
Yes, I'm having the same issue. The behavior in this latest version is broken (tested with 8.1.5 and 8.1.6).

I also noticed that `mask="separator"` and `mask="separator.2"` return different data types.
- separator returns a number 
- separator.2 returns a string.

Solution is to downgrade the lib. Currently I'm using 8.0.6 and it's working as expected, just remember to use the old style mask (dot_separator.2)

**Comment by lramondev** [comment]
I found a directive called decimalMarker but it didn't work. I will test version 8.0.6. tnks!

**Comment by ColinMorris83** [comment]
You can specify decimalMarker.
e.g. 

```
mask="separator.2"
thousandSeparator=","
decimalMarker="."
```

If you now paste in 2896.99, it will display in the input as 2,896.99 and it's actual model value will remain as 2896.99

**Comment by lramondev** [comment]
I need to show the reverse. Being the value of the model float.

`mask="separator.2"
thousandSeparator="."
decimalMarker=","`

My Model Value = 2896.99 (float)
Display = 2.896,99

**Comment by ColinMorris83** [comment]
@lramondev could you try checking out this branch https://github.com/ColinMorris83/ngx-mask/tree/624-float-formatting and running the app up locally and testing out?

**Comment by lramondev** [comment]
Sorry i'm getting an error TS2307: Cannot find module 'ngx-mask'.

**Comment by ColinMorris83** [comment]
You have to do npm run build:lib and then npm start

**Comment by lramondev** [comment]
It worked! Thank you so much friend.

**Comment by ColinMorris83** [comment]
This will need a bit more work, as this only works for the case where the input is currently empty. If pasting into the input on to the end for example of existing input, the existing input is lost.

**Comment by lramondev** [comment]
Ok, let's wait

**Comment by ikkyy** [comment]
I am having the same issue, tried to install from the branch
with: 
npm install git://github.com/ColinMorris83/ngx-mask.git#624-float-formatting --save

But I got an error TS2307: Cannot find module 'ngx-mask'.

**Comment by lucasglobalsys** [comment]
Same issue
