### ISSUE TITLE
EmitEvent not working with mask

### ISSUE THREAD

**Issue by pedroferreirazup** [JsDaddy/ngx-mask#629]
<input
                id="cep"
                name="cep"
                type="tel"
                mask="00000-000"
                formControlName="cep"
                class="form-control"
                matInput
                placeholder="CEP"
                [ngClass]="fieldForChange('cep') ? 'colorForChange' : 'colorChanged'"
                (keypress)="onlynumber($event)"
                (focus)="triggerAll('cep')">

angular version: 7

i'm try disable emitEvent when put value in input this my code: 
  this.form.get('cep').setValue(this.model.fields.cepResponse, { emitEvent: false });

but, not working.. continue calling valueChanges

**Comment by W3bDan** [comment]
Did you find resolve of problem?

**Comment by NepipenkoIgor** [comment]
@W3bDan  @pedroferreirazup   Hi. Thank you for using ngx-mask package. With latest version everything works as expected.
You could try https://stackblitz.com/edit/angular-ivy-mask-f5v6mm?file=src%2Fapp%2Fapp.component.ts. If you steel have an issue  please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag

**Comment by Serg-Mois** [comment]
@NepipenkoIgor hello, it still emits if the mask is dynamic.
See example.
https://stackblitz.com/edit/angular-ivy-mask-zi8vxj?file=src/app/app.component.ts

**Comment by mohamed-badaoui** [comment]
any updates on this issue?
