### ISSUE TITLE
There is any way to use two different masks in one input?

### ISSUE THREAD

**Issue by jknvlvxs** [JsDaddy/ngx-mask#631]
The problem is a numeric input where the number can contain 10 or 11 digits.

If it has 10 digits, the mask should be **(00) 0000-0000**, if it has 11 digits, the mask should be **(00) 0 0000-0000**.

I tried to use **(00) 9 0000-0000** but didn't work well.

Can someone help me?

**Comment by Kolpak86** [comment]
I have the same problem

**Comment by mmdutra** [comment]
I have the same fucking problem

**Comment by mmdutra** [comment]
I found this soluction:

https://www.npmjs.com/package/ngx-phone-mask-br

**Comment by carlosabud** [comment]
just checking, I'm also facing the same scenario where same input has to support 2 different masks

**Comment by newcaiosantos** [comment]
Yes, there is:
![image](https://user-images.githubusercontent.com/7950328/95394602-38dc1080-08d3-11eb-85a9-114b22027254.png)
bottom of https://github.com/JsDaddy/ngx-mask
