### ISSUE TITLE
Input working wrong when using iOS Japanese keyboard

### ISSUE THREAD

**Issue by anhhh11** [JsDaddy/ngx-mask#632]
I've tried input with mask and regex pattern on Japanese keyboard on iOS but cursor always at the beginning of the input; When type character .i.e: pp the input result `つpp` rather than 'pp'
(It seem there is problem with 2 byte character and maybe with autocomplete of 2 byte keyboard)

**Comment by lambdadbmal** [comment]
I have a same issue on iOS 13.3.1 + WebView application.

**Comment by anpi0316** [comment]
when it will be fixed?

**Comment by jdhmoreno** [comment]
I can reproduce it consistently but on Windows with Chinese Simplified Keyboard with Chinese input method. The symptoms are the same.

To reproduce it:

- Prerequisete:
* Windows 10
* Chinese simplfied keyboard
* Chinese input mode (see picture)
* Chrome

![chineseKeyboard_chineseEntryModus](https://user-images.githubusercontent.com/31096237/121476696-4815df80-c9c7-11eb-8456-09b55d3266e7.PNG)

1. Open the official JsDaddy page for testing the component: https://jsdaddy.github.io/ngx-mask-page/main
2. Ensuring that the chinese input mode is selected, start typing some number in an input field with a mask (e.g. Date)
3. Right before the mask element (in this case '/') is printed out, any number typed will be duplicated

![chineseKeyboard_problem](https://user-images.githubusercontent.com/31096237/121477120-ba86bf80-c9c7-11eb-9ceb-c348930e2589.PNG)

Hope these steps help reproduce and solve this problem

**Comment by bugkillerma** [comment]
Yes! I have the same issue when I use Chinese input method on windows

**Comment by andriikamaldinov1** [comment]
@bugkillerma @jdhmoreno @lambdadbmal @anpi0316 @anhhh11  Thanks for using Ngx-Mask. 
We tried to reproduce this bug, but unfortunately all work as expected. 
Please try the new version 16.3.8, if it has this problem, then reopen the new issue with stackblitz.
Check it in our documentation - https://jsdaddy.github.io/ngx-mask/
