### ISSUE TITLE
set multiple masks for it

### ISSUE THREAD

**Issue by GlauberF** [JsDaddy/ngx-mask#637]
In angularjs, we used a library where we could declare the mask like this:
`mask: ['9', '9.9', '9.9.99', '9.9.99.999', '9.9.99.999.999'],`

how could i do the same thing now using this library, in angular?
it adapts according to the size of the data

**Comment by skined90** [comment]
Did you find a solution on this one?

**Comment by GlauberF** [comment]
I created a get function and apply the logic there

![Captura de Tela_selecionar área_20191129090148](https://user-images.githubusercontent.com/11314585/69864894-afa18980-127e-11ea-814d-e7c72bcb6fba.png)

![Captura de Tela_selecionar área_20191129090211](https://user-images.githubusercontent.com/11314585/69864910-b7612e00-127e-11ea-8b6a-18ff63163bbb.png)

![Captura de Tela_selecionar área_20191129090255](https://user-images.githubusercontent.com/11314585/69864917-baf4b500-127e-11ea-9eb6-806fb412fcc0.png)

**Comment by easyplyDev** [comment]
> I created a get function and apply the logic there
> 
> ![Captura de Tela_selecionar área_20191129090148](https://user-images.githubusercontent.com/11314585/69864894-afa18980-127e-11ea-814d-e7c72bcb6fba.png)
> 
> ![Captura de Tela_selecionar área_20191129090211](https://user-images.githubusercontent.com/11314585/69864910-b7612e00-127e-11ea-8b6a-18ff63163bbb.png)
> 
> ![Captura de Tela_selecionar área_20191129090255](https://user-images.githubusercontent.com/11314585/69864917-baf4b500-127e-11ea-9eb6-806fb412fcc0.png)

make it copy able
