### ISSUE TITLE
Brazilian currency

### ISSUE THREAD

**Issue by GlauberF** [JsDaddy/ngx-mask#638]
I'm having problems with the mask for Brazilian currency, see the image below, on the right side of the image you can see the result.

![Captura de Tela_selecionar área_20191121100439](https://user-images.githubusercontent.com/11314585/69341009-7a29ea00-0c47-11ea-972f-10b903099f53.png)

I would need to do the formatting as follows:
**R$ 1.200,34**

If you add more numbers, you should do the following format:
**R$ 120**
**R$ 1.200,34**
**R$ 12.000,34**
**R$ 120.000,34**
**R$ 1.200.000,34**

I would also need that even if I type only **120**, in the end it will automatically include **,00**. Getting **120,00**

If anyone can help me, I appreciate it.

**Comment by jl91** [comment]
mask="dot_separator.2"

**Comment by GlauberF** [comment]
did not work

**Comment by jl91** [comment]
for me too, i'm sorry i forget to update that. So, what a did? 

<input matInput
           mask="separator.2"
           [thousandSeparator]="'.'"
           [decimalMarker]="','"
           prefix="R$ "
           title="{{ label | translate }}"
           type="text"
           [dropSpecialCharacters]="true"
           [ngModel]="value"
           (ngModelChange)="onValueChanges($event)"
    >

**Comment by jl91** [comment]
this is my implementation, and i put that implementation into a new component named app-currency, with that static configurations, and it works.!!!   this dot_separator.2  doesnt works anymore in new versions

**Comment by DionatanGG** [comment]
Above suggestion does not work.

**Comment by davifsroberto** [comment]
> for me too, i'm sorry i forget to update that. So, what a did?
> 
> <input matInput mask="separator.2" [thousandSeparator]="'.'" [decimalMarker]="','" prefix="R$ " title="{{ label | translate }}" type="text" [dropSpecialCharacters]="true" [ngModel]="value" (ngModelChange)="onValueChanges($event)" >



> for me too, i'm sorry i forget to update that. So, what a did?
> 
> <input matInput mask="separator.2" [thousandSeparator]="'.'" [decimalMarker]="','" prefix="R$ " title="{{ label | translate }}" type="text" [dropSpecialCharacters]="true" [ngModel]="value" (ngModelChange)="onValueChanges($event)" >


It worked!

Tks!

**Comment by gNaboa** [comment]
Valeu ai

**Comment by eduardosene** [comment]
Using ngx-maskhere didn't work. I get it using ng2-currency-mask, very simple configuration.

**Comment by JohnnyCarvalho** [comment]
Guys, I need it to display 1.20 when I type 120, how can I do that?

**Comment by GPA1992** [comment]
hi guys, i can't do this too... trying everything, any sugestions? 

  <input
          matInput
          #input
          min="0"
          type="text"
          prefix="R$ "
          mask="separator.2"
          [thousandSeparator]="'.'"
          [decimalMarker]="','"
          placeholder="Ex.: R$ 8,00"
          [dropSpecialCharacters]="true"
          formControlName="valor"
          autocomplete="off"
          required
        />

**Comment by andriikamaldinov1** [comment]
@GPA1992 Can you describe your problem, what's wrong? And provide stackblitz ?

**Comment by GPA1992** [comment]
> 

When i type number, the decimal maker "," doesn't appear automatically, like a thousandSeparator "."...

**Comment by andriikamaldinov1** [comment]
@GPA1992 Thanks for using Ngx-mask. 
By default behavior of our separator automotically put only the separator of thousandths. We do not have a feature that automatically puts decimals.
Сlose, since it issue works as expected.

**Comment by ionansantos** [comment]
Recomendo usar o  ng2-currency-mask. , funcionou para mim no angular 15    

basta executar : npm install ng2-currency-mask --save
 
logo em seguida importe no app.module.ts : 

import { CurrencyMaskModule } from 'ng2-currency-mask';

@NgModule({
  imports: [
    CurrencyMaskModule,
  ],
  // ...
})

então usei da seguinte forma : 

<input
  type="text"
  class="form-control"
  [(ngModel)]="form.price_purchase"
  name="price_purchase"
  [options]="{ prefix: 'R$ ', thousands: '.', decimal: ',' }"
  currencyMask
  placeholder="R$: 100.0000"
/>

**Comment by matheuskroska** [comment]
Tem um jeito utilizando ngxMask, segue exemplo

é o jeitinho 
![ManualDoMundoWorldManualGIF](https://github.com/user-attachments/assets/48e7541c-5608-4280-b7de-d1ceb1a64a42)


```
<input 
    type="text" 
    placeholder='R$ 50,00'
    prefix="R$ " 
    mask="0,00 || 00,00 || 000,00 || 0.000,00 || 00.000,00 || 000.000,00" 
/>
```
