### ISSUE TITLE
How to use thousandSeparator with pipe?

### ISSUE THREAD

**Issue by salazar-js** [JsDaddy/ngx-mask#639]
Using `mask` and `thousandSeparator` `directive` is easy
```html
<input mask="separator.2" thousandSeparator="." [(ngModel)]="value">
```
but there is a way use the `mask` `pipe` with `separator` and `thousandSeparator` at the same time?
```html
<span>{{  value | mask:'separator.2' }}</span> 🧐
```

**Comment by isysenko** [comment]
@salazar-js Hi! Such functionality will be in next mask version. Example: `<span>{{ value | mask: 'separator.2':',' }}</span>`

**Comment by claudiotrindade** [comment]
How set decimalMarker, suffix and prefix?

**Comment by lramondev** [comment]
How set decimalMarker, suffix and prefix?
