### ISSUE TITLE
Masking issue

### ISSUE THREAD

**Issue by rohanc202** [JsDaddy/ngx-mask#640]
I have added masking as 'mask="separator.0" thousandSeparator="," [dropSpecialCharacters]="true". I also want to limit number of characters input to 15 characters. How it can be done .
In 'mask' it is accepting only one options either to seperate or to limit characters.

**Comment by petr-like** [comment]
You can use **separatorLimi**
example:
```
 <input
      type="text"
      [dropSpecialCharacters]="true"
      mask="separator.0"
      thousandSeparator=","
      separatorLimit="999999999999999"
    >
```

**Comment by rohanc202** [comment]
Thanks @petr-like It wokred.
