### ISSUE TITLE
optional value does not work

### ISSUE THREAD

**Issue by GlauberF** [JsDaddy/ngx-mask#641]
I have a phone mask in Brazil.
where I'm using 9 to say it can have 4 or 5 numbers before the hyphen.

`mask: +00 (000) 00009-0000`

but typing it breaks, if I take the 9, it works normal.

in the other masks I already used, we used (? 9)

I need to understand, because in many cases I will use obligatory (0) and optional (9) numbers

see: https://i.imgur.com/VlwSSdL.mp4

ps: It doesn't work either
`mask: '+00 (000) 0000?-0000'`

**Comment by ivarorn85** [comment]
try this: 
mask="+00 (000) 0000?9-0000"

**Comment by marcelopradoufu** [comment]
> try this:
> mask="+00 (000) 0000?9-0000"

@ivarorn85 i have tried it and also didn't work. With 8 digits on number, the hyphen is in the wrong place:

`(000) 0000?9-0000` => `(034) 98008-045`

The expected result is `(034) 9800-8045`.

**Comment by GlauberF** [comment]
> try this:
> mask="+00 (000) 0000?9-0000"

not working

**Comment by andriikamaldinov1** [comment]
@GlauberF @marceloaprado @ivarorn85 @GlauberF  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-rzunxc?file=src%2Fmain.ts
