### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by danielczestki** [JsDaddy/ngx-mask#643]
Problems:
For this:
export const options: Partial<IConfig> | (() => Partial<IConfig>);

TSLint show:
TS1155: 'const' declarations must be initialized.

and app is not compiled.
I get error: Module parse failed: Unexpected token

**Comment by fidian** [comment]
Yeah, I noticed that in the README as well. It seems to work well without that line and perhaps the docs could be updated to show the available options.

Until then, this is what I did.

```typescript
import { NgxMaskModule } from 'ngx-mask'

@NgModule({
  (...)
  imports: [
    NgxMaskModule.forRoot()
  ]
  (...)
})
```

**Comment by jmchaves** [comment]
Try this:
```
import { IConfig, NgxMaskModule } from "ngx-mask";
export const options: Partial<IConfig> | (() => Partial<IConfig>) = {};

@NgModule({
  (...)
  imports: [
      NgxMaskModule.forRoot(options),
  ]
  (...)
})
```
