### ISSUE TITLE
Failed setting 'selectionStart' on number input field

### ISSUE THREAD

**Issue by fidian** [JsDaddy/ngx-mask#644]
I want to use a number input field so the browser will render the up/down arrows and could use an on-screen keyboard when entering data into this field. I also am using the mask of `0*` to limit the input to only digits (decimals and negatives are not allowed). When I use number fields with the mask directive, I see two different types of errors in the console.

> ERROR Error: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

> ERROR Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

I've made a simple test case that shows off how it is working for `<input type="text">` and fails for `<input type="number">` on [CodeSandbox](https://codesandbox.io/s/trusting-silence-8cf5h). When it loads, you can click on the Console tab near the bottom center to see errors written to console.

**Comment by fidian** [comment]
On further investigation, it appears that this is primarily hitting Chrome and impacts inputs that are hidden, email, date, month, week, time, datetime-local, number, range, color, checkbox, radio, ... It's easier to say it works with text, search, url, telephone, and password. A [StackOverflow post](https://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome) covers the question and proposes several techniques:

1. Update code to detect this and skip dealing with the selection.
2. Temporarily swap the input type to text, then restore it to number. May have issues when selecting text with a mouse.
3. Use a try/catch or detect if the element supports accessing the selection. If it does not, use 0.
4. Use `window.getSelection()` to get a selection object.
5. Use [caret](https://github.com/adelriosantiago/caret) or employ code like that plugin.

I hope this helps.

**Comment by fidian** [comment]
Another error shows up in number fields when backspace is pressed. You can demo it with the same example I had earlier. Just type 1 and press backspace.

> ERROR TypeError: Cannot read property 'toString' of undefined

**Comment by WuglyakBolgoink** [comment]
same with email fields

**Comment by andriikamaldinov1** [comment]
@WuglyakBolgoink @fidian  Thanks for using Ngx-mask. Please update to latest version.
There will be no errors in the console. But the main logic is tied to selectionStart && selectionEnd. 
This example will work as expected - https://stackblitz.com/edit/angular-7uxbmy?file=src%2Fmain.ts
