### ISSUE TITLE
TypeError: inputValue.slice is not a function

### ISSUE THREAD

**Issue by veronesecoms** [JsDaddy/ngx-mask#645]
I'm trying to apply a date mask but i'm receiving this error:

> core.js:15724 ERROR Error: Uncaught (in promise): TypeError: inputValue.slice is not a function
> TypeError: inputValue.slice is not a function
>     at MaskService.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskApplierService.applyMask (ngx-mask.js:162)
>     at MaskService.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskService.applyMask (ngx-mask.js:494)
>     at MaskDirective.<anonymous> (ngx-mask.js:980)
>     at step (tslib.es6.js:97)
>     at Object.next (tslib.es6.js:78)
>     at tslib.es6.js:71
>     at new ZoneAwarePromise (zone.js:910)
>     at __awaiter (tslib.es6.js:67)
>     at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective.writeValue (ngx-mask.js:966)
>     at setUpControl (forms.js:2057)
>     at resolvePromise (zone.js:831)
>     at new ZoneAwarePromise (zone.js:913)
>     at __awaiter (tslib.es6.js:67)
>     at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective.writeValue (ngx-mask.js:966)
>     at setUpControl (forms.js:2057)
>     at FormGroupDirective.push../node_modules/@angular/forms/fesm5/forms.js.FormGroupDirective.addControl (forms.js:5281)
>     at FormControlName.push../node_modules/@angular/forms/fesm5/forms.js.FormControlName._setUpControl (forms.js:5882)
>     at FormControlName.push../node_modules/@angular/forms/fesm5/forms.js.FormControlName.ngOnChanges (forms.js:5803)
>     at checkAndUpdateDirectiveInline (core.js:22095)
>     at checkAndUpdateNodeInline (core.js:23363)

My template:

```
                        <div class="w-25 m-2">
                            <kendo-textbox-container class='m-2 w-100' floatingLabel="Data Final">
                                <input kendoTextBox
                                kendoTooltip
                                type="text"
                                mask={{maskData}}
                                formControlName="end_date"
                                />
                            </kendo-textbox-container>
                        </div>
```

My ts file:
`  public maskData: string = '00/00/0000'`

My package json infos:
```
"ngx-mask": "^8.0.3",
"@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.7",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
@angular/animations": "~7.2.0",
    "@angular/cli": "~7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@coreui/angular": "^2.4.5",
    "typescript": "~3.2.2"
```

In my shared module i import and use:

`    NgxMaskModule.forRoot(),`

How i can fix this? If someone need more information, please ask me

**Comment by gabrielguerrero** [comment]
I got this error when using angular form way of disabling field by default

`
this.form = this.fb.group({
      myField: [{value:'', disabled:true}]})
`

The workaround is to use the usual way to set a default and later disable the field

`this.form = this.fb.group({
      myField: ['']})`

And later do 
`this.form.get('myField').disable()`

**Comment by NepipenkoIgor** [comment]
@gabrielguerrero @veronesecoms Thank you that using our package.  This issue fixed . Please look on latest changes and use lates version of ngx-mask
