### ISSUE TITLE
Esm module

### ISSUE THREAD

**Issue by qetr1ck-op** [JsDaddy/ngx-mask#65]
First of all thanks for your package and that you still maintain it.
Secondly, as a consumer, of the package I expect that it would be bundled into ES5 umd style. And I do not need to care about precompile my imported/required sources.

In order to do this you can:

* Set the value of the `main` property of `package.json` to point to the ES5 UMD bundle.
* Set the value of the `module` property to point to the entry file of the `esm` version of the library. `module` is a field in` package.json` where bundlers such as rollup and webpack 2 expect to find a reference to the ES2015 version of the code. Note that some older versions of the bundlers use `jsnext:main` instead of `module` so we need to set both properties.

More here [Distributing an Angular Library - The Brief Guide](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/)

Alternative is to use [ng-packagr](https://github.com/dherges/ng-packagr)

**Comment by LimarenkoDenis** [comment]
#84

**Comment by NepipenkoIgor** [comment]
@qetr1ck-op Please test and thank you
