### ISSUE TITLE
Ngx-mask in template driven forms

### ISSUE THREAD

**Issue by mikemicmike** [JsDaddy/ngx-mask#652]
Hi, we are revamping our app and have upgraded to 8.1.7 and also migrated a reactive form to a tmeplate driven form. However, the new mask in template driven forms seems to be crying and outputting a bunch of errors in the console. 

You can see this issue in this [stackblitz](https://stackblitz.com/edit/angular-kp3qqe)

As you can see the model is initialized to an empty string even though it should support a null model i think. 

Am i doing something wrong

Thanks!!

**Comment by NepipenkoIgor** [comment]
@mikemicmike  Hi. Thank you for using ngx-mask. Please try latest version of package .
https://stackblitz.com/edit/angular-ivy-mask-tu5mq4
Everything works as expected. If you think that you have new issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
