### ISSUE TITLE
How Can i Use This Package For Other Language Like Persian or Arabic ?

### ISSUE THREAD

**Issue by amirzenoozi** [JsDaddy/ngx-mask#656]
I need to use mask input in other language like arabic or persian. what should i do ?

**Comment by isysenko** [comment]
@amirzenoozi Hi, unfortunately current mask version don`t allow you use other language. We will discuss it and possible such functionality will appear in next versions.

**Comment by NepipenkoIgor** [comment]
@amirzenoozi  Hi .Thank you for using ngx-mask. Please recreate issue with new template and describe which things need to be translated ?

**Comment by m-khnarges** [comment]
Hello,
Thanks for your great package. I liked to tell that I also need ngx-mask for persian numbers.
I think it may help to say that the requested feature has been implemented in [ngx-currency](https://www.npmjs.com/package/ngx-currency) package a few years ago.

Sincerely,
Narges.
