### ISSUE TITLE
Configure if negative number is allowed in separator mask

### ISSUE THREAD

**Issue by ivarorn85** [JsDaddy/ngx-mask#659]
It would be nice to be able to config if a negative number is allowed in separator mask. For most of my currency inputs I don't want the user to be able to type negative numbers.

**Comment by luis-paulo-tdo** [comment]
This is will be very nice. 
Currently I couldn't find a simple way to block "-" character in inputs with the separator masks.
Even if the dropSpecialCharacters works, it would be good to prevent user typing.

**Comment by ColinMorris83** [comment]
Should be fixed in https://github.com/JsDaddy/ngx-mask/pull/708
