### ISSUE TITLE
IE11NotSupported 

### ISSUE THREAD

**Issue by mamadoudiallo727** [JsDaddy/ngx-mask#66]
Hi guys I tried to run the ngx-demo using internet explorer 11 but it is not working(page hangs at Loading...) although it is working fine in chrome. I am also working on a project in which I am using ngx-mask for my inputs and the mask works fine in chrome but doesn't work in IE11. Would someone help me .
Also noticed in the polyfills.ts file of the demo the imports for IE11 are commented out. So I guess that's why the demo is not working in IE11.
Any help on this will be appreciated

**Comment by NepipenkoIgor** [comment]
@mamadoudiallo727 Could you show error stack trace or screenshot

**Comment by NepipenkoIgor** [comment]
@mamadoudiallo727 You didn't respond and i have been closed this issue
