### ISSUE TITLE
Weird cursor behavior with backspace/type & custom patterns (credit card expiry date)

### ISSUE THREAD

**Issue by akvaliya** [JsDaddy/ngx-mask#660]
I have used custom patterns for credit card expiry date.

Cursor has weird behavior on typing & backspace. It moves randomly. See in [stackblitz](https://stackblitz.com/edit/angular-uqi5vv).

After one backspace. I am unable to delete more values.

This seems to be started from version `8.0.7`.

**Comment by bcordes1** [comment]
I also have this when i have [showMaskTyped] = "true" it'll delete the first one but then after that it has improper behavior

**Comment by andriikamaldinov1** [comment]
@akvaliya @bcordes1 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-9vvubt?file=src%2Fmain.ts
