### ISSUE TITLE
Backspace automatically delete special characters

### ISSUE THREAD

**Issue by andrewgazelka** [JsDaddy/ngx-mask#661]
I feel like, given the popularity of this repo, this is already implemented. Maybe I am blind.

Anyway, is there a way to make it so backspace automatically deletes special characters? For example, it is annoying to have to delete spaces and parenthesis in a phone number mask `mask="(000) 000-0000"`

**Comment by velu-dev** [comment]
is this issue fixed?
i am also facing this issue

**Comment by Kashin98** [comment]
I have found an easy fix for this issue, you can use the dynamic valid mask to delete the special characters.

Eg: Your phone number input is `mask="(000) 000-0000"`, as you use backspace the special characters should get deleted automatically. You can simply convert your mask to ` mask="(000) 000-0000 || (000) 000 || (000 || "`

This is simplest approach to this problem I have figured (make sure to validate your phone number length etc. during submission)

**Comment by andriikamaldinov1** [comment]
@andrewgazelka @velu-dev  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-58eyev?file=src%2Fmain.ts
