### ISSUE TITLE
Cursor moves weirdly with showMaskTyped & backspace doesn't work after deleting 1 character

### ISSUE THREAD

**Issue by akvaliya** [JsDaddy/ngx-mask#664]
With showMaskTyped cursor moves to one position forward on typing.

On backspace cursor doesn't moves to left after deleting digit. So after one backspace deleting using backspace doesn't work.

See in [stackblitz](https://stackblitz.com/edit/angular-d4lafs). Start typing & see weird behaviour. Then start deleting using backspace

This seems to be started from version `8.0.7`.

**Comment by SaltyPotato** [comment]
I'm also experiencing this issue

**Comment by cyberbobjr** [comment]
I'm also experiencing this issue

**Comment by asnow73** [comment]
I also have this problem. Made pull request https://github.com/JsDaddy/ngx-mask/pull/794

**Comment by andriikamaldinov1** [comment]
@akvaliya @jhgeluk  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-ymwtn4?file=src%2Fmain.ts
