### ISSUE TITLE
TypeError: Cannot read property 'length' of null at MaskDirective._validateTime

### ISSUE THREAD

**Issue by akvaliya** [JsDaddy/ngx-mask#665]
```
TypeError: Cannot read property 'length' of null
    at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective._validateTime (ngx-mask.js:1824)
    at MaskDirective.push../node_modules/ngx-mask/fesm5/ngx-mask.js.MaskDirective.validate (ngx-mask.js:1407)
    at forms.js:1191
    at forms.js:1170
    at Array.map (<anonymous>)
    at _executeValidators (forms.js:1170)
    at forms.js:1132
    at forms.js:1170
    at Array.map (<anonymous>)
    at _executeValidators (forms.js:1170)
```

I am getting this error with reactive forms.

Here is [stackblitz](https://stackblitz.com/edit/angular-pyphcn) that reproduces this error.

I have found this 3rd issue with latest version. 

This seems to be started from version `8.0.7`.

**Comment by mikemicmike** [comment]
Hi Akvaliya

This might be linked to my [issue](https://github.com/JsDaddy/ngx-mask/issues/652)

I'm really hoping we get an answer let me know if you do we've had to comment off all of our masks :(

**Comment by akvaliya** [comment]
@mikemicmike I have used reactive forms. Because of this issue couple of my pages stopped working. If we don't find resolution sooner then i am afraid i'll have to drop this plugin & find alternator one. I can't ask client to wait so long for this issue.

**Comment by ColinMorris83** [comment]
Fixed in https://github.com/JsDaddy/ngx-mask/pull/666

**Comment by NsdHSO** [comment]
ERROR TypeError: Cannot read property 'length' of undefined
    at MaskDirective._validateTime (ngx-mask.js:1232)
