### ISSUE TITLE
Add more information in the form validation error

### ISSUE THREAD

**Issue by JulienDuf** [JsDaddy/ngx-mask#669]
At the moment, when a value in a form control doesn't match the mask, it returns the error:
```json
{
    "Mask error": true
}
```

It would be nice to have an error with more information, in the same way that the match pattern validator does
```json
{
    "mask": {
        "requiredMask": "(000) 000-0000",
        "currentValue": "the value"
    }
}
```

**Comment by ColinMorris83** [comment]
Good idea, added in https://github.com/JsDaddy/ngx-mask/pull/666
Used actualValue to match the name Angular use in their validator:
https://github.com/angular/angular/blob/0b1e34de405891229dab85a0606f3d6bc5efab83/packages/forms/src/validators.ts#L364
```
{
    "mask": {
        "requiredMask": "(000) 000-0000",
        "actualValue": "the value"
    }
}
```

**Comment by JulienDuf** [comment]
Sounds good to me

**Comment by ColinMorris83** [comment]
@NepipenkoIgor can you close this issue please

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  Yes it seems like this suggesting implemented
