### ISSUE TITLE
Correct import in Angular 8 - Ionic 5

### ISSUE THREAD

**Issue by kalbzero** [JsDaddy/ngx-mask#670]
In app.module.ts

import { NgxMaskModule, IConfig } from 'ngx-mask';
export let options: Partial<IConfig> | (() => Partial<IConfig>);

@NgModule({
   imports: [
      ...
      NgxMaskModule.forRoot(options),
     ...
   ],
})

Enjoy! :)

**Comment by isysenko** [comment]
@kalbzero Hi, thanks but we don`t understand reason of this issue. If you answer to another issue - you should write comment there, if you have some issue which we need to solve - please open issue with correct problem description and code examples.

**Comment by kalbzero** [comment]
Hi @isysenko. It was just to inform. Because I was giving error when importing into my projects, and I believe it may be happening in other projects

**Comment by ctodobom** [comment]
@kalbzero , how do you use it with ionic 5? is there an example?
