### ISSUE TITLE
Incorrect behavior of decimalMarker

### ISSUE THREAD

**Issue by martamoshkin** [JsDaddy/ngx-mask#674]
If set `[decimalMarker]="','"`, have possibility to input commas and dots.

![image](https://user-images.githubusercontent.com/1945239/73179134-c7cd4200-4123-11ea-8877-f48626564119.png)

``` 
 <input class="form-control" placeholder="Separator" mask="separator" [formControl]="separatorForm" [decimalMarker]="','">`
```

**Comment by rskendzic** [comment]
@martamoshkin did you manage to change decimalMarker from `,` to `.` and vice versa?

**Comment by martamoshkin** [comment]
@rskendzic yes, but it working incorrectly
