### ISSUE TITLE
Negative numbers saved as positive when using separator

### ISSUE THREAD

**Issue by mujutsu** [JsDaddy/ngx-mask#675]
In version 8.1.7 it is possible to enter negative numbers when using the separator. However, the value is saved in the ngModel as a positive number.

mask="separator.3 "thousandSeparator="." decimalMarker=","

Additional info: if I add [dropSpecialCharacters]="false" then the minus is saved and shown, but the the ngModel saved is not a number anymore. For example:

with [dropSpecialCharacters]="true":
input: -123456,789 --> correct
displayed: 123.456,789 --> incorrect
ngModel: 123456.789 --> incorrect

with [dropSpecialCharacters]="false":
input: -123456,789 --> correct
displayed: -123.456,789 --> correct
ngModel: -123.456,789 --> incorrect: not a valid number, it's not converted back anymore

**Comment by efedorko** [comment]
Simply reducing the special characters array to thousand and fraction separator (eliminating the minus sign) works fine:
`<input mask="separator" [specialCharacters]="[',','.']">`

**Comment by mujutsu** [comment]
Surprisingly, it worked. It's a very non-intuitive solution, so I think the bug itself is still valid.

Thank you for the help efedorko!

**Comment by jasonhjohnson** [comment]
@mujutsu Do you know how I can prevent negative numbers (or I guess just the - (minus) key) from being typed in?

**Comment by mujutsu** [comment]
> @mujutsu Do you know how I can prevent negative numbers (or I guess just the - (minus) key) from being typed in?

Sadly, I didn't have time to figure this one out yet.

**Comment by jasonhjohnson** [comment]
@mujutsu I ended up finding and using this: https://github.com/JsDaddy/ngx-mask/issues/659#issuecomment-574685921

**Comment by ColinMorris83** [comment]
Should be fixed in https://github.com/JsDaddy/ngx-mask/pull/708
