### ISSUE TITLE
Cannot change decimalMarker

### ISSUE THREAD

**Issue by rskendzic** [JsDaddy/ngx-mask#678]
```
<input
        type="text"
        matInput
        autocomplete="off"
        formControlName="value"
        mask="separator.2"
        thousandSeparator="."
      />
```
By documentation this should be 
```
Input value: 1234,56
Masked value: 1.234,56
```
but I get
`1.234.56` for Masked value.

Also, I have tried to set these in `configOptions` 
```
    NgxMaskModule.forRoot({
      decimalMarker: ','
    })
```
and dynamically to bind it on the template -> 

```
<input
        matInput
        autocomplete="off"
        formControlName="value"
        *ngIf="formGroup.get('type')?.value === ATTRIBUTE_TYPE.INTEGER"
        mask="separator.2"
      [thousandSeparator]="(numberFormat$ | async)?.thousandSeparator"
      [decimalMarker]='(numberFormat$ | async)?.decimalMarker'
      />
```

and I got the same result. Can you tell me where is the mistake I am making?

**Comment by SabikAbtahee** [comment]
Try to not give third bracket in decimalMarker. It worked for me in angular.

<input
        matInput
        autocomplete="off"
        formControlName="value"
        *ngIf="formGroup.get('type')?.value === ATTRIBUTE_TYPE.INTEGER"
        mask="separator.2"
      thousandSeparator="(numberFormat$ | async)?.thousandSeparator"
      decimalMarker='(numberFormat$ | async)?.decimalMarker'
      />

**Comment by isysenko** [comment]
@rskendzic Hi. Did the answer of SabikAbtahee help you to solve issue?

**Comment by rskendzic** [comment]
No. In the end i wrote custom directive to handle my case.
