### ISSUE TITLE
Paste does not work for secure (hidden) fields

### ISSUE THREAD

**Issue by johnbigley** [JsDaddy/ngx-mask#679]
I have a mask of 'XXXXXXXXX' for a social security number. Everything works fine except when I try to paste into the field. The value does not change.

      <mat-form-field>
        <input matInput name="ssn" [(ngModel)]="ssn" placeholder="SSN" 
          [hiddenInput]="true" mask="XXXXXXXXX" autocomplete="off" [validation]="false">
      </mat-form-field>

**Comment by xakeppok** [comment]
Hi. I cant reproduce this in version 8.2.0. Please update to last version.

**Comment by isysenko** [comment]
@johnbigley Hi!
Please update the mask version to the latest(8.2.0) and let us know if you still have this issue

**Comment by mapsuren** [comment]
I am still facing this issue.  To clarify the issue:
- If there is already a value in the field (123456789)
- User selects all the text (or CTRL+A) (**123456789**)
- Then tries to paste (or CTRL+V), nothing happens

@johnbigley what was your solution to this?

**Comment by NepipenkoIgor** [comment]
@mapsuren  @johnbigley Hi . Thank you for using ngx-mask. Please check this https://stackblitz.com/edit/angular-ivy-mask-3dgzj1?file=src%2Fapp%2Fapp.component.html . Everything works as expected.  If you have issue , bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag

**Comment by mapsuren** [comment]
@NepipenkoIgor Thanks for your response but your example doesn't work and it's not working as expected.  

**If you try to paste in an SSN into the field when there is _already an SSN_, it does not paste correctly.**
