### ISSUE TITLE
displaying wrong value if decimalMaker, separator.2 and integer value

### ISSUE THREAD

**Issue by lramondev** [JsDaddy/ngx-mask#680]
Would it be possible to implement my example?
Ex:
model value: 1000
separator.2
decimalMaker=","
thousandSeparator="."
display: 1.000 its nok
**expected: 1.000,00**

Ex2:
model value: 1000.01
separator.2
decimalMaker=","
thousandSeparator="."
display: 1.000,01 its ok
**expected: 1.000,01**

**Comment by isysenko** [comment]
@lramondev Hi. We will discuss it and possible such functionality will appear in next versions of mask.

**Comment by vmkarpenko** [comment]
@isysenko Is any update there?

**Comment by thangnguyen5201** [comment]
@isysenko isn't it finish??? I need this feature :D

**Comment by lramondev** [comment]
please any news?
Is it possible to use decimalMaker as a pipe?
Ex: `value | mask: 'separator.2': '.': ','`

**Comment by andriikamaldinov1** [comment]
@lramondev  @vmkarpenko Thanks for your using Ngx-Mask. Please update to latest version.
We add leadZero to lead zeros to end of the model - https://stackblitz.com/edit/angular-xn8sjm?file=src%2Fmain.ts

**Comment by dmaf87** [comment]
hello @andriikamaldinov1. Thanks for your update.

I got problem if the number is 999999999999999.99 why it show 1000000000000000.00
**expected: 999,999,999,999,999.99** 

<img width="405" height="184" alt="Image" src="https://github.com/user-attachments/assets/0a86dfb9-8f25-4c4c-abbf-99cf0bfa9c35" />
