### ISSUE TITLE
Update compability with Angular 9  @angular/common, @angular/core,  @angular/forms

### ISSUE THREAD

**Issue by ArmandoPerdomo** [JsDaddy/ngx-mask#681]

**Comment by andrejm7** [comment]
npm WARN ngx-mask@8.1.7 requires a peer of @angular/common@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mask@8.1.7 requires a peer of @angular/core@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies 
yourself.
npm WARN ngx-mask@8.1.7 requires a peer of @angular/forms@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by damsorian** [comment]
any update for this?

**Comment by CepBoJIk** [comment]
Any update?

**Comment by RichetGuillaume** [comment]
Any update ? ;)

**Comment by andrejm7** [comment]
Any update ? ;)

**Comment by mgarcos** [comment]
Any update ? ;)

**Comment by zorlac** [comment]
Any update ? ;)

**Comment by damsorian** [comment]
the _"Any update ? ;)"_ message is a bot? :p

**Comment by Alatouo** [comment]
Any update?

**Comment by lixaotec** [comment]
Any update?

**Comment by andrejm7** [comment]
??????

**Comment by damsorian** [comment]
almost two months and nothing????

**Comment by ColinMorris83** [comment]
It's probably not high priority as these are just warnings, the library works fine with Angular 9.

**Comment by JACrazy** [comment]
`ngx-mask@9.0.2 requires a peer of @angular/common@^9.1.0. `
Any reason why the minimum is 9.1.0?

**Comment by fleetingconsultoria** [comment]
No progress yet?
