### ISSUE TITLE
Native change event is not fired on IE and Edge when mask directive is used

### ISSUE THREAD

**Issue by orestisioakeimidis** [JsDaddy/ngx-mask#682]
The title is quite self explanatory. Please test it with the following stackblitz.

[Demo](https://stackblitz.com/edit/angular-vndpmd)

**Comment by dipedro** [comment]
For Angular 8, you will need to have the polyfill for array includes, so add this line to your polyfills.ts file
**import 'core-js/modules/es7.array.includes';**

**Comment by orestisioakeimidis** [comment]
@dipedro thanks for the suggestion but I tried that already and it doesn't work.

**Comment by poctob** [comment]
Blur event is also suppressed. MS Edge 44.
Workaround for Angular 9 and Template forms:

1. Add **import 'core-js/modules/es.array.includes'** to polyfills.ts
2. Replace **change** event with **ngModelChange** event.

**Comment by mcjcloud** [comment]
This issue also occurs on Safari for Mac.
Stackblitz: https://stackblitz.com/edit/angular-lmqa19?file=src/app/app.component.html

**Comment by NepipenkoIgor** [comment]
@poctob  @mcjcloud  @dipedro @orestisioakeimidis  Thank you for using ngx-mask package. You need to add right polyfills for JavaScript environments that not support latest standarts. In your case it is array.includes

**Comment by hungvq** [comment]
I run your stackblitz and wok fine. But i need **change** event - not **ngModelChange**...

> Blur event is also suppressed. MS Edge 44.
> Workaround for Angular 9 and Template forms:
> 
> 1. Add **import 'core-js/modules/es.array.includes'** to polyfills.ts
> 2. Replace **change** event with **ngModelChange** event.
> 
> Modified stackblitz https://angular-j8jgpe.stackblitz.io
