### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by isysenko** [JsDaddy/ngx-mask#685]
@ColinMorris83 
Hi. Could you help me deal with debug mode? Now to start the mask, I first build it it and then start, and repeat this actions with every change. It is very inconvenient. Is there a way to start it so that when mask changes, it automatically builded and debuggers and console.logs were not deleted?

**Comment by ColinMorris83** [comment]
Hi, you could change the top level tsconfig.json paths property to this:

```
"paths": {
  "ngx-mask": ["projects/ngx-mask-lib/src/index"],
  "ngx-mask/*": ["projects/ngx-mask-lib/src/*"]
}
```
Making changes to the library code whilst you have the showcase app running will then automatically trigger a reload.

**Comment by isysenko** [comment]
@ColinMorris83 Got it, thanks)
