### ISSUE TITLE
How I get the value with prefix?

### ISSUE THREAD

**Issue by sbeka** [JsDaddy/ngx-mask#686]
How can I get the value along with the prefix?

For example:
`<input prefix="+7 (7" mask="00) 000-00-00">`

i get value without +7(7

i need value with prefix. Please help!

**Comment by ABaranchugov** [comment]
I use a crutch:
`
control.valueChanges
    .pipe(
        debounceTime(500)
    )
    .subscribe((value: string) =>
        value = `${prefix}${value}${suffix}`; 
        this.control.setValue(
            value, 
            {
                onlySelf: true,
                emitEvent: false,
                emitModelToViewChange: false,
                emitViewToModelChange: false
            }
        );
    );
`

**Comment by NepipenkoIgor** [comment]
@ABaranchugov  @sbeka Hi. Thank you got using ngx-mask. Please try version 11.1.2 . Now you `[dropSpecialCharacters]=false`  not skip prefix

**Comment by NeoSimvolist** [comment]
what about suffix? i need the same for it

**Comment by varundhariyal** [comment]
> what about suffix? i need the same for it

+1

**Comment by hochun836** [comment]
+1
