### ISSUE TITLE
Valid date and month with leading zeros.

### ISSUE THREAD

**Issue by MrDywar** [JsDaddy/ngx-mask#687]
ngx can create mask for valid day/month, it's really cool thanks.

Can you add the ability to create mask (or pattern) on month with leading zero?

For example if user type number from 2 to 9, ngx will automatically add leading "0" to it.

2 -> 02
...
9 -> 09

It's not so easy, because after month we can get an year in mask, and if user types "1" and than "5" do we need to add leading "0" before 1, or preventing input number different from 0/1/2. Who knows :)

Thx.

**Comment by andriikamaldinov1** [comment]
@MrDywar Thank you for using ngx-mask. Please update ngx-mask to latest version.
You can use for this leadZeroDateTime, example below
https://stackblitz.com/edit/angular-ngbh66?file=src%2Fmain.ts

**Comment by YSFKBDY** [comment]
When **leadZeroDateTime** parameter implemented to ngx-max? And can I use it with Angular 10?
