### ISSUE TITLE
Mask "IP" validate wrong ip address as valid

### ISSUE THREAD

**Issue by MikeSam** [JsDaddy/ngx-mask#688]
If we use a built-it mask "IP", it validates address like `127.000` as valid ip address
Example:
```
<mat-form-field fxFlex>
  <input matInput formControlName="test" placeholder="IP" mask="IP">
      <mat-error *ngIf="userForm.controls['test'].hasError('Mask error')">
        Wrong address
      </mat-error>
</mat-form-field>
```
### Expected result:
Get error `Mask error` fro invalid address `127.000`

**Comment by thekhegay** [comment]
@NepipenkoIgor any comments?)

**Comment by NepipenkoIgor** [comment]
@thekhegay  Hi .  We will look in priority need to discuss with team.

**Comment by NepipenkoIgor** [comment]
@MikeSam  @thekhegay  Thank you that using our mask. Please try version >= 14.0.1 . If you will have a question please reopen issue.

**Comment by thekhegay** [comment]
@NepipenkoIgor @GlebChiz Thank you for fast fix! You make great job 💪
