### ISSUE TITLE
 Support for Angular5

### ISSUE THREAD

**Issue by pucheoswaldo** [JsDaddy/ngx-mask#69]
This is not working for Angular5. Could please let us know for release plan.
Thanks 👍

**Comment by bdragonomega** [comment]
I used this in an Angular 5.0.5 and it seems to be working fine for the most part.  Which angular version are you using it for and what is the behavior/errors when you try to use it ?

Thanks

**Comment by LimarenkoDenis** [comment]
@pucheoswaldo Can you provide an example, please, because it works fine for me with Angular 5

**Comment by NepipenkoIgor** [comment]
@pucheoswaldo @bdragonomega Please test , all problem was solved

**Comment by rodrigo-fonseca** [comment]
This mask is not working with Angular 5 here
