### ISSUE TITLE
Last two number comma seperator in currency

### ISSUE THREAD

**Issue by tcetin** [JsDaddy/ngx-mask#690]
I want to use `comma` seperator for last two number.But it sets `dot` sperator.

So it should be like this: `1.000,25`
But it sets like this:`100.025`

Here my template implementation:
`<input matInput  formControlName="currentSpendingLimit" mask="separator.2" thousandSeparator="." />`

Thanks

**Comment by timrasche** [comment]
+1 same here...

**Comment by isysenko** [comment]
@tcetin @timrasche Hi. You can set decimalMarker. (decimalMarker and thousandSeparator have to be different). 
Example:
`<input matInput mask="separator.2" thousandSeparator="."  decimalMarker=","/>`
and you type 1000,25 you get 1.000,25.
In separator mask you have to type a decimal marker to divide decimal part.

**Comment by timrasche** [comment]
Works! Thanks a lot @isysenko

**Comment by oxycoder** [comment]
@isysenko 
What about model value like 0.5?
with `<input matInput mask="separator.2" thousandSeparator="." decimalMarker=","/>` and value is 0.5, it convert to 50 instead of 0,5

**Comment by raframil** [comment]
I'm using `mask="separator.2" thousandSeparator="." decimalMarker=","` inside my input, and when I get value from Db like 5000.98 it turns out to be 500.098 inside the mask

**Comment by christianbayer** [comment]
I'm having the same problem described by @raframil. Using `<input matInput mask="separator.2" thousandSeparator="." decimalMarker=","/>` doesn't solve it. If the value is parsed from **1.234,56** to **1234.56**, it is expected to do the opposite as well, as the `thousandSeparator` and `decimalMarker` sugests.
