### ISSUE TITLE
Can't get masket text as masked format 

### ISSUE THREAD

**Issue by tcetin** [JsDaddy/ngx-mask#691]
I want to get masked text format in currency.

It formats like this in input:`1.000.025`
It gets to component like this:`"100025.00"`

I want to get bind exact the masked value.

Here is my implementation in template:

`<input matInput  formControlName="currentSpendingLimit" mask="separator.2" thousandSeparator="." />`

How can I do this?

Thanks

**Comment by s0ckz** [comment]
Try [dropSpecialCharacters]="false"

**Comment by isysenko** [comment]
@tcetin Hi!
Did the previous suggestion solve your issue?

**Comment by jimbarrett33** [comment]
[dropSpecialCharacters]="false" turns your number decimal input to a string in reactive forms which is not helpful.

**Comment by NepipenkoIgor** [comment]
@jimbarrett33  @s0ckz  @tcetin  Hi Thank you for using ngx-mask. If you want to have masked value you should use [dropSpecialCharacters]="false". But If you think that issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
