### ISSUE TITLE
Phone mask backspace leaves opening parenthesis and considers the input valid

### ISSUE THREAD

**Issue by jasonhjohnson** [JsDaddy/ngx-mask#692]
Hi,

I have the following:

```
<input class="form-control" id="phone" type="text" formControlName="phone" mask="(000) 000-0000" />
```

When I type in a valid value and then backspace up to the opening parenthesis "(" it considers the input valid. The underlying form control value is empty but the input itself shows the opening parenthesis. Is this an issue or by design?

Thanks,
Jason

**Comment by plaramee1** [comment]
I have the same issue, any news on that ?

**Comment by jasonhjohnson** [comment]
@plaramee1 Hey, no I don't think I ever truly resolved it. I think I ended up using a different library/solution/workaround. It was only 21 days ago you'd think I'd remember :-)

**Comment by NepipenkoIgor** [comment]
@jasonhjohnson  @plaramee1  Hi . Thank you for using ngx-mask. Please try version v11.1.3 
https://stackblitz.com/edit/angular-ivy-mask-trtyt7?file=src%2Fapp%2Fapp.component.html

**Comment by Sutil** [comment]
The problem persists when using multiple masks.
[Using this example on stackblitz](https://stackblitz.com/edit/angular-ivy-mask-trtyt7?file=src%2Fapp%2Fapp.component.html) and changing the mask to `000-00-00||(000) 000-00-00`.
