### ISSUE TITLE
optionals alphanumerics take wrong spot

### ISSUE THREAD

**Issue by Laurent-A** [JsDaddy/ngx-mask#693]
Hello,
After several tries, I haven't found solution could you help ?
Here is my problem:,

My mask is composed:

- 3 numbers required
- 1 space required
- 1 alphanumeric required
- 1 letter not required
- 1 space required
- 2 numbers required

What I expect :

- 123 AA 12
- 123 A 12
- 123 1 12
- 123 12 12

below my code :

**side .ts**

```
  fullName: string;
  pattern = {
    // tslint:disable-next-line: object-literal-key-quotes
    W: {
      pattern: new RegExp("[a-zA-Z]"),
      optional: true
    },
    K: {
      pattern: new RegExp("[a-zA-Z0-9]")
    },
    X: {
      pattern: new RegExp("[0-9]")
    },
    E: {
      pattern: new RegExp("[ ]"),
      optional: true
    }
  };
```

**side .html**

```
<input
    mask="XXX KWEXX"
    [(ngModel)]="fullName"
    [patterns]="pattern"
    [dropSpecialCharacters]="false"
  />
  <p>format : XXX KW AA</p>

  <br /><br />

  <p>{{ fullName }}</p>
```

when i write 123 AA 12 everything is fine
when I write 123 A 12, the "1" disappears and the "2" takes is spot.

Do you have any tips so that I can find a solution?

**Comment by andriikamaldinov1** [comment]
@Laurent-A  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-k3rgyw?file=src%2Fmain.ts
