### ISSUE TITLE
Is there a way to create mask like "1 year and 2 months"?

### ISSUE THREAD

**Issue by Kenya-West** [JsDaddy/ngx-mask#695]
I want to create a mask that displays value that is split between two or more words.
For example, when I enter 35 (months), it formats input and displays: "2 years and 11 months".

**Comment by andriikamaldinov1** [comment]
@Kenya-West Thanks for using Ngx-mask. 
It example how u can use this case  - https://stackblitz.com/edit/angular-iuyxvz?file=src%2Fmain.ts
