### ISSUE TITLE
Problem when writing in the time validation mask

### ISSUE THREAD

**Issue by GabrielSouza28** [JsDaddy/ngx-mask#696]
When I press numbers greater than 1, like 6, and press another number the cursor goes to the wrong place before the number.

Example:
When I press 6 and 5 I visualize on the screen:
6:|5
and the cursor is before the 5.
So, if the user wants to press 6:50, the result will be 6:05.

**Comment by isysenko** [comment]
@GabrielSouza28 What mask version you use? This bug isn`t reproducible on 8.2.0. Please update the mask to the latest version.

**Comment by GabrielSouza28** [comment]
Solved when upgraded ngx-mask. I was unable to get this solved before because I was working with angular 7.
