### ISSUE TITLE
Cursor error when use optional value (like 9 instead 0) for numbers

### ISSUE THREAD

**Issue by raisiqueira** [JsDaddy/ngx-mask#697]
Hi, i'm trying to set my input with this mask: `(00) 90000-0000`, but the cursor jump to another position and repeat some characters.

That's my example: https://stackblitz.com/edit/angular-yjyq4q

**Comment by lixaotec** [comment]
same here

last version 8.1.7

**Comment by Medioman92** [comment]
same here with version ngx-mask@8.2.0. I'm using a mask like  "S9-0999" and after typing the first char the cursor jump after the "-" char.
is there a way to avoid this ?

**Comment by thiagoalmedeiros** [comment]
I have a similar problem. My mask is : '00 00 00 99 99 99 99 99 99 99' and number and spaces are in the wrong positions. Did anyone have the same problem? My version is 8.2.0 but I also tested it on the latest version (9.0.2).

**Comment by andriikamaldinov1** [comment]
@thiagoalmedeiros @Medioman92  @lixaotec @raisiqueira   Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-ay6dq2?file=src%2Fmain.ts,src%2Findex.html
