### ISSUE TITLE
Problems with Angular 9 (IVY): NgxMaskModule.forRoot returns a ModuleWithProviders type without a generic type argument

### ISSUE THREAD

**Issue by Josh961** [JsDaddy/ngx-mask#698]
I'm getting the following error when trying to import the ngx-mask module into my application following the startup guide. I've used this library successfully in lower versions of Angular.

> NgxMaskModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

> static forRoot(configValue?: optionsConfig | (() => optionsConfig)): ModuleWithProviders;

My app.module.ts file:

```
import { HttpClientModule } from '@angular/common/http';
import { APP_INITIALIZER, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { IConfig, NgxMaskModule } from 'ngx-mask';
import { routes } from './app-routing.module';
import { AppComponent } from './app.component';
import { DashboardModule } from './modules/dashboard/dashboard.module';
import { ConfigService } from './services/config.service';

const appInitializerFn = (configService: ConfigService) => {
  return () => {
    return configService.loadAppConfig();
  };
};

export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    DashboardModule,
    HttpClientModule,
    NgxMaskModule.forRoot(options),
    RouterModule.forRoot(routes)
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFn,
      multi: true,
      deps: [ConfigService]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by Alberto-Monteiro** [comment]
Tenta usar 

> export const options: Partial<IConfig> | (() => Partial<IConfig>) = {};

**Comment by hajaniain** [comment]
Try to remove node_modules folder, and rerun `npm install`

**Comment by NepipenkoIgor** [comment]
@hajaniain @Alberto-Monteiro @hajaniain @larini @bogdanconstantinescu Please try latest version
