### ISSUE TITLE
value not shown correct

### ISSUE THREAD

**Issue by tomort** [JsDaddy/ngx-mask#699]
When I set the properties
* mask="separator.2"
* thousandSeparator="."
* decimalMarker = ','
and set the value of the formfield to 2.25 as number
then the mask is not shown the value correct. (remove the . of the value 225)
I need this for the german language.
Is this a bug or missing property.

Also the mask did not format the value correct (1.1 = 1.1 and not 1.10) 
Please help me

**Comment by isysenko** [comment]
@tomort Hi!
You set ',' as decimalMarker so to divide decimal part you need type ',' instead of '.' . Note: thousandSeparator and decimalMarker have to be different.
And 1.1 = 1.1 but not 1.10, it`s the correct behavior of mask.
