### ISSUE TITLE
Sugestion to change Error Status for the Form Control

### ISSUE THREAD

**Issue by HDeiro** [JsDaddy/ngx-mask#700]
Currently I'm using the `ngx-mask` in a project that I'm working with. But I have to validate a phone number. When the number is invalid and I check the errors in my form control there is an error with key `Mask Error`.

In order to be able to have a custom message in my form control I had to access the errors via the array notation and pre-check if the errors object exists.

I would strongly suggest to change it to `masks` or at least have the possibility to change it in the setup of the library. 

This way it would be possible to use the pre-check acessor like: `formControl.errors?.masks` instead of `formControl.errors && formControl.errors['Mask error']`.

**Comment by ColinMorris83** [comment]
In version 8.2.0 the 'Mask error' has been renamed to just 'mask
