### ISSUE TITLE
Cursor jumps around when adding numbers to the beginning of textbox

### ISSUE THREAD

**Issue by NickolayK** [JsDaddy/ngx-mask#704]
i'm using "ngx-mask": "^8.1.6", with angular 9 :
 "typescript": "~3.7.5",
  "@angular-devkit/build-angular": "~0.900.1",
  "@angular/cli": "~9.0.1",
 "rxjs": "~6.5.4",
<input type='text' mask="separator"> jumps around when adding numbers to the beginning of textbox .
[Screencast 2020-03-30 12-24-56.zip](https://github.com/JsDaddy/ngx-mask/files/4401870/Screencast.2020-03-30.12-24-56.zip)
can you please fix it ?

**Comment by ColinMorris83** [comment]
Can you try in the actual showcase app, not sure what's deployed to that Github demo page is the latest version of the lib.

**Comment by splincode** [comment]
I have same issue

**Comment by mseradzenka** [comment]
Hello, same stuff over here, while adding symbols at the beginning of the input

**Comment by splincode** [comment]
workaround downgrade to less than `8.1.6`

**Comment by NickolayK** [comment]
> Can you try in the actual showcase app, not sure what's deployed to that Github demo page is the latest version of the lib.

https://stackblitz.com/edit/angular-ngx-mask-error

**Comment by NickolayK** [comment]
> workaround downgrade to less than `8.1.6`
the 'separator.2' added from  "ngx-mask": "8.0.7", so 8.0.7 and greater  version have this issue .

**Comment by sergeidrondin** [comment]
Same thing with 9.02 version.

**Comment by sebastienricher** [comment]
I got the same issue, was using ^8.1.7, switched to 8.1.6, issue is present. Switched to 8.1.5, still present. 8.0.6 fixed the issue, but I get other side effects, I lose the .2 for decimals. This is not working correctly for me...

**Comment by NepipenkoIgor** [comment]
@NickolayK @sebastienricher   @splincode  Seems like it was issue with old version of ngx-mask . Currently everything works as expected  https://stackblitz.com/edit/angular-uezh8e?file=src%2Fmain.ts . Seems like like was fixed with another issue

**Comment by andriikamaldinov1** [comment]
@NickolayK @sebastienricher @splincode 
Thank you for using ngx-mask. 
I'm closing issue as everything works as expected.
If you have any problems in the future in using the ngx-mask, open issue using the template
