### ISSUE TITLE
Can i use mask without thousandSeparator?

### ISSUE THREAD

**Issue by mcantonbul** [JsDaddy/ngx-mask#705]
I do not want to use the thousands separator of the mask process. When I don't give any value, it sets 1 space. Are there any solution suggestions?

Example Input : 45567,68
Current Output: 45 567,68

**Comment by ColinMorris83** [comment]
Should be enabled with https://github.com/JsDaddy/ngx-mask/pull/708
Will now be able to pass in **thousandSeparator=""**  and it should then have no separator

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  Hi. I have just merged could you close issues relative to latest version

**Comment by ColinMorris83** [comment]
@NepipenkoIgor I don't have any permissions to close issues. I think only you probably can do it or original author of issue.

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 Hmmm. It seems like i lost list of issues . Could you send me and i will be able to close

**Comment by ColinMorris83** [comment]
The 6 listed in the PR: https://github.com/JsDaddy/ngx-mask/pull/708

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  Done
