### ISSUE TITLE
Cursor jumps to position 0 on click or select if mask is null or undefined

### ISSUE THREAD

**Issue by darginyegor** [JsDaddy/ngx-mask#709]
So, I have a custom input component. My way to deal with multiple ControlValueAccessors was to put `[mask]` directly to the input element and connect it with a @Input() component property like this:

`<ms-input fromControlName="somecontrol" [mask_]="000-000"></ms-input>`
 
Then in input.component.ts i have `@Input() mask_: string` and it's binded to `[mask]` directive on the input element.
And before ngx-mask@8.2.0 it worked fine, but now If my `mask_` is not provided, something breaks. With no errors cursos on the input keeps jumping to position 0 if I click somewhere in the input or try to select part of it's value.

**Comment by Chmielinski** [comment]
Also experenced it. Spent 4 hours debugging before finally determining this was the cause...

**Comment by vmehrjouei** [comment]
also I have this problem, I think should be an option for disabling directive. I had this problem with input type number so I had to write ngIf for number cases and now I have to write another ngIf for null masks!!

**Comment by ColinMorris83** [comment]
@vmehrjouei I can take a look at this as have done the same thing myself with a separate input that doesn't have the mask directive if don't need a mask. Basically it would essentially be a check in all of the directive methods to just return and do nothing if the mask is empty, does that seem ok?

**Comment by ColinMorris83** [comment]
Have added it into https://github.com/JsDaddy/ngx-mask/pull/708 - the directive shouldn't try and do anything now on empty masks

**Comment by vmehrjouei** [comment]
@ColinMorris83 ,Thanks, and sorry about my late answer, for example in my case I have a custom form input component that have an input inside and use mask. I give mask string as a @Input and use it. and I use that custom component every where, so when I don't have mask, in fact I have mask="" in component. also I have @Input type for "number", "text" and "password".
so this causes to I have mask="" and type="number" together.
