### ISSUE TITLE
Angular forms behaviour with dirty state

### ISSUE THREAD

**Issue by timrasche** [JsDaddy/ngx-mask#711]
Lib marks form control with state dirty if any data was renewed and reformatted but not changed

**Comment by ColinMorris83** [comment]
Can you provide bit more info please?

**Comment by timrasche** [comment]
1. Create form group
2. Create form control within
3. Load async data to form
4. Save data via service
5. Renew form data with result from service (use form.reset(data))
6. Form control state changed to dirty (should be pristine)

i think that after data has changed via .reset() method of form group, this library reformat the float/string and forces the dirty state. Dirty state should only be set if user has changed input manually

**Comment by ColinMorris83** [comment]
Ok, should be fixed in https://github.com/JsDaddy/ngx-mask/pull/717
