### ISSUE TITLE
sufix and suffix are conflicting

### ISSUE THREAD

**Issue by tirupathi471** [JsDaddy/ngx-mask#713]
In older version input variable was taken as sufix and new version its corrected to suffix. As we are using to versions in different libraries those are not supporting each other. i Suggest to change 
 input() Suffix to input('sufix') Suffix. So that people who are referring older version still they can upgrade to new version.

**Comment by NepipenkoIgor** [comment]
@tirupathi471  Seems like  this issue not actual anymore for modern stack. Thank you that using ngx-mask
