### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by unixxxx** [JsDaddy/ngx-mask#714]
I am getting this error.

Angular 8,
Typescript 3.8.3

./node_modules/ngx-mask/lib/mask.service.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25     set formElementProperty([name, value]: [string, string | boolean]);

**Comment by ColinMorris83** [comment]
Angular 9.1 is the version that supports typescript 3.8, can you try updating your app to that.

**Comment by unixxxx** [comment]
@ColinMorris83 I can't update to angular 9, I installed Typescript@3.5.3 but the error remains

**Comment by ColinMorris83** [comment]
The library is built with typescript 3.8, therefore you'll need to be on Angular 9 to use the latest version 9.0.0 of the library.

**Comment by nedredmond** [comment]
Are there guidelines somewhere for what versions of ngx-mask are compatible with different Typescript/Angular versions? I am running Angular 7 with Typescript 3.2.2... is there a version of ngx-mask I can use?

**Comment by Victor1993** [comment]
I add to the doubt, is there any version that can be used with Angular 8 and Typescript 3.5.3?

**Comment by thouseefrogers** [comment]
I also hit the same issue with Angular 8 and typescript 3.5.3. 
The default version of ngx-mask that got installed was 9.0.2, I installed 8.2.0 and it compiled fine!!

**Comment by Yass196** [comment]
Hi, i had the same issue, i installed the 8.1.0 ngx-mask version for angular 8.2.14 and it works ! 
try to check the ngx-mask version  history in [https://www.npmjs.com/package/ngx-mask]

**Comment by vitorfiler** [comment]
O seguinte comando resolveu pra mim sem impactos no que eu estava usando: 
npm install ngx-mask@8.0.0
cheguei a esta conclusão abrindo o package.json e vendo ngx-mask@9.0.2 instalada, ela não era compatível com a versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionou

**Comment by thiagocall** [comment]
> O seguinte comando resolveu pra mim sem impactos no que eu estava usando:
> npm install ngx-mask@8.0.0
> cheguei a esta conclusão abrindo o package.json e vendo ngx-mask@9.0.2 instalada, ela não era compatível com a versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionou

@vitorfiler, tentei fazer aqui... o erro saiu, no entanto, ainda dá erro quando declaro "export const options: Partial<IConfig> | (() => Partial<IConfig>)" no App.module...
Como você fez??

**Comment by hitallow** [comment]
> O seguinte comando resolveu pra mim sem impactos no que eu estava usando:
> npm install ngx-mask@8.0.0
> cheguei a esta conclusão abrindo o package.json e vendo ngx-mask@9.0.2 instalada, ela não era compatível com a versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionou

Valeu, isso funcionou para mim.

**Comment by vitorfiler** [comment]
> > O seguinte comando resolvido para mim sem afetar o que você estava usando: 
> > npm install ngx-mask@8.0.0, que 
> > inicia esta conclusão abrindo o package.json e está vendo ngx-mask@9.0.2 aberto, ela não era compatível com uma versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionar
> 
> @vitorfiler , tentei fazer aqui ... o erro saiu, no entanto, ainda dá erro quando declarar "exportar const opções: Parcial | (() => Parcial)" no App.module ...
> Como você fez ??

no meu caso, tive esse problema, por que instalei o ngx-mask no meu projeto angular sem dizer qual versão eu queria(npm install ngx-mask) logo ele instalou a versão mais atual, que não era compatível com a versão do angular que eu usava, por isso instalei outra manualmente, mas apagar a pasta node modules e baixar de novo, irá baixar a versão talvez mais recomendada ou compatível com o projeto automaticamente(funcionou pra um amigo meu).

**Comment by hitallow** [comment]
> > O seguinte comando resolveu pra mim sem impactos no que eu estava usando:
> > npm install ngx-mask@8.0.0
> > cheguei a esta conclusão abrindo o package.json e vendo ngx-mask@9.0.2 instalada, ela não era compatível com a versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionou
> 
> @vitorfiler, tentei fazer aqui... o erro saiu, no entanto, ainda dá erro quando declaro "export const options: Partial | (() => Partial)" no App.module...
> Como você fez??

Acho que o erro que dá, é porque você não está adicionando valor a constante. o exemplo com 
`export const options: Partial | (() => Partial) ` é apenas um exemplo de como você deve fazer para inserir as configurações no modulo. nesse caso, voce esta declarando uma constante, adicionando a tipagem, mas não está inserindo o valor.

**Comment by DoanVanThuong** [comment]
i installed ngx-mask@8.2.0 for angular 8 and it works!

**Comment by nedredmond** [comment]
Yeah, we updated Angular to 9 and sailing is smooth.

**Comment by NepipenkoIgor** [comment]
@unixxxx  @Victor1993  @nedredmond  @ColinMorris83  @DoanVanThuong Thank you that using our package.

**Comment by souzace** [comment]
Just work for me, setting 
"compilerOptions": {
  "skipLibCheck": true,
}
on my tsconfig.json file

like this solution: https://stackoverflow.com/a/61155732

**Comment by guths** [comment]
> O seguinte comando resolveu pra mim sem impactos no que eu estava usando:
> npm install ngx-mask@8.0.0
> cheguei a esta conclusão abrindo o package.json e vendo ngx-mask@9.0.2 instalada, ela não era compatível com a versão do meu projeto angular que é 8.0, por isso pensei em voltar e funcionou

Me ajudou muito mano, valeu.
