### ISSUE TITLE
Issue with setting [allowNegativeNumbers]="true" 

### ISSUE THREAD

**Issue by sarwin-github** [JsDaddy/ngx-mask#718]
**Issue with [allowNegativeNumbers]="true"**

```
<input type="text" matInput #value="ngModel" #inputs
     [(ngModel)]="modelname" name="value" 
     [mask]="percent.2" 
     [prefix]="prefix || ''"
     [dropSpecialCharacters]="false"
     [allowNegativeNumbers]="true"
     [suffix]="suffix || ''">
```
**Issue:** 
- While using  [allowNegativeNumbers]="true" the percent.2 mask is not working as expected. It is not limiting the decimal to two.
- I tried fixing it by setting the mask to `separator.2` instead and I were able to solve the first issue however. Everytime I type 1000% the forth character in (1000%) become undefined.

I can email a video recording regarding this bug since I can't attach a file here. You can also check it in here: https://drive.google.com/file/d/16f5Vr-2eQ_PaG5KibG8Psh5OZCnn87MH/view?usp=sharing

@Version : 8.2.0
@Angular/cli: 8.0.2
@Angular/compiler-cli: 8.0.0

**Comment by andriikamaldinov1** [comment]
@sarwin-github Thank you for using ngx-mask. Please update ngx-mask to latest version.
Check our website, percent.2 work with allowNegativeNumber as expected. 
https://jsdaddy.github.io/ngx-mask/#11

**Comment by mohamed-badaoui** [comment]
On the demo, it is not possible to enter -100 (one hundred preceded by a minus sign)

https://jsdaddy.github.io/ngx-mask/#11

![image](https://github.com/JsDaddy/ngx-mask/assets/3098863/929b3897-91ff-4a37-8bb9-87cf285d39d2)

**Comment by andriikamaldinov1** [comment]
@mohamed-badaoui Thanks for using Ngx-Mask. We will fix that in our demo.
It example on stackblitz all work as expected - https://stackblitz.com/edit/stackblitz-starters-fwv39n?file=src%2Fmain.ts
