### ISSUE TITLE
Version compatible with Typescript 3.2.2?

### ISSUE THREAD

**Issue by nedredmond** [JsDaddy/ngx-mask#719]
I am running Angular 7 with Typescript 3.2.2, so I cannot run the latest version of this project. Is there a version of the project I can run?

Thank you.

**Comment by ColinMorris83** [comment]
What version of Angular are you on? If you can get to 8 which upgrades typescript to 3.5, then should be able to use 8.2.0 of this lib. If you can get to Angular 9 then you can latest version of this lib, 9.0.1

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  You are right that if possible need to use lates version of Angular. But @nedredmond  @iannisacksson  you could use previous  version of ngx-mask
