### ISSUE TITLE
Bug with decimalMarker

### ISSUE THREAD

**Issue by W3bDan** [JsDaddy/ngx-mask#721]
`<input type="text"  mask="separator.2" thousandSeparator=" " decimalMarker=",">`

When I input float number and type `.` (dot), mask doesn't ignore it.
Example:
![screencast-nimbus-capture-2020 04 13-12_33_27](https://user-images.githubusercontent.com/32509512/79098182-37e28000-7d83-11ea-8779-8a74d6fd5eb1.gif)

**Comment by ColinMorris83** [comment]
Fixed in https://github.com/JsDaddy/ngx-mask/pull/726
