### ISSUE TITLE
make secure input dynamic: XXXX0000  and XXXXXX00000

### ISSUE THREAD

**Issue by np29** [JsDaddy/ngx-mask#722]
I have a text input field of 17 length. but the input can be variable length. I want the last four digits to be unmasked while the preceding digits to be secured (e.g. *'s).
Examples:
XXX0000
XXXXXX0000
XXXXXXX0000
XX0000

**Comment by np29** [comment]
will this feature be added?

**Comment by andriikamaldinov1** [comment]
@np29 Thanks for your using Ngx-Mask. Please update to latest version.
It example, you can use for your case dynamicMask  -  https://stackblitz.com/edit/angular-xba5kb?file=src%2Fmain.ts
