### ISSUE TITLE
masked input with initial value on ngOnInit not working on ivy

### ISSUE THREAD

**Issue by joaqcid** [JsDaddy/ngx-mask#723]
I updated to Angular 9 and ngx-mask 9

There's an issue with masked inputs, when value is set OnInit it's not displaying the masked value

repro: [stackblitz](https://stackblitz.com/edit/ngx-mask-initial-value-repro?file=src/app/app.component.ts)

as a workaround you can wrap setting the value within `setTimeout` 

Angular CLI: 9.1.1
Node: 10.17.0
OS: darwin x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/fire                     5.2.3
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by GlauberF** [comment]
I have the same problem, I even thought it was an error in the form lib I have
Issue: https://github.com/ngx-formly/ngx-formly/issues/2179

the difference that I save in the database, always without formatting. I believe that it would not be a problem, since the number of characters and type is compatible with what the mask should receive

**Comment by ColinMorris83** [comment]
It's working ok, tested using both reactive forms and template driven forms.
https://ngx-mask-initial-value-repro-nvmewd.stackblitz.io

**Comment by GlauberF** [comment]
@ColinMorris83 true, linkey your test and demo in the other library

**Comment by joaqcid** [comment]
thanks @ColinMorris83 , looks like `mask` directive works when input is bound to ngModel, but not with value

**Comment by ColinMorris83** [comment]
Correct, the stackblitz repro was neither using reactive or template driven forms, that's why it did not work.
