### ISSUE TITLE
Optional Mask not working after a special character

### ISSUE THREAD

**Issue by wasimshariff** [JsDaddy/ngx-mask#724]
Hi,

I have problem with mask (0/9) . The optional numeric field allows characters as well.  Current version i am using is 8.1.7 . 

After some debugging , found below code may be causing this issue. It doesnt let the next character after special character to be inspected in case next mask expression is optional. It perfectly works if there is no optional (0/0) 

```
else if (this.maskSpecialCharacters.indexOf(inputSymbol) > -1 &&
                    this.maskAvailablePatterns[maskExpression[cursor]] &&
                    this.maskAvailablePatterns[maskExpression[cursor]].optional) {
                    if (!!inputArray[cursor] && maskExpression !== '099.099.099.099') {
                        result += inputArray[cursor];
                    }
                    cursor++;
                    i--;
                }
```

Below is the link to reproduce the issue. 

https://stackblitz.com/edit/ngx-mask-issue-optional

Thanks,
Wasim

**Comment by andriikamaldinov1** [comment]
@wasimshariff  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-hrvsef?file=src%2Fmain.ts
