### ISSUE TITLE
Accept number between 

### ISSUE THREAD

**Issue by OhadGef** [JsDaddy/ngx-mask#725]
I’m trying to create special patterns of number between -90 to 90.
(Don’t  accepts other numbers)
```html
<input 
[allowNegativeNumbers]=“true” 
[patterns]=customPattern
mask= “T”/>
```

```typescript

const customPattern= “{‘T’: {pattern: new RegExp(‘([0-8]?[0-9]$|90$)’)}}” 

```

Expected: 
To except all numbers -90 to +90
(Also 04 suppose to be correct) 
 

Someone knows what is wrong?

**Comment by andriikamaldinov1** [comment]
@OhadGef Thank you for using ngx-mask. Please update ngx-mask to latest version.
[alllowNegativeNumber]="true" , work as expected.

https://stackblitz.com/edit/angular-em2ulz?file=src%2Fmain.ts
