### ISSUE TITLE
prod build error => const declarations must be initialized (options)

### ISSUE THREAD

**Issue by vkywalker** [JsDaddy/ngx-mask#727]
Can't perform production build.
Export options not valid
export const options: Partial<IConfig> | (() => Partial<IConfig>);
Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'options'.

**Comment by ColinMorris83** [comment]
Readme is updated on https://github.com/JsDaddy/ngx-mask/pull/726
For your case, if you don't need to pass in any options, then don't define the variable, you only need to import the module like so:

NgxMaskModule.forRoot()

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 you are right . @vkywalker Please try.

**Comment by vkywalker** [comment]
NgxMaskModule.forRoot() works fine! Thank you very much.
