### ISSUE TITLE
[dropSpecialCharacters] Error with Angular Unit Testing

### ISSUE THREAD

**Issue by gmartinez-aval** [JsDaddy/ngx-mask#728]
Using [dropSpecialCharacters] I get an Angular unit testing error:

<input mask="00/00/0000" [dropSpecialCharacters]="false">  --> 20/04/2020 (good)

But running Karma Angular testing I get: Failed: "... Can't bind to 'dropSpecialCharacters' since it isn't a known property of 'input'... " 

Would appreciate if you have any solution for this uncompatibility with Angular
    "Angular": "^8.2.0"
    "karma": "^4.1.0"

Thanks a lot

**Comment by ColinMorris83** [comment]
Sounds like you haven't imported the mask module in your test.

**Comment by gmartinez-aval** [comment]
Yes, update: The error was in the module import.
I did:  imports: [ NgxMaskModule ] --> Error

Proper way: imports: [ NgxMaskModule.forRoot() ] --> Working 100%
