### ISSUE TITLE
Raw number value was changed when changing thousandSeparator

### ISSUE THREAD

**Issue by rvdung** [JsDaddy/ngx-mask#729]
I got an issue on **ngx-mask@9.0.1** when trying to change **thousandSeparator** option while directive is running. Raw value was changed from 11.000,23  to 11 when I changed thousandSeparator from `,` to `.`. The same issue occurred when changing from `.` to `,`.

```html
<input   [(ngModel)]="price"
                       mask="'separator.2'" 
                       thousandSeparator="','"
                       type='text'>
```

to

```html
<input   [(ngModel)]="price"
                       mask="'separator.2'" 
                       thousandSeparator="'."
                       type='text'>
```

**Comment by andriikamaldinov1** [comment]
@rvdung  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-dzkcmy?file=src%2Fmain.ts
