### ISSUE TITLE
Hidden input value are not updating using ngModel

### ISSUE THREAD

**Issue by ajay1208** [JsDaddy/ngx-mask#730]
Editor URL : https://stackblitz.com/edit/aj-ngx-mask
App URL: https://aj-ngx-mask.stackblitz.io

In the above example - steps to replicate the issue are as below:

1. Click set value button.
2. Now second value should be set with first value
3. You can check that values by using First1 and First2 buttons
4. Now change the value in first input and click again the set value button.
5. Now if you check the second input value will not be changed.

Expected: The second value should be updated.

**Comment by HassanHarajly** [comment]
did you find a solution to this i have a similar issue with ngmodel not clearing the value aswell

**Comment by andriikamaldinov1** [comment]
@ajay1208  @HassanHarajly Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-15xguk?file=src%2Fmain.ts
