### ISSUE TITLE
BUG: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by W3bDan** [JsDaddy/ngx-mask#735]
Bug when use mask in ReactiveForms and change value in subscribe on changes.
In version 9.0.2 it's working good, but in 8.2.0 I have next error 'Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded'.

Example on stackblitz [link](https://stackblitz.com/edit/angular-dvktsu)

**Comment by NepipenkoIgor** [comment]
@W3bDan  Currently we support v11 . We recommend update your solution to latest version of Angular.
