### ISSUE TITLE
Selector name is too general: collides with other properties

### ISSUE THREAD

**Issue by clecrois** [JsDaddy/ngx-mask#738]
The selector name `[mask]` creates conflicts with my application's properties names. For example, I can't be using both the ngxModule and have components with inputs named `mask` in my app.

```
// the ngx-mask directive
@Directive({
  selector: '[mask]',
  ...
})

// my component
@Component({
  selector: 'app-my-component',
  template: '...'
})
class MyComponent {
  @Input() mask: string;
}

// when using MyComponent
<app-my-component [mask]="myMask"><app-my-component>
=> The ngx-mask directive is called instead of passing the input value to MyComponent.
```
Shouldn't it be better to have it prefixed and have it called, for example, `[ngxMask]`?

It's also stated as a good practice in the Angular doc: https://angular.io/guide/attribute-directives#why-not-highlight

I know it would be not easy to make this change. Maybe, would anyone know a way to override third party directives selector names? 
(I'm looking for ways other than avoiding the use of the term `mask` in my whole application / module)

**Comment by ColinMorris83** [comment]
It's a good point, but to avoid breaking change, the selector in the library could probably just be amended to only target input elements.

@Directive({
  selector: 'input[mask]',
  ...
})

**Comment by clecrois** [comment]
Oh yes, that would be the best solution :)

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 @clecrois merged
