### ISSUE TITLE
Editing a number is broken

### ISSUE THREAD

**Issue by NicolasMaas** [JsDaddy/ngx-mask#743]
Hello everyone

For instance you have a input field which has a value of 100 000.00 (with the mask). This comes from an API.

But the value is wrong and I want to change it. It needs to be 155 000.00 but the mask is interfering. If I place my cursor behind the first zero starting from left and I press backspace. I go to the end of my value (so the last zero from the right). Also if you then go back to the right place in the number and start typing, after the first number I add it also goes straight to the end of the value (the last zero from the right).

`<input mask="separator.2" type="text" name="capital" class="form-control formControlName="capital" />`

This is the input field itself and it's part of a Angular FormGroup. The only way to enter a new value is to delete the entire value inside the field and start with an empty input. Otherwise it's really annoying to edit a value.

**Comment by sopovks** [comment]
The same issue with me, you cannot edit a number then using space as thousand separator (what is by default by the way). It works ok with comma, but I need space. How it could be that no one noticed that control is totally useless with default behavior? Cursor jumps unexpectedly hear and there and all you can do is to delete the number entirely and start from the scratch. 

Is there any chance to correct this?
