### ISSUE TITLE
value of input field changed after lost the focus

### ISSUE THREAD

**Issue by raycarter** [JsDaddy/ngx-mask#744]
Version: >= v9.0.1

Description:
the mask will change value of input if it lost focus. This happens in version >= v9.0.1

e.g. `<input mask="S 0 0">`
|input char|value showed|value of input field v9.0.0  | value of input field >= v9.0.1|
|-----------|---------------|-----------------------------|----------------------------|
|A              |A                    |A                                       |A                                      |
|1              |A 1                 |A1                                      |A1                                   |
|2              |A 1 2              |A12                                    |A12                                 |
|tab (focus changed)|A 1 2|A12                                  |**A 1 2**                          | 

Expected:
after the input field losts focus, the value of it is not changed by mask.

I don't know if this change is a bug or feature, can't find info about that in `CHANGELOG.md`

If it is actually a bug, please fix it. Thanks!

**Comment by NepipenkoIgor** [comment]
@raycarter  Hi. Thank you for using ngx-mask. Please try latest version every thing works as v9.0.0 ( as expected )
Please try https://stackblitz.com/edit/angular-ivy-mask-j2fakh?file=src/app/app.component.ts
