### ISSUE TITLE
clearIfNotMatch should not clear in blur.

### ISSUE THREAD

**Issue by qwe12e** [JsDaddy/ngx-mask#745]
Hi i want to use this package for credit card number masking.

example mask : "9999 9999 9999 9999"
Current behaviour: when user writes something like "4245 48" and then the input cleans itself if the user stops focusing.

I think there should be an option for not clear on blur if the written value somewhat valid.
Think of something like this happened: You are on the phone and your friend sent a photo about phone number or in this case credit card number and as you fill out the input you may have to forget and look at the photo again and when you come back, you see the input blank. I think this is a bad experience.

**Comment by NepipenkoIgor** [comment]
Hi @qwe12e  in case with phone experience you shouldn't use clearIfNotMatch
