### ISSUE TITLE
ngx mask for dob 00/00/0000 is not allowing edge browser(version 44.1) to autofill data into input field 

### ISSUE THREAD

**Issue by oliviyajohn** [JsDaddy/ngx-mask#747]
field dob which uses ngx mask in not allowing to auto fill data in edge browser 
<input  formControlName="dob"
              inputmode="numeric"
 mask="00/00/0000"
              [specialCharacters]="['/']"
             [dropSpecialCharacters]="false" >

**Comment by sreerag509** [comment]
I too have the above issue for autocomplete for the edge (44.1) browser.

**Comment by andriikamaldinov1** [comment]
@sreerag509 @oliviyajohn Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-jy8hhv?file=src%2Fmain.ts
