### ISSUE TITLE
Cursor jumps in negative number mask

### ISSUE THREAD

**Issue by Res42** [JsDaddy/ngx-mask#748]
When programmatically setting the input value and then manually modifying a number input with negative number support, the cursor jumps before the negative sign.

When not setting the input programmatically, it works as expected.

### Version info

Angular: 9.1.9
ngx-mask: 9.1.2

### Minimal reproduction demo

<https://stackblitz.com/edit/ngx-mask-negative-number-cursor-jump-bug>

or

HTML:
```(html)
<form [formGroup]="form">
  <input formControlName="input1" type="text" mask="separator.0" [allowNegativeNumbers]="true"/>
</form>
```

TypeScript:
```(typescript)
form = this.formBuilder.group({
  input1: this.formBuilder.control(42),
})
```

#### How to reproduce

1. Set the value of the control programmatically (for example: `input1: this.formBuilder.control(42)`).
2. Clear the input by hand.
3. Type the negative sign (`-`).

The cursor will jump to before the negative sign automatically:
![ngx-mask-cursor-bug 43](https://user-images.githubusercontent.com/2495806/83608320-01540500-a57d-11ea-95d3-e013f809b9b7.png)
This causes that if you write more than one character (`-1`), then the negative sign will be removed and the value will be `1`.

A gif of the bug:
![ngx-mask-cursor-bug-2](https://user-images.githubusercontent.com/2495806/83608840-ae2e8200-a57d-11ea-9b9c-bbc6edb08317.gif)
Keys pressed:
1. Mouse left click in the input.
2. Backspace.
3. Backspace.
4. Negative sign (`-`).
5. `1`.

### Expected
I don't want the cursor to jump.

### Debug
I debugged it a little, but I don't know the library enough to create a PR for this bug.

As I see it, the programmatic value change calls the `MaskDirective.writeValue` method which sets `this._maskService.isNumberValue = true;`.
When manually modifying the value, the `MaskService._checkSymbols('-')` method will try to parse the input as a number (`return Number(separatorValue);`) which will return `NaN`, and this somehow causes the cursor jump.

### Workaround
If somebody else has this error too, set `[dropSpecialCharacters]="false"` and parse the string output of `ngx-mask` yourself.

### Duplicate
This issue may be a duplicate of #736.

**Comment by vishmay-AF** [comment]
Same happens for round braces, after typing when I continuously click backspace button to earase every thing, symbol on first location is jumped from backspace.

Regex
(000) 0000 0000

After placing backspace
from '(0|' to '|(' in single back space.
Here, consider '|' as cursor

**Comment by vishmay-AF** [comment]
possible duplicate of #692

**Comment by Res42** [comment]
I updated my repro to the latest versions (Angular 11, ngx-mask 11.1.4) and I cannot reproduce the problem with these versions.

Closing this issue.
