### ISSUE TITLE
Mask validation can't be turned off

### ISSUE THREAD

**Issue by Leccho** [JsDaddy/ngx-mask#749]
This is a bug repport. I'm using Angular 9.1.1 and ngx-mask 9.1.2

I tried pretty much any way mentionned in the documentation.

None of the example showed below have work for me.

Also, I have to turn off the validation because it detect 123-123-1234 as an error.

Method 1 & 2 turning off validation on the input tag:
```html
<input type="text" formControlName="phone" placeholder="000-000-0000" mask="000-000-0000" [validation]="false">

<input type="text" formControlName="phone" placeholder="000-000-0000" [mask]="000-000-0000" [validation]="false">
```

Method 3 & 4 turning off validation in module:
```typescript
const maskConfig: Partial<IConfig> = {
  validation: false,
};

const maskConfigFunction: () => Partial<IConfig> = () => {
  return {
    validation: false,
  };
};

@NgModule({
  imports: [
      NgxMaskModule.forRoot(maskConfig),
      NgxMaskModule.forRoot(maskConfigFunction),
  ]
})
```

**Comment by Leccho** [comment]
Let's turn this into a feature. Turns out ngx-mask works fine. The problem is that the formcontrol associated will not be updated with the mask so instead of 123-123-1234 I'll have 1231231234. So form control validation was trowing the error.

So the feature suggested is that if the input has a formControl, taht formControl would update with the mask value (or adding an option for it).

**Comment by ColinMorris83** [comment]
Are you saying you want the hyphens in your actual form control value? If that is the case then just set [dropSpecialCharacters]=false on the input

**Comment by Leccho** [comment]
Yes, that's what I meant, must have missed it in the documentation.
