### ISSUE TITLE
FormControl is getting dirty after set some value

### ISSUE THREAD

**Issue by ebastian** [JsDaddy/ngx-mask#750]
Hi,

The formControl with mask is altways getting dirty, even after resetting it or marking as untouched.
I saw that some issues have already been created concerning similar problems:
https://github.com/JsDaddy/ngx-mask/issues/711
https://github.com/JsDaddy/ngx-mask/issues/189
https://github.com/JsDaddy/ngx-mask/issues/502

Here is a sample with a similar problem:
https://stackblitz.com/edit/ngx-mask-issue-48

In my case, the problem occurs after setting a value on the control.
I'm using ngx-mask on version 8.2.0.

HTML:
```
<form [formGroup]='form'>
...
 <input pInputText type='text' formControlName='time' mask='Hh:m0' [dropSpecialCharacters]="false">
 ...
</form>
```

TS:
```
this.form = formBuilder.group({
      time: ['', [Validators.required]],
});
```
If no value is set on the control, the 'dirty' property is false.
However after a value is set:

```
console.log('before set any value: ', this.form.get('time').dirty); // false

this.form.get('time').setValue('9:55');
console.log('after set value: ', this.form.get('time').dirty); // true

this.form.get('time').reset();
console.log('after reset without value: ', this.form.get('time').dirty); // false

this.form.get('time').reset('5:45');
console.log('after reset with value: ', this.form.get('time').dirty); // true

```

I tried marking it as untouched and resetting it with value, but the dirty property remains true.

**Comment by NepipenkoIgor** [comment]
@ebastian  Hi. Thank you for using ngx-mask . For latest version everything works as expected. Your could check fork from your stackblitz https://stackblitz.com/edit/ngx-mask-issue-48-rfwyzv?file=app%2Fapp.component.html. Also if you still have an issue , bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
