### ISSUE TITLE
On iPhone the Japanese keyboard incorrect work

### ISSUE THREAD

**Issue by grifin85** [JsDaddy/ngx-mask#751]
Hi
When on iPhone you try input number on the Japanese keyboard, you have the problem with input, the cursor does not move, and input magic numbers.
P.S. There is no problem on Android

I'm using **ngx-mask: 9.1.2**

**Comment by andriikamaldinov1** [comment]
@grifin85 Thanks for using Ngx-Mask. 
We tried to reproduce this bug, but unfortunately all work as expected. 
Please try the new version 16.3.8, if it has this problem, then reopen the new issue with stackblitz
