### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by daganox** [JsDaddy/ngx-mask#752]
I can't add any accented characters with the "S" mask. Is there any trick? I tried the specialCharacters config but not working.
Thanks

**Comment by fernandoox** [comment]
I have the same problem, I need something like this:

Fernández, Á, á

Thanks! :)

**Comment by andriikamaldinov1** [comment]
@daganox @fernandoox Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-sndb7t?file=src%2Fmain.ts
