### ISSUE TITLE
Mask Not Working on Reative forms

### ISSUE THREAD

**Issue by gmartinez-aval** [JsDaddy/ngx-mask#756]
Was working fine in ngModel forms with 
**<input ... mask="0-0-0-0"></input> Works**

But reactive is not working
**<reactive-input type="text"  [control]="otpControl" mask="0-0-0-0"> </reactive-input>**

Am I missing something?

thanks

**Comment by NepipenkoIgor** [comment]
@gmartinez-aval  Thank you that using our package. It seems like you use another custom for control reactive-input. If i am right then in angular we have limitation to use to custom form controls
