### ISSUE TITLE
How to get unmasked value

### ISSUE THREAD

**Issue by kee-yankee** [JsDaddy/ngx-mask#757]
Is there a way to use the mask and have a input that indicates weather I want the model to be updated so
`<input type="tel" mask="(000) 000-0000" [updateModel]="false" [value]="1234565432">` would produce bound value being '1234565432'

`<input type="tel" mask="(000) 000-0000" [updateModel]="true" [value]="1234565432">` would produce bound value being '(123) 456-5432'

but would still display (123) 456-5432 to the user, just want control of the value to be saved

**Comment by NepipenkoIgor** [comment]
@kee-yankee it seems this what you need 
https://github.com/JsDaddy/ngx-mask#dropspecialcharacters-boolean--string
