### ISSUE TITLE
does not work totally

### ISSUE THREAD

**Issue by r-shakeri** [JsDaddy/ngx-mask#758]
hi, i've added this plugin just today on angular 9 and after lots of trying to work, there is no way to achieve...
i did what ever people said about where to add the module..... still there is no result.
so what the hell is with this plugin...

**Comment by JayAhn2** [comment]
Metoo

**Comment by r-shakeri** [comment]
Finally, I got it to work in this way... I added module to the appModule with `.forRoot()` and also added it to my feature module with `.forChild()` where I really need to use it!
And still I don't know why should I add it to the appModule too?!!!!!

**Comment by NepipenkoIgor** [comment]
@r-shakeri  @JayAhn2  Yes you need .forRoot() for add mask services to  root injector once
