### ISSUE TITLE
Just installed 9.1.2, got a compiler error

### ISSUE THREAD

**Issue by dissy123** [JsDaddy/ngx-mask#759]
ERROR in ../node_modules/ngx-mask/lib/mask.service.d.ts:30:9 - error TS1086: An accessor cannot be declared in an ambient context.

30     set formElementProperty([name, value]: [string, string | boolean]);
           ~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.


Any ideas whats wrong?

**Comment by NathanAlcantara** [comment]
@dissy123 why you close this? i got the same problem

**Comment by vspok** [comment]
estou com mesmo problema

**Comment by MansoorJafari9** [comment]
I got the same problem? could you able to fix it?
