### ISSUE TITLE
prefix wrong cursor position after delete

### ISSUE THREAD

**Issue by JisonDinAlt** [JsDaddy/ngx-mask#760]
**Problem:** 
In input with prefix, after text deleting cursor displayed before prefix.

**How to reproduce:** 
fill some value in input (with prefix), then select all and press "Backspace".

**Result:** 
cursor displayed before prefix.

**Expected Result:**
cursor should be after prefix.

**Comment by Smip** [comment]
There is an issue in the same area.
If fill some value to the input with prefix, then select all and delete. The cursor will be at the begin of input. And if after it start writing the prefix will be after the cursor.

Demo from the documentation page:

![HkwF97AnEm](https://user-images.githubusercontent.com/11481452/91663469-45599600-eae9-11ea-9e7a-c2f6d60c4dbc.gif)

**Comment by andriikamaldinov1** [comment]
@Smip @JisonDinAlt Thanks for using Ngx-mask. Please update ngx-mask to latest version.
 It example, prefix work as expected - https://stackblitz.com/edit/angular-7zkepr?file=src%2Fmain.ts

**Comment by KirstenStake** [comment]
@andriikamaldinov1 am experiencing this same issue with package version **14.2.4**. our codebase is tied to Angular 14, are the latest versions with this bug fix compatible?
