### ISSUE TITLE
update for angular 10 - WARN

### ISSUE THREAD

**Issue by andrejm7** [JsDaddy/ngx-mask#762]
npm WARN ngx-mask@9.1.2 requires a peer of @angular/common@^9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mask@9.1.2 requires a peer of @angular/core@^9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-mask@9.1.2 requires a peer of @angular/forms@^9.1.0 but none is installed. You must install peer dependencies yourself.

**Comment by prolrafael** [comment]
Same here.

**Comment by gongAll** [comment]
Any news regarding this issue?

**Comment by dfleser** [comment]
Hello, when will this be fixed?

**Comment by dfleser** [comment]
🎺

**Comment by NepipenkoIgor** [comment]
@andrejm7 @prolrafael @gongAll @dfleser Hi all .Just published  ngx-mask@10.0.1

**Comment by dfleser** [comment]
> @andrejm7 @prolrafael @gongAll @dfleser Hi all .Just published ngx-mask@10.0.1

Thanks
