### ISSUE TITLE
Copy-Paste does not position the cursor at the end

### ISSUE THREAD

**Issue by denisian** [JsDaddy/ngx-mask#765]
Hi, I have the same issue with version 9.1.2 as described here https://github.com/JsDaddy/ngx-mask/issues/131.
When I use a mask, i.e. "00 - 0000 - 00000" and paste a number "123456789", it places the cursor in the middle of the number instead of the end of input. Thank you.

**Comment by StepaZol** [comment]
I get this problem with mask (000) 000-00-00

**Comment by NepipenkoIgor** [comment]
@denisian  @StepaZol  Thank you for using our package. Please try v11.1.0
