### ISSUE TITLE
NullInjectorError: No provider for InjectionToken config!

### ISSUE THREAD

**Issue by ahmedsaidzahran** [JsDaddy/ngx-mask#766]
When try to user ngx-mask in modal, it gave me this error 
@NullInjectorError: No provider for InjectionToken config!

**Comment by Warkst** [comment]
Check if you have properly imported the module using the `forRoot` method, and that you import it in the correct module (in which the component where you want to use the mask is declared).

**Comment by dmaf87** [comment]
ngx-mask works well in my first project, but got same problem as @ahmedsaidzahran in new project.

**Comment by NepipenkoIgor** [comment]
@ahmedsaidzahran  @dmaf87  Please check how you declare mask . In root module you should declare `NgxMaskModule.forRoot()` .  Also in another modules that you import in root and want to use mask inside `NgxMaskModule`
