### ISSUE TITLE
'Delete' button work incorrectly

### ISSUE THREAD

**Issue by stricozetc** [JsDaddy/ngx-mask#767]
Hi, I use Angular 9, ngx-mask 9.1.2 version, Google Chrome version 84.0.4147.89. Bug reproduced in input fields that have a custom mask (for example, in attach). When I press 'Delete' button, cursor moves to one character forward and remove previous character(same is 'Backspace' button work)
![image](https://user-images.githubusercontent.com/38862520/87686461-30b97c80-c78d-11ea-8815-81b4ae98db21.png)

**Comment by andriikamaldinov1** [comment]
@stricozetc  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-sjvtu5?file=src%2Fmain.ts
