### ISSUE TITLE
Incorrect behavior if you try to delete text

### ISSUE THREAD

**Issue by kovaldenys96** [JsDaddy/ngx-mask#770]
Steps to reproduce:

Type some text to any input with mask (in my case it's mask="00" and mask="0000").
Select all text in the input through either CTRL + A or by holding the left mouse button and dragging the mouse.
Clear the text by pressing backspace.
Expected behavior: the FormControl and input value are empty

Actual behavior: the FormControl is empty but input has value.

I know that the issue duplicates https://github.com/JsDaddy/ngx-mask/issues/200. But the issue was closed without fixing.

**Comment by NepipenkoIgor** [comment]
@kovaldenys96  Hi 
![ezgif-5-2f0fff893c83](https://user-images.githubusercontent.com/7725146/89897343-898f0000-dbe7-11ea-8131-5d16fac24b72.gif)
It seems work as expected

**Comment by dmytropanontko** [comment]
Hi @NepipenkoIgor
Thanks for your replay. Could you provide a link with code which you use for example? It will be good to have some similar to this one https://stackblitz.com/

**Comment by NepipenkoIgor** [comment]
@dmytropanontko  please play with https://stackblitz.com/edit/angular-ivy-vxcd1z
