### ISSUE TITLE
Dynamic Mask doesn't work for UK Post Codes

### ISSUE THREAD

**Issue by aivascu** [JsDaddy/ngx-mask#772]
I am trying to create a dynamic mask that would handle the [UK post codes](https://ideal-postcodes.co.uk/guides/uk-postcode-format). 
In terms of this library, I am trying to handle this dynamic mask `S0 0SS||SAA 0SS||SS0A 0SS`.
I checked the unit tests and they do fail for this scenario in the moment when a second character symbol is added to the input.

```ts
it('Dynamic Masks POST_CODE', () => {
  component.mask = 'S0 0SS||SAA 0SS||SS0A 0SS';
  equal('', '', fixture); // passes
  equal('A', 'A', fixture); // passes
  equal('AB', 'AB', fixture); // fails
  equal('AB17NC', 'AB1 7NC', fixture); // fails
});
```

#### Expected
`AB17NC` -> `AB1 7NC`

#### Actual
Fails on `AB`

**Comment by andriikamaldinov1** [comment]
Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-uymew3?file=src%2Fmain.ts

**Comment by aivascu** [comment]
@andriikamaldinov1 thank you! I posted this 3 years ago. I don't even remember what this is. 😅
