### ISSUE TITLE
Dynamic mask does not work as output pipe

### ISSUE THREAD

**Issue by ekalin** [JsDaddy/ngx-mask#773]
Given a mask `'(00) 0000-0000||(00) 00000-0000'`. It works fine in an input component, but when used as an output pipe for display, the last number is not displayed.

You can see the problem at https://stackblitz.com/edit/angular-ivy-ptq7pg

**Comment by mauricioat1902** [comment]
I have the same issue

**Comment by eestein** [comment]
Same problem, what I ended up doing was to check the length of the item and apply the proper mask.

```
myMask: string;
...
this.myMask = formValue.length === x ? maskX : maskY;
```
No ideal, but works for my case.

**Comment by dineikill** [comment]
I have the same issue

**Comment by cokita** [comment]
Same in here!!!

**Comment by andriikamaldinov1** [comment]
@cokita @dineikill @eestein @ekalin @mauricioat1902 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-dz4pxd?file=src%2Fmain.ts
