### ISSUE TITLE
New functional

### ISSUE THREAD

**Issue by marshallcompany** [JsDaddy/ngx-mask#775]
Hello. Make it possible to configure the plugin so that the mask behaves when the user enters the date like this: 09.MM.YYYY. That is, when the user entered the first two digits, his DD-date changed to 09, and so on. Thank you so much !

**Comment by NepipenkoIgor** [comment]
@marshallcompany  Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
