### ISSUE TITLE
Date mask with optional leading zeroes

### ISSUE THREAD

**Issue by nikhilgoud** [JsDaddy/ngx-mask#779]
I'm using the date mask for mat-date
`<input
      class="date"
      matInput
      autofocus
      [formControl]="dateCtrl"
      (blur)="onDateInputChange($event)"
      [patterns]="customPatterns" [showMaskTyped]="true"
      [mask]="dtmask"
    />
`

I was using `M0/d0/0000` initially which is good, However, I have to make month and day to accept values without `0`s. Can someone provide links to documentation(can't find)? 
the mask should accept values for (`JAN 01 2021: M/d/yy 1/2/21`)
`01/02/21`
`01/2/21`
`1/02/21`
`1/2/21`

I tried various possible mask values but of no use.
`M9/d9/yy`
`M/d/yy`
even tried to add customPattern
`public customPatternsMDY = {
    M: { pattern: new RegExp('([1-9])|(0[123]|1[0-9])') },
    D: { pattern: new RegExp('([1-9])|(0[1-9]|1[012])') },
    Y: { pattern: new RegExp('\\d{2}') },
  };`

Slackblitz link: [https://stackblitz.com/edit/mat-date-custom-formats](https://stackblitz.com/edit/mat-date-custom-formats?file=src/app/multi-lang-date/multi-lang-date.component.html)

Please let know of any possible solution

**Comment by codeSumanth** [comment]
Is there any work around for this ? I am also facing same issue in the app

**Comment by asnow73** [comment]
I also need such functionality. I have made PR https://github.com/JsDaddy/ngx-mask/pull/810
