### ISSUE TITLE
dropSpecialCharacters not working (always false)

### ISSUE THREAD

**Issue by cheapfun** [JsDaddy/ngx-mask#782]
Hello,

As of version 9.0.0, the dropSpecialCharacters property is always "false".

Everything works very well with version 8.2.0: I can apply a mask, and the special characters are well removed in the model.
But from version 9.0.0, this doesn't work anymore.

I noticed that on your site you can see this behavior:
https://jsdaddy.github.io/ngx-mask-page/main
In all your examples, the FormControl and NgModel values are are exactly the same.

**Comment by john-gilmer** [comment]
I have the same problem. I have this input:

<input type="text" [(ngModel)]="whatever" mask="separator.2" thousandSeparator="," [dropSpecialCharacters]="true">

But I want the input to removes the commas (thousand separators) when it puts the value in the model. This works with version 8 of ngx-mask but not with version 9 or 10. Is there any workaround?
Thanks

**Comment by nutman** [comment]
Hi @cheapfun @john-gilmer ,
Could you put more examples and steps to reproduce?
I have checked how it works and in the model, commas are removed.
You can open the `src/app/showcase/showcase.component.html` file in the packed and test your cases locally

**Comment by NepipenkoIgor** [comment]
@john-gilmer  @cheapfun  Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag

**Comment by troquatte** [comment]
Hello guys.

Solution of my code: 

if(isAlphanumeric){
    customPatternsMask = { '0': { pattern: new RegExp("\\S")} };
} else {
    customPatternsMask = { '0': { pattern: new RegExp("\[0-9\]")} };
}
