### ISSUE TITLE
Mask error don't show in production

### ISSUE THREAD

**Issue by hoangthai1331995** [JsDaddy/ngx-mask#783]
when i use formcontrol check error, i see 'Mask error' on formcontrol.error (enviroment localhost).
but in env production i see mask: {actualValue: "2", requiredMask: "000 000 0000"} on formcontrol.error, pls help me

**Comment by NepipenkoIgor** [comment]
@hoangthai1331995  Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
