### ISSUE TITLE
AllowNegativeNumbers param works only with separator.2

### ISSUE THREAD

**Issue by prosto-artem** [JsDaddy/ngx-mask#785]
Hello!

I have an issue, when i'm trying to combine simple mask (for example and mask="00.00") and negative numbers.
https://stackblitz.com/edit/angular-10-base-template-5rd66c?file=src/app/app.component.html

As you can see, input param "allowNegativeNumbers" has no effect

**Comment by yesparthasarathy** [comment]
PLEASE use separator.2 with separatorLimit for your case. allowNegativeNumbers as of now working with  "separator" type mask only. not with "00.00"..

**Comment by andriikamaldinov1** [comment]
@prosto-artem @yesparthasarathy Thank you for using ngx-mask. Please update ngx-mask to latest version.
U can use allowNegativeNumbers with all of mask. 
https://jsdaddy.github.io/ngx-mask/#11
