### ISSUE TITLE
mask "099.09" incorrect behavior 

### ISSUE THREAD

**Issue by prosto-artem** [JsDaddy/ngx-mask#786]
Hi!

stackblitz with description below.
https://stackblitz.com/edit/angular-10-base-template-bvejgc?file=src/app/app.component.html

input value 123.45 works perfectly fine, but if you're gonna try to type value 1.2 you'll see the problem.

**Comment by stormwin** [comment]
I have exactly the same problem.
my mask is: 099.00099999999999
What i need is phone numbers including country code in this format: +xxx.xxxxxxxxxx or it may be +xx.xxxxxxxxx or +x.xxxxxxxxxx

**Comment by v-skochko** [comment]
Same problem for me on the latest version (11.1.4)
I discovered that problem appears on all version starting from 8.0 (after introducing prefixes and suffixes)

**Comment by andriikamaldinov1** [comment]
@stormwin @v-skochko  @prosto-artem Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-c45srx?file=src%2Fmain.ts
