### ISSUE TITLE
How to get negative currency value.

### ISSUE THREAD

**Issue by yesparthasarathy** [JsDaddy/ngx-mask#788]
I would like to type "-" first and then numbers. if the input is -4000 , it should get -$4000 as output. if I use the prefix as "$"
and mask ="0000.00". I am getting $-4000 as result. please help on this.

**Comment by andriikamaldinov1** [comment]
@yesparthasarathy Thanks for using Ngx-mask. Please update to latest version.
It example for your case - https://stackblitz.com/edit/angular-n9xfok?file=src%2Fmain.ts
