### ISSUE TITLE
How can I create the mask for currency?

### ISSUE THREAD

**Issue by bretbas** [JsDaddy/ngx-mask#789]
I want to create mask for currency, but I can't.
I tried `mask="0{1,8}.00{2}"` but it does not work.
I want to constraint whole part of number by 8 digits, but I can't

Please help me

**Comment by bretbas** [comment]
Sorry for my carelessness.
I found:
```
prefix="₽"
mask="separator.2"
separatorLimit="10000000"
```

**Comment by NepipenkoIgor** [comment]
@bretbas Thank you that using our package
