### ISSUE TITLE
IP Mask and Reactive Form Value

### ISSUE THREAD

**Issue by mchallenger88** [JsDaddy/ngx-mask#790]
I'm using mask="IP" in an Angular Reactive Form. It works great for displaying values, but when I get the value from the control the dot separators are missing. So, for example, 192.168.34.155 becomes 19216834155 when I console.log the formcontrol.value. How do I get the masked value since there is no way to properly insert the dot separators?

**Comment by fpmk** [comment]
Use [dropSpecialCharacters]="false"

**Comment by mchallenger88** [comment]
Thanks. I'll try that. I ended up using @ViewChild...ElementRef, which allowed me to get the full value, but it felt a bit hackish.

**Comment by NepipenkoIgor** [comment]
@mchallenger88 @fpmk  Yes you should use dropSpecialCharacters property

**Comment by heyline** [comment]
Whoever invented this project is a genius
