### ISSUE TITLE
Number cast bug

### ISSUE THREAD

**Issue by eggp** [JsDaddy/ngx-mask#791]
## Error details:
In this case, if you initialize FormControl with values of number type and 2 decimal places, the type of stored values changes to string. For this I created a patch in which we automatically detect the separatorLimit value and cast the Number.toFixed (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed return value type is string) to a number.

---
[Demo stackblitz example](https://stackblitz.com/edit/angular-ivy-rmzynl?file=src/app/app.component.ts)
If we comment on lines 9-21 in the main.ts, the error occurs: in the first field a decimal value has to be deleted and the value stored in control becomes a string type. Putting the patch back on solves this.

**Comment by NepipenkoIgor** [comment]
@eggp Thank you for using library. Please try version v11.1.1
