### ISSUE TITLE
mask for words with specific special characters not working

### ISSUE THREAD

**Issue by Reaver86** [JsDaddy/ngx-mask#798]
What I'm trying to build is an input for a firstname, let's say up to 10 characters in total, only letters, space, - and ' allowed.
I'm seeing no way to solve this using ngx-mask, here's a minimal example:

https://angular-ivy-sot14p.stackblitz.io

with mask="S" it seems like the specialCharacters input doesn't do anything. It's only possible to input letters.

**Comment by ColinMorris83** [comment]
https://github.com/JsDaddy/ngx-mask/blob/develop/src/app/showcase/showcase.component.html

Look for Custom Pattern with special characters

Surname pattern used is in here: https://github.com/JsDaddy/ngx-mask/blob/develop/src/app/showcase/showcase.component.ts

**Comment by Reaver86** [comment]
thanks a lot, that works perfectly!

this is what I ended up with:
`<input mask="N{100}" [specialCharacters]="[]" [patterns]="namePatterns" [validation]="false"/>`

I couldn't find that documentation and think it should be included on the README. I can prepare a PR for that, would that be useful?

As a feature request, it would be great if mask would also accept N{1,100} for more regex-y control. I know I can also include the pattern Input with the same base regex as in [patterns], but I feel like that code isn't very clean.
