### ISSUE TITLE
"Delete" is not behaving as expected when using mask with spaces

### ISSUE THREAD

**Issue by juanwhite99** [JsDaddy/ngx-mask#799]
**Test cases:**

- If you write a value like '123 45 6789', then set the pointer at the beginning of the text and press "delete" the last digit is the one that will be deleted like this '123 45 678'

- If you set the pointer at any position that is not the beginning nor the end of the text when the input is filled i.e. between 4 and 5 in '123 45 6789' and press "delete" the value that will be deleted is backwards (in this case 4) resulting in '123 56 789' instead of '123 46 789'

- If you set the pointer inmediatelly after any space at any position that is not the beginning nor the end of the text when the input is filled i.e. between 3 and 4 in '123 45 6789' and press "delete" the value that will be deleted is backwards (in this case the space) then the text will be formatted as nothing had happened but the pointer will walk one position forwards and end between 4 and 5 in this example

- If you set the pointer in any position of the text (i.e. between 4 and 5 in '123 45 6789') and then press any digit (0-9) the last character of the string will be deleted and the pressed key value will be introduced in that position. (i.e. if press 6 between 4 and 5 the last character 9 will be deleted and the result will be '123 46 5678') 

https://stackblitz.com/edit/ngx-mask-for-ssn

**Comment by andriikamaldinov1** [comment]
@juanwhite99 Thanks for your using Ngx-Mask. Please update to latest version.
It example, delete work as expected -https://stackblitz.com/edit/angular-bjvnoj?file=src%2Fmain.ts
