### ISSUE TITLE
ERROR in node_modules/ngx-mask/lib/mask.service.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by malapati-suresh** [JsDaddy/ngx-mask#800]
I'm using Ngxmaskmodule but the above issue is coming local code like Vs code,

**Comment by fmorikawa** [comment]
Same here!

**Comment by NepipenkoIgor** [comment]
@malapati-suresh  @fmorikawa  Сould you share your dependencies and environment config . Also it is very difficult understand what is wrong
