### ISSUE TITLE
ngx-mask not working when we enable / disable the form control.

### ISSUE THREAD

**Issue by udayraj21** [JsDaddy/ngx-mask#803]
At the time of form building, I  set a form control to disable state using `phoneNumber: [{ value: '', disabled: true }]`.
But when I re-enable that form control, mask does not work. I re-enabled the form control using `this.form.controls.phoneNumber.enable();`

**Comment by NepipenkoIgor** [comment]
@udayraj21  Fixed in v.11.0.1 . Please try.
