### ISSUE TITLE
Impossible to do custom pattern

### ISSUE THREAD

**Issue by kbeaux** [JsDaddy/ngx-mask#805]
Hi, i am on version 10.0.1 and i'm trying to use a custom pattern.

in html 
        <input
          matInput
          [formControlName]="data?.id"
          mask="PPPPPPPP-PPPP-PPPP-PPPP-PPPPPPPPPPPP"
          [pattern]="customPatterns"
          [dropSpecialCharacters]="false"
          placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
          type="text"
        />

in ts : 

  public customPatterns = { P: { pattern: new RegExp('\[a-fA-F0-9\]')}};

i tried with many RegExp different and nothing seems to work.
when i change P by 0 or A i get a "regex.test is not a function" error.

What can i do for making it work please ?

**Comment by Andr1yk0** [comment]
I think changing  `[pattern] = "customPatterns"` to `[patterns] = "customPatterns"` should fix the problem

**Comment by NepipenkoIgor** [comment]
Yes @Andr1yk0  you a right .  @kbeaux  you should use right property for binding `[patterns]="yourCustomPattern"`
