### ISSUE TITLE
TypeError: Cannot read property 'firstCreatePass' of null TypeError: Cannot read property 'firstCreatePass' of null

### ISSUE THREAD

**Issue by juan291181** [JsDaddy/ngx-mask#806]
Hello, I'm on Angular 10.1.3, woking with Material IO and when I fill the tag mask in an Imput I always receve the same message and the page is not shown, in attached an example of the Imput and the error message.

Let me know if you need further information

![example2](https://user-images.githubusercontent.com/3452510/94578886-d5e8da80-023d-11eb-9b97-e64bef9c1327.JPG)
![example1](https://user-images.githubusercontent.com/3452510/94578891-d7b29e00-023d-11eb-9664-4e57227691b2.JPG)

Thank!

**Comment by NepipenkoIgor** [comment]
@juan291181 Thank you for using our package. It seems like problem in code base of your application because no method with name firstCreatePass relative to ngx-mask . You could provide more complex explanation but better to do this on stackoverflow with tag ngx-mask

**Comment by xyos** [comment]
If anyone gets this error again just restart your dev server.
