### ISSUE TITLE
Optional [patterns] value

### ISSUE THREAD

**Issue by Fiercekilla** [JsDaddy/ngx-mask#808]
In my case i have `@Input() customPattern?: IConfig['patterns']`

But i cant use optional [patterns] attribute because IConfig['patterns'] model cant be null or undefined

**Comment by NepipenkoIgor** [comment]
@Fiercekilla  Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
