### ISSUE TITLE
mask="separator", typing dot deletes numbers

### ISSUE THREAD

**Issue by Azemoten** [JsDaddy/ngx-mask#809]
![dot-bug](https://user-images.githubusercontent.com/38835724/95007553-dc5ac600-0632-11eb-9e95-4d9a274eb09f.gif)

`"dependencies": {
    "@angular/animations": "~10.1.4",
    "@angular/common": "~10.1.4",
    "@angular/compiler": "~10.1.4",
    "@angular/core": "~10.1.4",
    "@angular/forms": "~10.1.4",
    "@angular/platform-browser": "~10.1.4",
    "@angular/platform-browser-dynamic": "~10.1.4",
    "@angular/router": "~10.1.4",
    "ngx-mask": "^10.0.4",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },`

**Comment by NepipenkoIgor** [comment]
@Azemoten  Thank you for using our package . Can't reproduce. It seems like everything works as expected 
https://stackblitz.com/edit/angular-ivy-8f5ds7?file=src%2Fapp%2Fapp.component.html
 But If you steel have an issue  please create new one from template . If it is a question please use stackoverflow with ngx-mask tag
