### ISSUE TITLE
Presenting data

### ISSUE THREAD

**Issue by renanBritz** [JsDaddy/ngx-mask#81]
Hello.

Does this package include some sort of helpers to present data? I intend to store data in a raw format and present it with masks to the user, so that would require something like a masks pipe maybe... Is there anything built in? I couldn't find documentation on that.

Thank you!

**Comment by NepipenkoIgor** [comment]
@renanBritz Thank you for question.  In my opinion it is good idea to make some pipe . We will add this in next releases

**Comment by NepipenkoIgor** [comment]
@renanBritz @ghiscoding  You could try new 6.0.0 version
