### ISSUE TITLE
mask validate date on form fails tests

### ISSUE THREAD

**Issue by theswandog** [JsDaddy/ngx-mask#811]
"@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
"ngx-mask": "^9.1.4",

I have a form with an input guarded by a mask.
`<input type="text" class="form-control" id="dobFilter" formControlName="dobFilter" placeholder="mm/dd/yyyy" mask="m0/d0/0000" [dropSpecialCharacters]="false" />`

the test value for 44/44/2020 is seen as valid which is incorrect.  this test passed using ngx-mask@8.2.0 
`fit("validates dob", () => {
        let filterValue = { dobFilter: "44" };
        component.filterFormGroup.patchValue(filterValue);
        expect(component.filterFormGroup.valid).toBeFalsy();

        filterValue = { ...filterValue, dobFilter: "44/44/2020" };
        component.filterFormGroup.patchValue(filterValue);
        expect(component.filterFormGroup.valid).toBeFalsy();

        filterValue = { ...filterValue, dobFilter: "01/02/2020" };
        component.filterFormGroup.patchValue(filterValue);
        expect(component.filterFormGroup.valid).toBeTruthy();
    });`

**Comment by andriikamaldinov1** [comment]
@theswandog Thank you for using ngx-mask. Please update ngx-mask to latest version.

https://stackblitz.com/edit/angular-ngbh66?file=src%2Fmain.ts
