### ISSUE TITLE
Asterisk in masks prevents the validation 

### ISSUE THREAD

**Issue by jonaskistler** [JsDaddy/ngx-mask#812]
I tried to implement an email mask with this pattern: `A*@A*.SSS`

When you start typing any character in the field, the validation accepts immediately the value, even if you do not write a @ character or a dot.

The validation should fail as long as no @ or no dot is in the text, or the dot is not followed by 3 characters

**Comment by logic01** [comment]
Just so you are aware A*@A*.SSS  does not cover all possible emails. It's not even close. Something simple like test.test@test.com or even the common gmail test+test@gmail.com.


**List of Valid Email Addresses**

email@example.com
firstname.lastname@example.com
email@subdomain.example.com
firstname+lastname@example.com
email@123.123.123.123
email@[123.123.123.123]
"email"@example.com
1234567890@example.com
email@example-one.com
_______@example.com
email@example.name
email@example.museum
email@example.co.jp
firstname-lastname@example.com


**List of Strange Valid Email Addresses**

much.”more\ unusual”@example.com
very.unusual.”@”.unusual.com@example.com
very.”(),:;<>[]”.VERY.”very@\\ "very”.unusual@strange.example.com

**Comment by mikaelboff** [comment]
any updats? @Thegrep01 @NepipenkoIgor

**Comment by andriikamaldinov1** [comment]
@jonaskistler @mikaelboff @logic01 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-wnctvj?file=src%2Fmain.ts
