### ISSUE TITLE
patchValue not working

### ISSUE THREAD

**Issue by silvl** [JsDaddy/ngx-mask#813]
patchValue (or setValue) is not working and leaving the old value (NOTE: I have [showMaskTyped]=false)
The issue is when writeValue() is calling applyMask, applyMask is keeping the old value.

I am using ngx-mask v9.1.4

The problem is in this area of the code. Note, since this.actualValue.length is > 0 it will NOT take the new input value....

        if (this.hiddenInput !== undefined) {
            let actualResult = this.actualValue.split('');
            inputValue !== '' && actualResult.length
                ? typeof this.selStart === 'number' && typeof this.selEnd === 'number'
                    ? inputValue.length > actualResult.length
                        ? actualResult.splice(this.selStart, 0, getSymbol)
                        : inputValue.length < actualResult.length
                            ? actualResult.length - inputValue.length === 1
                                ? actualResult.splice(this.selStart - 1, 1)
                                : actualResult.splice(this.selStart, this.selEnd - this.selStart)
                            : null
                    : null
                : (actualResult = []);
            newInputValue = this.actualValue.length ? this.shiftTypedSymbols(actualResult.join('')) : inputValue;
        }

**Comment by BGBRWR** [comment]
https://github.com/JsDaddy/ngx-mask/blob/6377c2054ec22218f5671a4a1066408e87f882b9/projects/ngx-mask-lib/src/lib/mask.service.ts#L54

**Comment by silvl** [comment]
Hi @BGBRWR,
I see you have commented above.  Do you know how to resolve the issue?

**Comment by NepipenkoIgor** [comment]
@silvl @BGBRWR  Please check latest version. Can't reproduce issue 
https://stackblitz.com/edit/angular-ivy-vuq6fg?file=src/app/app.module.ts

**Comment by BGBRWR** [comment]
Looks good 👌

**Comment by AnatoliiDev** [comment]
How I see patchValue is not working in v15
https://stackblitz.com/edit/angular-1vasnw?file=src/app/app.component.html
