### ISSUE TITLE
How can I ignore the characters "h", "m", "s"?

### ISSUE THREAD

**Issue by RoxVell** [JsDaddy/ngx-mask#815]
I need a mask like this: '00 h. 00 min. 00 sec.'
I pass specialCharacters like this: [' ', '.', 'h', 'm', 'i', 'n', 's', 'e', 'c']. But it doesn't work.

**Comment by andriikamaldinov1** [comment]
@RoxVell Thanks for your using Ngx-Mask. 
It example, all work as expected - https://stackblitz.com/edit/angular-ogme8l?file=src%2Fmain.ts
