### ISSUE TITLE
Mixed mask d0/M0/0000 dissue

### ISSUE THREAD

**Issue by mattiLeBlanc** [JsDaddy/ngx-mask#816]
Hi,

Great library!
I was looking at the mixed mask: https://jsdaddy.github.io/ngx-mask-page/mask-component#mixed
and I noticed that I can break it by by typing 45123456 and just keep typing and it is adding 5 numbers to the year part.
![Oct-27-2020 22-13-08](https://user-images.githubusercontent.com/5285035/97294155-bcb96500-18a1-11eb-88ff-de5fc4d74be0.gif)

I have installed the latest version today.
Am I doing anything wrong or is this a bug?

**Comment by andriikamaldinov1** [comment]
@mattiLeBlanc Thank you for using ngx-mask. Please update ngx-mask to latest version.
https://stackblitz.com/edit/angular-dita8h?file=src%2Fmain.ts
