### ISSUE TITLE
OR condition in mask propery

### ISSUE THREAD

**Issue by r-shakeri** [JsDaddy/ngx-mask#817]
hello, i'm curious to know is there any plan to add `Or` condition to the mask or not? cause i need something like: `mask="SA*|00000000000"`.
or is there any way to define a complete pattern like: 
`public customPatterns = { 'USERNAME': { pattern: new RegExp(/^[a-zA-Z][a-zA-Z0-9]*$|^\d{11}$/)} };` then in mask:
`mask="USERNAME"`

**Comment by dandenton** [comment]
To `or` a mask you can use ||.

```
<input mask="000.000.000-00||00.000.000/0000-00" />
<input mask="(00) 0000-0000||(00) 0 0000-0000" />
```

See [Dynamic masks](https://github.com/JsDaddy/ngx-mask#dynamic-valid-mask)

**Comment by r-shakeri** [comment]
i tried that but does not work in any other pattern except yours! e.g. `mask="S*||00000000000"`

**Comment by NepipenkoIgor** [comment]
@r-shakeri  Thank you that using our package. If this issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
