### ISSUE TITLE
number input not parsed/displayed correctly with global decimalMarker/thousandSeparator config

### ISSUE THREAD

**Issue by lkoe** [JsDaddy/ngx-mask#825]
If decimalMarker/thousandSeparator is configured globally, input decimal numbers are not parsed/displayed correctly

Using:
```
export const maskConfig: Partial<IConfig> = {
    thousandSeparator: ".",
    decimalMarker: ","
};
```
An input number `1234.56` (actual ts number value) becomes `123.456` in the input field, expected is `1.234,56`.

It works correctly though, if thousandSeparator/decimalMarker is configured explicitly at the input field.

The issue can be viewed here: https://stackblitz.com/edit/ngx-mask-hwj1ep

**Comment by lramondev** [comment]
Me too!

**Comment by lramondev** [comment]
From what I saw the model has to be in accordance with the config ...  =/
Ex: 1000.58 = 1,000.58

**Comment by lramondev** [comment]
https://www.npmjs.com/package/ngx-currency

**Comment by norivanoliveira** [comment]
**Me too!**

**Comment by andriikamaldinov1** [comment]
@lkoe @norivanoliveira @lramondev Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-nr36ab?file=src%2Fmain.ts

**Comment by lramondev** [comment]
> @lkoe @norivanoliveira @lramondev Thanks for your using Ngx-Mask. Please update to latest version. It example, all work as expected - https://stackblitz.com/edit/angular-nr36ab?file=src%2Fmain.ts

Not Working. 
input an integer value
example: 1000
expected: 1.000,00
result: 1.000

**Comment by lramondev** [comment]
Nice. Thanksss!
