### ISSUE TITLE
Cannot get mask to output in decimal columns before integer columns

### ISSUE THREAD

**Issue by zukaru** [JsDaddy/ngx-mask#827]
Hello folks,

I am trying to create a mask for currency input that does the following:

Input 1
Mask 0.01

Input 12
Mask 0.12

Input 123
Mask 1.23

Input 1234
Mask 12.34

Input 12345
Mask 123.45

Input 123456
Mask 1,234.56

My current solution starts in the 1 column as integer

Input 1
Mask 1

`<input mask="separator.2 decimal.2" decimalMarker="."  thousandSeparator="," >`

Thanks for your time.

**Comment by andriikamaldinov1** [comment]
Dublicate #733
