### ISSUE TITLE
Suffix issue when deleting a part of it

### ISSUE THREAD

**Issue by nicorivat** [JsDaddy/ngx-mask#831]
# 🐞 bug report

### Is this a regression?

No

### Description

Hey guys ! I'm currently facing an issue with the suffix. When I select all my value and a part of the suffix and I press delete, the non-deleted part of the suffix is added to my ngModel (or form).

![ngx-mask-issue](https://user-images.githubusercontent.com/15010744/100237260-f9bf5880-2f2e-11eb-996d-c6877aa62bc3.gif)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mask-a3brvs

Steps to reproduce:
- Type (for example) "10A" in the input.
- Select from the start to the middle of the suffix.
- Press delete or backspace key.

## 🌍 Your Environment

**Angular Version:**
</code></pre>
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@angular/cdk                    10.2.1
@schematics/angular             10.1.2
@schematics/update              0.1001.2
ng-packagr                      10.1.0
rxjs                            6.6.3
typescript                      3.9.7

**Anything else relevant?**

I have cloned the repo, found a fix and try to push a branch to make a PR,  but unfortunately I don't have the permissions required.

**Comment by NepipenkoIgor** [comment]
@nicorivat Hi . Thank you for request an issue. We will look but if you want to open merge request you should fork repo and then open request from you fork.
