### ISSUE TITLE
Unable to customise placeHolderCharacter 

### ISSUE THREAD

**Issue by KirstenStake** [JsDaddy/ngx-mask#834]
Using placeHolderCharacter with a custom input still only displays the default _ in my view.

Code:
` <div class="label-float">
              <input type="tel" formControlName="dob" placeholder=" " mask="00/00/0000" [showMaskTyped]="true"
                placeHolderCharacter="*" [dropSpecialCharacters]="false" />
              <label>{{ 'Date of birth (DD/MM/YYYY)' | translate }}</label>
            </div>`

Ideally wanting to use a space.

1. Is a space allowed as the placeHolderCharacter?
2. Tried with exact example given in the docs (*) and also still displaying _ only

Angular CLI: 11.0.2
Node: 10.16.0
OS: darwin x64

Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)
rxjs                         5.5.11
typescript                   2.6.2

**Comment by NepipenkoIgor** [comment]
@KirstenStake  Hi . Thank you for using ngx-mask. Everything works as expected you could try and play https://stackblitz.com/edit/angular-ivy-mask-euyvlk?file=src/app/app.component.html
