### ISSUE TITLE
0*.00 is not working

### ISSUE THREAD

**Issue by lokeshdaiya** [JsDaddy/ngx-mask#835]
# 🐞 bug report

### Description
I want to mask a number in currency format using 0*.00.

Input : 12345
output: 123.45

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ngx-mask-currency-demo

## 🌍 Your Environment

**Angular Version:**

10.2.3

**Comment by AshotAleqs** [comment]
Hi @lokeshdaiya,

you can do like  this.
 
<input [(ngModel)]="val" mask="separator.2" thousandSeparator=","/>       // format is 000,000.00
<input [(ngModel)]="val"   mask="separator.2" thousandSeparator=""/>     // format is 000000.00

here is the working example.
https://stackblitz.com/edit/angular-ngx-mask-currency-demo-jsbwaj?file=src/app/app.component.html

**Comment by NepipenkoIgor** [comment]
@lokeshdaiya  Hi @AshotAleqs  totally right for your needs `separator.2` will be right choose
