### ISSUE TITLE
placeHolderCharacter to actually be a set of characters.

### ISSUE THREAD

**Issue by ecthelion07** [JsDaddy/ngx-mask#836]
# 🚀 feature request

### Description

At the moment it looks like we just can have a single placeHolderCharacter. So, if we have a date mask 00/00/0000 and showMaskTyped is enabled we currently see __ / __ /____ => 12 / __ /____ as the visible mask while the user is adding input.

### Describe the solution you'd like

I'd like to be able to show dd/mm/yyyy => 12/mm/yyyy   as the visible mask while the user is typing the date so that the user has a better experience.

**Comment by sumegha26** [comment]
+1
Any update on this ?

**Comment by andriikamaldinov1** [comment]
@sumegha26 @ecthelion07  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected -  https://stackblitz.com/edit/angular-5zfu6a?file=src%2Fmain.ts
