### ISSUE TITLE
Date formatting does not work correctly if month is placed before day

### ISSUE THREAD

**Issue by mounitsyna** [JsDaddy/ngx-mask#837]
# 🐞 bug report

### Is this a regression?

 No

### Description

 mask value d0/M0/0000 works as expected, with either one or two digits allowed in the month and day positions, however if the mask is written as M0/d0/0000 then one or two digits are allowed in the first (month) position, but one digit is not allowed in the day position and the input refuses to take the '/' delimiter until a second digit is entered

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/ngx-mask-qqyxzi?file=src/app/app.component.html

## 🌍 Your Environment

**Angular Version:**

<pre><code>11.0.4
also observed in 10.x.x
</code></pre>

**Comment by cmb0335** [comment]
Is there any update on this issue? This is a big problem if you can't use month/day/year format

**Comment by randysimplist** [comment]
Having the same problem!

**Comment by elementalPRESS** [comment]
I can confirm this issue with Angular 15 and date formats like 0000-M0-d0. In Angular 14 this was still working properly.

**Comment by andriikamaldinov1** [comment]
@mounitsyna @cmb0335 @randysimplist @elementalPRESS   
Thank you for using ngx-mask. Please update ngx-mask to latest version.
https://stackblitz.com/edit/angular-awcvr8?file=src%2Fmain.ts
