### ISSUE TITLE
valueChanges is fired unnecessarily

### ISSUE THREAD

**Issue by rafaelss95** [JsDaddy/ngx-mask#838]
# 🐞 bug report

### Is this a regression?
I don't think so.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-pafecq

Try to listen the FormControl#valueChanges and check how many unnecessary times it's being fired. It emits even when you type non allowed characters or when you type and the mask has reached its maximum length.

## 🌍 Your Environment

**Angular Version:** 11.x.

</code></pre>

**Anything else relevant?**
Currently we can workaround this by using `distinctUntilChanged`.

**Comment by andriikamaldinov1** [comment]
@rafaelss95 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-qeauvi?file=src%2Fmain.ts
