### ISSUE TITLE
Not able to type latin characters 

### ISSUE THREAD

**Issue by rafaelss95** [JsDaddy/ngx-mask#839]
# 🐞 bug report

### Is this a regression?
I don't know.

### Description
I'm not able to type latin characters even if I specify it in a custom pattern like this:

```ts
readonly customPatterns = { N: { pattern: /[a-zÀ-ÿ\s'-]/i } };
```

```html
<input matInput mask="N*" [formControl]="formControl" [patterns]="customPatterns">
```

It doesn't let me to type "á" or "é", for example.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-rmluab

## 🌍 Your Environment

**Angular Version:** 11.x

**Comment by andriikamaldinov1** [comment]
@rafaelss95  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-rfgcch?file=src%2Fmain.ts
