### ISSUE TITLE
thousandSeparator="."

### ISSUE THREAD

**Issue by orcdemir** [JsDaddy/ngx-mask#840]
Hi,
I have a input and I use dot separator with 2 decimal places.
When I send this value other input (mask="separator,2" thousandSeparator="."), 
it doesn't work.

for example:
1.234,56 --> 123.456

**Comment by pygoscelis13** [comment]
I guess you need to leave the dot in the mask and add another attribute: 
`mask="separator.2" thousandSeparator="." decimalMarker=","`

**Comment by NepipenkoIgor** [comment]
@orcdemir Hi . Seems like this issue relative to earlier version of ngx-mask. 
You could check latest behaviour https://stackblitz.com/edit/angular-6hrevx?file=src%2Fmain.ts%3AL8
And everything works as expected

**Comment by andriikamaldinov1** [comment]
@orcdemir 
Thank you for using ngx-mask. 
I'm closing issue as everything works as expected.
If you have any problems in the future in using the ngx-mask, open issue using the template
