### ISSUE TITLE
Provide ability to transform value before write

### ISSUE THREAD

**Issue by dev054** [JsDaddy/ngx-mask#841]
# 🚀 feature request
There are some cases where we should allow only letters (say full name) and as the user types, we transform to uppercase.

### Describe the solution you'd like
I'd like to have an option to transform value before masking.

```html
<!-- the name could be any, it's just an idea ->
<input matInput formControlName="test" mask="S*" [transformer]="transformerFn">
```

```ts
transformerFn = (value: string) => value.toLocaleUppercase();

this.formGroup.get('test').valueChanges.subscribe(console.log); // fired only once, with the value uppercased
```

### Describe alternatives you've considered
Well, while we could add a directive to perform its transformation by listening `input` event, but has the following drawback:

- The `valueChanges`/`(change)` would be emitted twice. One for the value masked and another for the value uppercased. To try workaround this you could `setValue` passing `{ emitEvent: false }`, however it would be a problem, because you'll have an outdated value in `valueChanges/(change)`;

**Comment by andriikamaldinov1** [comment]
@dev054 Thanks for using Ngx-mask. We add two new function "inputTransformFn" and "outputTransformFn".
It example with your case - https://stackblitz.com/edit/stackblitz-starters-wj3nvw?file=src%2Fmain.ts
