### ISSUE TITLE
Allow readonly arrays with strictTemplates enabled

### ISSUE THREAD

**Issue by dev054** [JsDaddy/ngx-mask#843]
# 🐞 bug report

### Description
Currently we can't pass `readonly string[]` to  `dropSpecialCharacters` and `specialCharacters` with `strictTemplates` enabled.

## 🔬 Minimal Reproduction
```html
<!-- Argument of type 'readonly [...]' is not assignable to parameter of type 'string[]'.
  The type 'readonly [...]' is 'readonly' and cannot be assigned to the mutable type 'string[]'. ->
<input matInput formControlName="test" mask="testing" [specialCharacters]="specialCharacters">
```

```ts
specialCharacters = ['[', ']', '\\'] as const;
```

## 🌍 Your Environment

**Angular Version:** 10.x.

**Anything else relevant?** To solve this we can do the following:

https://github.com/JsDaddy/ngx-mask/blob/f14b4fe9b9a7a80092d9c3febb1f1b0298c1895c/projects/ngx-mask-lib/src/lib/config.ts#L13-L14

```diff
- dropSpecialCharacters: boolean | string[];
- specialCharacters: string[];
+ dropSpecialCharacters: boolean | readonly string[];
+ specialCharacters: readonly string[];
```

**Comment by andriikamaldinov1** [comment]
@dev054 Thanks for using Ngx-mask. Pls update to latest version.
It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-epnjbs?file=src%2Fmain.ts
