### ISSUE TITLE
Cursor position after delete/backspace

### ISSUE THREAD

**Issue by camboui** [JsDaddy/ngx-mask#844]
# 🐞 bug report

### Is this a regression?

No, Seems to be present in any recent version since at least 8.x (didn't tests with previous ones)

### Description

Cursor position is wrong in some cases after using Delete or Backspace event keys.
Happening on date Masks and thousands separators masks.

## 🔬 Minimal Reproduction

Steps for date masks using : https://jsdaddy.github.io/ngx-mask-page/main#prefix
1 - Fill field associated to 'Mask: 00/00/0000' with "10/10/2345"
2 - Place cursor before character "2" 
3 - Press 'Delete' (not backspace), resulting in "10/10/345"
4 - Cursor position is between "3" and "4" but should be before "3".

Steps for thousands separator masks using : https://jsdaddy.github.io/ngx-mask-page/main#sep
1 - Fill any of the field with "1[any thousands separator]234"
2 a- Place cursor before character "1" and press 'Delete', resulting in "234"
OR
2 b- Place cursor between "1" and "2" and press 'Backspace' , resulting in "234"
3 - Cursor position is at then end of input (after "4") but shoud be before "2".

🌍 Your Environment
Angular Version: tested with 9.x and 11.x

**Comment by andriikamaldinov1** [comment]
@camboui  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-sscws5?file=src%2Fmain.ts
