### ISSUE TITLE
[dropSpecialCharacters]="false" doesnt work like it should it still doesnt return prefix

### ISSUE THREAD

**Issue by Ptol-v** [JsDaddy/ngx-mask#845]
<div class="input-group">
          <input id="phoneNumber" type="text" class="form-control pl-4"
                 (input)="saveDocument()"
                 [(ngModel)]="phoneNumber"
                 [dropSpecialCharacters]="false"
                 mask="000000000" [showMaskTyped]="true" prefix="+380"
                 placeHolderCharacter="X" [patterns]="customPatternNumber"
                 >
        </div>

**Comment by Ptol-v** [comment]
<div class="input-group">
          <input id="phoneNumber" type="text" class="form-control pl-4"
                 (input)="saveDocument()"
                 [(ngModel)]="phoneNumber"
                 [dropSpecialCharacters]="false"
                 mask="000000000" [showMaskTyped]="true" prefix="+380"
                 placeHolderCharacter="X" [patterns]="customPatternNumber"
                 >
        </div>

**Comment by andriikamaldinov1** [comment]
@Ptol-v Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-yhibax?file=src%2Fmain.ts
