### ISSUE TITLE
Repeat mask doesn't work

### ISSUE THREAD

**Issue by MasoudBimar** [JsDaddy/ngx-mask#853]
Hi

when we use pipe with Repeat mask Similar to what is stated in the ReadMe, pipe just show the first char of input value

# 🐞 bug report

This functionality (use pipe with repeat mask) was ok in previous versions.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Repeat mask
You can pass into mask pattern with brackets.

Usage

`<input type="text" mask="A{4}" />`

Output: 

Input: 123456
pipe output : 1

**Comment by andriikamaldinov1** [comment]
@MasoudBimar  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-vrcq8w?file=src%2Fmain.ts
