### ISSUE TITLE
Incorrect 24 hour format with date and month (29 hours)

### ISSUE THREAD

**Issue by Androsid** [JsDaddy/ngx-mask#854]
🐞 bug report

with a mask "d0.M0.0000 Hh:m0:s0" 

maximum input for hours is up to 29, but I need it up to 23

🔬 Minimal Reproduction

`<input matInput mask="d0.M0.0000 Hh:m0:s0" />`

🌍 Your Environment

**Angular Version:** 11.0.0
**ngx-mask**: "11.1.4"

**Comment by andriikamaldinov1** [comment]
@Androsid Thanks for your using Ngx-Mask. Please update to latest version.
Here example, all work as expected - https://stackblitz.com/edit/angular-rqwkh7?file=src%2Fmain.ts
