### ISSUE TITLE
First '(' is not getting cleared when using '(000) 000-0000' mask

### ISSUE THREAD

**Issue by KilledarRushikesh** [JsDaddy/ngx-mask#857]
Oh hi there! 
# 🐞 bug report

### Is this a regression?

 Not tested.

### Description
Mask: (000) 000-0000

After entering 1-2 digits. When tried to clear them one char/digit at a time, it is still showing '(' at start, when all input gets cleared  and i'm not able to clear it.

![mask-issue](https://user-images.githubusercontent.com/34641511/105031201-f8b42e80-5a7a-11eb-8c4d-136bfa49a706.png)

**Angular Version:**
10

**Comment by NepipenkoIgor** [comment]
@KilledarRushikesh  @YSFKBDY  Seems like this issue relative to old ngx-mask package and dosent exist anymore . 
Please check https://stackblitz.com/edit/angular-b4bk45?file=src%2Fmain.ts%3AL8

**Comment by NepipenkoIgor** [comment]
@YSFKBDY  I think something before 13, perhaps 12

**Comment by andriikamaldinov1** [comment]
@KilledarRushikesh @YSFKBDY 
Thank you for using ngx-mask. 
I'm closing issue as everything works as expected.
If you have any problems in the future in using the ngx-mask, open issue using the template
