### ISSUE TITLE
What happens if we run out of 26 alphabets and 9 numbers ?

### ISSUE THREAD

**Issue by iPankajKumar** [JsDaddy/ngx-mask#858]
`public customPatterns = { 

        //Alphanumric with space
        'A': { pattern: new RegExp('\[a-zA-Z0-9 \]')},

        //Alphanumeric 
        'B': { pattern: new RegExp('\[a-zA-Z0-9\]')},

        //Alphabets only 
        'C': { pattern: new RegExp('\[a-zA-Z\]')},

        //Alphabets with space 
        'D': { pattern: new RegExp('\[a-zA-Z \]')},

        //Numeric only
        'E': { pattern: new RegExp(`^[0-9]*$`)},

        //Numeric with space
        'F': { pattern: new RegExp(`^[0-9 ]*$`)},

        //Float
        'G': { pattern: new RegExp(`[+-]?([0-9]*\[.\])?[0-9]+`)}, 

        'HI': { pattern: new RegExp('\[a-zA-Z\]')},
      };`

`mask="A{5}" [patterns]="customPatterns"`

As you can see above, I have 8 custom Patterns defined, but looks like it only works with single alphabet declaration.
The last declration is "**HI**" which doesn't work, so I have 26 letters and 9 numbers, so a total of 35 different ways to make my custom masks ? What after that ?

**Comment by andriikamaldinov1** [comment]
@iPankajKumar Thanks for using Ngx-mask. 
Our opinion is that our mask gives enough opportunity to use 35 patterns. If you provide us with a real example in which it is really not enough. We will think to implement the possibility to add more patterns, but in our understanding it is enough.
