### ISSUE TITLE
How to mask optionally negative number with digits after coma (-2,2321;   2,321;  -123; 232)?

### ISSUE THREAD

**Issue by Falynsky** [JsDaddy/ngx-mask#860]
Hi,

Is there any posible way to create a mask for optionally negative number with optional unlimited digits after coma?

My inputs: 
1. -12345..9.2
2. -1,222222222222
3. 12345,2
4. 111111111111.2
5. 1234567
6. -1

I tried this pattern, but i can't type dot if i dont type '-' character before

```
           mask="M9*D9*"
           [patterns]="numericCustomPattern"
           [allowNegativeNumbers]="true"
           [dropSpecialCharacters]="false"
```

```
  numericCustomPattern = {
    'M' : { pattern : new RegExp('-?') },
    '9' : { pattern : new RegExp('[0-9]') },
    'D' : { pattern : new RegExp(/[.,]/g) }
  };

```

**Comment by andriikamaldinov1** [comment]
@Falynsky Thank you for using ngx-mask. Please update ngx-mask to latest version.
We fix [allowNegativeNumber]="true", it should work as expected with all of mask.

https://stackblitz.com/edit/angular-em2ulz?file=src%2Fmain.ts
