### ISSUE TITLE
Hidden Input doesn't clear on reset.

### ISSUE THREAD

**Issue by BGBRWR** [JsDaddy/ngx-mask#863]
# 🐞 bug report

### Description

Similar to https://github.com/JsDaddy/ngx-mask/issues/856. Form reset, setValue, or patchValue don't work on hiddenInputs.

## 🔬 Minimal Reproduction

StackBlitz below will explain to how reproduce.
https://stackblitz.com/edit/angular-h41zum?file=src/app/app.component.html

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.0.2
Node: 14.15.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.1
@angular/material               11.0.1
@schematics/angular             11.0.2
@schematics/update              0.1100.2
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by NepipenkoIgor** [comment]
@BGBRWR Thank you. Please try newest version
