### ISSUE TITLE
"Number" input sometimes returns 0 when the input is empty

### ISSUE THREAD

**Issue by Res42** [JsDaddy/ngx-mask#867]
# 🐞 bug report

### Description

"Number" input sometimes returns 0 when the input is empty.

**I want empty inputs to have value `""` or `null` or `undefined`.**

When it works: when you just type into an input and then delete it, it will work "okay". You get a string of your number, and the empty value is `""` (empty string). See reproduction `working` section.

**When it does not work:** if you programmatically set a `number` value to your form control, then delete the value the empty value will be `0`. See reproduction `buggy` section.

## 🔬 Minimal Reproduction

<https://stackblitz.com/edit/ngx-mask-number-empty-zero>

1. Delete the value from the `buggy` input.
2. See that the value of the control is `0`.

## 🔥 Exception or Error

As I see it, when you programmatically set the value of the control to a number, the `MaskDirective` sets `this._maskService.isNumberValue = true;` .

<https://github.com/JsDaddy/ngx-mask/blob/01a10455a23e9a0abf14e43ff39b0b4fc07022df/projects/ngx-mask-lib/src/lib/mask.directive.ts#L438-L442>

Then, when you delete the value from the input manually, it triggers this method with `inputValue = ""`.

<https://github.com/JsDaddy/ngx-mask/blob/01a10455a23e9a0abf14e43ff39b0b4fc07022df/projects/ngx-mask-lib/src/lib/mask.service.ts#L320-L333>

Which will trigger this method with `value= ""`.

<https://github.com/JsDaddy/ngx-mask/blob/01a10455a23e9a0abf14e43ff39b0b4fc07022df/projects/ngx-mask-lib/src/lib/mask.service.ts#L335-L341>

And because `this.isNumberValue === true` it will run this line:

```javascript
const num = Number(value); // value === ""
// num === 0
```

## 🌍 Your Environment

**Angular version:**

```
11.2.0
```

**ngx-mask version:**

```
11.1.4
```

**Comment by efedorko** [comment]
It seems it was introduced just recently with #829. I had to revert to version 11.1.0 which works fine in this regard.

**Comment by Res42** [comment]
It seems that v11.1.5 (https://github.com/JsDaddy/ngx-mask/pull/864) fixed this issue and the empty number input is `""` now.

Stackblitz for testing it: <https://stackblitz.com/edit/ngx-mask-number-empty-zero-v11-1-5>

**Comment by JoaoPauloLisboa** [comment]
> It seems that v11.1.5 (#864) fixed this issue and the empty number input is `""` now.
> 
> Stackblitz for testing it: https://stackblitz.com/edit/ngx-mask-number-empty-zero-v11-1-5

The bug remains if you use the property **prefix**, still returning 0 when the input is empty after set value programatically.
 I tested in this same stackblitz above and with an app v14.1.2
