### ISSUE TITLE
24h input: cursor jumps while writing

### ISSUE THREAD

**Issue by FA91AN** [JsDaddy/ngx-mask#870]
# 🐞 bug report

### Description

 When I use the "Hh:m0" mask, the cursor jumps one unit to the left while writing.

## 🔬 Minimal Reproduction

Can also be reproduced here: https://jsdaddy.github.io/ngx-mask-page/main#valid24

Write "735". The input changes to "7:53" instead of "7:35".

**Comment by andriikamaldinov1** [comment]
@FA91AN Thanks for using Ngx-mask.  Please update ngx-mask to latest version.
https://stackblitz.com/edit/angular-4nayah?file=src%2Fmain.ts
