### ISSUE TITLE
dropSpecialCharacters still drops special characters in the model

### ISSUE THREAD

**Issue by RRGT19** [JsDaddy/ngx-mask#873]
# 🐞 bug report

### Description

`[dropSpecialCharacters]="false"` still drops special characters in the model.

## 🔬 Minimal Reproduction

Do a fresh install and add this:

`<input class="form-control" type="text" mask="00/00" [dropSpecialCharacters]="false">`

**Result:**
Input value: 01/21
Model value: 01/21

**Should be:**
Input value: 01/21
Model value: **0121**

## 🔥 Exception or Error

None

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.2.1
Node: 14.15.5
OS: darwin x64

Angular: 11.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.1
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**ngx-mask:** 11.1.4

**Comment by NepipenkoIgor** [comment]
@RRGT19  Hi . Everything works as expected . If dropSpecialCharacters = false we shouldn't remove special characters from value.
Please check https://stackblitz.com/edit/angular-ivy-mask-dtdppm?file=src%2Fapp%2Fapp.component.html
