### ISSUE TITLE
Issue with zeros on separator.2 mask directive

### ISSUE THREAD

**Issue by ytsimbolynets-perfectial** [JsDaddy/ngx-mask#879]
# 🐞 bug report

### Is this a regression?

 No

### Description

 According to current behavior, a user can't enter leading zeros with `separator.2` mask. But, when we enter some numbers, like 10000, and then delete 1 from the input, the result is incorrect - 000. While the expected result is 0 or 0 000.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ngx-mask-error-ubagwg?file=src/app/app.component.html

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 10.2.2
Node: 12.20.0
OS: darwin x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.8
@angular-devkit/build-angular      0.1000.8
@angular-devkit/build-ng-packagr   0.1000.8
@angular-devkit/core               10.0.8
@angular-devkit/schematics         10.2.2
@angular/cli                       10.2.2
@angular/elements                  10.2.4
@angular/localize                  10.2.4
@schematics/angular                10.2.2
@schematics/update                 0.1002.2
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         3.9.7

ngx-mask: 11.1.5

Also, reproducible in Angular 9 (see stackblitz)
</code></pre>

**Comment by andriikamaldinov1** [comment]
@ytsimbolynets-perfectial Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-souxcq?file=src%2Fmain.ts
