### ISSUE TITLE
Secure input doesn't work with showMaskTyped

### ISSUE THREAD

**Issue by wonderlaw1** [JsDaddy/ngx-mask#880]
# 🐞 bug report

### Is this a regression?

No

### Description

I need to show only the first four numbers of SSN. Secure input works well without showMaskTyped, but with turned on showMaskedType it doesn't hide numbers at all.

## 🔬 Minimal Reproduction

[demo](https://stackblitz.com/edit/angular-ivy-avwwlc?file=src%2Fapp%2Fapp.component.html)

## 🌍 Your Environment

**Angular Version:**

<pre><code>
@angular-devkit/architect          0.1100.1
@angular-devkit/build-angular      0.1100.1
@angular-devkit/core               11.0.1
@angular-devkit/schematics         10.2.3
@angular/cli                       11.2.3
@angular/material-moment-adapter   11.0.1
@schematics/angular                10.2.3
@schematics/update                 0.1102.3
rxjs                               6.6.3
typescript                         4.0.5
</code></pre>

**Anything else relevant?**

No

**Comment by andriikamaldinov1** [comment]
@wonderlaw1  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-1duybx?file=src%2Fmain.ts

**Comment by quis0** [comment]
@andriikamaldinov1 Hi, is there any workaround to show the remaining part of the mask (placeHolderCharacters) when typing in secure input? Should I create an issue or it's expected behavior? Demo: https://stackblitz.com/edit/angular-nuifs2?file=src%2Fmain.ts

**Comment by andriikamaldinov1** [comment]
@quis0  Hi, create issue with this stackblitz
