### ISSUE TITLE
Cursor jumps to the end when deleting single digit before special character

### ISSUE THREAD

**Issue by smita-cognologix** [JsDaddy/ngx-mask#883]
# 🐞 bug report

### Is this a regression?
No idea

### Description
For example, when editing 7,465 if 7 is deleted then cursor jumps to end. If it is 72,465 and if you delete 2 it works fine.
We used this library as it managed cursor jumping issue very well. Only this little bug is an issue so far.

Can you kindly fix the same?

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-mask-qmbjmg?file=src/app/app.component.ts
when you delete 7 it jumps to the end. If there is more than one digit in front of special character it works fine.

## 🔥 Exception or Error
Not applicable
 

## 🌍 Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.7
Node: 14.15.4
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@angular/material               11.0.4
@angular/router                 11.0.3
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by andriikamaldinov1** [comment]
@smita-cognologix  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-wwnnra?file=src%2Fmain.ts
