### ISSUE TITLE
version 11.1.4 not working in IE 11

### ISSUE THREAD

**Issue by Yermi** [JsDaddy/ngx-mask#886]
related to #337, #425.

after installing '11.1.4' version, IE browser stopped working and display a blank page. console logs `syntax error` that points to  `MaskApplierService` which is probably caused by the use of [Array.prototype.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) which is not supported in IE 11.

in `polyfills.ts` file i add `import 'core-js'` which should contain the `include` but it doesn't work.

## 🌍 Environment

**ngx-mask**: 11.1.4
**Angular Version:** 9.1.12
**core-js**: 3.6.4,

![image](https://user-images.githubusercontent.com/17401730/115722518-bf47d380-a387-11eb-83ca-d48be1d3945b.png)
![image](https://user-images.githubusercontent.com/17401730/115722626-dab2de80-a387-11eb-94d0-4490fce8bfff.png)

**Comment by ColinMorris83** [comment]
In polyfills, try with:

`import 'core-js/modules/es.array.includes';`

**Comment by Yermi** [comment]
Hi

I think it has probably nothing to do with the `includes` method. it still not working even after adding all imports that are conceivable.

For me, the solution was to downgrade the package to `9.1.4` that works perfectly for me even without prod build, but above that version still not working in IE.

**Comment by NepipenkoIgor** [comment]
@Yermi  Thank you that using ngx-mask .  I believe that @ColinMorris83  totally right . Only what we need it is right pollyfils for old environment . Also in general we no plan to support IE ( As we remember Microsoft stopped support this product long time ago).
