### ISSUE TITLE
Mask prefix keep showing after input is empty

### ISSUE THREAD

**Issue by LeonardoRick** [JsDaddy/ngx-mask#889]
# 🐞 Bug report

### Description

```html

<input type="tel" placeholder="* 100,00" mask=0* prefix="$ ">
```

The '$' on the example should not be shown if the user delete all the content typed on input. The placeholder should be shown again if the input is empty

https://stackblitz.com/edit/angular-ivy-zuiigu?file=src/app/app.component.html

As is possible to see in the demo, It works pretty well on suffix values, but prefix values do not delete the prefix when the input is empty

## 🌍 Environment

**Angular Version:**

<pre><code>
Angular CLI: 10.0.8
Node: 12.15.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1002.2
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.1.7
@angular-devkit/schematics        10.1.7
@angular/cdk                      10.2.5
@angular/cli                      10.0.8
@angular/fire                     6.1.4
@ngtools/webpack                  10.0.8
@schematics/angular               10.1.7
@schematics/update                0.1000.8
rxjs                              6.6.3
typescript                        3.9.7

</code></pre>

### ngx-mask version
```json
"ngx-mask": "^11.1.5",
```

**Comment by igoodwinVolly** [comment]
I found a work around using Angular 10 and ngx-mask version 11.1.4.

Using reactive forms with a formGroup of "inputForm" and formControlName of "input", I am able to remove the prefix and suffix on the input element with only template code. The placeholder appears when the input and prefix / suffix disappears. 

```html
<form [formGroup]="inputForm">
    <input
      placeholder="Enter a value"
      [prefix]="inputForm.controls.input.value ? prefix : ''"
      [suffix]="inputForm.controls.input.value ? suffix : ''"
      [mask]="mask"
      formControlName="input"
    />
</form>
```

**Comment by andriikamaldinov1** [comment]
@LeonardoRick Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-vicxs3?file=src%2Fmain.ts

**Comment by Naveen112001** [comment]
We are using the same latest version 17.0.1 ngx-mask
But still issue is there
<input type="tel" placeholder="+1 (123) 456-7890" prefix ="+1" mask=" (000) 000-0000" >
