### ISSUE TITLE
Changing mask programmatically marks the input as dirty 

### ISSUE THREAD

**Issue by BGBRWR** [JsDaddy/ngx-mask#892]
# 🐞 bug report

### Is this a regression?

No

### Description

When changing the value of `mask` , it marks the input as dirty. It shouldn't do that.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-bjofqt?file=src/app/app.component.ts

## 🌍 Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 14.16.1
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.3
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.5.4
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by williamxsp** [comment]
This is causing me some validation bugs. Thanks for the PR. Waiting for the merge
