### ISSUE TITLE
Misleading "backspace/delete" tests

### ISSUE THREAD

**Issue by manuelmeister** [JsDaddy/ngx-mask#900]
### Description
The "Directive: Mask (Delete)" tests do not replicate real browser behavior at all. With real "Delete/Backspace" events, the browser actually deletes the characters selected / next to the cursor.

### Example
For instance this test only tests if the value that is set at the beginning is formatted correctly.
https://github.com/JsDaddy/ngx-mask/blob/fb6f176ce841bb78b3ec5ca4e3a3d52bce7404ac/projects/ngx-mask-lib/src/test/delete.spec.ts#L24-L39
The same would happen if the two triggerEventHandlers were omitted, because after the value "2/34/5678" is set, the input value is automatically formatted to "23/45/678".
Also the cursor position is checked incorrectly. After a backspace at position 1 (between "2" and "3") the cursor should be at position 0.

### Problem
With these tests, a false sense of security is created and changes that would solve the misbehavior fail. 

### Solution
- [added cypress to be able to e2e test the directive](https://github.com/manuelmeister/ngx-mask/tree/add-e2e-tests).
- tried to [solve the problems in the mask directive](https://github.com/manuelmeister/ngx-mask/blob/a39649a610d7e86db488f0ea992e4b730ffcba6d/projects/ngx-mask-lib/src/lib/mask.directive.ts#L485-L511) but didn't fully understand the apply mask service.

### Issues probably caused by these tests or relevant:
https://github.com/JsDaddy/ngx-mask/issues/664
https://github.com/JsDaddy/ngx-mask/issues/799
https://github.com/JsDaddy/ngx-mask/issues/844
https://github.com/JsDaddy/ngx-mask/issues/865

There are also other issues like you can't select text and delete the selected text with backspace. Instead it will only delete one character.  
![Screen Shot 2021-05-20 at 11 16 33](https://user-images.githubusercontent.com/3001985/118953254-f1376000-b95c-11eb-98aa-f1269a87aee5.png)
![Screen Shot 2021-05-20 at 11 16 40](https://user-images.githubusercontent.com/3001985/118953264-f2688d00-b95c-11eb-962d-33469341478f.png)

**Comment by KingDarBoja** [comment]
Maybe these tests and mask directive changes could fix #899 as well? 🙈

**Comment by NepipenkoIgor** [comment]
@manuelmeister @KingDarBoja  Seems like we merged a couple request relative to this . If problem still actual please create new one issues or connect with me directly
