### ISSUE TITLE
When allowing '-' for negative numbers, bug when selecting all and pressing '-'

### ISSUE THREAD

**Issue by boltex** [JsDaddy/ngx-mask#903]
Thanks for your great product, 

but I just found a bug in relation with the 'allowNegativeNumbers' option and the press of the '-' key whilehaving the whole input text field selected. (all highlighted)

Easy to reproduce with the  [allowNegativeNumbers]="true" parameter, which let user have negative numbers by allowing '-' character at front: 

When having a numeric input with a mask restricting the number input, selecting all the input field's content, and then typing the negative symbol '-', results in the whole field gets cleared and left empty, instead of all being replaced with the '-' character.

**Comment by msankar1991** [comment]
@boltex Did you found any solution for your question. For me also needs same solution let me know.

**Comment by andriikamaldinov1** [comment]
@boltex @msankar1991 Thank you for using ngx-mask. Please update ngx-mask to latest version.
[allowNegativeNumber]="true", work as expected

https://stackblitz.com/edit/angular-em2ulz?file=src%2Fmain.ts

**Comment by boltex** [comment]
@andriikamaldinov1 Wow! Thank you! (& please Stay safe !!)
