### ISSUE TITLE
Customize symbol of secure input

### ISSUE THREAD

**Issue by theRaffe** [JsDaddy/ngx-mask#904]
# 🚀 feature request

### Description

 Is there a way to change the symbol of a secure input

### Describe the solution you'd like

 Now this is showing * asteric for secured caracters and I would like to show  dots instead

**Comment by niknokseyer** [comment]
This is doable using **patterns**.

You can do this:
```
  public hiddenPattern = {
    X: {
      pattern: new RegExp('[a-zA-Z0-9]'),
      symbol: '.',
    }
  };
  ```

**Comment by theRaffe** [comment]
Oh thks!! @niknokseyer
