### ISSUE TITLE
dynamically changing mask with pipe do not work properly.

### ISSUE THREAD

**Issue by chhaya90** [JsDaddy/ngx-mask#905]
Hi Guys,
  
My mask format dynamically changes on change of value in input box for Example :  
"0000 0000 0000 0000||0000 0000 0000 0000 00||**0000 0000 0000 0000 000**" with "0000 0000 0000 0000", Though mask 
value 
changes it still takes dummy value from previous mask and allows  **0000 0000 0000 0000 000** digits  instead of expected "0000 
0000 0000 0000" .
  
Example : 
For Visa card  allowed digits are 16,18,19. mask : "0000 0000 0000 0000||0000 0000 0000 0000 00||0000 0000 0000 0000 000"
Mastercard allowed digits are 16 digit. mask : **0000 0000 0000 0000 000** 

If change is from visa to Mastercard it still allows 19 digit . though the change in mask value is visible .

But if we apply repetitive concatenation on Mastercard  mask  "**0000 0000 0000 0000 || 0000 0000 0000 0000**" .This works as expected and allow only 16 digit.
This Issue is only seen when we change the mask dynamically from Visa card that allows multiple variation of digits to Mastercard that allows only single fixed digit. Changing from Visa to Mastercard works as expected.

Any Suggestion or workaround will be of great help.

Thanks
Chhaya

**Comment by chhaya90** [comment]
Let me know if further explanation is required

**Comment by andriikamaldinov1** [comment]
@chhaya90 Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-y6nequ?file=src%2Fmain.ts
