### ISSUE TITLE
ClearIfNotMatch does not work with a custom placeHolderCharacter

### ISSUE THREAD

**Issue by jacobmainzer-sb** [JsDaddy/ngx-mask#906]
### Description
clearIfNotMatch does not clear invalid input if showMaskTyped=true and placeHolderCharacter is set to a different character than an underscore.  This issue is an extension of the problem seen in https://github.com/JsDaddy/ngx-mask/issues/304

## 🔬 Minimal Reproduction
Example shows two inputs, one with a custom placeholder, one without.  The input with a custom placeholder does not clear properly if not a match.
https://stackblitz.com/edit/angular-ivy-mask-hzqt3s

## Possible Cause
https://github.com/JsDaddy/ngx-mask/blob/feab974e488365484807b237e9816d114e0f8374/projects/ngx-mask-lib/src/lib/mask.service.ts#L220
It appears like this code assumes that the placeholder character is the default placeholder.

**Comment by zepelega** [comment]
My problem with the **clearIfNotMatch** is that it dont reset the input value, it clears on the view, yes, but once you get the data, the suppoused value cleared is there.

With that, I have to add an extra validator anyway, so I don't see the point using it.

Ex.:
```
logValue(value: string): void
{
console.log('Input value: ', value);
}

<input type="text" mask="0000" [clearIfNotMatch]="true" (blur)="logValue(test.value)" #test>
```

value typed: 125 

**console**

Input value: 125

**Comment by andriikamaldinov1** [comment]
@zepelega @jacobmainzer-sb Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-phrw4d?file=src%2Fmain.ts
