### ISSUE TITLE
Deletion of text does not work properly in Chrome with ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by andrewritchie** [JsDaddy/ngx-mask#909]
# 🐞 bug report

### Is this a regression?

No; I tested this with both 10.x and 12.0.0 and this does not work with either.

### Description

Specifying an input mask with [showMaskTyped]="true", or an input mask with special characters that involve spaces, such as the phone number mask "(000) 000-0000", does not work allow proper deletion of characters in desktop browsers if the component's encapsulation is set to ViewEncapsulation.ShadowDom. 

With showMaskTyped=true, only the last character is deleted when backspace is pressed if the encapsulation is ViewEncapsulation.ShadowDom.
With showMaskTyped=false, the space after the ) in the mask prevents further backspacing if the encapsulation is ViewEncapsulation.ShadowDom

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-v4yznq

## 🔥 Exception or Error

None

## 🌍 Your Environment

**Angular Version:**

<pre><code>

11.2.14
</code></pre>

**Anything else relevant?**

I tested this with Google Chrome 91.0.4472.77. 

I have attempted reproducing this on Chrome on my Android phone, and was unable to do so.

**Comment by NepipenkoIgor** [comment]
@andrewritchie Hi thank you that using ngx-mask . Please use ngx-mask >=13.1.12
