### ISSUE TITLE
Is there a way to use this mask for date/time range?

### ISSUE THREAD

**Issue by Phoenix-Alpha** [JsDaddy/ngx-mask#911]
# 🚀 feature request

### Description
I'd like to use this mask for DD.MM.YYYY HH:MM - HH:MM
And I tried this "d0.M0.0000 Hh:m0 - Hh:m0" and it's not working well.
The mask allows the following input which is not correct.
![image](https://user-images.githubusercontent.com/71273009/121833429-9c250a80-cccc-11eb-8afe-eb809289c04c.png)

### Describe the solution you'd like

I'd like to use this mask for date/time range.

### Describe alternatives you've considered

No alternatives found yet.

**Comment by andriikamaldinov1** [comment]
@Phoenix-Alpha Thanks for your using Ngx-Mask. Please update to latest version.
Here example, all work as expected -https://stackblitz.com/edit/angular-aczu84?file=src%2Fmain.ts
