### ISSUE TITLE
Option for uppercase letters only

### ISSUE THREAD

**Issue by biel-correa** [JsDaddy/ngx-mask#912]
# 🚀 feature request

### Description

 Add a new option for the masks that accepts only uppercase letters, this would be god for names 

### Describe the solution you'd like

 Create a new option in the mask tag 
#### Examples: 
HTML mask="UUUU"
Input TEXT
HTML mask="USSS"
Input TexT

### Describe alternatives you've considered

 I can't think in a better solution

**Comment by dlebee** [comment]
> # 🚀 feature request
> ### Description
> Add a new option for the masks that accepts only uppercase letters, this would be god for names
> ### Describe the solution you'd like
> Create a new option in the mask tag
> #### Examples:
> HTML mask="UUUU"
> Input TEXT
> HTML mask="USSS"
> Input TexT
> 
> ### Describe alternatives you've considered
> I can't think in a better solution

I second that :rocket:

**Comment by int128fly** [comment]
That would be very useful for postal codes 👯

**Comment by niknokseyer** [comment]
This is doable using **patterns**.

You can do this:
```
  public casePatterns = {
    U: {
      pattern: new RegExp('[A-Z]'),
    },
    S: {
      pattern: new RegExp('[a-zA-Z]')
    }
  };
  ```

**Comment by biel-correa** [comment]
So we could do it like this:

```
  public casePatterns = {
    U: {
      pattern: new RegExp('[A-Z]'),
    },
    S: {
      pattern: new RegExp('[a-zA-Z]')
    },
    L: {
      pattern: new RegExp('[a-z]')    
    }
  };
```

What do you think @crhistianramirez?

Now that I have more free time I'll try to implement this.

**Comment by crhistianramirez** [comment]
Looks great @biel-correa

**Comment by NepipenkoIgor** [comment]
@crhistianramirez  @biel-correa @int128fly  @niknokseyer  Thank you that you using  our package . Please try mask >=13.1.7
