### ISSUE TITLE
Disable thousand seperator

### ISSUE THREAD

**Issue by DanielPinkpank** [JsDaddy/ngx-mask#913]
# 🚀 feature request

### Description

Is there a way to disable the thousand seperator?

### Describe the solution you'd like

I have a number like `1234.567` and want to display it the european way without seperators: `1234,567` -> NOT `1.234,567`

### Describe alternatives you've considered

I tried to set the thousand seperator to an empty string ("") but that causes some Issues. For example when I set the cursor in the middle of the number, I can destroy the value by typing in dots (".").

**Comment by andriikamaldinov1** [comment]
@DanielPinkpank Thanks for using Ngx-Mask! See example above.
If this ishyu is still relevant, open the issue using the template.
