### ISSUE TITLE
Define dynamic decimal places

### ISSUE THREAD

**Issue by GabrielBack28** [JsDaddy/ngx-mask#914]
### Description
I need to set decimal places as dynamic. Would it be possible to do this? 

Example:
I have the number `19.15`, but my separator is for 6 digits and the number is shown  `19.150000` 

Is there any way to define the maximum digits after the point to 6 but show only the digits informed in the input and not the zeros?

**Comment by andriikamaldinov1** [comment]
@GabrielBack28 Thanks for your using Ngx-Mask.
You can use dynamic operator "||" or 9 it optional parametr.
It example, for your cases  - https://stackblitz.com/edit/angular-fzqf3v?file=src%2Fmain.ts
