### ISSUE TITLE
Dynamic mask not working on copy/ paste

### ISSUE THREAD

**Issue by paulflo150** [JsDaddy/ngx-mask#915]
# 🐞 bug report

### Is this a regression?

Don't know

### Description

I have a mask function that returns a dynamic mask which changes based on input. The mask works when typing, however copy/ paste appears to always use the most strict mask. For instance if I use '0000 0000 0000 0000 000||0000 0000 0000 0000', and I copy/ paste 4111111111111111111, the text gets formatted as 4111 1111 1111 1111 and it loses the last three digits. Copy pasting again works.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-tcuqnp

 https://stackblitz.com/edit/angular-ivy-tcuqnp

## 🌍 Your Environment

**Angular Version:**

<pre><code>
Angular: 11.2.7
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cdk                    11.2.13
@angular/cli                    11.2.6
@angular/material               11.2.13
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.0.7

</code></pre>

**Comment by NepipenkoIgor** [comment]
@paulflo150  Thank you that using ngx-mask . Please try version >=13.1.13
