### ISSUE TITLE
Wrong behavior with custom pattern and optional

### ISSUE THREAD

**Issue by mhagnumdw** [JsDaddy/ngx-mask#916]
# 🐞 bug report

### Is this a regression?

No.

### Description

Add this custom pattern:

```ts
const ngxMaskCustomPatterns = {
  // Letters only and Optional
  B: { pattern: new RegExp('[a-zA-Z]'), optional: true },
};
```

Use this mask: `SSBB-0999`

Which should be valid for:
- AB-1234
- ABC-1234
- ABCD-1234

But when typing, for example, `AB-12`, we get `AB-1-12`. :boom: 

## 🔬 Minimal Reproduction

- ngx-mask v8: https://stackblitz.com/edit/angular-ivy-n6lhoj?file=src%2Fapp%2Fapp.component.ts
- ngx-mask v12: https://stackblitz.com/edit/angular-ivy-aqj6my?file=src%2Fapp%2Fapp.component.ts

## 🌍 Your Environment

**Angular Version:** v6 and v12

Is it possible to solve this?

**Comment by andriikamaldinov1** [comment]
@mhagnumdw  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-yvebwj?file=src%2Fmain.ts
