### ISSUE TITLE
Complete Event

### ISSUE THREAD

**Issue by ericrovtar** [JsDaddy/ngx-mask#917]
# 🚀 feature request

### Description

 It'd be helpful to have some sort of value emitted when the mask is fulfilled/completed.

### Describe the solution you'd like

 Add `@Output complete` to the directive to fire when the mask has been fulfilled and is valid.

### Describe alternatives you've considered

 Unsure

**Comment by NepipenkoIgor** [comment]
@ericrovtar  Thank you that use our library , please try ngx-mask@13.1.4 or higher
