### ISSUE TITLE
Global Config for decimalMarker ignored

### ISSUE THREAD

**Issue by finzero** [JsDaddy/ngx-mask#918]
# 🐞 bug report

### Is this a regression?

Dont Know

### Description

<code>"ngx-mask": "^12.0.0",</code>

so i have these config on my app
<pre><code>
const maskConfig: Partial<IConfig> = {
  validation: false,
  thousandSeparator: '.',
  decimalMarker: ','
};

@NgModule({
...
imports: [
   NgxMaskModule.forRoot(maskConfig)
]
...
})
</code></pre>
i have a form control with value 200000.55 and i have code like this:
<code><input [formControl]="numberWithDecimal" mask="separator.2"/></code> and the displayed value is <code>20.000.055</code>
but if i insert inline config for decimalMarker then it's worked as it should be
<code><input [formControl]="numberWithDecimal" mask="separator.2" decimalMarker=","/></code> and the displayed value is <code>200.000,55</code> which is correct

## 🔬 Minimal Reproduction
<a href="https://stackblitz.com/edit/angular-ivy-kkvtfw?file=src/app/app.component.html">https://stackblitz.com/edit/angular-ivy-kkvtfw?file=src/app/app.component.html</a>

## 🌍 Your Environment

**Angular Version:**

<pre><code>Angular CLI: 10.1.7
Node: 14.17.3
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cli                    10.1.7
@schematics/angular             10.2.1
@schematics/update              0.1002.1
rxjs                            6.6.3
typescript                      4.0.5</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@finzero  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected -  https://stackblitz.com/edit/angular-5w7xbh?file=src%2Fmain.ts
