### ISSUE TITLE
@angular/router: really a dependency?

### ISSUE THREAD

**Issue by mautematico** [JsDaddy/ngx-mask#92]
I think this is not an actual dependency, and I hope it's not.
I am trying to use it on ionic@latest, which does not use @angular/router but a custom one.

├── UNMET PEER DEPENDENCY @angular/router@>=2.4.3

Will try to use it without router, and then propose a PR.

**Comment by mautematico** [comment]
Done. It does not seem to actually need @angular/router to work.
In fact, @angular/router@2.4.3 is not even available today.

Will send a PR later.

**Comment by NepipenkoIgor** [comment]
@mautematico  removed
