### ISSUE TITLE
How to allow plus & minus symbols at first word with input

### ISSUE THREAD

**Issue by msankar1991** [JsDaddy/ngx-mask#920]
Input needs accept both positive and negative number with mask options.

_-233.34, -10.09_
 (**or**)
_+233.45, +11.10_
(**or**)
_15.76, 44.78_

Given `<input type="text" mask="000.00" [allowNegativeNumbers]="true" [dropSpecialCharacters]="false" > ` but its not accepting minus sign.

**Comment by andriikamaldinov1** [comment]
@msankar1991 Thank you for using ngx-mask. Please update ngx-mask to latest version. 
[allowNegativeNumbers]="true" work as expected
https://stackblitz.com/edit/angular-em2ulz?file=src%2Fmain.ts
