### ISSUE TITLE
Date with validation mask cannot handle certain dates

### ISSUE THREAD

**Issue by tkutcher** [JsDaddy/ngx-mask#925]
# 🐞 bug report

### Is this a regression?

Unknown - I don't think so?

### Description

If using a mask such as `'M0/d0/0000'` with the `leadZeroDateTime`, let's say a user wants to specify September 3rd, 2020. The ideal keystrokes would be to enter `9`,`3`,`2`,`0`,`2`,`0`.  After `9`,`3`, the input looks like `09/3`. With the next `2`, it detects that it needs to add the `0` for the `3`, but then the cursor needs to be bumped one more I believe (in the case of the number is greater than number of days).

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mask-hqpfe3?file=src%2Fapp%2Fapp.component.html

## 🌍 Your Environment

**Angular Version:**

12.0.2

<pre><code>
Angular CLI: 12.0.2
Node: 12.22.1
Package Manager: npm 6.14.12
</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@tkutcher Thank you for using ngx-mask. Please update ngx-mask to latest version.
When you fill in the days, they can be 30-31, so leadZeroDateTime will work after driving the second character there.

https://stackblitz.com/edit/angular-u2tkvk?file=src%2Fmain.ts
