### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when change suffix and value

### ISSUE THREAD

**Issue by louis-neologix** [JsDaddy/ngx-mask#926]
# 🐞 bug report

### Is this a regression?

Don't think so

### Description

When I try to update the suffix and the value of an masked input, a ExpressionChangedAfterItHasBeenCheckedError is raised and the value of the input remains.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-mask-suffix?file=src/app/app.component.html

## 🔥 Exception or Error

<pre><code>
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '100'. Current value: '150'.
</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>
11.0.2
</code></pre>

**Comment by andriikamaldinov1** [comment]
@louis-neologix  Thanks for your using Ngx-Mask. 
It example, all work as expected add cdr - https://stackblitz.com/edit/angular-mask-suffix-49a2i4?file=src%2Fapp%2Fapp.component.ts

By calling this.cdr.detectChanges() after modifying the properties, you manually inform Angular to check for any changes and update the view accordingly. This should prevent the ExpressionChangedAfterItHasBeenCheckedError error from occurring.
