### ISSUE TITLE
ngx-mask rounding off to nearest

### ISSUE THREAD

**Issue by Jagan-Rameshbabu** [JsDaddy/ngx-mask#929]
I'm using ngx-mask for a angular reactive formControl that gets input from user in dollar amount. Below is the replica of my code.

<input type="text" formControlName="asset" matInput prefix="$" mask="separator.2" thousandSeparator="," separatorLimit="100000000000000">

When i enter input as 999999999999999.99, I'm getting 1000000000000000 as formControl value which is throwing error at backend where i have 15,2 decimal restriction.

I'm using ngx 11.1.5 with Angular 11 with Material UI.

**Comment by Jagan-Rameshbabu** [comment]
Using ngx 11.1.5 version

**Comment by andriikamaldinov1** [comment]
@Jagan-Rameshbabu  Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-pumvn1?file=src%2Fmain.ts
