### ISSUE TITLE
IE 11. mask="000000000" doesn't work.

### ISSUE THREAD

**Issue by YuriiZadorozhnyi** [JsDaddy/ngx-mask#93]
In IE in fields with mask="000000000" text inputs are possible and while moving out from this field either text or numbers input data are disappear. 

Problem was solved with mask="000000000''". 

But I don't like this solution and I don't understand it.

**Comment by NepipenkoIgor** [comment]
@YuriiZadorozhnyi Could you try last version ?

**Comment by NepipenkoIgor** [comment]
@YuriiZadorozhnyi  You didn't respond and i have been closed this issue
