### ISSUE TITLE
Mask pipe does not correctly render with hidden input

### ISSUE THREAD

**Issue by rub-sky** [JsDaddy/ngx-mask#932]
# 🐞 bug report

### Is this a regression?

No. I am not aware that this worked in previous versions.

### Description
When using a `custom pattern` that has a symbol that is to hide some of the input, the `mask pipe` does not hide any of the characters even if the `hiddenInput` value is set to `true` globally.

#### Configuration
```typescript
  public readonly SSN_MASK = 'AAA - AA - 0000';
  public readonly SSN_PATTERNS: IConfig['patterns'] = {
    0: { pattern: new RegExp('\\d')},
    A: { pattern: new RegExp('\\d'), symbol: '●' },
  };
```

#### Template code
This is the use in the template:
```html
<span>{{ ssnValue | mask: [SSN_MASK, SSN_PATTERNS] }}</span>
```

#### Results
For input `123456789`,
the expected output is `●●● - ●● - 6789`,
but actual output is `123 - 45 - 6789`.

The pipe does not allow `hiddenInput` configuration, and so will never go down the branch to format the text with the hidden characters.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-r2cy7e?file=src/app/app.component.html

## 🔥 Exception or Error

None, just unexpected behavior.

## 🌍 Your Environment

**Angular Version:**
```json
  "dependencies": {
    "@angular/animations": "12.2.0",
    "@angular/common": "12.2.0",
    "@angular/compiler": "12.2.0",
    "@angular/core": "12.2.0",
    "@angular/forms": "12.2.0",
    "@angular/platform-browser": "12.2.0",
    "@angular/platform-browser-dynamic": "12.2.0",
    "@angular/router": "12.2.0",
    "ngx-mask": "^12.0.0",
    "rxjs": "^7.3.0",
    "tslib": "^2.3.1",
    "zone.js": "^0.11.4"
  }
```

**Anything else relevant?**

**Comment by LeinadAsid** [comment]
Same issue here.
