### ISSUE TITLE
Mask pipe does not work with multiple configurations

### ISSUE THREAD

**Issue by michaelworm** [JsDaddy/ngx-mask#933]
# 🐞 bug report

### Is this a regression?

I don't know since I am using the latest version and no previous version.

### Description
I am using multiple masking patterns to fit my needs which works perfectly fine when using the mask attribute in an input like so.
 For example taking the following input mask:
`<input name="umsatz" mask="0,00||00,00||000,00||0000,00||00.000,00" />` 
and typing `100099` the input value gets correctly masked like so: `1000,99`

But when outputting the input value with a mask pipe, only the first pattern works and everything after the first `||` gets ignored. 

So in the case above, `umsatz` has the value `100099` and I am using the following pipe mask:
`{{umsatz | mask: '0,00||00,00||000,00||0000,00||00.000,00'}}` 
then the output is **always** like so: `1,00`.

I can't get this working so I guess this might be a bug.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mask-nmangf?file=src/app/app.component.html

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>
ng version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.4
Node: 14.17.3
Package Manager: npm 7.19.1
OS: darwin x64

Angular: 12.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.4
@angular-devkit/build-angular   12.2.4
@angular-devkit/core            12.2.4
@angular-devkit/schematics      12.2.4
@schematics/angular             12.2.4
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by lramondev** [comment]
I have the same issue

**Comment by lramondev** [comment]
could anyone fix this?

**Comment by cokita** [comment]
Me To!

**Comment by andriikamaldinov1** [comment]
@michaelworm @cokita @lramondev Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected  -  https://stackblitz.com/edit/angular-zkvxot?file=src%2Fmain.ts

**Comment by lramondev** [comment]
> @michaelworm @cokita @lramondev Thanks for your using Ngx-Mask. Please update to latest version. It example, all work as expected - https://stackblitz.com/edit/angular-zkvxot?file=src%2Fmain.ts

thanks. I'll try!
