### ISSUE TITLE
Caret / focus before prefix after clearing field

### ISSUE THREAD

**Issue by hv-pul** [JsDaddy/ngx-mask#936]
# 🐞 bug report

## Is this a regression?

No.

## Description

If a field has a `prefix` and `[showMaskTyped]="true"`, when the input field is cleared, the focus-caret is placed *before* the prefix, but it should be placed *after* the prefix.
To clear the input field, select all text (via CTRL-A) then delete via backspace or delete.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-mask-jbe55w

## 🌍 Your Environment

**Angular Version:**
`11.0.2`

**ngx-mask Version:**
`11.1.0`

**Browser Version:**
`Chrome 94.0.4606.61`

**Comment by andriikamaldinov1** [comment]
@hv-pul Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-bqpskz?file=src%2Fmain.ts

**Comment by KirstenStake** [comment]
@andriikamaldinov1 experiencing this issue still with version **14.2.4**. We are using Angular 14 so need to use the ngx-mask version compatible. What version was this fix applied in?
