### ISSUE TITLE
Buggy on Mobile devices

### ISSUE THREAD

**Issue by odahcam** [JsDaddy/ngx-mask#94]
When typing, the cursor moves to a position before the last inserted character (Galaxy S5, Galaxy S7, Moto G4 Play). 

In older devices (Galaxy J2 mini), the cursor doesn't moves as well and all the characters are inserted to the right of the cursor.

You can test it in: https://jsdaddy.github.io/ngx-mask/

Some other plugins, seems to have fixed it by changing the `input.selectionStart` usage by `input.selectionEnd`.

As you can see, `selectionStart` is used here:

https://github.com/JsDaddy/ngx-mask/blob/f83223332b9a462ce9b4863bf185952a5a8f21c3/src/app/ngx-mask/mask.directive.ts#L69

And also used here: 

https://github.com/JsDaddy/ngx-mask/blob/f83223332b9a462ce9b4863bf185952a5a8f21c3/src/app/ngx-mask/mask.directive.ts#L76

Related: https://github.com/angular-ui/ui-mask/pull/200

**Comment by odahcam** [comment]
This problem occours in Galaxy S7 Edge too.

**Comment by felipecslima** [comment]
I had the same problem.

**Comment by suhelkhan1** [comment]
For numeric input just use input type 'tel' like
`<input type="tel" mask="000 000 000" />`
It will work smoothly on mobile devices

**Comment by odahcam** [comment]
Not on Samsungs or any other device that doesn't supports tel.

**Comment by ozknemoy** [comment]
had same issue about a year ago. thought it was resolved

**Comment by NepipenkoIgor** [comment]
@odahcam Сould you check latest version ?

**Comment by odahcam** [comment]
Looks ok in my Moto G4. 🎉 
Gonna try to test in more devices along the next week.

**Comment by NepipenkoIgor** [comment]
@odahcam Awesome , waiting for your feedback

**Comment by odahcam** [comment]
Stills buggy on Galaxy J5 Pro with Samsung Internet:
![image](https://user-images.githubusercontent.com/3942006/39085655-42cb6cd6-455c-11e8-8b13-f10edfccd900.png)
> Image provided by @anologicon

**Comment by parthnayak7448** [comment]
Does anyone have a solution to this issue? I am facing an issue when my mask is to input date like MM/YYYY after slash cursor moves forward and start entering values reverse. 

Thanks in advance

**Comment by odahcam** [comment]
@NepipenkoIgor seems like this issue should be reopened. :/

**Comment by parthnayak7448** [comment]
@LimarenkoDenis  and @NepipenkoIgor  its mainly happen in MOTO G5 with Android 7

**Comment by thiagog3** [comment]
Same issue with some of LG devices

**Comment by ghiscoding** [comment]
@NepipenkoIgor 
I think your last version might have fixed this issue since it's also related to the cursor. 

Perhaps some of you might try with latest and see if it's fixed?

**Comment by NepipenkoIgor** [comment]
maybe @odahcam  could help ?

**Comment by parthnayak7448** [comment]
I check with updated version of ngx-mask and problem still persists.

**Comment by NepipenkoIgor** [comment]
@parthnayak7448  any idea why?

**Comment by odahcam** [comment]
Works fine on Xiaomi Mi A1 in Chrome, couldn't test any other devices yet.

**Comment by NepipenkoIgor** [comment]
@odahcam i am сlose and will reopen if we find all bugs

**Comment by Dok11** [comment]
@NepipenkoIgor same bug in Samsung Internet browser in any android devices
https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser

**Comment by bradenpoirier** [comment]
Issue persists on up to date Samsung Galaxy S7 (SM-G930F) when demoing on https://jsdaddy.github.io/ngx-mask/

**Comment by Dok11** [comment]
@bradenpoirier what browser are you using?

**Comment by bradenpoirier** [comment]
> @bradenpoirier what browser are you using?

This is occurring on Samsung Internet browser

**Comment by Dok11** [comment]
> This is occurring on Samsung Internet browser

![image](https://user-images.githubusercontent.com/2697890/52868291-eecd7680-3153-11e9-989b-e86875a68140.png)

**Comment by bradenpoirier** [comment]
Can we expect a fix for this? It looks like this has been fixed on other plugins..

**Comment by samshay** [comment]
I test with Samsung Internet Browser version 15.0.4.9 and i haven't the problem.
