### ISSUE TITLE
Cannot start input with character at end of suffix

### ISSUE THREAD

**Issue by bouc1620** [JsDaddy/ngx-mask#943]
# 🐞 bug report

### Description

- A user cannot start entering text/number in an input field with the character at the very end of the suffix for that input
- Characters are added at beginning of input whenever the user writes all the characters from the suffix

## 🔬 Minimal Reproduction

[stackblitz link](https://stackblitz.com/edit/angular-rifqfi?file=src/app/app.component.html)

**Comment by CharlieGreenman** [comment]
I am having this issue as well

**Comment by CharlieGreenman** [comment]
I made a pull request here to solve this issue for anyone interested: https://github.com/JsDaddy/ngx-mask/pull/1039
