### ISSUE TITLE
MaskPipe no longer works with a string mask if you use it with a custom pattern.

### ISSUE THREAD

**Issue by agrube** [JsDaddy/ngx-mask#945]
# 🐞 bug report

### Is this a regression?

 I do not know.

### Description

 After using a custom pattern mask with the MaskPipe, normal string masks no longer work with the MaskPipe. I believe this is because all MaskPipes share the same MaskApplierService. Perhaps it's because the customPattern variable is set in the applyMaskWithPattern function. Because of this, the _checkSymbolMask function is always looking for a custom pattern. Not sure what the fix could be to keep global configuration working. Perhaps any non-globally configured custom patterns should be passed into the applyMask function instead of setting the customPattern variable?

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/ngx-mask-yjnmmu

## 🌍 Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 10.0.8
Node: 14.18.1
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      11.2.7
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.6.6
typescript                        3.9.9
webpack                           4.43.0

ngx-mask 12.0.0
</code></pre>

**Comment by andriikamaldinov1** [comment]
@agrube If it still actual, open issue with teamplate!
