### ISSUE TITLE
Duplicates Current input value

### ISSUE THREAD

**Issue by alvaroenrich** [JsDaddy/ngx-mask#950]
# 🐞 bug report

### Is this a regression?
NO

### Description
When using chrome on android, if using SS00 0000 as a Mask, when introducing the 5th character, it auto duplicates the current input.
**EDIT**: Only being able to reproduce with android devices using Google Board. i.e: Won't happen with SwiftKey Keyboard

## 🔬 Minimal Reproduction
Please find a stackblitz link to reproduce the issue. **MUST BE OPENED FROM CHROME ON ANDROID **
https://stackblitz.com/edit/angular-ivy-qzy73n

## 🔥 Exception or Error
No error being thrown

## 🌍 Your Environment
Reproduced in both Angular 12 and 11.
Chrome 96 on Android 11.

**Comment by NepipenkoIgor** [comment]
@alvaroenrich  Hi. Seems like a mistake because your stackblitz without ngx-mask dependencies and relative to another packages. Please recheck and provide new issues with right dependencies and issue case
