### ISSUE TITLE
Possibility to disable "*" special character in mask

### ISSUE THREAD

**Issue by maxhorobets** [JsDaddy/ngx-mask#958]
# 🚀 feature request

### Description

 
Hi all!

I need to register my own custom pattern for "*" character, but as I know this character is using as a special character:

![image](https://user-images.githubusercontent.com/32305918/145059589-0faec7e7-3624-4c93-9ab6-400c434c7f84.png)

Also I not found option to disable using this character in your docs.

My code:

```
private readonly allPrintableSymbols: RegExp = new RegExp(`[\u0020-\u007e\u00a0-\u00ff]`);

public customPatterns: IConfig['patterns'] = {
  '#': { pattern: this.numberPattern },
  '0': { pattern: this.numberPattern },
  '9': { pattern: this.numberPattern },
  '@': { pattern: this.lettersPattern },
  ['A']: { pattern: this.lettersPattern },
  ['S']: { pattern: this.lettersPattern },
  ['!']: { pattern: this.punctuationPattern },    
  ['*']: { pattern: this.allPrintableSymbols },
};
public readonly specialCharacters = ['-', ' ', '.', ',', '/', '(', ')', ':', '+', '[', ']'];
```

Can I have any solutions to register my own pattern for "*"?

**Comment by andriikamaldinov1** [comment]
@maxhorobets Thanks for your using Ngx-Mask. Please update to latest version.
It example, all work as expected - https://stackblitz.com/edit/angular-dn6ajx?file=src%2Fmain.ts
