### ISSUE TITLE
masking ip address one or two or three digits. 

### ISSUE THREAD

**Issue by ConnectedReasoning** [JsDaddy/ngx-mask#96]
when I use mask 000.000.000.000  I must use three digits per section. much of the time We use one or two or three digits in each section. I tried regex [0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}  no luck. 
Anyone able to use IP mask?

**Comment by ysrodrigues** [comment]
You can use digit 9 for that.
in Mask you can do that.

<input mask="099.099.099.099" ... >

You must have one digit, the zero represents that, and may have or not more two digits, nine's is that.

In documentation: 
9 | digits (like 0 to 9 numbers), but optional

**Comment by NepipenkoIgor** [comment]
@ysrodrigues Thank you for answer . We will implement `?` special character in future. @ConnectedReasoning  Yes you can use <input mask="099.099.099.099" ... >
