### ISSUE TITLE
Ability to replace special characters from mask in model

### ISSUE THREAD

**Issue by mirzinho** [JsDaddy/ngx-mask#963]
# 🚀 feature request

### Description

Ability to replace special characters defined in mask for model.

### Describe the solution you'd like

Add additional input for characters to be replaced ie [replaceSpecialChars]="["," "."]"
meaning replace the coma in the mask with the dot in the model value.
So, the mask is 123,22 and the model value would be 123.22

### Describe alternatives you've considered
Only workaround is replacing he values in the form or model using replace method.

**Comment by andriikamaldinov1** [comment]
@mirzinho @nosovk Thanks for using Ngx-Mask. Please update to latest version. We added new feature 
outputTransfromFn  => it fn transform value in model
inputTransformFn => it transform value and model when user write. 
It example - https://stackblitz.com/edit/angular-pgajam?file=src%2Fmain.ts
