### ISSUE TITLE
rename injection token from config so it is easier to determine the library.

### ISSUE THREAD

**Issue by pete-mcwilliams** [JsDaddy/ngx-mask#965]
# 🚀 feature request

### Description

When NgxMaskModule.forRoot() is missing in app.module.ts or inside a .spec.ts file the error message displayed is not very helpful in identifying what the issue is.

ERROR NullInjectorError: R3InjectorError(<snip>)[InjectionToken config -> InjectionToken config -> InjectionToken config -> InjectionToken config]:
NullInjectorError: No provider for InjectionToken config!

Please consider renaming InjectionToken('config') to InjectionToken('ngxmask-config') or similar in the following

export const config: InjectionToken<IConfig> = new InjectionToken('config');

**Comment by NepipenkoIgor** [comment]
@pete-mcwilliams Hi. Thank you for request . Please use  ngx-mask@13.1.3
