### ISSUE TITLE
Cursor Jump if FormControl is init or if setValue() is called.

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [JsDaddy/ngx-mask#968]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: v11.1.5

### Description

The input cursor jump to the left when we enter a "0" note that happens only if we provide a formControl default value.

## 🔬 Minimal Reproduction

- https://stackblitz.com/github/alexis-landrieu-avanade/ngx-mask-cursor-jump
- https://github.com/alexis-landrieu-avanade/ngx-mask-cursor-jump

## 🔥 Exception or Error

<pre><code>
</code></pre>
![Animation](https://user-images.githubusercontent.com/31771810/150192877-e6d58487-3cbd-4db3-8eed-846204967620.gif)

```html
<form [formGroup]="formGroup">
  <mat-form-field>
    <mat-label>Doesn't work (Cursor jump)</mat-label>
    <input matInput formControlName="a" mask="separator.4" thousandSeparator="," />
  </mat-form-field>
  <mat-form-field>
    <mat-label>Work</mat-label>
    <input matInput formControlName="b" mask="separator.4" thousandSeparator="," />
  </mat-form-field>
</form>
```

```typescript
export class AppComponent {
  formGroup = new FormGroup( {
    a: new FormControl(1), // Issue
    b: new FormControl()   // No Issue
  });
}
```

## 🌍 Your Environment

**ngx-mask Version:**
<pre><code>
"ngx-mask": "^13.1.1"
</code></pre>

**Angular Version:**

<pre><code>
Angular CLI: 13.1.3
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4
</code></pre>

**Anything else relevant?**

**Comment by daniel-barac** [comment]
I have the same issue since upgrading ngx-mask from 12.0.0 to 13.1.1. Using angular version 13.2.3 .  Downgrading back to v. 12.0.0 solved the issue. Any updates on this issue?

**Comment by NepipenkoIgor** [comment]
@alexis-landrieu-avanade @daniel-barac Thank you that using ngx-mask. Cant reproduce with latest version of ngx-mask
Some small example https://stackblitz.com/edit/angular-5zhmbp?file=src%2Fmain.ts%3AL8
Please check and if you will have problems recreate issue .
