### ISSUE TITLE
HELP: Using Prefix/Suffix - What is the mask value to accept all characters of any length?

### ISSUE THREAD

**Issue by bkarv** [JsDaddy/ngx-mask#976]
### Description
Thanks for this great plugin. We purely want to use this feature to add prefix and suffix to the input text. The only thing we can't workout what is the mask value that can accept any character (ie Integers, decimals, upper and lower case letters) of any length?

Thanks in advance.

**Comment by andriikamaldinov1** [comment]
@bkarv Thanks for using Ngx-mask.
It example for ur case - https://stackblitz.com/edit/angular-9qkmhg?file=src%2Fmain.ts
If you need to add more specialCharacters u can add it to pattern
