### ISSUE TITLE
Error: Missing "./bundles/ngx-mask.umd.js" export in "ngx-mask" package

### ISSUE THREAD

**Issue by novakand** [JsDaddy/ngx-mask#978]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/45287302/154872167-1f0740ed-d6fa-4610-91ec-c2657d090632.png">

Help me fix the error
https://stackblitz.com/edit/github-xkabze

**Comment by mattcheah** [comment]
Same issue, attempting to use ngx-mask on stackblitz still gives this same error. 
Using version 12.0.0 appears to work.

**Comment by NepipenkoIgor** [comment]
@novakand  @mattcheah  @gultyaev  Hi all. Yes it was issues with build config and paths . Please use ngx-mask >=14.2.1.
Also you could look on patched original stackblitz https://stackblitz.com/edit/github-xkabze-nf5dfk?file=README.md
