### ISSUE TITLE
Not compiling in Angular 13+. 

### ISSUE THREAD

**Issue by Saqib92** [JsDaddy/ngx-mask#981]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  Angular 9 / ngx-mask 7.9.10

### Description
Not compiling in angular 13+, the moment i add `NgxMaskModule.forRoot(maskConfig)` it stop compiling. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-ojryhg?file=src/app/app.module.ts

## 🔥 Exception or Error

it should work with angular 13 / I am expecting it to work in ionic 6 project based on angular 13.0.0

## 🌍 Your Environment

**Angular Version:**

<pre><code>
13.0.0
</code></pre>

**Anything else relevant?**

**Comment by kevinch3-shoutly** [comment]
Same issue here

**Comment by Lightllord** [comment]
hi
any progress on this?

**Comment by nickeeromo** [comment]
Which version of ngx-mask are you using? The version should correlate to the Angular version I believe, so you should be using ngx-mask version 13 or higher. I'm fine with Angular version 13.0.3 and ngx-mask 13.1.12

**Comment by Saqib92** [comment]
> 

```
@angular/core: 13.2.3,
ngx-mask: 13.1.1
```

Please check stackblitz i have added above.

**Comment by NepipenkoIgor** [comment]
@Saqib92  @Lightllord @kevinch3-shoutly Hi . Thank you that using our package. Yes it was  problem in package build configuration  and paths . Everything should works started ngx-mask 14.2.1. This is patched original stackblitz 
https://stackblitz.com/edit/angular-ivy-d4rwyn?file=src%2Fapp%2Fapp.component.html
