### ISSUE TITLE
Cursor jumps at beginning ifthe model is set

### ISSUE THREAD

**Issue by florinsuman** [JsDaddy/ngx-mask#984]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 the cursor jumps at the beginning when -, or 0, or 0,0, or 0,00 or 0,0000000 is typed if the model is set in typescript

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/ngx-mask-negative-number-cursor-jump-bug-v5j7fs

## 🔥 Exception or Error

```
<input
  type="text"
  id="valueId"
  [(ngModel)]="decimalValue"
  name="valueName"
  mask="separator.8"
  thousandSeparator="."
  decimalMarker=","
  [allowNegativeNumbers]="true"
  [specialCharacters]="[',', '.']"
/>
```

```
export class AppComponent {
  decimalValue = 0.723;
  constructor() {}
}
```

## 🌍 Your Environment

**Angular Version:**

<pre><code>

"ngx-mask": "9.1.2"

"dependencies": {
    "@angular/animations": "11.2.0",
    "@angular/common": "11.2.0",
    "@angular/compiler": "11.2.0",
    "@angular/core": "11.2.0",
    "@angular/forms": "11.2.0",
    "@angular/platform-browser": "11.2.0",
    "@angular/platform-browser-dynamic": "11.2.0",
    "@angular/router": "11.2.0",
    "ngx-mask": "9.1.2",
    "rxjs": "6.6.3",
    "tslib": "2.1.0",
    "zone.js": "0.11.3"
  },
</code></pre>

**Anything else relevant?**

**Comment by berubemartin** [comment]
The issues still here again !   If you press '-', the cursor jump at the beginning of the input IF THE ngModel is binded.  If no ngModel is binded then input acts correctyl

**Comment by GlebChiz** [comment]
@berubemartin This issue has not yet been fixed. I'll fix this in the next few days.

**Comment by NepipenkoIgor** [comment]
@florinsuman @timrasche @berubemartin Thank you for using ngx-mask. Please try version >=13.1.14

**Comment by dinbtechit** [comment]
still an issue in `15.2.3`

![Kapture 2024-03-06 at 12 51 47](https://github.com/JsDaddy/ngx-mask/assets/17984781/4c441d02-4d63-43f4-b27c-3e3d9a93d94c)

**Comment by andriikamaldinov1** [comment]
@dinbtechit Thanks for using Ngx-mask. 
It example with your mask, all work as expected - https://stackblitz.com/edit/angular-15-starter-pack-rpkdyd?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

If you have any questions or bugs, open new issues by teamplate
