### ISSUE TITLE
Text after mask

### ISSUE THREAD

**Issue by RichardBosworth** [JsDaddy/ngx-mask#99]
Hi,

I would like to automatically add text following the mask that is presented to the user whilst typing.

e.g. 009/009 mmHg.
would ideally show the mmHg at the end.

Is this possible?

**Comment by martinmanzo** [comment]
Hi @RichardBosworth, could you do this?

**Comment by martinmanzo** [comment]
@RichardBosworth Hi, I found [this jQuery plugin](http://www.bestjquery.com/?qsm7HWPO) to serve as example:
![imagen](https://user-images.githubusercontent.com/3625887/40549577-32599d10-600e-11e8-9fa7-5fa5b6b46707.png)

For my app I ended up using ngx-mask and appending a boostrap-ish input group to show the unit of the field.

**Comment by Serge0111** [comment]
Hi @RichardBosworth and @martinmanzo,
we've released new version which includes 'sufix' property, check out 6.3.8.

**Comment by martinmanzo** [comment]
Awesome! Thanks!
