### ISSUE TITLE
HiddenInput doesn't keep formControl value when being toggled

### ISSUE THREAD

**Issue by mattcheah** [JsDaddy/ngx-mask#996]
# 🐞 bug report

### Description

When editing a `hiddenInput` field, the form control value is edited properly, but when hiddenInput is toggled off, the form will clear or have unexpected results. 

Similar to this issue: https://github.com/JsDaddy/ngx-mask/issues/706
Which was marked as closed on 3/19/21, when version 11.1.5 was released. 
Version 11.1.5 still produces this error. 

## 🔬 Minimal Reproduction

Reproduction can be seen here, as well as an ugly workaround using `setTimeout`. 
https://stackblitz.com/edit/angular-ivy-noofof?file=src/app/app.component.html

## 🌍 Your Environment

Angular Version: 13.3.2
ngx-mask Version: 11.1.5 (Error also occurs with 12.0.0 or 13.0.0)

**Comment by xakeppok** [comment]
@mattcheah Thank you that you using ngx-mask. Duplicate #1008. Issue has been fixed. Please try version >=14.0.2
