### ISSUE TITLE
Handle null values

### ISSUE THREAD

**Issue by fzs1994** [JsDaddy/ngx-mask#999]
# 🐞 bug report

### Description

 A clear and concise description of the problem...
I have some masked fields like date & phone number whose values come from database. But these values are not required and they can be null. So as my input value is null, there is one error in console saying `TypeError: inputValue.slice is not a function`
Null values with masking should not return this error. It should be handled.

## 🔥 Exception or Error
<pre><code>TypeError: inputValue.slice is not a function</code></pre>

## 🌍 Your Environment

**Angular Version:**
<pre><code>@angular-devkit/schematics        9.1.5
@angular/cdk                      9.2.4
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.13
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0</code></pre>

**Comment by xakeppok** [comment]
hi @fzs1994 can you please provide some example on stackblitz maybe ?

**Comment by andriikamaldinov1** [comment]
@fzs1994 Thanks for your using Ngx-Mask. 
If it issue relevant in latest version, please open issue with template
